/**
 * Car purchase (kupní smlouva na vozidlo) — translations EN/UK/RU/VN/DE.
 */
import type { ContractSection, StoredContractData } from '../contracts';
import { buildBilingualTranslations, fmtAmount, fmtDate, pad, type ParaPair } from './helpers';

const date = (v: unknown, l: string) => v ? fmtDate(v, l) : new Date().toLocaleDateString(l);

function en(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const cashOverLimit = d.paymentMethod === 'cash' && Number(d.priceAmount ?? d.purchasePrice ?? 0) > 270000;
  const paymentText = d.paymentMethod === 'cash' ? (cashOverLimit ? 'Notice: the purchase price exceeds CZK 270,000; cash payment is excluded (§ 4 Act No. 254/2004 Coll.). The parties must choose a non-cash payment before signing.' : 'In cash upon signing, no later than physical handover. Cash payment above CZK 270,000 is excluded under Act No. 254/2004 Coll.') : d.bankAccount ? `By bank transfer to the seller's account no. ${pad(d.bankAccount)}${d.variableSymbol ? `, VS ${pad(d.variableSymbol)}` : ''}, within ${pad(d.paymentDueDays) || '3'} working days of signing.` : `By bank transfer to the seller's account, details provided at signing, within ${pad(d.paymentDueDays) || '3'} working days of signing.`;
  const ownershipTransfer = d.ownershipTransferMoment === 'payment' ? 'Title passes to the buyer upon full payment of the purchase price.' : 'Title passes to the buyer upon physical handover of the vehicle.';
  const sections: ParaPair[] = [
    { title: 'PREAMBLE', body: ['This purchase agreement (the "Agreement") is concluded under § 2079 et seq. of Act No. 89/2012 Coll., the Czech Civil Code, as amended (the "Civil Code").', `Date of conclusion: ${date(d.contractDate, 'en-GB')}`] },
    { title: 'I. PARTIES', body: [`Seller: ${pad(d.sellerName)}, date of birth / Company ID: ${pad(d.sellerId) || '—'}, residence / registered office: ${pad(d.sellerAddress)}`, d.sellerOP ? `Seller ID card no.: ${pad(d.sellerOP)}` : '', d.sellerEmail ? `Seller e-mail: ${pad(d.sellerEmail)}` : '', d.sellerPhone ? `Seller phone: ${pad(d.sellerPhone)}` : '', `Buyer: ${pad(d.buyerName)}, date of birth / Company ID: ${pad(d.buyerId) || '—'}, residence / registered office: ${pad(d.buyerAddress)}`, d.buyerOP ? `Buyer ID card no.: ${pad(d.buyerOP)}` : '', d.buyerEmail ? `Buyer e-mail: ${pad(d.buyerEmail)}` : '', d.buyerPhone ? `Buyer phone: ${pad(d.buyerPhone)}` : ''] },
    { title: 'II. SUBJECT OF PURCHASE', body: [`The subject of the purchase is a motor vehicle of make ${pad(d.carMake)}${d.carModel ? `, model ${pad(d.carModel)}` : ''}.`, [d.carVIN ? `VIN: ${pad(d.carVIN)}` : '', d.carPlate ? `Registration plate: ${pad(d.carPlate)}` : ''].filter(Boolean).join(', '), (() => { const parts = [d.carMileage ? `Odometer reading on signing: ${fmtAmount(d.carMileage)} km` : '', d.carYear ? `year of manufacture: ${pad(d.carYear)}` : ''].filter(Boolean); return parts.length ? `${parts.join('. ')}.` : ''; })(), d.carFirstRegistration ? `Date of first registration: ${pad(d.carFirstRegistration)}.` : ''] },
    { title: 'III. PURCHASE PRICE, PAYMENT AND TRANSFER OF TITLE', body: [`Purchase price: CZK ${fmtAmount(d.priceAmount ?? d.purchasePrice)}${d.priceWords ? ` (in words: ${pad(d.priceWords)})` : ''}.`, `Payment method: ${paymentText}`, ownershipTransfer, d.handoverDate ? `Agreed date of physical handover: ${fmtDate(d.handoverDate)}.` : '', d.handoverPlace ? `Place of handover: ${pad(d.handoverPlace)}.` : ''] },
    { title: "IV. TECHNICAL CONDITION, SELLER'S DECLARATIONS AND WARRANTIES", body: [(() => { if (d.buyerInspectedVehicle === false) return 'The buyer acknowledges not having had the opportunity to fully inspect the technical condition of the vehicle before signing; this has been reflected in the purchase price.'; const details: string[] = ['The buyer confirms having duly inspected the technical condition of the vehicle before signing']; if (d.testDriveCompleted) details.push('took a test drive'); if (d.mechanicInspectionOffered) details.push('had the opportunity to have the vehicle examined by an independent mechanic'); return details.join(', ') + '; and accepts the vehicle in this condition (§ 2104 Civil Code).'; })(), `The seller declares known defects: ${pad(d.knownDefects) || 'no apparent defects beyond ordinary wear and tear for the age and mileage'}.`, d.odometerGuaranteed === false ? 'The seller does not guarantee the correctness of the odometer reading.' : "The seller declares the odometer reading corresponds to the seller's best knowledge and has not been tampered with.", d.isPledged ? 'The seller states the vehicle IS subject to a security right — details agreed separately.' : 'The seller declares the vehicle is NOT subject to any security right.', d.isInLeasing ? 'The seller states the vehicle IS subject to a lease or other financial obligation.' : 'The seller declares the vehicle is NOT subject to a lease or other financial obligation.', d.hasThirdPartyRights ? 'The vehicle is encumbered by rights of third parties — details agreed separately.' : 'The seller declares the vehicle is NOT encumbered by third-party rights.', d.strictWarranties ? 'The seller provides a 6-month contractual quality warranty from handover.' : 'The vehicle is sold as used; the seller provides no contractual quality warranty beyond statute.'] },
    { title: 'V. DUTIES AFTER HANDOVER AND REGISTRATION TRANSFER', body: ['The parties shall, within 15 days of transfer of title, notify the change of owner to the competent municipal office (§ 8(2) Act No. 56/2001 Coll.).', 'The seller shall hand over all documents, keys and equipment as listed.', 'Compulsory motor third-party liability and any comprehensive insurance pass on the date of transfer; the buyer shall arrange new policies.', 'The buyer shall conduct a reasonable inspection and notify any apparent defects in writing within 5 working days from receipt (§ 2104 Civil Code).'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'VI. DETAILED VEHICLE CONDITION AND DOCUMENTS HANDED OVER', body: [(() => { const parts = [d.carColor ? `colour ${pad(d.carColor)}` : '', d.fuelType ? `fuel ${pad(d.fuelType)}` : '', d.engineCapacity ? `engine capacity ${pad(d.engineCapacity)} cc` : '', d.powerKW ? `power ${pad(d.powerKW)} kW` : ''].filter(Boolean); return parts.length ? `Technical data: ${parts.join(', ')}.` : ''; })(), (() => { const parts = [d.stkValidUntil ? `MOT (STK) valid until ${pad(d.stkValidUntil)}` : '', d.emissionsValidUntil ? `emissions valid until ${pad(d.emissionsValidUntil)}` : ''].filter(Boolean); return parts.length ? `Validity of technical and emissions inspection: ${parts.join(', ')}.` : ''; })(), (() => { const parts = [d.previousOwnersCount ? `previous owners: ${pad(d.previousOwnersCount)}` : '', d.vehicleOrigin ? `origin: ${pad(d.vehicleOrigin)}` : ''].filter(Boolean); return parts.length ? `History — ${parts.join(', ')}.` : ''; })(), `Service book: ${d.serviceHistory ? 'yes, handed over with the vehicle' : 'not available'}.`, `Accident history: ${d.accidentHistory ? 'has been in an accident, repairs per service docs' : 'no accidents known to the seller'}.`, d.equipmentIncluded ? `Equipment: ${pad(d.equipmentIncluded)}.` : 'Equipment: as-is at handover.', d.tiresInfo ? `Tyres: ${pad(d.tiresInfo)}.` : '', d.documentsIncluded ? `Documents: ${pad(d.documentsIncluded)}.` : 'Documents: vehicle registration certificate.', d.keysCount ? `Keys handed over: ${pad(d.keysCount)}.` : ''] });
    sections.push({ title: 'VII. CONTRACTUAL PENALTIES AND LIABILITY FOR CONCEALED DEFECTS', body: ['The seller is liable for defects existing at the time of passing of risk.', d.hiddenDefectPenalty && Number(d.hiddenDefectPenalty) > 0 ? `For knowingly concealed defects: contractual penalty CZK ${fmtAmount(d.hiddenDefectPenalty)}.` : 'For knowingly concealed defects: full damages plus cost of remedy.', `Buyer late payment penalty: ${pad(d.buyerLatePenalty) || '0.05'}% of amount due per day.`, d.sellerLatePenalty && Number(d.sellerLatePenalty) > 0 ? `Seller handover delay penalty: CZK ${fmtAmount(d.sellerLatePenalty)} per day.` : 'Seller handover delay: buyer may claim demonstrable damages.', "The seller declares no execution, lien or other limitation; liability per § 1728 et seq. Civil Code."] });
    sections.push({ title: 'VIII. INSURANCE, DEBT-FREE STATUS AND TRANSFER PENALTIES', body: ['The parties mutually authorise each other for the registration transfer. If a party fails to appear, the other may carry out the transfer alone based on this Agreement.', "If the seller fails to attend the transfer, penalty CZK 200/day plus reasonable enforcement costs.", "From transfer of title, the buyer shall take out new compulsory motor third-party liability insurance. The seller terminates existing insurance.", 'The seller declares no outstanding obligation to leasing companies, banks or other parties from prior financing.', 'No pending or unresolved insurance events known.', d.declarationPenalty && Number(d.declarationPenalty) > 0 ? `False declaration penalty: CZK ${fmtAmount(d.declarationPenalty)}.` : 'False declarations: damages plus reasonable enforcement costs.'] });
  }
  sections.push({ title: `${hasPremium ? 'IX' : 'VI'}. FINAL PROVISIONS`, body: ['Governed by the laws of the Czech Republic, in particular Act No. 89/2012 Coll., the Civil Code.', 'Disputes shall be resolved primarily amicably; failing agreement, by the competent court.', 'Executed in two counterparts; each party receives one.', 'Amendments only as written, numbered and signed addenda.', 'Severability clause: invalidity of one provision does not affect the rest.', 'Personal data per EU Regulation 2016/679 (GDPR) and Act No. 110/2019 Coll.', 'Force majeure exception (§ 2913(2) Civil Code).'] });
  sections.push({ title: `${hasPremium ? 'X' : 'VII'}. SIGNATURES`, body: [] });
  return sections;
}

function uk(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const cashOverLimit = d.paymentMethod === 'cash' && Number(d.priceAmount ?? d.purchasePrice ?? 0) > 270000;
  const paymentText = d.paymentMethod === 'cash' ? (cashOverLimit ? 'Увага: ціна перевищує 270 000 крон; платіж готівкою виключено (§ 4 Закону № 254/2004 Sb.). Сторони повинні обрати безготівковий платіж до підпису.' : 'Готівкою при підписі, не пізніше фізичної передачі. Платіж готівкою понад 270 000 крон виключено за Законом № 254/2004 Sb.') : d.bankAccount ? `Банківським переказом на рахунок продавця № ${pad(d.bankAccount)}${d.variableSymbol ? `, VS ${pad(d.variableSymbol)}` : ''}, протягом ${pad(d.paymentDueDays) || '3'} робочих днів з підпису.` : `Банківським переказом на рахунок продавця, реквізити надано при підписі, протягом ${pad(d.paymentDueDays) || '3'} робочих днів з підпису.`;
  const ownershipTransfer = d.ownershipTransferMoment === 'payment' ? 'Право власності переходить на покупця при повній сплаті ціни.' : 'Право власності переходить на покупця при фізичній передачі транспортного засобу.';
  const sections: ParaPair[] = [
    { title: 'ПРЕАМБУЛА', body: ['Цей договір купівлі-продажу («Договір») укладається відповідно до § 2079 та наступних Закону № 89/2012 Sb., Цивільний кодекс Чехії, з наступними змінами («ЦК»).', `Дата укладення: ${date(d.contractDate, 'uk-UA')}`] },
    { title: 'I. СТОРОНИ', body: [`Продавець: ${pad(d.sellerName)}, дата народження / IČO: ${pad(d.sellerId) || '—'}, місце проживання / місцезнаходження: ${pad(d.sellerAddress)}`, d.sellerOP ? `Номер посвідчення продавця: ${pad(d.sellerOP)}` : '', d.sellerEmail ? `E-mail продавця: ${pad(d.sellerEmail)}` : '', d.sellerPhone ? `Телефон продавця: ${pad(d.sellerPhone)}` : '', `Покупець: ${pad(d.buyerName)}, дата народження / IČO: ${pad(d.buyerId) || '—'}, місце проживання / місцезнаходження: ${pad(d.buyerAddress)}`, d.buyerOP ? `Номер посвідчення покупця: ${pad(d.buyerOP)}` : '', d.buyerEmail ? `E-mail покупця: ${pad(d.buyerEmail)}` : '', d.buyerPhone ? `Телефон покупця: ${pad(d.buyerPhone)}` : ''] },
    { title: 'II. ПРЕДМЕТ КУПІВЛІ', body: [`Предметом купівлі є моторне транспортний засіб марки ${pad(d.carMake)}${d.carModel ? `, модель ${pad(d.carModel)}` : ''}.`, [d.carVIN ? `VIN (номер кузова): ${pad(d.carVIN)}` : '', d.carPlate ? `Реєстраційний номер: ${pad(d.carPlate)}` : ''].filter(Boolean).join(', '), (() => { const parts = [d.carMileage ? `Показник одометра на день підпису: ${fmtAmount(d.carMileage)} км` : '', d.carYear ? `рік випуску: ${pad(d.carYear)}` : ''].filter(Boolean); return parts.length ? `${parts.join('. ')}.` : ''; })(), d.carFirstRegistration ? `Дата першої реєстрації: ${pad(d.carFirstRegistration)}.` : ''] },
    { title: 'III. ЦІНА КУПІВЛІ, СПЛАТА І ПЕРЕХІД ПРАВА ВЛАСНОСТІ', body: [`Ціна купівлі автомобіля: ${fmtAmount(d.priceAmount ?? d.purchasePrice)} крон${d.priceWords ? ` (словами: ${pad(d.priceWords)})` : ''}.`, `Спосіб сплати: ${paymentText}`, ownershipTransfer, d.handoverDate ? `Погоджена дата фізичної передачі: ${fmtDate(d.handoverDate, 'uk-UA')}.` : '', d.handoverPlace ? `Місце передачі: ${pad(d.handoverPlace)}.` : ''] },
    { title: 'IV. ТЕХНІЧНИЙ СТАН, ЗАЯВИ ПРОДАВЦЯ ТА ГАРАНТІЇ', body: [(() => { if (d.buyerInspectedVehicle === false) return 'Покупець бере до уваги, що не мав можливості у повному обсязі ознайомитись з технічним станом транспортного засобу перед підписом; цей факт враховано при погодженні ціни.'; const details: string[] = ['Покупець підтверджує, що перед підписом договору належно ознайомився з технічним станом транспортного засобу']; if (d.testDriveCompleted) details.push('здійснив пробну поїздку'); if (d.mechanicInspectionOffered) details.push('мав можливість перевірити транспортний засіб у власного механіка'); return details.join(', ') + '; транспортний засіб у цьому стані приймає (§ 2104 ЦК).'; })(), `Продавець заявляє, що йому відомі такі дефекти: ${pad(d.knownDefects) || 'Жодних явних дефектів понад звичайне зношування, що відповідає віку та пробігу'}.`, d.odometerGuaranteed === false ? 'Продавець виразно не гарантує правильність показника одометра.' : 'Продавець заявляє, що показник одометра відповідає його найкращому знанню та не був неправомірно змінений.', d.isPledged ? 'Продавець вказує, що на транспортному засобі ОБТЯЖЕНЕ заставне право — деталі сторонуються окремо.' : 'Продавець заявляє, що транспортний засіб НЕ є предметом жодного заставного права.', d.isInLeasing ? 'Продавець вказує, що транспортний засіб Є предметом лізингу — деталі сторонуються окремо.' : 'Продавець заявляє, що транспортний засіб НЕ є предметом лізингу.', d.hasThirdPartyRights ? 'На транспортному засобі ОБТЯЖЕНІ права третіх осіб — деталі сторонуються окремо.' : 'Продавець заявляє, що на транспортному засобі НЕ ОБТЯЖЕНІ жодні права третіх осіб.', d.strictWarranties ? 'Продавець надає договірну гарантію якості 6 місяців від передачі.' : 'Транспортний засіб продається як вживаний; продавець не надає договірну гарантію якості понад законні рамки.'] },
    { title: 'V. ОБОВ\'ЯЗКИ ПІСЛЯ ПЕРЕДАЧІ ТА ПЕРЕРЕЄСТРАЦІЯ', body: ['Сторони зобов\'язані негайно, не пізніше 15 днів від переходу права власності, повідомити про зміну власника відповідному муніципальному органу (§ 8(2) Закону № 56/2001 Sb.).', 'Продавець зобов\'язаний передати покупцю всі документи, ключі та обладнання згідно з переліком.', 'Обов\'язкове цивільне страхування переходить на покупця з дня переходу права власності; покупець укладає нові поліси.', 'Покупець зобов\'язаний здійснити належну перевірку та повідомити явні дефекти письмово протягом 5 робочих днів з прийняття (§ 2104 ЦК).'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'VI. ДЕТАЛЬНИЙ СТАН ТЗ ТА ПЕРЕДАНІ ДОКУМЕНТИ', body: [(() => { const parts = [d.carColor ? `колір ${pad(d.carColor)}` : '', d.fuelType ? `паливо ${pad(d.fuelType)}` : '', d.engineCapacity ? `об\'єм двигуна ${pad(d.engineCapacity)} см³` : '', d.powerKW ? `потужність ${pad(d.powerKW)} кВт` : ''].filter(Boolean); return parts.length ? `Технічні дані: ${parts.join(', ')}.` : ''; })(), (() => { const parts = [d.stkValidUntil ? `СТК дійсна до ${pad(d.stkValidUntil)}` : '', d.emissionsValidUntil ? `емісії дійсні до ${pad(d.emissionsValidUntil)}` : ''].filter(Boolean); return parts.length ? `Чинність технічного огляду: ${parts.join(', ')}.` : ''; })(), (() => { const parts = [d.previousOwnersCount ? `кількість попередніх власників: ${pad(d.previousOwnersCount)}` : '', d.vehicleOrigin ? `походження: ${pad(d.vehicleOrigin)}` : ''].filter(Boolean); return parts.length ? `Історія — ${parts.join(', ')}.` : ''; })(), `Сервісна книжка: ${d.serviceHistory ? 'так, передається разом з ТЗ' : 'не доступна'}.`, `Історія аварій: ${d.accidentHistory ? 'ТЗ був у ДТП, ремонти за документацією' : 'продавцю не відомі жодні ДТП'}.`, d.equipmentIncluded ? `Обладнання: ${pad(d.equipmentIncluded)}.` : 'Обладнання: за фактичним станом при передачі.', d.tiresInfo ? `Шини: ${pad(d.tiresInfo)}.` : '', d.documentsIncluded ? `Документи: ${pad(d.documentsIncluded)}.` : 'Документи: технічний паспорт.', d.keysCount ? `Передано ключів: ${pad(d.keysCount)}.` : ''] });
    sections.push({ title: 'VII. ШТРАФИ ТА ВІДПОВІДАЛЬНІСТЬ ЗА ПРИХОВАНІ ДЕФЕКТИ', body: ['Продавець відповідає за дефекти, що існували на момент переходу ризику.', d.hiddenDefectPenalty && Number(d.hiddenDefectPenalty) > 0 ? `За свідомо приховані дефекти: штраф ${fmtAmount(d.hiddenDefectPenalty)} крон.` : 'За свідомо приховані дефекти: повне відшкодування шкоди плюс витрати на усунення.', `Штраф за прострочення сплати покупцем: ${pad(d.buyerLatePenalty) || '0,05'}% від заборгованості за день.`, d.sellerLatePenalty && Number(d.sellerLatePenalty) > 0 ? `Штраф за прострочення передачі продавцем: ${fmtAmount(d.sellerLatePenalty)} крон за день.` : 'Прострочення передачі: покупець може вимагати доведене відшкодування шкоди.', 'Продавець заявляє про відсутність виконання, застави або інших обмежень; відповідальність за § 1728 та наступних ЦК.'] });
    sections.push({ title: 'VIII. СТРАХУВАННЯ, БЕЗ ЗАБОРГОВАНОСТЕЙ ТА ШТРАФИ ПРИ ПЕРЕРЕЄСТРАЦІЇ', body: ['Сторони взаємно уповноважують одна одну на представництво у перереєстрації власника. Якщо одна сторона не з\'явиться, друга може здійснити перереєстрацію самостійно на підставі цього Договору.', 'Якщо продавець без поважної причини не з\'явиться на перереєстрацію, зобов\'язаний сплатити штраф 200 крон за кожен день прострочення.', 'З моменту переходу права власності покупець зобов\'язаний оформити нове обов\'язкове цивільне страхування. Продавець завершує існуюче страхування.', 'Продавець заявляє про відсутність незавершених зобов\'язань перед лізингом, банком або іншою третьою особою.', 'Продавцю не відомі поточні чи невирішені страхові події.', d.declarationPenalty && Number(d.declarationPenalty) > 0 ? `У разі неправдивості заяв: штраф ${fmtAmount(d.declarationPenalty)} крон.` : 'У разі неправдивості заяв: відшкодування доведеної шкоди.'] });
  }
  sections.push({ title: `${hasPremium ? 'IX' : 'VI'}. ЗАКЛЮЧНІ ПОЛОЖЕННЯ`, body: ['Регулюється правом Чеської Республіки, зокрема Законом № 89/2012 Sb., Цивільним кодексом.', 'Спори вирішуються насамперед мирним шляхом; за відсутності згоди — компетентним судом.', 'Договір складено у двох примірниках; кожна сторона отримує по одному.', 'Зміни лише у формі писемних, нумерованих і підписаних доповнень.', 'Недійсність окремого положення не впливає на дійсність решти.', 'Обробка персональних даних за Регламентом ЄС 2016/679 (GDPR) та Законом № 110/2019 Sb.', 'Виняток для форс-мажору (§ 2913(2) ЦК).'] });
  sections.push({ title: `${hasPremium ? 'X' : 'VII'}. ПІДПИСИ`, body: [] });
  return sections;
}

function ru(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const cashOverLimit = d.paymentMethod === 'cash' && Number(d.priceAmount ?? d.purchasePrice ?? 0) > 270000;
  const paymentText = d.paymentMethod === 'cash' ? (cashOverLimit ? 'Внимание: цена превышает 270 000 крон; платёж наличными исключён (§ 4 Закона № 254/2004 Sb.). Стороны обязаны выбрать безналичный платёж до подписания.' : 'Наличными при подписании, не позднее физической передачи. Платёж наличными свыше 270 000 крон исключён согласно Закону № 254/2004 Sb.') : d.bankAccount ? `Банковским переводом на счёт продавца № ${pad(d.bankAccount)}${d.variableSymbol ? `, VS ${pad(d.variableSymbol)}` : ''}, в течение ${pad(d.paymentDueDays) || '3'} рабочих дней с подписания.` : `Банковским переводом на счёт продавца, реквизиты предоставлены при подписании, в течение ${pad(d.paymentDueDays) || '3'} рабочих дней с подписания.`;
  const ownershipTransfer = d.ownershipTransferMoment === 'payment' ? 'Право собственности переходит к покупателю в момент полной уплаты цены.' : 'Право собственности переходит к покупателю в момент физической передачи транспортного средства.';
  const sections: ParaPair[] = [
    { title: 'ПРЕАМБУЛА', body: ['Настоящий договор купли-продажи («Договор») заключается согласно § 2079 и далее Закона № 89/2012 Sb., Гражданский кодекс Чехии, с последующими изменениями («ГК»).', `Дата заключения: ${date(d.contractDate, 'ru-RU')}`] },
    { title: 'I. СТОРОНЫ', body: [`Продавец: ${pad(d.sellerName)}, дата рождения / IČO: ${pad(d.sellerId) || '—'}, место жительства / юридический адрес: ${pad(d.sellerAddress)}`, d.sellerOP ? `Номер удостоверения продавца: ${pad(d.sellerOP)}` : '', d.sellerEmail ? `E-mail продавца: ${pad(d.sellerEmail)}` : '', d.sellerPhone ? `Телефон продавца: ${pad(d.sellerPhone)}` : '', `Покупатель: ${pad(d.buyerName)}, дата рождения / IČO: ${pad(d.buyerId) || '—'}, место жительства / юридический адрес: ${pad(d.buyerAddress)}`, d.buyerOP ? `Номер удостоверения покупателя: ${pad(d.buyerOP)}` : '', d.buyerEmail ? `E-mail покупателя: ${pad(d.buyerEmail)}` : '', d.buyerPhone ? `Телефон покупателя: ${pad(d.buyerPhone)}` : ''] },
    { title: 'II. ПРЕДМЕТ ПОКУПКИ', body: [`Предметом покупки является моторное транспортное средство марки ${pad(d.carMake)}${d.carModel ? `, модель ${pad(d.carModel)}` : ''}.`, [d.carVIN ? `VIN (номер кузова): ${pad(d.carVIN)}` : '', d.carPlate ? `Регистрационный номер: ${pad(d.carPlate)}` : ''].filter(Boolean).join(', '), (() => { const parts = [d.carMileage ? `Показатель одометра на день подписания: ${fmtAmount(d.carMileage)} км` : '', d.carYear ? `год выпуска: ${pad(d.carYear)}` : ''].filter(Boolean); return parts.length ? `${parts.join('. ')}.` : ''; })(), d.carFirstRegistration ? `Дата первой регистрации: ${pad(d.carFirstRegistration)}.` : ''] },
    { title: 'III. ЦЕНА ПОКУПКИ, ПЛАТЁЖ И ПЕРЕХОД ПРАВА СОБСТВЕННОСТИ', body: [`Цена покупки автомобиля: ${fmtAmount(d.priceAmount ?? d.purchasePrice)} крон${d.priceWords ? ` (словами: ${pad(d.priceWords)})` : ''}.`, `Способ оплаты: ${paymentText}`, ownershipTransfer, d.handoverDate ? `Согласованная дата физической передачи: ${fmtDate(d.handoverDate, 'ru-RU')}.` : '', d.handoverPlace ? `Место передачи: ${pad(d.handoverPlace)}.` : ''] },
    { title: 'IV. ТЕХНИЧЕСКОЕ СОСТОЯНИЕ, ЗАЯВЛЕНИЯ ПРОДАВЦА И ГАРАНТИИ', body: [(() => { if (d.buyerInspectedVehicle === false) return 'Покупатель принимает к сведению, что не имел возможности в полном объёме ознакомиться с техническим состоянием транспортного средства перед подписанием; этот факт учтён при согласовании цены.'; const details: string[] = ['Покупатель подтверждает, что перед подписанием договора надлежащим образом ознакомился с техническим состоянием транспортного средства']; if (d.testDriveCompleted) details.push('совершил пробную поездку'); if (d.mechanicInspectionOffered) details.push('имел возможность проверить транспортное средство у собственного механика'); return details.join(', ') + '; транспортное средство в этом состоянии принимает (§ 2104 ГК).'; })(), `Продавец заявляет, что ему известны следующие дефекты: ${pad(d.knownDefects) || 'Никаких явных дефектов сверх обычного износа, соответствующего возрасту и пробегу'}.`, d.odometerGuaranteed === false ? 'Продавец явно не гарантирует правильность показателя одометра.' : 'Продавец заявляет, что показатель одометра соответствует его наилучшему знанию и не был неправомерно изменён.', d.isPledged ? 'Продавец указывает, что на транспортном средстве ОБРЕМЕНЕНО залоговое право — детали оговариваются отдельно.' : 'Продавец заявляет, что транспортное средство НЕ является предметом какого-либо залогового права.', d.isInLeasing ? 'Продавец указывает, что транспортное средство ЯВЛЯЕТСЯ предметом лизинга — детали оговариваются отдельно.' : 'Продавец заявляет, что транспортное средство НЕ является предметом лизинга.', d.hasThirdPartyRights ? 'На транспортном средстве ОБРЕМЕНЕНЫ права третьих лиц — детали оговариваются отдельно.' : 'Продавец заявляет, что на транспортном средстве НЕ ОБРЕМЕНЕНЫ никакие права третьих лиц.', d.strictWarranties ? 'Продавец предоставляет договорную гарантию качества 6 месяцев с передачи.' : 'Транспортное средство продаётся как подержанное; продавец не предоставляет договорную гарантию качества сверх законных рамок.'] },
    { title: 'V. ОБЯЗАННОСТИ ПОСЛЕ ПЕРЕДАЧИ И ПЕРЕРЕГИСТРАЦИЯ', body: ['Стороны обязаны незамедлительно, не позднее 15 дней с перехода права собственности, сообщить об изменении владельца соответствующему муниципальному органу (§ 8(2) Закона № 56/2001 Sb.).', 'Продавец обязан передать покупателю все документы, ключи и оборудование согласно списку.', 'Обязательное гражданское страхование переходит к покупателю в день перехода права собственности; покупатель обязан оформить новые полисы.', 'Покупатель обязан провести надлежащую проверку и сообщить явные дефекты письменно в течение 5 рабочих дней с принятия (§ 2104 ГК).'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'VI. ДЕТАЛЬНОЕ СОСТОЯНИЕ ТС И ПЕРЕДАННЫЕ ДОКУМЕНТЫ', body: [(() => { const parts = [d.carColor ? `цвет ${pad(d.carColor)}` : '', d.fuelType ? `топливо ${pad(d.fuelType)}` : '', d.engineCapacity ? `объём двигателя ${pad(d.engineCapacity)} см³` : '', d.powerKW ? `мощность ${pad(d.powerKW)} кВт` : ''].filter(Boolean); return parts.length ? `Технические данные: ${parts.join(', ')}.` : ''; })(), (() => { const parts = [d.stkValidUntil ? `ТО (СТК) действителен до ${pad(d.stkValidUntil)}` : '', d.emissionsValidUntil ? `эмиссии действительны до ${pad(d.emissionsValidUntil)}` : ''].filter(Boolean); return parts.length ? `Действительность ТО: ${parts.join(', ')}.` : ''; })(), (() => { const parts = [d.previousOwnersCount ? `количество предыдущих владельцев: ${pad(d.previousOwnersCount)}` : '', d.vehicleOrigin ? `происхождение: ${pad(d.vehicleOrigin)}` : ''].filter(Boolean); return parts.length ? `История — ${parts.join(', ')}.` : ''; })(), `Сервисная книжка: ${d.serviceHistory ? 'да, передаётся вместе с ТС' : 'не доступна'}.`, `История аварий: ${d.accidentHistory ? 'ТС был в ДТП, ремонты по документации' : 'продавцу не известны никакие ДТП'}.`, d.equipmentIncluded ? `Оборудование: ${pad(d.equipmentIncluded)}.` : 'Оборудование: по фактическому состоянию при передаче.', d.tiresInfo ? `Шины: ${pad(d.tiresInfo)}.` : '', d.documentsIncluded ? `Документы: ${pad(d.documentsIncluded)}.` : 'Документы: технический паспорт.', d.keysCount ? `Передано ключей: ${pad(d.keysCount)}.` : ''] });
    sections.push({ title: 'VII. ШТРАФЫ И ОТВЕТСТВЕННОСТЬ ЗА СКРЫТЫЕ ДЕФЕКТЫ', body: ['Продавец отвечает за дефекты, существовавшие на момент перехода риска.', d.hiddenDefectPenalty && Number(d.hiddenDefectPenalty) > 0 ? `За сознательно скрытые дефекты: штраф ${fmtAmount(d.hiddenDefectPenalty)} крон.` : 'За сознательно скрытые дефекты: полное возмещение ущерба плюс расходы на устранение.', `Штраф за просрочку оплаты покупателем: ${pad(d.buyerLatePenalty) || '0,05'}% от задолженности за день.`, d.sellerLatePenalty && Number(d.sellerLatePenalty) > 0 ? `Штраф за просрочку передачи продавцом: ${fmtAmount(d.sellerLatePenalty)} крон за день.` : 'Просрочка передачи: покупатель может требовать доказанного возмещения ущерба.', 'Продавец заявляет об отсутствии исполнения, залога или иных ограничений; ответственность по § 1728 и далее ГК.'] });
    sections.push({ title: 'VIII. СТРАХОВАНИЕ, БЕЗ ЗАДОЛЖЕННОСТЕЙ И ШТРАФЫ ПРИ ПЕРЕРЕГИСТРАЦИИ', body: ['Стороны взаимно уполномочивают друг друга на представительство в перерегистрации владельца. Если одна сторона не явится, другая может осуществить перерегистрацию самостоятельно на основании настоящего Договора.', 'Если продавец без уважительной причины не явится на перерегистрацию, обязан уплатить штраф 200 крон за каждый день просрочки.', 'С момента перехода права собственности покупатель обязан оформить новое обязательное гражданское страхование. Продавец завершает существующее страхование.', 'Продавец заявляет об отсутствии незавершённых обязательств перед лизингом, банком или иной третьей стороной.', 'Продавцу не известны текущие или нерешённые страховые события.', d.declarationPenalty && Number(d.declarationPenalty) > 0 ? `В случае неправдивости заявлений: штраф ${fmtAmount(d.declarationPenalty)} крон.` : 'В случае неправдивости заявлений: возмещение доказанного ущерба.'] });
  }
  sections.push({ title: `${hasPremium ? 'IX' : 'VI'}. ЗАКЛЮЧИТЕЛЬНЫЕ ПОЛОЖЕНИЯ`, body: ['Регулируется правом Чешской Республики, в частности Законом № 89/2012 Sb., Гражданским кодексом.', 'Споры разрешаются прежде всего мирным путём; при отсутствии соглашения — компетентным судом.', 'Договор составлен в двух экземплярах; каждая сторона получает по одному.', 'Изменения только в форме письменных, пронумерованных и подписанных дополнений.', 'Недействительность отдельного положения не влияет на действительность остальных.', 'Обработка персональных данных согласно Регламенту ЕС 2016/679 (GDPR) и Закону № 110/2019 Sb.', 'Исключение для форс-мажора (§ 2913(2) ГК).'] });
  sections.push({ title: `${hasPremium ? 'X' : 'VII'}. ПОДПИСИ`, body: [] });
  return sections;
}

function vn(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const cashOverLimit = d.paymentMethod === 'cash' && Number(d.priceAmount ?? d.purchasePrice ?? 0) > 270000;
  const paymentText = d.paymentMethod === 'cash' ? (cashOverLimit ? 'Lưu ý: giá vượt quá 270.000 crown Séc; thanh toán bằng tiền mặt bị loại trừ (§ 4 Luật số 254/2004 Sb.). Các bên phải chọn thanh toán không dùng tiền mặt trước khi ký.' : 'Bằng tiền mặt khi ký, không muộn hơn lúc bàn giao vật lý. Thanh toán bằng tiền mặt trên 270.000 crown Séc bị loại trừ theo Luật số 254/2004 Sb.') : d.bankAccount ? `Bằng chuyển khoản ngân hàng vào tài khoản của người bán số ${pad(d.bankAccount)}${d.variableSymbol ? `, VS ${pad(d.variableSymbol)}` : ''}, trong vòng ${pad(d.paymentDueDays) || '3'} ngày làm việc kể từ khi ký.` : `Bằng chuyển khoản ngân hàng vào tài khoản của người bán, thông tin chi tiết sẽ được cung cấp khi ký, trong vòng ${pad(d.paymentDueDays) || '3'} ngày làm việc kể từ khi ký.`;
  const ownershipTransfer = d.ownershipTransferMoment === 'payment' ? 'Quyền sở hữu chuyển cho người mua tại thời điểm thanh toán đầy đủ giá mua.' : 'Quyền sở hữu chuyển cho người mua tại thời điểm bàn giao vật lý phương tiện.';
  const sections: ParaPair[] = [
    { title: 'LỜI MỞ ĐẦU', body: ['Hợp đồng mua bán này ("Hợp đồng") được ký kết theo § 2079 trở đi của Luật số 89/2012 Sb., Bộ luật Dân sự Séc, có sửa đổi ("BLDS").', `Ngày ký kết: ${date(d.contractDate, 'vi-VN')}`] },
    { title: 'I. CÁC BÊN', body: [`Người bán: ${pad(d.sellerName)}, ngày sinh / IČO: ${pad(d.sellerId) || '—'}, nơi cư trú / trụ sở: ${pad(d.sellerAddress)}`, d.sellerOP ? `Số CMND người bán: ${pad(d.sellerOP)}` : '', d.sellerEmail ? `E-mail người bán: ${pad(d.sellerEmail)}` : '', d.sellerPhone ? `Điện thoại người bán: ${pad(d.sellerPhone)}` : '', `Người mua: ${pad(d.buyerName)}, ngày sinh / IČO: ${pad(d.buyerId) || '—'}, nơi cư trú / trụ sở: ${pad(d.buyerAddress)}`, d.buyerOP ? `Số CMND người mua: ${pad(d.buyerOP)}` : '', d.buyerEmail ? `E-mail người mua: ${pad(d.buyerEmail)}` : '', d.buyerPhone ? `Điện thoại người mua: ${pad(d.buyerPhone)}` : ''] },
    { title: 'II. ĐỐI TƯỢNG MUA', body: [`Đối tượng mua là phương tiện cơ giới hiệu ${pad(d.carMake)}${d.carModel ? `, model ${pad(d.carModel)}` : ''}.`, [d.carVIN ? `VIN (số khung): ${pad(d.carVIN)}` : '', d.carPlate ? `Biển số đăng ký: ${pad(d.carPlate)}` : ''].filter(Boolean).join(', '), (() => { const parts = [d.carMileage ? `Chỉ số công-tơ-mét tại ngày ký: ${fmtAmount(d.carMileage)} km` : '', d.carYear ? `năm sản xuất: ${pad(d.carYear)}` : ''].filter(Boolean); return parts.length ? `${parts.join('. ')}.` : ''; })(), d.carFirstRegistration ? `Ngày đăng ký đầu tiên: ${pad(d.carFirstRegistration)}.` : ''] },
    { title: 'III. GIÁ MUA, THANH TOÁN VÀ CHUYỂN QUYỀN SỞ HỮU', body: [`Giá mua: ${fmtAmount(d.priceAmount ?? d.purchasePrice)} crown Séc${d.priceWords ? ` (bằng chữ: ${pad(d.priceWords)})` : ''}.`, `Phương thức thanh toán: ${paymentText}`, ownershipTransfer, d.handoverDate ? `Ngày bàn giao vật lý đã thỏa thuận: ${fmtDate(d.handoverDate, 'vi-VN')}.` : '', d.handoverPlace ? `Nơi bàn giao: ${pad(d.handoverPlace)}.` : ''] },
    { title: 'IV. TÌNH TRẠNG KỸ THUẬT, TUYÊN BỐ CỦA NGƯỜI BÁN VÀ BẢO HÀNH', body: [(() => { if (d.buyerInspectedVehicle === false) return 'Người mua ghi nhận rằng đã không có cơ hội kiểm tra đầy đủ tình trạng kỹ thuật của phương tiện trước khi ký; điều này đã được phản ánh trong giá mua.'; const details: string[] = ['Người mua xác nhận đã kiểm tra hợp lệ tình trạng kỹ thuật của phương tiện trước khi ký']; if (d.testDriveCompleted) details.push('đã lái thử'); if (d.mechanicInspectionOffered) details.push('đã có cơ hội kiểm tra phương tiện với thợ máy riêng'); return details.join(', ') + '; chấp nhận phương tiện trong tình trạng này (§ 2104 BLDS).'; })(), `Người bán tuyên bố các lỗi đã biết: ${pad(d.knownDefects) || 'không có lỗi rõ ràng vượt quá hao mòn thông thường tương ứng với tuổi và quãng đường đã đi'}.`, d.odometerGuaranteed === false ? 'Người bán không bảo đảm tính chính xác của chỉ số công-tơ-mét.' : 'Người bán tuyên bố rằng chỉ số công-tơ-mét tương ứng với hiểu biết tốt nhất của người bán và không bị can thiệp.', d.isPledged ? 'Người bán nêu rằng phương tiện CÓ quyền cầm cố — chi tiết thỏa thuận riêng.' : 'Người bán tuyên bố phương tiện KHÔNG thuộc bất kỳ quyền cầm cố nào.', d.isInLeasing ? 'Người bán nêu rằng phương tiện CÓ thuê tài chính — chi tiết thỏa thuận riêng.' : 'Người bán tuyên bố phương tiện KHÔNG thuộc thuê tài chính.', d.hasThirdPartyRights ? 'Phương tiện CÓ quyền của bên thứ ba — chi tiết thỏa thuận riêng.' : 'Người bán tuyên bố phương tiện KHÔNG có quyền của bên thứ ba.', d.strictWarranties ? 'Người bán cung cấp bảo hành chất lượng hợp đồng 6 tháng kể từ ngày bàn giao.' : 'Phương tiện được bán dưới dạng đã qua sử dụng; người bán không cung cấp bảo hành chất lượng hợp đồng ngoài khuôn khổ luật định.'] },
    { title: 'V. NGHĨA VỤ SAU BÀN GIAO VÀ ĐĂNG KÝ LẠI', body: ['Các bên có nghĩa vụ, trong vòng 15 ngày kể từ ngày chuyển quyền sở hữu, thông báo cho cơ quan thành phố có thẩm quyền về sự thay đổi chủ sở hữu (§ 8(2) Luật số 56/2001 Sb.).', 'Người bán phải bàn giao cho người mua tất cả các giấy tờ, chìa khóa và thiết bị theo danh sách.', 'Bảo hiểm trách nhiệm dân sự bắt buộc chuyển sang người mua vào ngày chuyển quyền sở hữu; người mua phải ký kết hợp đồng bảo hiểm mới.', 'Người mua phải kiểm tra hợp lý sau khi nhận phương tiện và thông báo các lỗi rõ ràng bằng văn bản trong vòng 5 ngày làm việc kể từ ngày nhận (§ 2104 BLDS).'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'VI. TÌNH TRẠNG CHI TIẾT VÀ GIẤY TỜ BÀN GIAO', body: [(() => { const parts = [d.carColor ? `màu ${pad(d.carColor)}` : '', d.fuelType ? `nhiên liệu ${pad(d.fuelType)}` : '', d.engineCapacity ? `dung tích động cơ ${pad(d.engineCapacity)} cc` : '', d.powerKW ? `công suất ${pad(d.powerKW)} kW` : ''].filter(Boolean); return parts.length ? `Dữ liệu kỹ thuật: ${parts.join(', ')}.` : ''; })(), (() => { const parts = [d.stkValidUntil ? `Đăng kiểm (STK) có hiệu lực đến ${pad(d.stkValidUntil)}` : '', d.emissionsValidUntil ? `kiểm tra khí thải có hiệu lực đến ${pad(d.emissionsValidUntil)}` : ''].filter(Boolean); return parts.length ? `Hiệu lực kiểm tra kỹ thuật: ${parts.join(', ')}.` : ''; })(), (() => { const parts = [d.previousOwnersCount ? `số chủ sở hữu trước: ${pad(d.previousOwnersCount)}` : '', d.vehicleOrigin ? `nguồn gốc: ${pad(d.vehicleOrigin)}` : ''].filter(Boolean); return parts.length ? `Lịch sử — ${parts.join(', ')}.` : ''; })(), `Sổ bảo dưỡng: ${d.serviceHistory ? 'có, bàn giao cùng phương tiện' : 'không có'}.`, `Lịch sử tai nạn: ${d.accidentHistory ? 'đã có tai nạn, sửa chữa theo tài liệu dịch vụ' : 'người bán không biết tai nạn nào'}.`, d.equipmentIncluded ? `Thiết bị: ${pad(d.equipmentIncluded)}.` : 'Thiết bị: theo tình trạng thực tế khi bàn giao.', d.tiresInfo ? `Lốp: ${pad(d.tiresInfo)}.` : '', d.documentsIncluded ? `Giấy tờ: ${pad(d.documentsIncluded)}.` : 'Giấy tờ: giấy đăng ký phương tiện.', d.keysCount ? `Số chìa khóa: ${pad(d.keysCount)}.` : ''] });
    sections.push({ title: 'VII. TIỀN PHẠT VÀ TRÁCH NHIỆM ĐỐI VỚI LỖI BỊ CHE GIẤU', body: ['Người bán chịu trách nhiệm về các lỗi tồn tại tại thời điểm chuyển rủi ro.', d.hiddenDefectPenalty && Number(d.hiddenDefectPenalty) > 0 ? `Đối với lỗi bị cố ý che giấu: tiền phạt hợp đồng ${fmtAmount(d.hiddenDefectPenalty)} crown Séc.` : 'Đối với lỗi bị cố ý che giấu: bồi thường thiệt hại toàn bộ cộng chi phí sửa chữa.', `Tiền phạt cho việc chậm thanh toán của người mua: ${pad(d.buyerLatePenalty) || '0,05'}% giá trị nợ mỗi ngày chậm.`, d.sellerLatePenalty && Number(d.sellerLatePenalty) > 0 ? `Tiền phạt cho việc chậm bàn giao của người bán: ${fmtAmount(d.sellerLatePenalty)} crown Séc mỗi ngày.` : 'Chậm bàn giao: người mua có thể yêu cầu bồi thường thiệt hại được chứng minh.', 'Người bán tuyên bố không có thi hành, cầm cố hay hạn chế khác; trách nhiệm theo § 1728 trở đi BLDS.'] });
    sections.push({ title: 'VIII. BẢO HIỂM, KHÔNG NỢ VÀ TIỀN PHẠT KHI ĐĂNG KÝ LẠI', body: ['Các bên ủy quyền lẫn nhau đại diện trong việc đăng ký chuyển quyền sở hữu. Nếu một bên không có mặt, bên kia có thể tự thực hiện đăng ký dựa trên Hợp đồng này.', 'Nếu người bán không có lý do chính đáng mà không có mặt để đăng ký chuyển quyền, phải trả tiền phạt 200 crown Séc cho mỗi ngày chậm.', 'Từ thời điểm chuyển quyền sở hữu, người mua phải ký kết hợp đồng bảo hiểm trách nhiệm dân sự bắt buộc mới. Người bán chấm dứt bảo hiểm hiện có.', 'Người bán tuyên bố không có nghĩa vụ chưa hoàn thành đối với công ty cho thuê, ngân hàng hay bên thứ ba khác.', 'Người bán không biết về sự kiện bảo hiểm đang diễn ra hoặc chưa giải quyết.', d.declarationPenalty && Number(d.declarationPenalty) > 0 ? `Trong trường hợp tuyên bố sai: tiền phạt ${fmtAmount(d.declarationPenalty)} crown Séc.` : 'Trong trường hợp tuyên bố sai: bồi thường thiệt hại được chứng minh.'] });
  }
  sections.push({ title: `${hasPremium ? 'IX' : 'VI'}. ĐIỀU KHOẢN CUỐI CÙNG`, body: ['Được điều chỉnh bởi pháp luật Cộng hòa Séc, đặc biệt là Luật số 89/2012 Sb., Bộ luật Dân sự.', 'Tranh chấp được giải quyết trước hết bằng cách thân thiện; khi không thỏa thuận được, do tòa án có thẩm quyền giải quyết.', 'Hợp đồng được lập thành hai bản; mỗi bên nhận một bản.', 'Các sửa đổi chỉ có hiệu lực dưới dạng phụ lục bằng văn bản, được đánh số và ký.', 'Sự vô hiệu của một điều khoản riêng lẻ không ảnh hưởng đến hiệu lực của các điều khoản còn lại.', 'Xử lý dữ liệu cá nhân theo Quy định EU 2016/679 (GDPR) và Luật số 110/2019 Sb.', 'Ngoại lệ bất khả kháng (§ 2913(2) BLDS).'] });
  sections.push({ title: `${hasPremium ? 'X' : 'VII'}. CHỮ KÝ`, body: [] });
  return sections;
}

function de(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const cashOverLimit = d.paymentMethod === 'cash' && Number(d.priceAmount ?? d.purchasePrice ?? 0) > 270000;
  const paymentText = d.paymentMethod === 'cash' ? (cashOverLimit ? 'Hinweis: Der Kaufpreis übersteigt 270.000 CZK; Barzahlung ist ausgeschlossen (§ 4 Gesetz Nr. 254/2004 Slg.). Die Parteien müssen vor Vertragsschluss eine bargeldlose Zahlung wählen.' : 'In bar bei Vertragsschluss, spätestens bei physischer Übergabe. Barzahlung über 270.000 CZK ist nach Gesetz Nr. 254/2004 Slg. ausgeschlossen.') : d.bankAccount ? `Per Banküberweisung auf das Konto des Verkäufers Nr. ${pad(d.bankAccount)}${d.variableSymbol ? `, VS ${pad(d.variableSymbol)}` : ''}, innerhalb von ${pad(d.paymentDueDays) || '3'} Werktagen nach Vertragsschluss.` : `Per Banküberweisung auf das Konto des Verkäufers, dessen Daten bei Vertragsschluss mitgeteilt werden, innerhalb von ${pad(d.paymentDueDays) || '3'} Werktagen nach Vertragsschluss.`;
  const ownershipTransfer = d.ownershipTransferMoment === 'payment' ? 'Das Eigentum geht mit vollständiger Zahlung des Kaufpreises auf den Käufer über.' : 'Das Eigentum geht mit der physischen Übergabe des Fahrzeugs auf den Käufer über.';
  const sections: ParaPair[] = [
    { title: 'PRÄAMBEL', body: ['Dieser Kaufvertrag (der „Vertrag") wird gemäß § 2079 ff. des Gesetzes Nr. 89/2012 Slg., tschechisches BGB, in der geltenden Fassung („BGB"), geschlossen.', `Datum des Abschlusses: ${date(d.contractDate, 'de-DE')}`] },
    { title: 'I. VERTRAGSPARTEIEN', body: [`Verkäufer: ${pad(d.sellerName)}, Geburtsdatum / IČO: ${pad(d.sellerId) || '—'}, Wohnsitz / Sitz: ${pad(d.sellerAddress)}`, d.sellerOP ? `Ausweisnummer des Verkäufers: ${pad(d.sellerOP)}` : '', d.sellerEmail ? `E-Mail des Verkäufers: ${pad(d.sellerEmail)}` : '', d.sellerPhone ? `Telefon des Verkäufers: ${pad(d.sellerPhone)}` : '', `Käufer: ${pad(d.buyerName)}, Geburtsdatum / IČO: ${pad(d.buyerId) || '—'}, Wohnsitz / Sitz: ${pad(d.buyerAddress)}`, d.buyerOP ? `Ausweisnummer des Käufers: ${pad(d.buyerOP)}` : '', d.buyerEmail ? `E-Mail des Käufers: ${pad(d.buyerEmail)}` : '', d.buyerPhone ? `Telefon des Käufers: ${pad(d.buyerPhone)}` : ''] },
    { title: 'II. KAUFGEGENSTAND', body: [`Kaufgegenstand ist ein Kraftfahrzeug der Marke ${pad(d.carMake)}${d.carModel ? `, Modell ${pad(d.carModel)}` : ''}.`, [d.carVIN ? `VIN (Fahrgestellnummer): ${pad(d.carVIN)}` : '', d.carPlate ? `Kennzeichen: ${pad(d.carPlate)}` : ''].filter(Boolean).join(', '), (() => { const parts = [d.carMileage ? `Kilometerstand am Tag des Vertragsschlusses: ${fmtAmount(d.carMileage)} km` : '', d.carYear ? `Baujahr: ${pad(d.carYear)}` : ''].filter(Boolean); return parts.length ? `${parts.join('. ')}.` : ''; })(), d.carFirstRegistration ? `Datum der Erstzulassung: ${pad(d.carFirstRegistration)}.` : ''] },
    { title: 'III. KAUFPREIS, ZAHLUNG UND EIGENTUMSÜBERGANG', body: [`Kaufpreis: ${fmtAmount(d.priceAmount ?? d.purchasePrice)} CZK${d.priceWords ? ` (in Worten: ${pad(d.priceWords)})` : ''}.`, `Zahlungsweise: ${paymentText}`, ownershipTransfer, d.handoverDate ? `Vereinbartes Datum der physischen Übergabe: ${fmtDate(d.handoverDate, 'de-DE')}.` : '', d.handoverPlace ? `Übergabeort: ${pad(d.handoverPlace)}.` : ''] },
    { title: 'IV. TECHNISCHER ZUSTAND, ERKLÄRUNGEN UND GEWÄHRLEISTUNGEN', body: [(() => { if (d.buyerInspectedVehicle === false) return 'Der Käufer nimmt zur Kenntnis, dass er den technischen Zustand des Fahrzeugs vor Vertragsschluss nicht in vollem Umfang prüfen konnte; dies wurde im Kaufpreis berücksichtigt.'; const details: string[] = ['Der Käufer bestätigt, den technischen Zustand des Fahrzeugs vor Vertragsschluss ordnungsgemäß geprüft zu haben']; if (d.testDriveCompleted) details.push('absolvierte eine Probefahrt'); if (d.mechanicInspectionOffered) details.push('hatte die Möglichkeit, das Fahrzeug bei einem eigenen Mechaniker prüfen zu lassen'); return details.join(', ') + '; er nimmt das Fahrzeug in diesem Zustand an (§ 2104 BGB).'; })(), `Der Verkäufer erklärt folgende bekannte Mängel: ${pad(d.knownDefects) || 'Keine offensichtlichen Mängel über die übliche Abnutzung für Alter und Laufleistung hinaus'}.`, d.odometerGuaranteed === false ? 'Der Verkäufer garantiert die Richtigkeit des Kilometerstands ausdrücklich nicht.' : 'Der Verkäufer erklärt, dass der Kilometerstand seinem besten Wissen entspricht und nicht manipuliert wurde.', d.isPledged ? 'Der Verkäufer gibt an, dass auf dem Fahrzeug ein Pfandrecht LASTET — Details gesondert vereinbart.' : 'Der Verkäufer erklärt, dass das Fahrzeug NICHT mit einem Pfandrecht belastet ist.', d.isInLeasing ? 'Der Verkäufer gibt an, dass das Fahrzeug Gegenstand eines Leasings IST — Details gesondert vereinbart.' : 'Der Verkäufer erklärt, dass das Fahrzeug NICHT Gegenstand eines Leasings ist.', d.hasThirdPartyRights ? 'Auf dem Fahrzeug LASTEN Rechte Dritter — Details gesondert vereinbart.' : 'Der Verkäufer erklärt, dass auf dem Fahrzeug KEINE Rechte Dritter lasten.', d.strictWarranties ? 'Der Verkäufer gibt eine vertragliche Qualitätsgarantie von 6 Monaten ab Übergabe.' : 'Das Fahrzeug wird als Gebrauchtfahrzeug verkauft; der Verkäufer gewährt über den gesetzlichen Rahmen hinaus keine vertragliche Qualitätsgarantie.'] },
    { title: 'V. PFLICHTEN NACH ÜBERGABE UND UMSCHREIBUNG', body: ['Die Parteien haben unverzüglich, spätestens innerhalb von 15 Tagen nach dem Eigentumsübergang, die Änderung des Eigentümers der zuständigen Gemeindebehörde mit erweiterter Zuständigkeit zu melden (§ 8(2) Gesetz Nr. 56/2001 Slg.).', 'Der Verkäufer hat dem Käufer alle Unterlagen, Schlüssel und Ausstattung gemäß Aufstellung zu übergeben.', 'Die Kfz-Haftpflichtversicherung geht am Tag des Eigentumsübergangs auf den Käufer über; der Käufer hat neue Versicherungen abzuschließen.', 'Der Käufer hat eine angemessene Untersuchung durchzuführen und offensichtliche Mängel schriftlich unverzüglich, spätestens binnen 5 Werktagen nach Übernahme, anzuzeigen (§ 2104 BGB).'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'VI. DETAILLIERTER FAHRZEUGZUSTAND UND ÜBERGEBENE DOKUMENTE', body: [(() => { const parts = [d.carColor ? `Farbe ${pad(d.carColor)}` : '', d.fuelType ? `Kraftstoff ${pad(d.fuelType)}` : '', d.engineCapacity ? `Hubraum ${pad(d.engineCapacity)} ccm` : '', d.powerKW ? `Leistung ${pad(d.powerKW)} kW` : ''].filter(Boolean); return parts.length ? `Technische Daten: ${parts.join(', ')}.` : ''; })(), (() => { const parts = [d.stkValidUntil ? `HU (STK) gültig bis ${pad(d.stkValidUntil)}` : '', d.emissionsValidUntil ? `AU gültig bis ${pad(d.emissionsValidUntil)}` : ''].filter(Boolean); return parts.length ? `Gültigkeit der technischen Inspektion: ${parts.join(', ')}.` : ''; })(), (() => { const parts = [d.previousOwnersCount ? `Anzahl Vorbesitzer: ${pad(d.previousOwnersCount)}` : '', d.vehicleOrigin ? `Herkunft: ${pad(d.vehicleOrigin)}` : ''].filter(Boolean); return parts.length ? `Historie — ${parts.join(', ')}.` : ''; })(), `Serviceheft: ${d.serviceHistory ? 'ja, wird mit dem Fahrzeug übergeben' : 'nicht verfügbar'}.`, `Unfallhistorie: ${d.accidentHistory ? 'Fahrzeug hatte einen Unfall, Reparaturen gemäß Serviceunterlagen' : 'dem Verkäufer sind keine Unfälle bekannt'}.`, d.equipmentIncluded ? `Ausstattung: ${pad(d.equipmentIncluded)}.` : 'Ausstattung: nach tatsächlichem Zustand bei Übergabe.', d.tiresInfo ? `Reifen: ${pad(d.tiresInfo)}.` : '', d.documentsIncluded ? `Dokumente: ${pad(d.documentsIncluded)}.` : 'Dokumente: Zulassungsbescheinigung.', d.keysCount ? `Übergebene Schlüssel: ${pad(d.keysCount)}.` : ''] });
    sections.push({ title: 'VII. VERTRAGSSTRAFEN UND HAFTUNG FÜR VERSTECKTE MÄNGEL', body: ['Der Verkäufer haftet für Mängel, die zum Zeitpunkt des Gefahrübergangs vorlagen.', d.hiddenDefectPenalty && Number(d.hiddenDefectPenalty) > 0 ? `Für wissentlich verschwiegene Mängel: Vertragsstrafe ${fmtAmount(d.hiddenDefectPenalty)} CZK.` : 'Für wissentlich verschwiegene Mängel: voller Schadensersatz und Mängelbeseitigungskosten.', `Vertragsstrafe für Zahlungsverzug des Käufers: ${pad(d.buyerLatePenalty) || '0,05'}% des fälligen Betrags pro Tag.`, d.sellerLatePenalty && Number(d.sellerLatePenalty) > 0 ? `Vertragsstrafe für Übergabeverzug des Verkäufers: ${fmtAmount(d.sellerLatePenalty)} CZK pro Tag.` : 'Übergabeverzug des Verkäufers: der Käufer kann nachweisbaren Schadensersatz verlangen.', 'Der Verkäufer erklärt, dass keine Vollstreckung, kein Pfandrecht oder sonstige Verfügungsbeschränkung besteht; Haftung nach § 1728 ff. BGB.'] });
    sections.push({ title: 'VIII. VERSICHERUNG, SCHULDENFREIHEIT UND VERTRAGSSTRAFEN BEI UMSCHREIBUNG', body: ['Die Parteien bevollmächtigen sich gegenseitig zur Vertretung bei der Umschreibung des Eigentümers. Erscheint eine Partei nicht, kann die andere die Umschreibung allein auf Grundlage dieses Vertrags vornehmen.', 'Erscheint der Verkäufer ohne wichtigen Grund nicht zur Umschreibung, hat er eine Vertragsstrafe von 200 CZK pro Tag des Verzugs zu zahlen.', 'Ab dem Eigentumsübergang hat der Käufer eine neue Kfz-Haftpflichtversicherung abzuschließen. Der Verkäufer beendet die bestehende Versicherung.', 'Der Verkäufer erklärt, dass keine offenen Verbindlichkeiten gegenüber Leasinggesellschaften, Banken oder Dritten bestehen.', 'Es sind keine laufenden oder ungelösten Versicherungsfälle bekannt.', d.declarationPenalty && Number(d.declarationPenalty) > 0 ? `Bei Unrichtigkeit der Erklärungen: Vertragsstrafe ${fmtAmount(d.declarationPenalty)} CZK.` : 'Bei Unrichtigkeit der Erklärungen: nachweisbarer Schadensersatz.'] });
  }
  sections.push({ title: `${hasPremium ? 'IX' : 'VI'}. SCHLUSSBESTIMMUNGEN`, body: ['Unterliegt dem Recht der Tschechischen Republik, insbesondere dem Gesetz Nr. 89/2012 Slg., BGB.', 'Streitigkeiten werden vorrangig einvernehmlich beigelegt; sonst durch das zuständige Gericht.', 'Vertrag in zwei Ausfertigungen; jede Partei erhält eine.', 'Änderungen nur als schriftliche, nummerierte und unterzeichnete Nachträge.', 'Die Unwirksamkeit einer Bestimmung berührt die übrigen nicht.', 'Personenbezogene Daten gemäß EU-Verordnung 2016/679 (DSGVO) und Gesetz Nr. 110/2019 Slg.', 'Force-majeure-Ausnahme (§ 2913(2) BGB).'] });
  sections.push({ title: `${hasPremium ? 'X' : 'VII'}. UNTERSCHRIFTEN`, body: [] });
  return sections;
}

export function buildCarTranslationsBySection(d: StoredContractData, hasPremium: boolean): Array<NonNullable<ContractSection['translations']>> {
  return buildBilingualTranslations({
    en: () => en(d, hasPremium),
    ua: () => uk(d, hasPremium),
  });
}
