/**
 * Car purchase (kupní smlouva na vozidlo) — translations EN/UK/RU/VN/DE.
 */
import type { ContractSection, StoredContractData } from '../contracts';
import { buildBilingualTranslations, fmtAmount, fmtDate, pad, type ParaPair } from './helpers';

const date = (v: unknown, l: string) => v ? fmtDate(v, l) : new Date().toLocaleDateString(l);

function en(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const cashOverLimit = d.paymentMethod === 'cash' && Number(d.priceAmount ?? d.purchasePrice ?? 0) > 270000;
  const paymentText = d.paymentMethod === 'cash' ? (cashOverLimit ? 'Notice: the purchase price exceeds CZK 270,000; cash payment is excluded (§ 4 Act No. 254/2004 Coll.). The parties must choose a non-cash payment before signing.' : 'In cash upon signing, no later than physical handover. Cash payment above CZK 270,000 is excluded under Act No. 254/2004 Coll.') : d.bankAccount ? `By bank transfer to the seller's account no. ${pad(d.bankAccount)}${d.variableSymbol ? `, VS ${pad(d.variableSymbol)}` : ''}, within ${pad(d.paymentDueDays) || '3'} working days of signing.` : `By bank transfer to the seller's account, details provided at signing, within ${pad(d.paymentDueDays) || '3'} working days of signing.`;
  const ownershipTransfer = d.ownershipTransferMoment === 'payment' ? 'Title passes to the buyer upon full payment of the purchase price.' : 'Title passes to the buyer upon physical handover of the vehicle.';
  const sections: ParaPair[] = [
    { title: 'PREAMBLE', body: ['This purchase agreement (the "Agreement") is concluded under § 2079 et seq. of Act No. 89/2012 Coll., the Czech Civil Code, as amended (the "Civil Code").', `Date of conclusion: ${date(d.contractDate, 'en-GB')}`] },
    { title: 'I. PARTIES', body: [`Seller: ${pad(d.sellerName)}, date of birth / Company ID: ${pad(d.sellerId) || '—'}, residence / registered office: ${pad(d.sellerAddress)}`, d.sellerOP ? `Seller ID card no.: ${pad(d.sellerOP)}` : '', d.sellerEmail ? `Seller e-mail: ${pad(d.sellerEmail)}` : '', d.sellerPhone ? `Seller phone: ${pad(d.sellerPhone)}` : '', `Buyer: ${pad(d.buyerName)}, date of birth / Company ID: ${pad(d.buyerId) || '—'}, residence / registered office: ${pad(d.buyerAddress)}`, d.buyerOP ? `Buyer ID card no.: ${pad(d.buyerOP)}` : '', d.buyerEmail ? `Buyer e-mail: ${pad(d.buyerEmail)}` : '', d.buyerPhone ? `Buyer phone: ${pad(d.buyerPhone)}` : ''] },
    { title: 'II. SUBJECT OF PURCHASE', body: [`The subject of the purchase is a motor vehicle of make ${pad(d.carMake)}${d.carModel ? `, model ${pad(d.carModel)}` : ''}.`, [d.carVIN ? `VIN: ${pad(d.carVIN)}` : '', d.carPlate ? `Registration plate: ${pad(d.carPlate)}` : ''].filter(Boolean).join(', '), (() => { const parts = [d.carMileage ? `Odometer reading on signing: ${fmtAmount(d.carMileage)} km` : '', d.carYear ? `year of manufacture: ${pad(d.carYear)}` : ''].filter(Boolean); return parts.length ? `${parts.join('. ')}.` : ''; })(), d.carFirstRegistration ? `Date of first registration: ${pad(d.carFirstRegistration)}.` : ''] },
    { title: 'III. PURCHASE PRICE, PAYMENT AND TRANSFER OF TITLE', body: [`Purchase price: CZK ${fmtAmount(d.priceAmount ?? d.purchasePrice)}${d.priceWords ? ` (in words: ${pad(d.priceWords)})` : ''}.`, `Payment method: ${paymentText}`, ownershipTransfer, d.handoverDate ? `Agreed date of physical handover: ${fmtDate(d.handoverDate)}.` : '', d.handoverPlace ? `Place of handover: ${pad(d.handoverPlace)}.` : ''] },
    { title: "IV. TECHNICAL CONDITION, SELLER'S DECLARATIONS AND WARRANTIES", body: [(() => { if (d.buyerInspectedVehicle === false) return 'The buyer acknowledges not having had the opportunity to fully inspect the technical condition of the vehicle before signing; this has been reflected in the purchase price.'; const details: string[] = ['The buyer confirms having duly inspected the technical condition of the vehicle before signing']; if (d.testDriveCompleted) details.push('took a test drive'); if (d.mechanicInspectionOffered) details.push('had the opportunity to have the vehicle examined by an independent mechanic'); return details.join(', ') + '; and accepts the vehicle in this condition (§ 2104 Civil Code).'; })(), `The seller declares known defects: ${pad(d.knownDefects) || 'no apparent defects beyond ordinary wear and tear for the age and mileage'}.`, d.odometerGuaranteed === false ? 'The seller does not guarantee the correctness of the odometer reading.' : "The seller declares the odometer reading corresponds to the seller's best knowledge and has not been tampered with.", d.isPledged ? 'The seller states the vehicle IS subject to a security right — details agreed separately.' : 'The seller declares the vehicle is NOT subject to any security right.', d.isInLeasing ? 'The seller states the vehicle IS subject to a lease or other financial obligation.' : 'The seller declares the vehicle is NOT subject to a lease or other financial obligation.', d.hasThirdPartyRights ? 'The vehicle is encumbered by rights of third parties — details agreed separately.' : 'The seller declares the vehicle is NOT encumbered by third-party rights.', d.strictWarranties ? 'The seller provides a 6-month contractual quality warranty from handover.' : 'The vehicle is sold as used; the seller provides no contractual quality warranty beyond statute.'] },
    { title: 'V. DUTIES AFTER HANDOVER AND REGISTRATION TRANSFER', body: ['The parties shall, within 15 days of transfer of title, notify the change of owner to the competent municipal office (§ 8(2) Act No. 56/2001 Coll.).', 'The seller shall hand over all documents, keys and equipment as listed.', 'Compulsory motor third-party liability and any comprehensive insurance pass on the date of transfer; the buyer shall arrange new policies.', 'The buyer shall conduct a reasonable inspection and notify any apparent defects in writing within 5 working days from receipt (§ 2104 Civil Code).'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'VI. DETAILED VEHICLE CONDITION AND DOCUMENTS HANDED OVER', body: [(() => { const parts = [d.carColor ? `colour ${pad(d.carColor)}` : '', d.fuelType ? `fuel ${pad(d.fuelType)}` : '', d.engineCapacity ? `engine capacity ${pad(d.engineCapacity)} cc` : '', d.powerKW ? `power ${pad(d.powerKW)} kW` : '', d.techCardNumber ? `registration certificate no. ${pad(d.techCardNumber)}` : ''].filter(Boolean); return parts.length ? `Technical data: ${parts.join(', ')}.` : ''; })(), (() => { const parts = [d.stkValidUntil ? `MOT (STK) valid until ${pad(d.stkValidUntil)}` : '', d.emissionsValidUntil ? `emissions valid until ${pad(d.emissionsValidUntil)}` : ''].filter(Boolean); return parts.length ? `Validity of technical and emissions inspection: ${parts.join(', ')}.` : ''; })(), (() => { const parts = [d.previousOwnersCount ? `previous owners: ${pad(d.previousOwnersCount)}` : '', d.vehicleOrigin ? `origin: ${pad(d.vehicleOrigin)}` : ''].filter(Boolean); return parts.length ? `History — ${parts.join(', ')}.` : ''; })(), `Service book: ${d.serviceHistory ? 'yes, handed over with the vehicle' : 'not available'}.`, `Accident history: ${d.accidentHistory ? 'has been in an accident, repairs per service docs' : 'no accidents known to the seller'}.`, d.equipmentIncluded ? `Equipment: ${pad(d.equipmentIncluded)}.` : 'Equipment: as-is at handover.', d.tiresInfo ? `Tyres: ${pad(d.tiresInfo)}.` : '', d.documentsIncluded ? `Documents: ${pad(d.documentsIncluded)}.` : 'Documents: vehicle registration certificate.', d.keysCount ? `Keys handed over: ${pad(d.keysCount)}.` : ''] });
    sections.push({ title: 'VII. CONTRACTUAL PENALTIES AND LIABILITY FOR CONCEALED DEFECTS', body: ['The seller is liable for defects existing at the time of passing of risk.', d.hiddenDefectPenalty && Number(d.hiddenDefectPenalty) > 0 ? `For knowingly concealed defects: contractual penalty CZK ${fmtAmount(d.hiddenDefectPenalty)}.` : 'For knowingly concealed defects: full damages plus cost of remedy.', `Buyer late payment penalty: ${pad(d.buyerLatePenalty) || '0.05'}% of amount due per day.`, d.sellerLatePenalty && Number(d.sellerLatePenalty) > 0 ? `Seller handover delay penalty: CZK ${fmtAmount(d.sellerLatePenalty)} per day.` : 'Seller handover delay: buyer may claim demonstrable damages.', "The seller declares no execution, lien or other limitation; liability per § 1728 et seq. Civil Code."] });
    sections.push({ title: 'VIII. INSURANCE, DEBT-FREE STATUS AND TRANSFER PENALTIES', body: ['The parties mutually authorise each other for the registration transfer. If a party fails to appear, the other may carry out the transfer alone based on this Agreement.', "If the seller fails to attend the transfer, penalty CZK 200/day plus reasonable enforcement costs.", "From transfer of title, the buyer shall take out new compulsory motor third-party liability insurance. The seller terminates existing insurance.", 'The seller declares no outstanding obligation to leasing companies, banks or other parties from prior financing.', 'No pending or unresolved insurance events known.', d.declarationPenalty && Number(d.declarationPenalty) > 0 ? `False declaration penalty: CZK ${fmtAmount(d.declarationPenalty)}.` : 'False declarations: damages plus reasonable enforcement costs.'] });
  }
  sections.push({ title: `${hasPremium ? 'IX' : 'VI'}. FINAL PROVISIONS`, body: ['Governed by the laws of the Czech Republic, in particular Act No. 89/2012 Coll., the Civil Code.', 'Disputes shall be resolved primarily amicably; failing agreement, by the competent court.', 'Executed in two counterparts; each party receives one.', 'Amendments only as written, numbered and signed addenda.', 'Severability clause: invalidity of one provision does not affect the rest.', 'Personal data per EU Regulation 2016/679 (GDPR) and Act No. 110/2019 Coll.', 'Force majeure exception (§ 2913(2) Civil Code).'] });
  sections.push({ title: `${hasPremium ? 'X' : 'VII'}. SIGNATURES`, body: [] });
  return sections;
}

function uk(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const cashOverLimit = d.paymentMethod === 'cash' && Number(d.priceAmount ?? d.purchasePrice ?? 0) > 270000;
  const paymentText = d.paymentMethod === 'cash' ? (cashOverLimit ? 'Увага: ціна перевищує 270 000 крон; платіж готівкою виключено (§ 4 Закону № 254/2004 Sb.). Сторони повинні обрати безготівковий платіж до підпису.' : 'Готівкою при підписі, не пізніше фізичної передачі. Платіж готівкою понад 270 000 крон виключено за Законом № 254/2004 Sb.') : d.bankAccount ? `Банківським переказом на рахунок продавця № ${pad(d.bankAccount)}${d.variableSymbol ? `, VS ${pad(d.variableSymbol)}` : ''}, протягом ${pad(d.paymentDueDays) || '3'} робочих днів з підпису.` : `Банківським переказом на рахунок продавця, реквізити надано при підписі, протягом ${pad(d.paymentDueDays) || '3'} робочих днів з підпису.`;
  const ownershipTransfer = d.ownershipTransferMoment === 'payment' ? 'Право власності переходить на покупця при повній сплаті ціни.' : 'Право власності переходить на покупця при фізичній передачі транспортного засобу.';
  const sections: ParaPair[] = [
    { title: 'ПРЕАМБУЛА', body: ['Цей договір купівлі-продажу («Договір») укладається відповідно до § 2079 та наступних Закону № 89/2012 Sb., Цивільний кодекс Чехії, з наступними змінами («ЦК»).', `Дата укладення: ${date(d.contractDate, 'uk-UA')}`] },
    { title: 'I. СТОРОНИ', body: [`Продавець: ${pad(d.sellerName)}, дата народження / IČO: ${pad(d.sellerId) || '—'}, місце проживання / місцезнаходження: ${pad(d.sellerAddress)}`, d.sellerOP ? `Номер посвідчення продавця: ${pad(d.sellerOP)}` : '', d.sellerEmail ? `E-mail продавця: ${pad(d.sellerEmail)}` : '', d.sellerPhone ? `Телефон продавця: ${pad(d.sellerPhone)}` : '', `Покупець: ${pad(d.buyerName)}, дата народження / IČO: ${pad(d.buyerId) || '—'}, місце проживання / місцезнаходження: ${pad(d.buyerAddress)}`, d.buyerOP ? `Номер посвідчення покупця: ${pad(d.buyerOP)}` : '', d.buyerEmail ? `E-mail покупця: ${pad(d.buyerEmail)}` : '', d.buyerPhone ? `Телефон покупця: ${pad(d.buyerPhone)}` : ''] },
    { title: 'II. ПРЕДМЕТ КУПІВЛІ', body: [`Предметом купівлі є моторне транспортний засіб марки ${pad(d.carMake)}${d.carModel ? `, модель ${pad(d.carModel)}` : ''}.`, [d.carVIN ? `VIN (номер кузова): ${pad(d.carVIN)}` : '', d.carPlate ? `Реєстраційний номер: ${pad(d.carPlate)}` : ''].filter(Boolean).join(', '), (() => { const parts = [d.carMileage ? `Показник одометра на день підпису: ${fmtAmount(d.carMileage)} км` : '', d.carYear ? `рік випуску: ${pad(d.carYear)}` : ''].filter(Boolean); return parts.length ? `${parts.join('. ')}.` : ''; })(), d.carFirstRegistration ? `Дата першої реєстрації: ${pad(d.carFirstRegistration)}.` : ''] },
    { title: 'III. ЦІНА КУПІВЛІ, СПЛАТА І ПЕРЕХІД ПРАВА ВЛАСНОСТІ', body: [`Ціна купівлі автомобіля: ${fmtAmount(d.priceAmount ?? d.purchasePrice)} крон${d.priceWords ? ` (словами: ${pad(d.priceWords)})` : ''}.`, `Спосіб сплати: ${paymentText}`, ownershipTransfer, d.handoverDate ? `Погоджена дата фізичної передачі: ${fmtDate(d.handoverDate, 'uk-UA')}.` : '', d.handoverPlace ? `Місце передачі: ${pad(d.handoverPlace)}.` : ''] },
    { title: 'IV. ТЕХНІЧНИЙ СТАН, ЗАЯВИ ПРОДАВЦЯ ТА ГАРАНТІЇ', body: [(() => { if (d.buyerInspectedVehicle === false) return 'Покупець бере до уваги, що не мав можливості у повному обсязі ознайомитись з технічним станом транспортного засобу перед підписом; цей факт враховано при погодженні ціни.'; const details: string[] = ['Покупець підтверджує, що перед підписом договору належно ознайомився з технічним станом транспортного засобу']; if (d.testDriveCompleted) details.push('здійснив пробну поїздку'); if (d.mechanicInspectionOffered) details.push('мав можливість перевірити транспортний засіб у власного механіка'); return details.join(', ') + '; транспортний засіб у цьому стані приймає (§ 2104 ЦК).'; })(), `Продавець заявляє, що йому відомі такі дефекти: ${pad(d.knownDefects) || 'Жодних явних дефектів понад звичайне зношування, що відповідає віку та пробігу'}.`, d.odometerGuaranteed === false ? 'Продавець виразно не гарантує правильність показника одометра.' : 'Продавець заявляє, що показник одометра відповідає його найкращому знанню та не був неправомірно змінений.', d.isPledged ? 'Продавець вказує, що на транспортному засобі ОБТЯЖЕНЕ заставне право — деталі сторонуються окремо.' : 'Продавець заявляє, що транспортний засіб НЕ є предметом жодного заставного права.', d.isInLeasing ? 'Продавець вказує, що транспортний засіб Є предметом лізингу — деталі сторонуються окремо.' : 'Продавець заявляє, що транспортний засіб НЕ є предметом лізингу.', d.hasThirdPartyRights ? 'На транспортному засобі ОБТЯЖЕНІ права третіх осіб — деталі сторонуються окремо.' : 'Продавець заявляє, що на транспортному засобі НЕ ОБТЯЖЕНІ жодні права третіх осіб.', d.strictWarranties ? 'Продавець надає договірну гарантію якості 6 місяців від передачі.' : 'Транспортний засіб продається як вживаний; продавець не надає договірну гарантію якості понад законні рамки.'] },
    { title: 'V. ОБОВ\'ЯЗКИ ПІСЛЯ ПЕРЕДАЧІ ТА ПЕРЕРЕЄСТРАЦІЯ', body: ['Сторони зобов\'язані негайно, не пізніше 15 днів від переходу права власності, повідомити про зміну власника відповідному муніципальному органу (§ 8(2) Закону № 56/2001 Sb.).', 'Продавець зобов\'язаний передати покупцю всі документи, ключі та обладнання згідно з переліком.', 'Обов\'язкове цивільне страхування переходить на покупця з дня переходу права власності; покупець укладає нові поліси.', 'Покупець зобов\'язаний здійснити належну перевірку та повідомити явні дефекти письмово протягом 5 робочих днів з прийняття (§ 2104 ЦК).'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'VI. ДЕТАЛЬНИЙ СТАН ТЗ ТА ПЕРЕДАНІ ДОКУМЕНТИ', body: [(() => { const parts = [d.carColor ? `колір ${pad(d.carColor)}` : '', d.fuelType ? `паливо ${pad(d.fuelType)}` : '', d.engineCapacity ? `об\'єм двигуна ${pad(d.engineCapacity)} см³` : '', d.powerKW ? `потужність ${pad(d.powerKW)} кВт` : '', d.techCardNumber ? `номер техпаспорта ${pad(d.techCardNumber)}` : ''].filter(Boolean); return parts.length ? `Технічні дані: ${parts.join(', ')}.` : ''; })(), (() => { const parts = [d.stkValidUntil ? `СТК дійсна до ${pad(d.stkValidUntil)}` : '', d.emissionsValidUntil ? `емісії дійсні до ${pad(d.emissionsValidUntil)}` : ''].filter(Boolean); return parts.length ? `Чинність технічного огляду: ${parts.join(', ')}.` : ''; })(), (() => { const parts = [d.previousOwnersCount ? `кількість попередніх власників: ${pad(d.previousOwnersCount)}` : '', d.vehicleOrigin ? `походження: ${pad(d.vehicleOrigin)}` : ''].filter(Boolean); return parts.length ? `Історія — ${parts.join(', ')}.` : ''; })(), `Сервісна книжка: ${d.serviceHistory ? 'так, передається разом з ТЗ' : 'не доступна'}.`, `Історія аварій: ${d.accidentHistory ? 'ТЗ був у ДТП, ремонти за документацією' : 'продавцю не відомі жодні ДТП'}.`, d.equipmentIncluded ? `Обладнання: ${pad(d.equipmentIncluded)}.` : 'Обладнання: за фактичним станом при передачі.', d.tiresInfo ? `Шини: ${pad(d.tiresInfo)}.` : '', d.documentsIncluded ? `Документи: ${pad(d.documentsIncluded)}.` : 'Документи: технічний паспорт.', d.keysCount ? `Передано ключів: ${pad(d.keysCount)}.` : ''] });
    sections.push({ title: 'VII. ШТРАФИ ТА ВІДПОВІДАЛЬНІСТЬ ЗА ПРИХОВАНІ ДЕФЕКТИ', body: ['Продавець відповідає за дефекти, що існували на момент переходу ризику.', d.hiddenDefectPenalty && Number(d.hiddenDefectPenalty) > 0 ? `За свідомо приховані дефекти: штраф ${fmtAmount(d.hiddenDefectPenalty)} крон.` : 'За свідомо приховані дефекти: повне відшкодування шкоди плюс витрати на усунення.', `Штраф за прострочення сплати покупцем: ${pad(d.buyerLatePenalty) || '0,05'}% від заборгованості за день.`, d.sellerLatePenalty && Number(d.sellerLatePenalty) > 0 ? `Штраф за прострочення передачі продавцем: ${fmtAmount(d.sellerLatePenalty)} крон за день.` : 'Прострочення передачі: покупець може вимагати доведене відшкодування шкоди.', 'Продавець заявляє про відсутність виконання, застави або інших обмежень; відповідальність за § 1728 та наступних ЦК.'] });
    sections.push({ title: 'VIII. СТРАХУВАННЯ, БЕЗ ЗАБОРГОВАНОСТЕЙ ТА ШТРАФИ ПРИ ПЕРЕРЕЄСТРАЦІЇ', body: ['Сторони взаємно уповноважують одна одну на представництво у перереєстрації власника. Якщо одна сторона не з\'явиться, друга може здійснити перереєстрацію самостійно на підставі цього Договору.', 'Якщо продавець без поважної причини не з\'явиться на перереєстрацію, зобов\'язаний сплатити штраф 200 крон за кожен день прострочення.', 'З моменту переходу права власності покупець зобов\'язаний оформити нове обов\'язкове цивільне страхування. Продавець завершує існуюче страхування.', 'Продавець заявляє про відсутність незавершених зобов\'язань перед лізингом, банком або іншою третьою особою.', 'Продавцю не відомі поточні чи невирішені страхові події.', d.declarationPenalty && Number(d.declarationPenalty) > 0 ? `У разі неправдивості заяв: штраф ${fmtAmount(d.declarationPenalty)} крон.` : 'У разі неправдивості заяв: відшкодування доведеної шкоди.'] });
  }
  sections.push({ title: `${hasPremium ? 'IX' : 'VI'}. ЗАКЛЮЧНІ ПОЛОЖЕННЯ`, body: ['Регулюється правом Чеської Республіки, зокрема Законом № 89/2012 Sb., Цивільним кодексом.', 'Спори вирішуються насамперед мирним шляхом; за відсутності згоди — компетентним судом.', 'Договір складено у двох примірниках; кожна сторона отримує по одному.', 'Зміни лише у формі писемних, нумерованих і підписаних доповнень.', 'Недійсність окремого положення не впливає на дійсність решти.', 'Обробка персональних даних за Регламентом ЄС 2016/679 (GDPR) та Законом № 110/2019 Sb.', 'Виняток для форс-мажору (§ 2913(2) ЦК).'] });
  sections.push({ title: `${hasPremium ? 'X' : 'VII'}. ПІДПИСИ`, body: [] });
  return sections;
}

export function buildCarTranslationsBySection(d: StoredContractData, hasPremium: boolean): Array<NonNullable<ContractSection['translations']>> {
  return buildBilingualTranslations({
    en: () => en(d, hasPremium),
    ua: () => uk(d, hasPremium),
  });
}
