/**
 * DPP (dohoda o provedení práce) — translations EN/UA.
 */
import type { ContractSection, StoredContractData } from '../contracts';
import { buildBilingualTranslations, fmtAmount, fmtDate, pad, type ParaPair } from './helpers';
import { DPP_MONTHLY_THRESHOLD_2026_CZK, MIN_WAGE_HOURLY_2026_CZK } from '../legal-constants-2026';

const date = (v: unknown, l: string) => v ? fmtDate(v, l) : new Date().toLocaleDateString(l);

function en(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const remuneration = d.remunerationType === 'hourly'
    ? `The agreed remuneration is CZK ${fmtAmount(d.hourlyRate)} per hour. The total amount will be calculated based on actually worked hours.`
    : d.remunerationType === 'fixed' || d.totalRemuneration
    ? `The agreed remuneration for the whole task is CZK ${fmtAmount(d.totalRemuneration)}. Remuneration will be paid after the task is completed.`
    : 'The amount of remuneration will be set by mutual agreement before work begins and recorded in a written addendum.';
  const taxNote = `Insurance participation does not arise while monthly DPP income with one employer remains below CZK ${DPP_MONTHLY_THRESHOLD_2026_CZK.toLocaleString('cs-CZ')}; reaching that amount triggers participation. From 1 July 2026, the worker must be registered before work begins; a Czech worker may first be pre-registered and fully registered within 8 days, while a foreign worker must be fully registered before starting.`;
  const minimumWageNote = `Pay for hours actually worked may not be below the minimum wage; in 2026 it is at least CZK ${MIN_WAGE_HOURLY_2026_CZK.toFixed(2)} per hour.`;
  const sections: ParaPair[] = [
    { title: 'PREAMBLE', body: ['This work-completion agreement (DPP) is concluded under § 75 et seq. of Act No. 262/2006 Coll., the Czech Labour Code, as amended (the "Labour Code").', `Date of conclusion: ${date(d.contractDate, 'en-GB')}`, 'Note: The total work performed under a DPP must not exceed 300 hours per calendar year per employer (§ 75(2) Labour Code).'] },
    { title: 'I. PARTIES', body: [`Employer: ${pad(d.employerName)}, Company ID: ${pad(d.employerIco) || '—'}, registered office: ${pad(d.employerAddress)}`, d.employerEmail ? `Employer e-mail: ${pad(d.employerEmail)}` : '', `Worker: ${pad(d.employeeName)}, date of birth: ${pad(d.employeeBirth) || '—'}, residence: ${pad(d.employeeAddress)}`, d.employeeEmail ? `Worker e-mail: ${pad(d.employeeEmail)}` : ''] },
    { title: 'II. SUBJECT — DESCRIPTION OF THE WORK TASK', body: [`The worker undertakes to perform the following task (type of work): ${pad(d.taskDescription) || 'unspecified'}`, d.taskDetails ? `Detailed description: ${pad(d.taskDetails)}` : '', `Place of work: ${pad(d.workPlace) || 'unspecified'}`, `Estimated scope of work: ${pad(d.estimatedHours) || 'unspecified'} hours (max. 300 h/year per employer).`] },
    { title: 'III. TERM AND TERMINATION', body: [`The agreement is concluded for: ${d.durationType === 'fixed' && d.startDate && d.endDate ? `a fixed term from ${fmtDate(d.startDate)} to ${fmtDate(d.endDate)}` : 'an indefinite term'}`, d.deadline ? `The task must be completed no later than: ${pad(d.deadline)}` : '', 'The agreement may be terminated by written mutual agreement. Unless agreed otherwise, either party may terminate with or without giving reasons with a 15-day notice period from delivery of the notice.', 'The agreement further ends per the Labour Code — in particular by completion of the task, expiry of the agreed term, mutual agreement, or immediate termination on statutory grounds.'] },
    { title: 'IV. REMUNERATION AND PAYMENT', body: [remuneration, minimumWageNote, taxNote, d.paymentAccount ? `Remuneration will be paid to the worker's bank account no. ${pad(d.paymentAccount)} within ${pad(d.paymentDays) || '15'} days of task completion / month end.` : 'Remuneration will be paid in cash or by bank transfer.'] },
    { title: 'V. WORK CONDITIONS', body: ["The worker shall perform the agreed work personally, properly and in accordance with the employer's instructions.", 'A DPP is, in its basic scope, not subject to Labour Code provisions on working time, severance and other entitlements typical of a main employment relationship (§ 77(2) Labour Code).', "The employer shall schedule the worker's working time in a written shift schedule and acquaint the worker with it at least 3 days before the start of the shift or scheduled period.", "Work may be performed at the employer's premises, at the agreed place of work, or remotely from a place chosen by the worker where the nature of the task permits.", d.toolsProvided === 'employer' ? 'Work tools, equipment and instruments are provided by the employer.' : d.toolsProvided === 'employee' ? "The worker provides work tools at their own cost; the employer reimburses costs only where agreed in writing in advance." : 'Work tools and equipment are provided by mutual agreement of the parties.'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'VI. CONFIDENTIALITY AND INFORMATION PROTECTION', body: ['The worker shall maintain confidentiality of all confidential facts learnt in performance (business strategies, pricing, customer databases, internal processes, personal data).', 'This duty survives termination of the agreement for 2 years.', 'Liability for breach is governed by § 257 Labour Code. Contractual penalties against the worker may not be agreed under a DPP (§ 346d Labour Code).', 'Upon termination the worker shall return all documents and materials containing confidential information and erase such data from any private devices.'] });
    sections.push({ title: 'VII. INTELLECTUAL PROPERTY', body: ['Outputs of the work created by the worker are employee works within § 58 of Act No. 121/2000 Coll. The employer exercises all economic copyrights from their creation.', "The worker grants consent to adapt, process, combine and otherwise modify outputs to the extent required for their customary use.", 'The same applies to software, algorithms and technical solutions developed by the worker; source code, documentation and know-how must be handed over no later than at the end of the agreement.'] });
    sections.push({ title: 'VIII. LIABILITY FOR PROPER PERFORMANCE AND DAMAGES', body: ['If the worker fails to perform properly and on time without serious reason, the worker is liable for damage within § 257 Labour Code.', "If the worker fails to complete the task on time or to required quality, the employer may, within 5 working days of delivery, raise a written quality reservation and require free remediation within 10 working days.", 'Contractual penalties against the worker may not be agreed under a DPP. The employer may claim demonstrable damages within the statutory framework.'] });
  }
  sections.push({ title: `${hasPremium ? 'IX' : 'VI'}. FINAL PROVISIONS`, body: ['This agreement is governed by Act No. 262/2006 Coll., the Labour Code, as amended, and subsidiarily by Act No. 89/2012 Coll., the Civil Code.', 'Labour disputes shall be heard by the competent court under § 9(1) CCP.', 'Executed in two counterparts; each party receives one.', 'Amendments are valid only as written, numbered and signed addenda.', 'The invalidity of any individual provision does not affect the validity of the remaining provisions.', 'Neither party is liable for non-performance of non-monetary obligations caused by force majeure (§ 2913(2) Civil Code).'] });
  sections.push({ title: `${hasPremium ? 'X' : 'VII'}. SIGNATURES`, body: [] });
  if (hasPremium) sections.push({ title: 'ANNEX 1 – DELIVERY AND ACCEPTANCE PROTOCOL', body: [] });
  return sections;
}

function uk(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const remuneration = d.remunerationType === 'hourly' ? `Погоджена винагорода становить ${fmtAmount(d.hourlyRate)} крон за годину. Загальна сума буде розрахована на основі фактично відпрацьованих годин.` : d.remunerationType === 'fixed' || d.totalRemuneration ? `Погоджена винагорода за виконання всього завдання становить ${fmtAmount(d.totalRemuneration)} крон. Винагорода буде виплачена після виконання завдання.` : 'Розмір винагороди буде встановлено за взаємною згодою сторін до початку роботи та зафіксовано у письмовому доповненні.';
  const taxNote = `Участь у страхуванні не виникає, доки місячний дохід за DPP у одного роботодавця залишається нижчим за ${DPP_MONTHLY_THRESHOLD_2026_CZK.toLocaleString('cs-CZ')} Kč; досягнення цієї суми спричиняє участь. З 1 липня 2026 року працівника потрібно зареєструвати до початку роботи; працівника з Чехії можна спочатку попередньо зареєструвати й завершити реєстрацію протягом 8 днів, а іноземного працівника слід повністю зареєструвати до початку.`;
  const minimumWageNote = `Оплата за фактично відпрацьований час не може бути нижчою за мінімальну зарплату; у 2026 році це щонайменше ${MIN_WAGE_HOURLY_2026_CZK.toLocaleString('uk-UA', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} Kč за годину.`;
  const sections: ParaPair[] = [
    { title: 'ПРЕАМБУЛА', body: ['Ця угода про виконання роботи (DPP) укладається відповідно до § 75 та наступних Закону № 262/2006 Sb., Трудовий кодекс Чехії, з наступними змінами («ТК»).', `Дата укладення: ${date(d.contractDate, 'uk-UA')}`, 'Увага: Загальний обсяг роботи за DPP не може перевищити 300 годин у календарному році у одного роботодавця (§ 75(2) ТК).'] },
    { title: 'I. СТОРОНИ', body: [`Роботодавець: ${pad(d.employerName)}, IČO: ${pad(d.employerIco) || '—'}, місцезнаходження: ${pad(d.employerAddress)}`, d.employerEmail ? `E-mail роботодавця: ${pad(d.employerEmail)}` : '', `Працівник: ${pad(d.employeeName)}, дата народження: ${pad(d.employeeBirth) || '—'}, місце проживання: ${pad(d.employeeAddress)}`, d.employeeEmail ? `E-mail працівника: ${pad(d.employeeEmail)}` : ''] },
    { title: 'II. ПРЕДМЕТ — ОПИС РОБОЧОГО ЗАВДАННЯ', body: [`Працівник зобов\'язується виконати для роботодавця таке завдання (вид роботи): ${pad(d.taskDescription) || 'не вказано'}`, d.taskDetails ? `Детальний опис: ${pad(d.taskDetails)}` : '', `Місце виконання роботи: ${pad(d.workPlace) || 'не вказано'}`, `Очікуваний обсяг роботи: ${pad(d.estimatedHours) || 'не вказано'} годин (макс. 300 год./рік у одного роботодавця).`] },
    { title: 'III. СТРОК ДІЇ ТА ПРИПИНЕННЯ', body: [`Угода укладається на: ${d.durationType === 'fixed' && d.startDate && d.endDate ? `визначений строк з ${fmtDate(d.startDate, 'uk-UA')} до ${fmtDate(d.endDate, 'uk-UA')}` : 'невизначений строк'}`, d.deadline ? `Робоче завдання має бути виконане не пізніше: ${pad(d.deadline)}` : '', 'Угоду можна припинити письмовою згодою сторін. Якщо інше не погоджено, будь-яка зі сторін може припинити угоду з будь-якої причини або без зазначення причини з 15-денним строком попередження.', 'Угода припиняється способами, передбаченими ТК — виконанням завдання, спливом строку, згодою сторін або негайним розірванням з підстав, встановлених законом.'] },
    { title: 'IV. ВИНАГОРОДА ТА СПОСІБ ВИПЛАТИ', body: [remuneration, minimumWageNote, taxNote, d.paymentAccount ? `Винагорода буде виплачена на банківський рахунок працівника № ${pad(d.paymentAccount)} протягом ${pad(d.paymentDays) || '15'} днів після виконання завдання / закінчення місяця.` : 'Винагорода буде виплачена готівкою або банківським переказом.'] },
    { title: 'V. УМОВИ ВИКОНАННЯ РОБОТИ', body: ['Працівник зобов\'язаний виконувати погоджену роботу особисто, належно та відповідно до вказівок роботодавця.', 'На DPP в основному обсязі не поширюються положення ТК про робочий час, вихідну допомогу та інші права типові для основного трудового відношення (§ 77(2) ТК).', 'Роботодавець зобов\'язаний заздалегідь розписати робочий час працівника у письмовому графіку змін і ознайомити з ним працівника не пізніше ніж за 3 дні до початку зміни.', 'Робота може виконуватись у місцезнаходженні роботодавця, на погодженому місці виконання роботи або віддалено з місця, обраного працівником.', d.toolsProvided === 'employer' ? 'Робочі засоби, інструменти та обладнання забезпечує роботодавець.' : d.toolsProvided === 'employee' ? 'Працівник забезпечує робочі засоби за власний рахунок; роботодавець відшкодовує понесені витрати лише за попередньою письмовою згодою.' : 'Робочі засоби та обладнання забезпечують сторони за взаємною домовленістю.'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'VI. КОНФІДЕНЦІЙНІСТЬ ТА ЗАХИСТ ІНФОРМАЦІЇ', body: ['Працівник зобов\'язаний зберігати конфіденційність про всі факти, з якими ознайомлюється під час виконання угоди та які позначені як конфіденційні (бізнес-стратегії, ціни, клієнтські бази даних, внутрішні процеси, персональні дані).', 'Цей обов\'язок зберігається і після припинення угоди, протягом 2 років від її припинення.', 'Відповідальність за шкоду, заподіяну порушенням обов\'язку конфіденційності, працівник несе у обсязі § 257 ТК. Договірний штраф за рахунок працівника у DPP не сторонується (§ 346d ТК).', 'Після припинення угоди працівник зобов\'язаний повернути всі документи, носії даних та інші матеріали, які містять конфіденційну інформацію, та видалити такі дані з приватних пристроїв.'] });
    sections.push({ title: 'VII. ІНТЕЛЕКТУАЛЬНА ВЛАСНІСТЬ', body: ['Результати роботи, створені працівником у рамках виконання угоди, є службовими творами у розумінні § 58 Закону № 121/2000 Sb. Роботодавець здійснює всі майнові авторські права з моменту їх створення.', 'Працівник надає роботодавцю згоду на адаптацію, обробку, поєднання з іншим твором та інші зміни виходів у обсязі, необхідному для їхнього звичайного використання.', 'Те саме стосується і програмного забезпечення, алгоритмів і технічних рішень, розроблених працівником; працівник зобов\'язаний передати вихідні коди, документацію та know-how не пізніше припинення угоди.'] });
    sections.push({ title: 'VIII. ВІДПОВІДАЛЬНІСТЬ ЗА НАЛЕЖНЕ ВИКОНАННЯ ТА ВІДШКОДУВАННЯ ШКОДИ', body: ['Якщо працівник не виконає погоджене робоче завдання належно та своєчасно без серйозної причини на боці роботодавця, він відповідає за шкоду в обсязі § 257 ТК.', 'Якщо працівник не виконає завдання у погоджений строк або відповідної якості, роботодавець має право письмово заявити рекламацію якості протягом 5 робочих днів від передачі та вимагати безкоштовного усунення вад у строк 10 робочих днів.', 'Договірний штраф за рахунок працівника у DPP не сторонується (§ 346d ТК). Роботодавець може вимагати відшкодування доведеної шкоди у законному обсязі.'] });
  }
  sections.push({ title: `${hasPremium ? 'IX' : 'VI'}. ЗАКЛЮЧНІ ПОЛОЖЕННЯ`, body: ['Угода регулюється Законом № 262/2006 Sb., Трудовим кодексом, з наступними змінами, та субсидіарно Законом № 89/2012 Sb., Цивільним кодексом.', 'Трудові спори вирішує компетентний суд за § 9(1) ЦПК.', 'Угода складена у двох примірниках; кожна сторона отримує по одному.', 'Зміни дійсні лише у формі писемних, нумерованих і підписаних доповнень.', 'Недійсність окремого положення не впливає на дійсність решти положень.', 'Жодна сторона не відповідає за невиконання немайнових зобов\'язань, спричинене форс-мажором (§ 2913(2) ЦК).'] });
  sections.push({ title: `${hasPremium ? 'X' : 'VII'}. ПІДПИСИ`, body: [] });
  if (hasPremium) sections.push({ title: 'ДОДАТОК № 1 – ПРОТОКОЛ ПЕРЕДАЧІ ТА ПРИЙМАННЯ', body: [] });
  return sections;
}

export function buildDppTranslationsBySection(d: StoredContractData, hasPremium: boolean): Array<NonNullable<ContractSection['translations']>> {
  return buildBilingualTranslations({
    en: () => en(d, hasPremium),
    ua: () => uk(d, hasPremium),
  });
}
