/**
 * DPP (dohoda o provedení práce) — translations EN/UK/RU/VN/DE.
 */
import type { ContractSection, StoredContractData } from '../contracts';
import { buildBilingualTranslations, fmtAmount, fmtDate, pad, type ParaPair } from './helpers';

const date = (v: unknown, l: string) => v ? fmtDate(v, l) : new Date().toLocaleDateString(l);

function en(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const remuneration = d.remunerationType === 'hourly'
    ? `The agreed remuneration is CZK ${fmtAmount(d.hourlyRate)} per hour. The total amount will be calculated based on actually worked hours.`
    : d.remunerationType === 'fixed' || d.totalRemuneration
    ? `The agreed remuneration for the whole task is CZK ${fmtAmount(d.totalRemuneration)}. Remuneration will be paid after the task is completed.`
    : 'The amount of remuneration will be set by mutual agreement before work begins and recorded in a written addendum.';
  const taxNote = 'Remuneration under a DPP (work-completion agreement) is not subject to social and health insurance contributions provided that, within one employer and one calendar month, it does not exceed the statutory participation threshold. The employer reports DPP workers monthly to the Czech Social Security Administration.';
  const sections: ParaPair[] = [
    { title: 'PREAMBLE', body: ['This work-completion agreement (DPP) is concluded under § 75 et seq. of Act No. 262/2006 Coll., the Czech Labour Code, as amended (the "Labour Code").', `Date of conclusion: ${date(d.contractDate, 'en-GB')}`, 'Note: The total work performed under a DPP must not exceed 300 hours per calendar year per employer (§ 75(2) Labour Code).'] },
    { title: 'I. PARTIES', body: [`Employer: ${pad(d.employerName)}, Company ID: ${pad(d.employerIco) || '—'}, registered office: ${pad(d.employerAddress)}`, d.employerEmail ? `Employer e-mail: ${pad(d.employerEmail)}` : '', `Worker: ${pad(d.employeeName)}, date of birth: ${pad(d.employeeBirth) || '—'}, residence: ${pad(d.employeeAddress)}`, d.employeeEmail ? `Worker e-mail: ${pad(d.employeeEmail)}` : ''] },
    { title: 'II. SUBJECT — DESCRIPTION OF THE WORK TASK', body: [`The worker undertakes to perform the following task (type of work): ${pad(d.taskDescription) || 'unspecified'}`, d.taskDetails ? `Detailed description: ${pad(d.taskDetails)}` : '', `Place of work: ${pad(d.workPlace) || 'unspecified'}`, `Estimated scope of work: ${pad(d.estimatedHours) || 'unspecified'} hours (max. 300 h/year per employer).`] },
    { title: 'III. TERM AND TERMINATION', body: [`The agreement is concluded for: ${d.durationType === 'fixed' && d.startDate && d.endDate ? `a fixed term from ${fmtDate(d.startDate)} to ${fmtDate(d.endDate)}` : 'an indefinite term'}`, d.deadline ? `The task must be completed no later than: ${pad(d.deadline)}` : '', 'The agreement may be terminated by written mutual agreement. Unless agreed otherwise, either party may terminate with or without giving reasons with a 15-day notice period from delivery of the notice.', 'The agreement further ends per the Labour Code — in particular by completion of the task, expiry of the agreed term, mutual agreement, or immediate termination on statutory grounds.'] },
    { title: 'IV. REMUNERATION AND PAYMENT', body: [remuneration, taxNote, d.paymentAccount ? `Remuneration will be paid to the worker's bank account no. ${pad(d.paymentAccount)} within ${pad(d.paymentDays) || '15'} days of task completion / month end.` : 'Remuneration will be paid in cash or by bank transfer.'] },
    { title: 'V. WORK CONDITIONS', body: ["The worker shall perform the agreed work personally, properly and in accordance with the employer's instructions.", 'A DPP is, in its basic scope, not subject to Labour Code provisions on working time, severance and other entitlements typical of a main employment relationship (§ 77(2) Labour Code).', "The employer shall schedule the worker's working time in a written shift schedule and acquaint the worker with it at least 3 days before the start of the shift or scheduled period.", "Work may be performed at the employer's premises, at the agreed place of work, or remotely from a place chosen by the worker where the nature of the task permits.", d.toolsProvided === 'employer' ? 'Work tools, equipment and instruments are provided by the employer.' : d.toolsProvided === 'employee' ? "The worker provides work tools at their own cost; the employer reimburses costs only where agreed in writing in advance." : 'Work tools and equipment are provided by mutual agreement of the parties.'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'VI. CONFIDENTIALITY AND INFORMATION PROTECTION', body: ['The worker shall maintain confidentiality of all confidential facts learnt in performance (business strategies, pricing, customer databases, internal processes, personal data).', 'This duty survives termination of the agreement for 2 years.', 'Liability for breach is governed by § 257 Labour Code. Contractual penalties against the worker may not be agreed under a DPP (§ 346d Labour Code).', 'Upon termination the worker shall return all documents and materials containing confidential information and erase such data from any private devices.'] });
    sections.push({ title: 'VII. INTELLECTUAL PROPERTY', body: ['Outputs of the work created by the worker are employee works within § 58 of Act No. 121/2000 Coll. The employer exercises all economic copyrights from their creation.', "The worker grants consent to adapt, process, combine and otherwise modify outputs to the extent required for their customary use.", 'The same applies to software, algorithms and technical solutions developed by the worker; source code, documentation and know-how must be handed over no later than at the end of the agreement.'] });
    sections.push({ title: 'VIII. LIABILITY FOR PROPER PERFORMANCE AND DAMAGES', body: ['If the worker fails to perform properly and on time without serious reason, the worker is liable for damage within § 257 Labour Code.', "If the worker fails to complete the task on time or to required quality, the employer may, within 5 working days of delivery, raise a written quality reservation and require free remediation within 10 working days.", 'Contractual penalties against the worker may not be agreed under a DPP. The employer may claim demonstrable damages within the statutory framework.'] });
  }
  sections.push({ title: `${hasPremium ? 'IX' : 'VI'}. FINAL PROVISIONS`, body: ['This agreement is governed by Act No. 262/2006 Coll., the Labour Code, as amended, and subsidiarily by Act No. 89/2012 Coll., the Civil Code.', 'Labour disputes shall be heard by the competent court under § 9(1) CCP.', 'Executed in two counterparts; each party receives one.', 'Amendments are valid only as written, numbered and signed addenda.', 'The invalidity of any individual provision does not affect the validity of the remaining provisions.', "Personal data are processed under EU Regulation 2016/679 (GDPR), Act No. 110/2019 Coll. and § 316 of the Labour Code, for performance of the DPP and the employer's statutory duties.", 'Neither party is liable for non-performance of non-monetary obligations caused by force majeure (§ 2913(2) Civil Code).'] });
  sections.push({ title: `${hasPremium ? 'X' : 'VII'}. SIGNATURES`, body: [] });
  if (hasPremium) sections.push({ title: 'ANNEX 1 – DELIVERY AND ACCEPTANCE PROTOCOL', body: [] });
  return sections;
}

function uk(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const remuneration = d.remunerationType === 'hourly' ? `Погоджена винагорода становить ${fmtAmount(d.hourlyRate)} крон за годину. Загальна сума буде розрахована на основі фактично відпрацьованих годин.` : d.remunerationType === 'fixed' || d.totalRemuneration ? `Погоджена винагорода за виконання всього завдання становить ${fmtAmount(d.totalRemuneration)} крон. Винагорода буде виплачена після виконання завдання.` : 'Розмір винагороди буде встановлено за взаємною згодою сторін до початку роботи та зафіксовано у письмовому доповненні.';
  const taxNote = 'Винагорода за угодою про виконання роботи (DPP) не підлягає сплаті соціального та медичного страхування, якщо у одного роботодавця в одному календарному місяці не перевищить встановлений законом поріг для участі у страхуванні. Роботодавець щомісяця звітує про працівників за DPP до ЧССЗ.';
  const sections: ParaPair[] = [
    { title: 'ПРЕАМБУЛА', body: ['Ця угода про виконання роботи (DPP) укладається відповідно до § 75 та наступних Закону № 262/2006 Sb., Трудовий кодекс Чехії, з наступними змінами («ТК»).', `Дата укладення: ${date(d.contractDate, 'uk-UA')}`, 'Увага: Загальний обсяг роботи за DPP не може перевищити 300 годин у календарному році у одного роботодавця (§ 75(2) ТК).'] },
    { title: 'I. СТОРОНИ', body: [`Роботодавець: ${pad(d.employerName)}, IČO: ${pad(d.employerIco) || '—'}, місцезнаходження: ${pad(d.employerAddress)}`, d.employerEmail ? `E-mail роботодавця: ${pad(d.employerEmail)}` : '', `Працівник: ${pad(d.employeeName)}, дата народження: ${pad(d.employeeBirth) || '—'}, місце проживання: ${pad(d.employeeAddress)}`, d.employeeEmail ? `E-mail працівника: ${pad(d.employeeEmail)}` : ''] },
    { title: 'II. ПРЕДМЕТ — ОПИС РОБОЧОГО ЗАВДАННЯ', body: [`Працівник зобов\'язується виконати для роботодавця таке завдання (вид роботи): ${pad(d.taskDescription) || 'не вказано'}`, d.taskDetails ? `Детальний опис: ${pad(d.taskDetails)}` : '', `Місце виконання роботи: ${pad(d.workPlace) || 'не вказано'}`, `Очікуваний обсяг роботи: ${pad(d.estimatedHours) || 'не вказано'} годин (макс. 300 год./рік у одного роботодавця).`] },
    { title: 'III. СТРОК ДІЇ ТА ПРИПИНЕННЯ', body: [`Угода укладається на: ${d.durationType === 'fixed' && d.startDate && d.endDate ? `визначений строк з ${fmtDate(d.startDate, 'uk-UA')} до ${fmtDate(d.endDate, 'uk-UA')}` : 'невизначений строк'}`, d.deadline ? `Робоче завдання має бути виконане не пізніше: ${pad(d.deadline)}` : '', 'Угоду можна припинити письмовою згодою сторін. Якщо інше не погоджено, будь-яка зі сторін може припинити угоду з будь-якої причини або без зазначення причини з 15-денним строком попередження.', 'Угода припиняється способами, передбаченими ТК — виконанням завдання, спливом строку, згодою сторін або негайним розірванням з підстав, встановлених законом.'] },
    { title: 'IV. ВИНАГОРОДА ТА СПОСІБ ВИПЛАТИ', body: [remuneration, taxNote, d.paymentAccount ? `Винагорода буде виплачена на банківський рахунок працівника № ${pad(d.paymentAccount)} протягом ${pad(d.paymentDays) || '15'} днів після виконання завдання / закінчення місяця.` : 'Винагорода буде виплачена готівкою або банківським переказом.'] },
    { title: 'V. УМОВИ ВИКОНАННЯ РОБОТИ', body: ['Працівник зобов\'язаний виконувати погоджену роботу особисто, належно та відповідно до вказівок роботодавця.', 'На DPP в основному обсязі не поширюються положення ТК про робочий час, вихідну допомогу та інші права типові для основного трудового відношення (§ 77(2) ТК).', 'Роботодавець зобов\'язаний заздалегідь розписати робочий час працівника у письмовому графіку змін і ознайомити з ним працівника не пізніше ніж за 3 дні до початку зміни.', 'Робота може виконуватись у місцезнаходженні роботодавця, на погодженому місці виконання роботи або віддалено з місця, обраного працівником.', d.toolsProvided === 'employer' ? 'Робочі засоби, інструменти та обладнання забезпечує роботодавець.' : d.toolsProvided === 'employee' ? 'Працівник забезпечує робочі засоби за власний рахунок; роботодавець відшкодовує понесені витрати лише за попередньою письмовою згодою.' : 'Робочі засоби та обладнання забезпечують сторони за взаємною домовленістю.'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'VI. КОНФІДЕНЦІЙНІСТЬ ТА ЗАХИСТ ІНФОРМАЦІЇ', body: ['Працівник зобов\'язаний зберігати конфіденційність про всі факти, з якими ознайомлюється під час виконання угоди та які позначені як конфіденційні (бізнес-стратегії, ціни, клієнтські бази даних, внутрішні процеси, персональні дані).', 'Цей обов\'язок зберігається і після припинення угоди, протягом 2 років від її припинення.', 'Відповідальність за шкоду, заподіяну порушенням обов\'язку конфіденційності, працівник несе у обсязі § 257 ТК. Договірний штраф за рахунок працівника у DPP не сторонується (§ 346d ТК).', 'Після припинення угоди працівник зобов\'язаний повернути всі документи, носії даних та інші матеріали, які містять конфіденційну інформацію, та видалити такі дані з приватних пристроїв.'] });
    sections.push({ title: 'VII. ІНТЕЛЕКТУАЛЬНА ВЛАСНІСТЬ', body: ['Результати роботи, створені працівником у рамках виконання угоди, є службовими творами у розумінні § 58 Закону № 121/2000 Sb. Роботодавець здійснює всі майнові авторські права з моменту їх створення.', 'Працівник надає роботодавцю згоду на адаптацію, обробку, поєднання з іншим твором та інші зміни виходів у обсязі, необхідному для їхнього звичайного використання.', 'Те саме стосується і програмного забезпечення, алгоритмів і технічних рішень, розроблених працівником; працівник зобов\'язаний передати вихідні коди, документацію та know-how не пізніше припинення угоди.'] });
    sections.push({ title: 'VIII. ВІДПОВІДАЛЬНІСТЬ ЗА НАЛЕЖНЕ ВИКОНАННЯ ТА ВІДШКОДУВАННЯ ШКОДИ', body: ['Якщо працівник не виконає погоджене робоче завдання належно та своєчасно без серйозної причини на боці роботодавця, він відповідає за шкоду в обсязі § 257 ТК.', 'Якщо працівник не виконає завдання у погоджений строк або відповідної якості, роботодавець має право письмово заявити рекламацію якості протягом 5 робочих днів від передачі та вимагати безкоштовного усунення вад у строк 10 робочих днів.', 'Договірний штраф за рахунок працівника у DPP не сторонується (§ 346d ТК). Роботодавець може вимагати відшкодування доведеної шкоди у законному обсязі.'] });
  }
  sections.push({ title: `${hasPremium ? 'IX' : 'VI'}. ЗАКЛЮЧНІ ПОЛОЖЕННЯ`, body: ['Угода регулюється Законом № 262/2006 Sb., Трудовим кодексом, з наступними змінами, та субсидіарно Законом № 89/2012 Sb., Цивільним кодексом.', 'Трудові спори вирішує компетентний суд за § 9(1) ЦПК.', 'Угода складена у двох примірниках; кожна сторона отримує по одному.', 'Зміни дійсні лише у формі писемних, нумерованих і підписаних доповнень.', 'Недійсність окремого положення не впливає на дійсність решти положень.', 'Обробка персональних даних здійснюється за Регламентом ЄС 2016/679 (GDPR), Законом № 110/2019 Sb. та § 316 ТК.', 'Жодна сторона не відповідає за невиконання немайнових зобов\'язань, спричинене форс-мажором (§ 2913(2) ЦК).'] });
  sections.push({ title: `${hasPremium ? 'X' : 'VII'}. ПІДПИСИ`, body: [] });
  if (hasPremium) sections.push({ title: 'ДОДАТОК № 1 – ПРОТОКОЛ ПЕРЕДАЧІ ТА ПРИЙМАННЯ', body: [] });
  return sections;
}

function ru(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const remuneration = d.remunerationType === 'hourly' ? `Согласованное вознаграждение составляет ${fmtAmount(d.hourlyRate)} крон за час. Общая сумма будет рассчитана на основе фактически отработанных часов.` : d.remunerationType === 'fixed' || d.totalRemuneration ? `Согласованное вознаграждение за выполнение всей задачи составляет ${fmtAmount(d.totalRemuneration)} крон. Вознаграждение будет выплачено после выполнения задачи.` : 'Размер вознаграждения будет установлен по взаимному согласию сторон до начала работы и зафиксирован в письменном дополнении.';
  const taxNote = 'Вознаграждение по соглашению о выполнении работы (DPP) не подлежит уплате социального и медицинского страхования, если у одного работодателя в одном календарном месяце не превысит установленный законом порог для участия в страховании. Работодатель ежемесячно отчитывается о работниках по DPP в ЧССЗ.';
  const sections: ParaPair[] = [
    { title: 'ПРЕАМБУЛА', body: ['Настоящее соглашение о выполнении работы (DPP) заключается согласно § 75 и далее Закона № 262/2006 Sb., Трудовой кодекс Чехии, с последующими изменениями («ТК»).', `Дата заключения: ${date(d.contractDate, 'ru-RU')}`, 'Внимание: Общий объём работы по DPP не может превысить 300 часов в календарном году у одного работодателя (§ 75(2) ТК).'] },
    { title: 'I. СТОРОНЫ', body: [`Работодатель: ${pad(d.employerName)}, IČO: ${pad(d.employerIco) || '—'}, юридический адрес: ${pad(d.employerAddress)}`, d.employerEmail ? `E-mail работодателя: ${pad(d.employerEmail)}` : '', `Работник: ${pad(d.employeeName)}, дата рождения: ${pad(d.employeeBirth) || '—'}, место жительства: ${pad(d.employeeAddress)}`, d.employeeEmail ? `E-mail работника: ${pad(d.employeeEmail)}` : ''] },
    { title: 'II. ПРЕДМЕТ — ОПИСАНИЕ РАБОЧЕЙ ЗАДАЧИ', body: [`Работник обязуется выполнить для работодателя следующую задачу (вид работы): ${pad(d.taskDescription) || 'не указано'}`, d.taskDetails ? `Детальное описание: ${pad(d.taskDetails)}` : '', `Место выполнения работы: ${pad(d.workPlace) || 'не указано'}`, `Предполагаемый объём работы: ${pad(d.estimatedHours) || 'не указано'} часов (макс. 300 ч./год у одного работодателя).`] },
    { title: 'III. СРОК ДЕЙСТВИЯ И ПРЕКРАЩЕНИЕ', body: [`Соглашение заключается на: ${d.durationType === 'fixed' && d.startDate && d.endDate ? `определённый срок с ${fmtDate(d.startDate, 'ru-RU')} по ${fmtDate(d.endDate, 'ru-RU')}` : 'неопределённый срок'}`, d.deadline ? `Рабочая задача должна быть выполнена не позднее: ${pad(d.deadline)}` : '', 'Соглашение можно расторгнуть письменным согласием сторон. Если иное не согласовано, любая из сторон может расторгнуть соглашение по любой причине или без указания причины с 15-дневным сроком уведомления.', 'Соглашение прекращается способами, предусмотренными ТК — выполнением задачи, истечением срока, согласием сторон или немедленным расторжением по основаниям, установленным законом.'] },
    { title: 'IV. ВОЗНАГРАЖДЕНИЕ И СПОСОБ ВЫПЛАТЫ', body: [remuneration, taxNote, d.paymentAccount ? `Вознаграждение будет выплачено на банковский счёт работника № ${pad(d.paymentAccount)} в течение ${pad(d.paymentDays) || '15'} дней после выполнения задачи / окончания месяца.` : 'Вознаграждение будет выплачено наличными или банковским переводом.'] },
    { title: 'V. УСЛОВИЯ ВЫПОЛНЕНИЯ РАБОТЫ', body: ['Работник обязан выполнять согласованную работу лично, надлежащим образом и в соответствии с указаниями работодателя.', 'На DPP в основном объёме не распространяются положения ТК о рабочем времени, выходном пособии и иных правах типичных для основного трудового отношения (§ 77(2) ТК).', 'Работодатель обязан заранее расписать рабочее время работника в письменном графике смен и ознакомить с ним работника не позднее чем за 3 дня до начала смены.', 'Работа может выполняться в месте нахождения работодателя, на согласованном месте выполнения работы или удалённо из места, выбранного работником.', d.toolsProvided === 'employer' ? 'Рабочие средства, инструменты и оборудование обеспечивает работодатель.' : d.toolsProvided === 'employee' ? 'Работник обеспечивает рабочие средства за свой счёт; работодатель возмещает понесённые расходы только при предварительном письменном согласии.' : 'Рабочие средства и оборудование обеспечивают стороны по взаимной договорённости.'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'VI. КОНФИДЕНЦИАЛЬНОСТЬ И ЗАЩИТА ИНФОРМАЦИИ', body: ['Работник обязан сохранять конфиденциальность о всех фактах, с которыми знакомится при выполнении соглашения и которые обозначены как конфиденциальные (бизнес-стратегии, цены, клиентские базы данных, внутренние процессы, персональные данные).', 'Эта обязанность сохраняется и после прекращения соглашения, в течение 2 лет с его прекращения.', 'Ответственность за ущерб, причинённый нарушением обязанности конфиденциальности, работник несёт в объёме § 257 ТК. Договорный штраф в счёт работника в DPP не оговаривается (§ 346d ТК).', 'После прекращения соглашения работник обязан вернуть все документы, носители данных и иные материалы, содержащие конфиденциальную информацию, и удалить такие данные с частных устройств.'] });
    sections.push({ title: 'VII. ИНТЕЛЛЕКТУАЛЬНАЯ СОБСТВЕННОСТЬ', body: ['Результаты работы, созданные работником в рамках выполнения соглашения, являются служебными произведениями в смысле § 58 Закона № 121/2000 Sb. Работодатель осуществляет все имущественные авторские права с момента их создания.', 'Работник предоставляет работодателю согласие на адаптацию, обработку, объединение с другим произведением и иные изменения выходов в объёме, необходимом для их обычного использования.', 'То же относится и к программному обеспечению, алгоритмам и техническим решениям, разработанным работником; работник обязан передать исходные коды, документацию и know-how не позднее прекращения соглашения.'] });
    sections.push({ title: 'VIII. ОТВЕТСТВЕННОСТЬ ЗА НАДЛЕЖАЩЕЕ ВЫПОЛНЕНИЕ И ВОЗМЕЩЕНИЕ УЩЕРБА', body: ['Если работник не выполнит согласованную задачу надлежащим образом и своевременно без серьёзной причины на стороне работодателя, он отвечает за ущерб в объёме § 257 ТК.', 'Если работник не выполнит задачу в согласованный срок или соответствующего качества, работодатель вправе письменно заявить рекламацию качества в течение 5 рабочих дней с передачи и требовать бесплатного устранения недостатков в срок 10 рабочих дней.', 'Договорный штраф в счёт работника в DPP не оговаривается (§ 346d ТК). Работодатель может требовать возмещения доказанного ущерба в законном объёме.'] });
  }
  sections.push({ title: `${hasPremium ? 'IX' : 'VI'}. ЗАКЛЮЧИТЕЛЬНЫЕ ПОЛОЖЕНИЯ`, body: ['Соглашение регулируется Законом № 262/2006 Sb., Трудовым кодексом, с последующими изменениями, и субсидиарно Законом № 89/2012 Sb., Гражданским кодексом.', 'Трудовые споры разрешает компетентный суд по § 9(1) ГПК.', 'Соглашение составлено в двух экземплярах; каждая сторона получает по одному.', 'Изменения действительны только в форме письменных, пронумерованных и подписанных дополнений.', 'Недействительность отдельного положения не влияет на действительность остальных положений.', 'Обработка персональных данных осуществляется согласно Регламенту ЕС 2016/679 (GDPR), Закону № 110/2019 Sb. и § 316 ТК.', 'Ни одна из сторон не отвечает за неисполнение неимущественных обязательств, вызванное форс-мажором (§ 2913(2) ГК).'] });
  sections.push({ title: `${hasPremium ? 'X' : 'VII'}. ПОДПИСИ`, body: [] });
  if (hasPremium) sections.push({ title: 'ПРИЛОЖЕНИЕ № 1 – ПРОТОКОЛ ПЕРЕДАЧИ И ПРИЁМКИ', body: [] });
  return sections;
}

function vn(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const remuneration = d.remunerationType === 'hourly' ? `Mức thù lao đã thỏa thuận là ${fmtAmount(d.hourlyRate)} crown Séc mỗi giờ. Tổng số sẽ được tính dựa trên số giờ thực tế đã làm việc.` : d.remunerationType === 'fixed' || d.totalRemuneration ? `Mức thù lao thỏa thuận cho toàn bộ nhiệm vụ là ${fmtAmount(d.totalRemuneration)} crown Séc. Thù lao sẽ được thanh toán sau khi nhiệm vụ hoàn thành.` : 'Mức thù lao sẽ được hai bên thỏa thuận trước khi bắt đầu công việc và ghi nhận trong phụ lục bằng văn bản.';
  const taxNote = 'Thù lao theo thỏa thuận thực hiện công việc (DPP) không phải chịu đóng góp bảo hiểm xã hội và y tế nếu trong một tháng dương lịch ở một người sử dụng lao động không vượt quá mức ngưỡng tham gia bảo hiểm theo luật. Người sử dụng lao động báo cáo nhân viên DPP hàng tháng cho Cơ quan An sinh Xã hội Séc (ČSSZ).';
  const sections: ParaPair[] = [
    { title: 'LỜI MỞ ĐẦU', body: ['Thỏa thuận thực hiện công việc này (DPP) được ký kết theo § 75 trở đi của Luật số 262/2006 Sb., Bộ luật Lao động Séc, có sửa đổi ("BLLĐ").', `Ngày ký kết: ${date(d.contractDate, 'vi-VN')}`, 'Lưu ý: Tổng thời gian làm việc theo DPP không được vượt quá 300 giờ mỗi năm dương lịch tại một người sử dụng lao động (§ 75(2) BLLĐ).'] },
    { title: 'I. CÁC BÊN', body: [`Người sử dụng lao động: ${pad(d.employerName)}, IČO: ${pad(d.employerIco) || '—'}, trụ sở: ${pad(d.employerAddress)}`, d.employerEmail ? `E-mail người sử dụng lao động: ${pad(d.employerEmail)}` : '', `Người lao động: ${pad(d.employeeName)}, ngày sinh: ${pad(d.employeeBirth) || '—'}, nơi cư trú: ${pad(d.employeeAddress)}`, d.employeeEmail ? `E-mail người lao động: ${pad(d.employeeEmail)}` : ''] },
    { title: 'II. ĐỐI TƯỢNG — MÔ TẢ NHIỆM VỤ CÔNG VIỆC', body: [`Người lao động cam kết thực hiện cho người sử dụng lao động nhiệm vụ sau (loại công việc): ${pad(d.taskDescription) || 'chưa nêu rõ'}`, d.taskDetails ? `Mô tả chi tiết: ${pad(d.taskDetails)}` : '', `Nơi làm việc: ${pad(d.workPlace) || 'chưa nêu rõ'}`, `Khối lượng công việc dự kiến: ${pad(d.estimatedHours) || 'chưa nêu rõ'} giờ (tối đa 300 giờ/năm tại một người sử dụng lao động).`] },
    { title: 'III. THỜI HẠN VÀ CHẤM DỨT', body: [`Thỏa thuận được ký kết với: ${d.durationType === 'fixed' && d.startDate && d.endDate ? `thời hạn xác định từ ${fmtDate(d.startDate, 'vi-VN')} đến ${fmtDate(d.endDate, 'vi-VN')}` : 'thời hạn không xác định'}`, d.deadline ? `Nhiệm vụ công việc phải được hoàn thành chậm nhất vào: ${pad(d.deadline)}` : '', 'Thỏa thuận có thể chấm dứt bằng văn bản thỏa thuận của các bên. Trừ khi có thỏa thuận khác, bất kỳ bên nào cũng có thể chấm dứt với bất kỳ lý do nào hoặc không cần nêu lý do với thời hạn thông báo 15 ngày kể từ ngày giao thông báo.', 'Thỏa thuận cũng chấm dứt theo các phương thức được BLLĐ quy định — đặc biệt là hoàn thành nhiệm vụ, hết thời hạn, thỏa thuận của các bên hoặc hủy bỏ ngay lập tức theo căn cứ luật định.'] },
    { title: 'IV. THÙ LAO VÀ PHƯƠNG THỨC THANH TOÁN', body: [remuneration, taxNote, d.paymentAccount ? `Thù lao sẽ được trả vào tài khoản ngân hàng số ${pad(d.paymentAccount)} của người lao động trong vòng ${pad(d.paymentDays) || '15'} ngày sau khi hoàn thành nhiệm vụ / kết thúc tháng.` : 'Thù lao sẽ được trả bằng tiền mặt hoặc chuyển khoản ngân hàng.'] },
    { title: 'V. ĐIỀU KIỆN THỰC HIỆN CÔNG VIỆC', body: ['Người lao động phải tự mình thực hiện công việc đã thỏa thuận, đúng cách và phù hợp với chỉ dẫn của người sử dụng lao động.', 'DPP trong phạm vi cơ bản không áp dụng các quy định của BLLĐ về thời giờ làm việc, trợ cấp thôi việc và các quyền lợi khác điển hình của quan hệ lao động chính (§ 77(2) BLLĐ).', 'Người sử dụng lao động phải lên lịch trình làm việc của người lao động bằng lịch ca làm việc viết và thông báo cho người lao động chậm nhất 3 ngày trước khi bắt đầu ca.', 'Công việc có thể được thực hiện tại trụ sở của người sử dụng lao động, tại địa điểm làm việc đã thỏa thuận hoặc từ xa từ nơi do người lao động chọn nếu tính chất nhiệm vụ cho phép.', d.toolsProvided === 'employer' ? 'Dụng cụ làm việc, thiết bị và công cụ do người sử dụng lao động cung cấp.' : d.toolsProvided === 'employee' ? 'Người lao động cung cấp dụng cụ làm việc bằng chi phí của mình; người sử dụng lao động chỉ hoàn trả chi phí phát sinh nếu đã thỏa thuận trước bằng văn bản.' : 'Dụng cụ làm việc và thiết bị do các bên thỏa thuận cung cấp.'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'VI. BẢO MẬT VÀ BẢO VỆ THÔNG TIN', body: ['Người lao động có nghĩa vụ giữ bí mật về tất cả các sự kiện được biết trong quá trình thực hiện thỏa thuận và được đánh dấu là bí mật (chiến lược kinh doanh, giá cả, cơ sở dữ liệu khách hàng, quy trình nội bộ, dữ liệu cá nhân).', 'Nghĩa vụ này còn tồn tại sau khi chấm dứt thỏa thuận, trong vòng 2 năm.', 'Trách nhiệm về thiệt hại do vi phạm nghĩa vụ bảo mật được điều chỉnh theo § 257 BLLĐ. Tiền phạt hợp đồng đối với người lao động không được thỏa thuận trong DPP (§ 346d BLLĐ).', 'Sau khi chấm dứt thỏa thuận, người lao động phải trả lại tất cả các tài liệu, phương tiện lưu trữ và các tài liệu khác chứa thông tin bí mật và xóa dữ liệu đó khỏi thiết bị cá nhân.'] });
    sections.push({ title: 'VII. SỞ HỮU TRÍ TUỆ', body: ['Kết quả công việc do người lao động tạo ra trong khuôn khổ thực hiện thỏa thuận là tác phẩm của nhân viên theo § 58 của Luật số 121/2000 Sb. Người sử dụng lao động thực hiện tất cả các quyền tác giả về tài sản từ thời điểm tạo ra.', 'Người lao động đồng ý cho người sử dụng lao động sửa đổi, xử lý, kết hợp với tác phẩm khác và các thay đổi khác đối với kết quả đầu ra ở mức độ cần thiết cho việc sử dụng thông thường.', 'Điều tương tự cũng áp dụng cho phần mềm, thuật toán và giải pháp kỹ thuật do người lao động phát triển; người lao động phải bàn giao mã nguồn, tài liệu và know-how chậm nhất vào ngày chấm dứt thỏa thuận.'] });
    sections.push({ title: 'VIII. TRÁCH NHIỆM VÀ BỒI THƯỜNG THIỆT HẠI', body: ['Nếu người lao động không thực hiện nhiệm vụ đúng cách và đúng thời hạn mà không có lý do nghiêm trọng từ phía người sử dụng lao động, sẽ chịu trách nhiệm về thiệt hại theo § 257 BLLĐ.', 'Nếu người lao động không hoàn thành nhiệm vụ trong thời hạn đã thỏa thuận hoặc theo chất lượng yêu cầu, người sử dụng lao động có thể trong vòng 5 ngày làm việc kể từ ngày bàn giao đưa ra yêu cầu chất lượng bằng văn bản và yêu cầu sửa chữa miễn phí trong thời hạn 10 ngày làm việc.', 'Tiền phạt hợp đồng đối với người lao động không được thỏa thuận trong DPP. Người sử dụng lao động có thể yêu cầu bồi thường thiệt hại đã chứng minh trong khuôn khổ luật định.'] });
  }
  sections.push({ title: `${hasPremium ? 'IX' : 'VI'}. ĐIỀU KHOẢN CUỐI CÙNG`, body: ['Thỏa thuận này được điều chỉnh bởi Luật số 262/2006 Sb., Bộ luật Lao động, có sửa đổi, và bổ sung bởi Luật số 89/2012 Sb., Bộ luật Dân sự.', 'Tranh chấp lao động do tòa án có thẩm quyền xét xử theo § 9(1) BLTTDS.', 'Thỏa thuận được lập thành hai bản; mỗi bên nhận một bản.', 'Các sửa đổi chỉ có hiệu lực dưới dạng phụ lục bằng văn bản, được đánh số và ký.', 'Sự vô hiệu của một điều khoản riêng lẻ không ảnh hưởng đến hiệu lực của các điều khoản còn lại.', 'Việc xử lý dữ liệu cá nhân tuân thủ Quy định EU 2016/679 (GDPR), Luật số 110/2019 Sb. và § 316 BLLĐ.', 'Không bên nào chịu trách nhiệm về việc không thực hiện các nghĩa vụ phi tiền tệ do bất khả kháng (§ 2913(2) BLDS).'] });
  sections.push({ title: `${hasPremium ? 'X' : 'VII'}. CHỮ KÝ`, body: [] });
  if (hasPremium) sections.push({ title: 'PHỤ LỤC 1 – BIÊN BẢN BÀN GIAO VÀ NGHIỆM THU', body: [] });
  return sections;
}

function de(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const remuneration = d.remunerationType === 'hourly' ? `Die vereinbarte Vergütung beträgt ${fmtAmount(d.hourlyRate)} CZK pro Stunde. Der Gesamtbetrag wird auf Grundlage der tatsächlich geleisteten Stunden berechnet.` : d.remunerationType === 'fixed' || d.totalRemuneration ? `Die vereinbarte Vergütung für die gesamte Aufgabe beträgt ${fmtAmount(d.totalRemuneration)} CZK. Die Vergütung wird nach Erfüllung der Aufgabe gezahlt.` : 'Die Höhe der Vergütung wird in einvernehmlicher Vereinbarung vor Arbeitsbeginn festgelegt und in einem schriftlichen Nachtrag festgehalten.';
  const taxNote = 'Die Vergütung aus dem DPP (Arbeitsleistungsvereinbarung) unterliegt nicht den Beiträgen zur Sozial- und Krankenversicherung, sofern sie bei einem Arbeitgeber in einem Kalendermonat nicht den gesetzlich festgelegten Schwellenwert für die Versicherungspflicht überschreitet. Der Arbeitgeber meldet die DPP-Arbeitnehmer monatlich an die ČSSZ.';
  const sections: ParaPair[] = [
    { title: 'PRÄAMBEL', body: ['Diese Arbeitsleistungsvereinbarung (DPP) wird gemäß § 75 ff. des Gesetzes Nr. 262/2006 Slg., tschechisches Arbeitsgesetzbuch, in der geltenden Fassung („AGB"), geschlossen.', `Datum des Abschlusses: ${date(d.contractDate, 'de-DE')}`, 'Hinweis: Der gesamte Arbeitsumfang im Rahmen eines DPP darf bei einem Arbeitgeber 300 Stunden pro Kalenderjahr nicht übersteigen (§ 75(2) AGB).'] },
    { title: 'I. VERTRAGSPARTEIEN', body: [`Arbeitgeber: ${pad(d.employerName)}, IČO: ${pad(d.employerIco) || '—'}, eingetragener Sitz: ${pad(d.employerAddress)}`, d.employerEmail ? `E-Mail des Arbeitgebers: ${pad(d.employerEmail)}` : '', `Arbeitnehmer: ${pad(d.employeeName)}, Geburtsdatum: ${pad(d.employeeBirth) || '—'}, Wohnsitz: ${pad(d.employeeAddress)}`, d.employeeEmail ? `E-Mail des Arbeitnehmers: ${pad(d.employeeEmail)}` : ''] },
    { title: 'II. GEGENSTAND — BESCHREIBUNG DER ARBEITSAUFGABE', body: [`Der Arbeitnehmer verpflichtet sich, für den Arbeitgeber folgende Aufgabe (Art der Arbeit) zu erbringen: ${pad(d.taskDescription) || 'nicht angegeben'}`, d.taskDetails ? `Detaillierte Beschreibung: ${pad(d.taskDetails)}` : '', `Arbeitsort: ${pad(d.workPlace) || 'nicht angegeben'}`, `Voraussichtlicher Arbeitsumfang: ${pad(d.estimatedHours) || 'nicht angegeben'} Stunden (max. 300 h/Jahr bei einem Arbeitgeber).`] },
    { title: 'III. LAUFZEIT UND BEENDIGUNG', body: [`Die Vereinbarung wird auf ${d.durationType === 'fixed' && d.startDate && d.endDate ? `bestimmte Zeit vom ${fmtDate(d.startDate, 'de-DE')} bis ${fmtDate(d.endDate, 'de-DE')}` : 'unbestimmte Zeit'} geschlossen.`, d.deadline ? `Die Arbeitsaufgabe ist spätestens bis zum ${pad(d.deadline)} zu erfüllen.` : '', 'Die Vereinbarung kann durch schriftliche Vereinbarung der Parteien beendet werden. Sofern nichts anderes vereinbart ist, kann jede Partei die Vereinbarung aus beliebigem Grund oder ohne Angabe von Gründen mit einer Kündigungsfrist von 15 Tagen ab Zustellung der Kündigung kündigen.', 'Die Vereinbarung endet ferner nach dem AGB — insbesondere durch Erfüllung der Aufgabe, Ablauf der vereinbarten Zeit, Vereinbarung der Parteien oder fristlose Aufhebung aus gesetzlichen Gründen.'] },
    { title: 'IV. VERGÜTUNG UND ZAHLUNG', body: [remuneration, taxNote, d.paymentAccount ? `Die Vergütung wird auf das Bankkonto des Arbeitnehmers Nr. ${pad(d.paymentAccount)} innerhalb von ${pad(d.paymentDays) || '15'} Tagen nach Erfüllung der Aufgabe / Monatsende gezahlt.` : 'Die Vergütung wird bar oder per Banküberweisung gezahlt.'] },
    { title: 'V. ARBEITSBEDINGUNGEN', body: ['Der Arbeitnehmer hat die vereinbarte Arbeit persönlich, ordnungsgemäß und nach den Weisungen des Arbeitgebers zu erbringen.', 'Auf den DPP finden im Grundumfang die AGB-Bestimmungen über Arbeitszeit, Abfindung und sonstige für ein Hauptarbeitsverhältnis typische Ansprüche keine Anwendung (§ 77(2) AGB).', 'Der Arbeitgeber hat die Arbeitszeit des Arbeitnehmers im Voraus in einem schriftlichen Schichtplan einzuteilen und den Arbeitnehmer mindestens 3 Tage vor Schichtbeginn damit vertraut zu machen.', 'Die Arbeit kann am Sitz des Arbeitgebers, am vereinbarten Arbeitsort oder remote von einem vom Arbeitnehmer gewählten Ort erbracht werden, sofern die Art der Aufgabe dies zulässt.', d.toolsProvided === 'employer' ? 'Arbeitsmittel, Werkzeuge und Ausrüstung stellt der Arbeitgeber zur Verfügung.' : d.toolsProvided === 'employee' ? 'Der Arbeitnehmer stellt Arbeitsmittel auf eigene Kosten bereit; der Arbeitgeber erstattet nachweislich entstandene Kosten nur, wenn dies im Voraus schriftlich vereinbart wurde.' : 'Arbeitsmittel und Ausrüstung werden von den Parteien einvernehmlich bereitgestellt.'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'VI. VERTRAULICHKEIT UND INFORMATIONSSCHUTZ', body: ['Der Arbeitnehmer hat Stillschweigen über alle Tatsachen zu bewahren, mit denen er bei der Durchführung der Vereinbarung in Berührung kommt und die als vertraulich gekennzeichnet sind (Geschäftsstrategien, Preise, Kundendatenbanken, interne Prozesse, personenbezogene Daten).', 'Diese Verschwiegenheitspflicht besteht auch nach Beendigung der Vereinbarung für 2 Jahre fort.', 'Die Haftung für Schäden aus Verletzung der Verschwiegenheitspflicht richtet sich nach § 257 AGB. Eine Vertragsstrafe zulasten des Arbeitnehmers darf in einem DPP nicht vereinbart werden (§ 346d AGB).', 'Nach Beendigung der Vereinbarung hat der Arbeitnehmer alle Dokumente, Datenträger und sonstige Materialien mit vertraulichen Informationen zurückzugeben und solche Daten von privaten Geräten zu löschen.'] });
    sections.push({ title: 'VII. GEISTIGES EIGENTUM', body: ['Arbeitsergebnisse, die der Arbeitnehmer im Rahmen der Vereinbarung schafft, sind Arbeitnehmerwerke im Sinne von § 58 des Gesetzes Nr. 121/2000 Slg. Der Arbeitgeber übt alle vermögensrechtlichen Urheberrechte ab Entstehung aus.', 'Der Arbeitnehmer erteilt dem Arbeitgeber die Zustimmung zur Bearbeitung, Verarbeitung, Verbindung mit anderen Werken und sonstigen Änderungen der Outputs im Umfang, der für ihre gewöhnliche Nutzung erforderlich ist.', 'Gleiches gilt für vom Arbeitnehmer entwickelte Software, Algorithmen und technische Lösungen; Quellcodes, Dokumentation und Know-how sind spätestens zum Ende der Vereinbarung an den Arbeitgeber zu übergeben.'] });
    sections.push({ title: 'VIII. HAFTUNG FÜR ORDNUNGSGEMÄSSE ERFÜLLUNG UND SCHADENSERSATZ', body: ['Erfüllt der Arbeitnehmer die vereinbarte Aufgabe nicht ordnungsgemäß und rechtzeitig ohne einen schwerwiegenden Grund auf Arbeitgeberseite, haftet er für nachweisbare Schäden im Umfang des § 257 AGB.', 'Erfüllt der Arbeitnehmer die Aufgabe nicht im vereinbarten Termin oder in der erforderlichen Qualität, kann der Arbeitgeber innerhalb von 5 Werktagen nach Übergabe schriftlich Qualitätsvorbehalt erheben und unentgeltliche Mängelbeseitigung innerhalb einer Frist von 10 Werktagen verlangen.', 'Eine Vertragsstrafe zulasten des Arbeitnehmers darf in einem DPP nicht vereinbart werden. Der Arbeitgeber kann nachweisbare Schäden im gesetzlichen Rahmen geltend machen.'] });
  }
  sections.push({ title: `${hasPremium ? 'IX' : 'VI'}. SCHLUSSBESTIMMUNGEN`, body: ['Diese Vereinbarung unterliegt dem Gesetz Nr. 262/2006 Slg., dem AGB, in der geltenden Fassung, und subsidiär dem Gesetz Nr. 89/2012 Slg., BGB.', 'Arbeitsstreitigkeiten werden vom zuständigen Gericht nach § 9(1) ZPO entschieden.', 'Die Vereinbarung wird in zwei Ausfertigungen erstellt; jede Partei erhält eine.', 'Änderungen sind nur in Form schriftlicher, nummerierter und unterzeichneter Nachträge wirksam.', 'Die Unwirksamkeit einer einzelnen Bestimmung berührt die Wirksamkeit der übrigen Bestimmungen nicht.', 'Die Verarbeitung personenbezogener Daten erfolgt gemäß EU-Verordnung 2016/679 (DSGVO), Gesetz Nr. 110/2019 Slg. und § 316 AGB.', 'Keine Vertragspartei haftet für die Nichterfüllung nichtmonetärer Verpflichtungen aufgrund höherer Gewalt (§ 2913(2) BGB).'] });
  sections.push({ title: `${hasPremium ? 'X' : 'VII'}. UNTERSCHRIFTEN`, body: [] });
  if (hasPremium) sections.push({ title: 'ANLAGE 1 – ÜBERGABE- UND ABNAHMEPROTOKOLL', body: [] });
  return sections;
}

export function buildDppTranslationsBySection(d: StoredContractData, hasPremium: boolean): Array<NonNullable<ContractSection['translations']>> {
  return buildBilingualTranslations({
    en: () => en(d, hasPremium),
    ua: () => uk(d, hasPremium),
  });
}
