/**
 * Employment contract (pracovní smlouva) — translations EN/UK/RU/VN/DE.
 */
import type { ContractSection, StoredContractData } from '../contracts';
import { buildBilingualTranslations, fmtAmount, fmtDate, pad, type ParaPair } from './helpers';

const date = (v: unknown, l: string) => v ? fmtDate(v, l) : new Date().toLocaleDateString(l);

function shared(d: StoredContractData) {
  const leadershipRole = /vedouc|ředitel|manager|director|leader/i.test(String(d.jobTitle ?? '')) || Boolean(d.isManager || d.isExecutive || d.isLeader);
  const requestedTrialMonths = Number(d.trialPeriodMonths || 0);
  const maxTrialMonths = leadershipRole ? 8 : 4;
  const effectiveTrial = Number.isFinite(requestedTrialMonths) && requestedTrialMonths > 0 ? Math.min(requestedTrialMonths, maxTrialMonths) : 0;
  return { effectiveTrial };
}

function en(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const { effectiveTrial } = shared(d);
  const trialClause = effectiveTrial > 0 ? `A probationary period of ${effectiveTrial} month${effectiveTrial === 1 ? '' : 's'} from the start of employment is agreed (§ 35 Labour Code, as amended by Act No. 120/2025 Coll.). For a fixed-term employment, the probationary period may not exceed half of the agreed duration. During the probationary period either party may terminate employment at any time, with or without giving reasons.` : 'No probationary period is agreed.';
  const duration = d.employmentType === 'fixed' ? `for a fixed term until ${fmtDate(d.endDate) || 'unspecified'} (§ 39 Labour Code)` : 'for an indefinite term';
  const salary = d.salaryType === 'monthly' ? `The employee is entitled to a monthly gross salary of CZK ${fmtAmount(d.salary)}. Salary is due on the regular payday, i.e. the ${pad(d.payDay) || '15'}th day of the calendar month following the month for which it is paid, by bank transfer to the employee's account.` : `The employee is entitled to an hourly gross wage of CZK ${fmtAmount(d.hourlyRate)} per hour.`;
  const workTime = d.workHours ? `Agreed weekly working time: ${pad(d.workHours)} hours. Schedule: ${pad(d.workSchedule) || 'Mon–Fri, 8:00–17:00'}.` : 'Weekly working time is set at 40 hours (§ 79 Labour Code). Schedule: Mon–Fri, 8:00–17:00.';
  const sections: ParaPair[] = [
    { title: 'PREAMBLE', body: ['This employment contract (the "Contract") is concluded under § 34 et seq. of Act No. 262/2006 Coll., the Czech Labour Code, as amended (the "Labour Code").', `Date of conclusion: ${date(d.contractDate, 'en-GB')}`] },
    { title: 'I. PARTIES', body: [`Employer: ${pad(d.employerName)}, Company ID: ${pad(d.employerIco) || '—'}, registered office: ${pad(d.employerAddress)}`, d.employerEmail ? `Employer e-mail: ${pad(d.employerEmail)}` : '', `Employee: ${pad(d.employeeName)}, date of birth: ${pad(d.employeeBirth) || '—'}, residence: ${pad(d.employeeAddress)}`, d.employeeEmail ? `Employee e-mail: ${pad(d.employeeEmail)}` : ''] },
    { title: 'II. TYPE AND PLACE OF WORK', body: [`Type of work (job title): ${pad(d.jobTitle) || 'unspecified'}`, `Job description: ${pad(d.jobDescription) || 'according to the current job description'}`, `Place of work: ${pad(d.workPlace) || 'unspecified'}`, d.remoteWork ? `Remote work option (home office): ${pad(d.remoteWork)}` : ''] },
    { title: 'III. COMMENCEMENT AND DURATION', body: [`Start date: ${fmtDate(d.startDate) || 'unspecified'}`, `The employment is agreed ${duration}.`, trialClause] },
    { title: 'IV. WORKING TIME', body: [workTime, `Meal and rest break: ${pad(d.breakMinutes) || '30'} minutes under § 88 Labour Code.`, `Vacation: ${pad(d.vacationWeeks) || '4'} weeks of paid leave per calendar year under § 212 Labour Code.`] },
    { title: 'V. SALARY AND REMUNERATION', body: [salary, d.bonusDesc ? `Variable components of pay (bonuses) may be granted: ${pad(d.bonusDesc)}.` : '', 'The employer shall provide the employee, on payment, with a written pay slip showing the components of pay and deductions made.'] },
    { title: 'VI. RIGHTS AND DUTIES OF THE EMPLOYEE', body: ['The employee shall:', '(a) personally perform the work under this Contract and observe working time,', "(b) comply with occupational safety regulations and the employer's rules and complete legally required OSH training (§ 103 Labour Code),", '(c) notify the employer of work obstacles (illness, care duties) without undue delay,', '(d) maintain confidentiality regarding information marked as confidential,', "(e) protect the employer's property and not consume alcohol or other addictive substances at the workplace."] },
    { title: 'VII. TERMINATION OF EMPLOYMENT', body: ['Employment may be terminated by agreement, notice, immediate termination, or expiry of an agreed term (§ 48 Labour Code).', `Notice period under § 51 Labour Code: ${pad(d.noticePeriod) || '2'} months. The notice period starts on the first day of the calendar month following delivery of the notice.`, 'Notice from the employer must be justified (§ 52 Labour Code). The employee may give notice with or without giving reasons.'] },
  ];
  if (hasPremium) {
    if (d.nonCompete) {
      sections.push({ title: 'VIII. NON-COMPETE CLAUSE', body: [`For a period of ${pad(d.nonCompetePeriod) || '12'} months after termination of employment, the employee shall not engage in any gainful activity identical with or competing against the employer's business (§ 310 Labour Code).`, 'For compliance, the employee receives monetary compensation of at least half of the average monthly earnings for each month of compliance. The compensation is payable monthly in arrears, by the 15th day of the following month.', 'The non-compete is appropriate in subject matter, time and territory in light of the information accessible to the employee. The employer may withdraw from the non-compete during employment (§ 310(4) Labour Code).', "If the employee breaches the non-compete, the employee shall return compensation received for the months breached; this is without prejudice to the employer's right to demonstrable damages."] });
    }
    sections.push({ title: 'IX. CONFIDENTIALITY AND PROTECTION OF TRADE SECRETS', body: ['The employee shall maintain confidentiality of all facts learnt in connection with employment that are marked as confidential or whose nature plainly implies confidentiality.', 'This duty applies throughout employment and for 3 years after its end.', 'Liability is governed by § 257 Labour Code; intentional damage or damage caused under the influence of alcohol or other substances entails full liability (§ 257(3) Labour Code). Note: contractual penalties against the employee may not be agreed in an employment relationship (§ 346d Labour Code).'] });
  }
  sections.push({ title: `${hasPremium ? 'X' : 'VIII'}. FINAL PROVISIONS`, body: ['This Contract is governed by the Labour Code, as amended, and subsidiarily by Act No. 89/2012 Coll., the Civil Code.', 'The employer must conclude the employment contract before the employee starts work (§ 34(3) Labour Code). The employee may not start work until the Contract is signed.', 'Labour disputes shall be heard by the competent court under § 9(1) CCP.', 'The Contract is executed in two counterparts; each party receives one (§ 37 Labour Code).', 'Amendments are valid only as written, numbered and signed addenda (§ 564 Civil Code).', 'The invalidity of any individual provision does not affect the validity of the remaining provisions.', 'Personal data are processed under EU Regulation 2016/679 (GDPR), Act No. 110/2019 Coll. and § 316 of the Labour Code.', 'Neither party is liable for non-performance of non-monetary obligations caused by force majeure (§ 2913(2) Civil Code).'] });
  sections.push({ title: `${hasPremium ? 'XI' : 'IX'}. SIGNATURES`, body: [] });
  return sections;
}

function uk(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const { effectiveTrial } = shared(d);
  const trialClause = effectiveTrial > 0 ? `Випробувальний строк погоджується на ${effectiveTrial} місяців з дати виникнення трудових відносин (§ 35 ТК у редакції Закону № 120/2025 Sb.). У трудових відносинах на визначений строк випробувальний строк не може перевищити половини погодженої тривалості. Протягом випробувального строку будь-яка сторона може припинити трудові відносини у будь-який час, з будь-яких або без зазначення причини.` : 'Випробувальний строк не сторонується.';
  const duration = d.employmentType === 'fixed' ? `на визначений строк до ${fmtDate(d.endDate, 'uk-UA') || 'не вказано'} (§ 39 ТК)` : 'на невизначений строк';
  const salary = d.salaryType === 'monthly' ? `Працівнику належить щомісячна заробітна плата у розмірі ${fmtAmount(d.salary)} крон брутто. Заробітна плата сплачується у регулярний день виплати, тобто ${pad(d.payDay) || '15'}. дня календарного місяця, що настає за місяцем, за який належить заробітна плата, безготівковим переказом на банківський рахунок працівника.` : `Працівнику належить погодинна заробітна плата у розмірі ${fmtAmount(d.hourlyRate)} крон/год брутто.`;
  const workTime = d.workHours ? `Погоджений тижневий робочий час: ${pad(d.workHours)} годин. Графік: ${pad(d.workSchedule) || 'понеділок–п\'ятниця, 8:00–17:00'}.` : 'Тижневий робочий час встановлюється у обсязі 40 годин (§ 79 ТК). Графік: понеділок–п\'ятниця, 8:00–17:00.';
  const sections: ParaPair[] = [
    { title: 'ПРЕАМБУЛА', body: ['Ця трудова угода («Угода») укладається відповідно до § 34 та наступних Закону № 262/2006 Sb., Трудовий кодекс Чехії, з наступними змінами («ТК»).', `Дата укладення: ${date(d.contractDate, 'uk-UA')}`] },
    { title: 'I. СТОРОНИ', body: [`Роботодавець: ${pad(d.employerName)}, IČO: ${pad(d.employerIco) || '—'}, місцезнаходження: ${pad(d.employerAddress)}`, d.employerEmail ? `E-mail роботодавця: ${pad(d.employerEmail)}` : '', `Працівник: ${pad(d.employeeName)}, дата народження: ${pad(d.employeeBirth) || '—'}, місце проживання: ${pad(d.employeeAddress)}`, d.employeeEmail ? `E-mail працівника: ${pad(d.employeeEmail)}` : ''] },
    { title: 'II. ВИД ТА МІСЦЕ ВИКОНАННЯ РОБОТИ', body: [`Вид роботи (посада): ${pad(d.jobTitle) || 'не вказано'}`, `Опис посадових обов\'язків: ${pad(d.jobDescription) || 'згідно з актуальним описом робочого місця'}`, `Місце виконання роботи: ${pad(d.workPlace) || 'не вказано'}`, d.remoteWork ? `Можливість віддаленої роботи (home office): ${pad(d.remoteWork)}` : ''] },
    { title: 'III. ВИНИКНЕННЯ ТРУДОВИХ ВІДНОСИН І СТРОК', body: [`Трудові відносини виникають у день виходу на роботу: ${fmtDate(d.startDate, 'uk-UA') || 'не вказано'}`, `Трудові відносини сторонуються ${duration}.`, trialClause] },
    { title: 'IV. РОБОЧИЙ ЧАС', body: [workTime, `Перерва на обід та відпочинок: ${pad(d.breakMinutes) || '30'} хвилин за § 88 ТК.`, `Відпустка: Працівнику належить відпустка у тривалості ${pad(d.vacationWeeks) || '4'} тижнів за календарний рік за § 212 ТК.`] },
    { title: 'V. ЗАРОБІТНА ПЛАТА ТА ВИНАГОРОДА', body: [salary, d.bonusDesc ? `Працівнику можуть бути нараховані рухомі складові зарплати (премії/бонуси): ${pad(d.bonusDesc)}.` : '', 'Роботодавець зобов\'язаний при виплаті надати працівнику письмовий документ (платіжну стрічку) з даними про окремі складові зарплати та проведені утримання.'] },
    { title: 'VI. ПРАВА ТА ОБОВ\'ЯЗКИ ПРАЦІВНИКА', body: ['Працівник зобов\'язаний:', '(a) особисто виконувати роботу за трудовою угодою та дотримуватися робочого часу,', '(b) дотримуватися приписів безпеки праці, трудового розпорядку роботодавця та проходити законом вимагане навчання БНП (§ 103 ТК),', '(c) повідомляти роботодавця про перешкоди в роботі (хвороба, догляд) без зайвої затримки,', '(d) зберігати конфіденційність про інформацію, позначену як конфіденційну,', '(e) захищати майно роботодавця та не вживати алкоголь та інші засоби на робочому місці.'] },
    { title: 'VII. ПРИПИНЕННЯ ТРУДОВИХ ВІДНОСИН', body: ['Трудові відносини можуть бути припинені: угодою, попередженням, негайним розірванням або спливом погодженого строку (§ 48 ТК).', `Строк попередження відповідно до § 51 ТК становить ${pad(d.noticePeriod) || '2'} місяці. Строк попередження починається з першого дня календарного місяця, що настає за врученням попередження.`, 'Попередження від роботодавця має бути обґрунтоване (§ 52 ТК). Попередження від працівника може бути надано з будь-якої або без зазначення причини.'] },
  ];
  if (hasPremium) {
    if (d.nonCompete) {
      sections.push({ title: 'VIII. КОНКУРЕНТНА ОБМОВКА', body: [`Працівник зобов\'язується, що протягом ${pad(d.nonCompetePeriod) || '12'} місяців з припинення трудових відносин не виконуватиме платну діяльність, яка б була тотожна предмету бізнесу роботодавця або мала б щодо роботодавця конкурентний характер (§ 310 ТК).`, 'За дотримання цього зобов\'язання працівнику належить грошове компенсаційне забезпечення у розмірі принаймні половини середнього щомісячного заробітку за кожен місяць виконання зобов\'язання. Компенсація сплачується щомісяця заднім числом, завжди до 15. дня календарного місяця, що настає за місяцем, за який належить.', 'Конкурентна обмовка предметно, тимчасово і територіально визначена з урахуванням характеру інформації, до якої працівник мав доступ. Роботодавець має право відмовитись від конкурентної обмовки протягом тривалості трудових відносин працівника (§ 310(4) ТК).', 'При порушенні конкурентної обмовки працівник зобов\'язаний повернути отримане компенсаційне забезпечення, що припадає на місяці, у які зобов\'язання не дотримав; тим не порушується право роботодавця на відшкодування доведеної шкоди.'] });
    }
    sections.push({ title: 'IX. КОНФІДЕНЦІЙНІСТЬ ТА ЗАХИСТ КОМЕРЦІЙНОЇ ТАЄМНИЦІ', body: ['Працівник зобов\'язаний зберігати конфіденційність про всі факти, з якими ознайомився у зв\'язку з виконанням свого трудового відношення та які позначені як конфіденційні або характер яких явно вимагає такої конфіденційності.', 'Обов\'язок конфіденційності діє протягом тривалості трудових відносин та далі протягом 3 років з їхнього припинення.', 'За шкоду, заподіяну порушенням обов\'язку конфіденційності, працівник відповідає у обсязі § 257 ТК. У випадку умисного заподіяння шкоди або шкоди, заподіяної під впливом алкоголю чи інших звикальних речовин, працівник відповідає за шкоду в повному обсязі (§ 257(3) ТК). Зауваження: договірний штраф за рахунок працівника у трудово-правовому відношенні не сторонується (§ 346d ТК).'] });
  }
  sections.push({ title: `${hasPremium ? 'X' : 'VIII'}. ЗАКЛЮЧНІ ПОЛОЖЕННЯ`, body: ['Трудова угода регулюється Законом № 262/2006 Sb., Трудовим кодексом, з наступними змінами, та субсидіарно Законом № 89/2012 Sb., Цивільним кодексом.', 'Роботодавець зобов\'язаний укласти трудову угоду перед виходом працівника на роботу (§ 34(3) ТК). Працівник не може вийти на роботу, доки трудова угода не була підписана.', 'Трудові спори вирішує компетентний суд за § 9(1) ЦПК.', 'Угода складена у двох примірниках; кожна сторона отримує по одному (§ 37 ТК).', 'Зміни трудової угоди дійсні лише у формі писемних, нумерованих і підписаних доповнень (§ 564 ЦК).', 'Недійсність окремого положення не впливає на дійсність решти положень.', 'Обробка персональних даних здійснюється відповідно до Регламенту ЄС 2016/679 (GDPR), Закону № 110/2019 Sb. та § 316 ТК.', 'Жодна сторона не відповідає за невиконання немайнових зобов\'язань, спричинене форс-мажором (§ 2913(2) ЦК).'] });
  sections.push({ title: `${hasPremium ? 'XI' : 'IX'}. ПІДПИСИ`, body: [] });
  return sections;
}

function ru(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const { effectiveTrial } = shared(d);
  const trialClause = effectiveTrial > 0 ? `Испытательный срок согласовывается на ${effectiveTrial} месяцев со дня возникновения трудовых отношений (§ 35 ТК в редакции Закона № 120/2025 Sb.). При трудовых отношениях на определённый срок испытательный срок не может превышать половины согласованной длительности. В течение испытательного срока любая сторона может прекратить трудовые отношения в любое время, по любой причине или без указания.` : 'Испытательный срок не согласовывается.';
  const duration = d.employmentType === 'fixed' ? `на определённый срок до ${fmtDate(d.endDate, 'ru-RU') || 'не указано'} (§ 39 ТК)` : 'на неопределённый срок';
  const salary = d.salaryType === 'monthly' ? `Работнику полагается ежемесячная заработная плата в размере ${fmtAmount(d.salary)} крон брутто. Заработная плата выплачивается в регулярный день выплаты, т.е. ${pad(d.payDay) || '15'}-го дня календарного месяца, следующего за месяцем, за который полагается заработная плата, безналичным переводом на банковский счёт работника.` : `Работнику полагается почасовая заработная плата в размере ${fmtAmount(d.hourlyRate)} крон/час брутто.`;
  const workTime = d.workHours ? `Согласованное недельное рабочее время: ${pad(d.workHours)} часов. График: ${pad(d.workSchedule) || 'понедельник–пятница, 8:00–17:00'}.` : 'Недельное рабочее время устанавливается в объёме 40 часов (§ 79 ТК). График: понедельник–пятница, 8:00–17:00.';
  const sections: ParaPair[] = [
    { title: 'ПРЕАМБУЛА', body: ['Настоящий трудовой договор («Договор») заключается согласно § 34 и далее Закона № 262/2006 Sb., Трудовой кодекс Чехии, с последующими изменениями («ТК»).', `Дата заключения: ${date(d.contractDate, 'ru-RU')}`] },
    { title: 'I. СТОРОНЫ', body: [`Работодатель: ${pad(d.employerName)}, IČO: ${pad(d.employerIco) || '—'}, юридический адрес: ${pad(d.employerAddress)}`, d.employerEmail ? `E-mail работодателя: ${pad(d.employerEmail)}` : '', `Работник: ${pad(d.employeeName)}, дата рождения: ${pad(d.employeeBirth) || '—'}, место жительства: ${pad(d.employeeAddress)}`, d.employeeEmail ? `E-mail работника: ${pad(d.employeeEmail)}` : ''] },
    { title: 'II. ВИД И МЕСТО ВЫПОЛНЕНИЯ РАБОТЫ', body: [`Вид работы (должность): ${pad(d.jobTitle) || 'не указано'}`, `Описание должностных обязанностей: ${pad(d.jobDescription) || 'согласно актуальному описанию рабочего места'}`, `Место выполнения работы: ${pad(d.workPlace) || 'не указано'}`, d.remoteWork ? `Возможность удалённой работы (home office): ${pad(d.remoteWork)}` : ''] },
    { title: 'III. ВОЗНИКНОВЕНИЕ ТРУДОВЫХ ОТНОШЕНИЙ И СРОК', body: [`Трудовые отношения возникают в день выхода на работу: ${fmtDate(d.startDate, 'ru-RU') || 'не указано'}`, `Трудовые отношения заключаются ${duration}.`, trialClause] },
    { title: 'IV. РАБОЧЕЕ ВРЕМЯ', body: [workTime, `Перерыв на обед и отдых: ${pad(d.breakMinutes) || '30'} минут по § 88 ТК.`, `Отпуск: Работнику полагается отпуск длительностью ${pad(d.vacationWeeks) || '4'} недель за календарный год по § 212 ТК.`] },
    { title: 'V. ЗАРАБОТНАЯ ПЛАТА И ВОЗНАГРАЖДЕНИЕ', body: [salary, d.bonusDesc ? `Работнику могут быть начислены подвижные составляющие зарплаты (премии/бонусы): ${pad(d.bonusDesc)}.` : '', 'Работодатель обязан при выплате предоставить работнику письменный документ (расчётный лист) с данными об отдельных составляющих зарплаты и произведённых удержаниях.'] },
    { title: 'VI. ПРАВА И ОБЯЗАННОСТИ РАБОТНИКА', body: ['Работник обязан:', '(a) лично выполнять работу по трудовому договору и соблюдать рабочее время,', '(b) соблюдать предписания безопасности труда, трудовой распорядок работодателя и проходить требуемое законом обучение БиОТ (§ 103 ТК),', '(c) сообщать работодателю о препятствиях в работе (болезнь, уход) без излишней задержки,', '(d) сохранять конфиденциальность об информации, обозначенной как конфиденциальную,', '(e) защищать имущество работодателя и не употреблять алкоголь и иные средства на рабочем месте.'] },
    { title: 'VII. ПРЕКРАЩЕНИЕ ТРУДОВЫХ ОТНОШЕНИЙ', body: ['Трудовые отношения могут быть прекращены: соглашением, уведомлением, немедленным расторжением или истечением согласованного срока (§ 48 ТК).', `Срок уведомления согласно § 51 ТК составляет ${pad(d.noticePeriod) || '2'} месяца. Срок уведомления начинается с первого дня календарного месяца, следующего за вручением уведомления.`, 'Уведомление от работодателя должно быть обосновано (§ 52 ТК). Уведомление от работника может быть подано по любой причине или без указания причины.'] },
  ];
  if (hasPremium) {
    if (d.nonCompete) {
      sections.push({ title: 'VIII. КОНКУРЕНТНАЯ ОГОВОРКА', body: [`Работник обязуется, что в течение ${pad(d.nonCompetePeriod) || '12'} месяцев с прекращения трудовых отношений не будет вести оплачиваемую деятельность, которая бы была тождественна предмету бизнеса работодателя или имела бы относительно работодателя конкурентный характер (§ 310 ТК).`, 'За соблюдение этого обязательства работнику полагается денежное компенсационное обеспечение в размере не менее половины среднего ежемесячного заработка за каждый месяц выполнения обязательства. Компенсация выплачивается ежемесячно с отставанием, всегда до 15-го дня календарного месяца, следующего за месяцем, за который полагается.', 'Конкурентная оговорка предметно, временно и территориально определена с учётом характера информации, к которой работник имел доступ. Работодатель имеет право отказаться от конкурентной оговорки в течение длительности трудовых отношений работника (§ 310(4) ТК).', 'При нарушении конкурентной оговорки работник обязан вернуть полученное компенсационное обеспечение, приходящееся на месяцы, в которые обязательство не соблюдал; тем не нарушается право работодателя на возмещение доказанного ущерба.'] });
    }
    sections.push({ title: 'IX. КОНФИДЕНЦИАЛЬНОСТЬ И ЗАЩИТА КОММЕРЧЕСКОЙ ТАЙНЫ', body: ['Работник обязан сохранять конфиденциальность о всех фактах, с которыми ознакомился в связи с выполнением своих трудовых отношений и которые обозначены как конфиденциальные или характер которых явно требует такой конфиденциальности.', 'Обязанность конфиденциальности действует в течение длительности трудовых отношений и далее в течение 3 лет с их прекращения.', 'За ущерб, причинённый нарушением обязанности конфиденциальности, работник отвечает в объёме § 257 ТК. В случае умышленного причинения ущерба или ущерба, причинённого под влиянием алкоголя или иных привыкательных веществ, работник отвечает за ущерб в полном объёме (§ 257(3) ТК). Замечание: договорный штраф в счёт работника в трудово-правовом отношении не оговаривается (§ 346d ТК).'] });
  }
  sections.push({ title: `${hasPremium ? 'X' : 'VIII'}. ЗАКЛЮЧИТЕЛЬНЫЕ ПОЛОЖЕНИЯ`, body: ['Трудовой договор регулируется Законом № 262/2006 Sb., Трудовым кодексом, с последующими изменениями, и субсидиарно Законом № 89/2012 Sb., Гражданским кодексом.', 'Работодатель обязан заключить трудовой договор до выхода работника на работу (§ 34(3) ТК). Работник не может выйти на работу, пока трудовой договор не был подписан.', 'Трудовые споры разрешает компетентный суд по § 9(1) ГПК.', 'Договор составлен в двух экземплярах; каждая сторона получает по одному (§ 37 ТК).', 'Изменения трудового договора действительны только в форме письменных, пронумерованных и подписанных дополнений (§ 564 ГК).', 'Недействительность отдельного положения не влияет на действительность остальных положений.', 'Обработка персональных данных осуществляется в соответствии с Регламентом ЕС 2016/679 (GDPR), Законом № 110/2019 Sb. и § 316 ТК.', 'Ни одна из сторон не отвечает за неисполнение неимущественных обязательств, вызванное форс-мажором (§ 2913(2) ГК).'] });
  sections.push({ title: `${hasPremium ? 'XI' : 'IX'}. ПОДПИСИ`, body: [] });
  return sections;
}

function vn(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const { effectiveTrial } = shared(d);
  const trialClause = effectiveTrial > 0 ? `Thời gian thử việc được thỏa thuận trong ${effectiveTrial} tháng kể từ ngày bắt đầu quan hệ lao động (§ 35 BLLĐ, sửa đổi bởi Luật số 120/2025 Sb.). Đối với hợp đồng lao động có thời hạn, thời gian thử việc không được vượt quá một nửa thời hạn đã thỏa thuận. Trong thời gian thử việc, bất kỳ bên nào cũng có thể chấm dứt quan hệ lao động bất kỳ lúc nào, có hoặc không có lý do.` : 'Không thỏa thuận thời gian thử việc.';
  const duration = d.employmentType === 'fixed' ? `với thời hạn xác định đến ${fmtDate(d.endDate, 'vi-VN') || 'chưa nêu rõ'} (§ 39 BLLĐ)` : 'với thời hạn không xác định';
  const salary = d.salaryType === 'monthly' ? `Người lao động có quyền nhận lương tháng gộp là ${fmtAmount(d.salary)} crown Séc. Lương được trả vào ngày trả lương thường xuyên, tức ngày ${pad(d.payDay) || '15'} của tháng dương lịch sau tháng được trả lương, bằng chuyển khoản vào tài khoản ngân hàng của người lao động.` : `Người lao động có quyền nhận lương giờ gộp là ${fmtAmount(d.hourlyRate)} crown Séc mỗi giờ.`;
  const workTime = d.workHours ? `Thời gian làm việc hàng tuần đã thỏa thuận: ${pad(d.workHours)} giờ. Lịch: ${pad(d.workSchedule) || 'Thứ Hai–Thứ Sáu, 8:00–17:00'}.` : 'Thời gian làm việc hàng tuần được quy định là 40 giờ (§ 79 BLLĐ). Lịch: Thứ Hai–Thứ Sáu, 8:00–17:00.';
  const sections: ParaPair[] = [
    { title: 'LỜI MỞ ĐẦU', body: ['Hợp đồng lao động này ("Hợp đồng") được ký kết theo § 34 trở đi của Luật số 262/2006 Sb., Bộ luật Lao động Séc, có sửa đổi ("BLLĐ").', `Ngày ký kết: ${date(d.contractDate, 'vi-VN')}`] },
    { title: 'I. CÁC BÊN', body: [`Người sử dụng lao động: ${pad(d.employerName)}, IČO: ${pad(d.employerIco) || '—'}, trụ sở: ${pad(d.employerAddress)}`, d.employerEmail ? `E-mail người sử dụng lao động: ${pad(d.employerEmail)}` : '', `Người lao động: ${pad(d.employeeName)}, ngày sinh: ${pad(d.employeeBirth) || '—'}, nơi cư trú: ${pad(d.employeeAddress)}`, d.employeeEmail ? `E-mail người lao động: ${pad(d.employeeEmail)}` : ''] },
    { title: 'II. LOẠI VÀ NƠI LÀM VIỆC', body: [`Loại công việc (chức danh): ${pad(d.jobTitle) || 'chưa nêu rõ'}`, `Mô tả công việc: ${pad(d.jobDescription) || 'theo mô tả vị trí công việc hiện tại'}`, `Nơi làm việc: ${pad(d.workPlace) || 'chưa nêu rõ'}`, d.remoteWork ? `Lựa chọn làm việc từ xa (home office): ${pad(d.remoteWork)}` : ''] },
    { title: 'III. BẮT ĐẦU VÀ THỜI HẠN', body: [`Ngày bắt đầu: ${fmtDate(d.startDate, 'vi-VN') || 'chưa nêu rõ'}`, `Quan hệ lao động được ký kết ${duration}.`, trialClause] },
    { title: 'IV. THỜI GIAN LÀM VIỆC', body: [workTime, `Nghỉ ăn và nghỉ ngơi: ${pad(d.breakMinutes) || '30'} phút theo § 88 BLLĐ.`, `Nghỉ phép: Người lao động có quyền nghỉ phép ${pad(d.vacationWeeks) || '4'} tuần cho mỗi năm dương lịch theo § 212 BLLĐ.`] },
    { title: 'V. LƯƠNG VÀ THÙ LAO', body: [salary, d.bonusDesc ? `Người lao động có thể được hưởng các thành phần lương biến đổi (tiền thưởng): ${pad(d.bonusDesc)}.` : '', 'Người sử dụng lao động khi thanh toán phải cung cấp cho người lao động bằng văn bản (phiếu lương) với dữ liệu về các thành phần lương và các khoản khấu trừ đã thực hiện.'] },
    { title: 'VI. QUYỀN VÀ NGHĨA VỤ CỦA NGƯỜI LAO ĐỘNG', body: ['Người lao động có nghĩa vụ:', '(a) tự mình thực hiện công việc theo hợp đồng lao động và tuân thủ thời gian làm việc,', '(b) tuân thủ các quy định về an toàn lao động, nội quy lao động của người sử dụng lao động và tham gia đào tạo BHLĐ theo luật định (§ 103 BLLĐ),', '(c) thông báo cho người sử dụng lao động về các trở ngại trong công việc (bệnh tật, chăm sóc) không chậm trễ,', '(d) giữ bí mật về các thông tin được đánh dấu là bí mật,', '(e) bảo vệ tài sản của người sử dụng lao động và không sử dụng rượu hoặc các chất gây nghiện khác tại nơi làm việc.'] },
    { title: 'VII. CHẤM DỨT QUAN HỆ LAO ĐỘNG', body: ['Quan hệ lao động có thể chấm dứt bằng: thỏa thuận, thông báo, chấm dứt ngay lập tức hoặc hết thời hạn đã thỏa thuận (§ 48 BLLĐ).', `Thời hạn thông báo theo § 51 BLLĐ là ${pad(d.noticePeriod) || '2'} tháng. Thời hạn thông báo bắt đầu từ ngày đầu tiên của tháng dương lịch sau khi giao thông báo.`, 'Thông báo từ người sử dụng lao động phải có lý do (§ 52 BLLĐ). Thông báo từ người lao động có thể đưa ra với bất kỳ lý do nào hoặc không nêu lý do.'] },
  ];
  if (hasPremium) {
    if (d.nonCompete) {
      sections.push({ title: 'VIII. ĐIỀU KHOẢN KHÔNG CẠNH TRANH', body: [`Trong vòng ${pad(d.nonCompetePeriod) || '12'} tháng sau khi chấm dứt quan hệ lao động, người lao động không được thực hiện hoạt động có thu nhập tương tự hoặc cạnh tranh với hoạt động kinh doanh của người sử dụng lao động (§ 310 BLLĐ).`, 'Để tuân thủ nghĩa vụ này, người lao động nhận được tiền bù tài chính ít nhất là một nửa thu nhập hàng tháng trung bình cho mỗi tháng tuân thủ. Tiền bù được trả hàng tháng sau, luôn vào ngày 15 của tháng tiếp theo.', 'Điều khoản không cạnh tranh được xác định về đối tượng, thời gian và lãnh thổ có tính đến tính chất của thông tin mà người lao động đã tiếp cận. Người sử dụng lao động có quyền rút khỏi điều khoản không cạnh tranh trong thời gian quan hệ lao động (§ 310(4) BLLĐ).', 'Khi vi phạm điều khoản không cạnh tranh, người lao động phải hoàn trả tiền bù đã nhận tương ứng với các tháng vi phạm; điều này không ảnh hưởng đến quyền của người sử dụng lao động được bồi thường thiệt hại đã chứng minh.'] });
    }
    sections.push({ title: 'IX. BẢO MẬT VÀ BẢO VỆ BÍ MẬT KINH DOANH', body: ['Người lao động có nghĩa vụ giữ bí mật về tất cả các sự kiện đã biết liên quan đến công việc và được đánh dấu là bí mật hoặc có tính chất hiển nhiên đòi hỏi sự bảo mật.', 'Nghĩa vụ bảo mật áp dụng trong thời gian quan hệ lao động và sau đó 3 năm kể từ ngày chấm dứt.', 'Trách nhiệm về thiệt hại do vi phạm nghĩa vụ bảo mật được điều chỉnh theo § 257 BLLĐ. Trong trường hợp gây thiệt hại có chủ ý hoặc thiệt hại gây ra dưới tác động của rượu hoặc các chất gây nghiện khác, người lao động chịu trách nhiệm toàn bộ (§ 257(3) BLLĐ). Lưu ý: tiền phạt hợp đồng đối với người lao động không được thỏa thuận trong quan hệ lao động (§ 346d BLLĐ).'] });
  }
  sections.push({ title: `${hasPremium ? 'X' : 'VIII'}. ĐIỀU KHOẢN CUỐI CÙNG`, body: ['Hợp đồng lao động được điều chỉnh bởi Luật số 262/2006 Sb., Bộ luật Lao động, có sửa đổi, và bổ sung bởi Luật số 89/2012 Sb., Bộ luật Dân sự.', 'Người sử dụng lao động phải ký hợp đồng lao động trước khi người lao động bắt đầu làm việc (§ 34(3) BLLĐ). Người lao động không được bắt đầu làm việc cho đến khi Hợp đồng được ký.', 'Tranh chấp lao động do tòa án có thẩm quyền giải quyết theo § 9(1) BLTTDS.', 'Hợp đồng được lập thành hai bản; mỗi bên nhận một bản (§ 37 BLLĐ).', 'Các sửa đổi của hợp đồng lao động chỉ có hiệu lực dưới dạng phụ lục bằng văn bản, được đánh số và ký (§ 564 BLDS).', 'Sự vô hiệu của một điều khoản riêng lẻ không ảnh hưởng đến hiệu lực của các điều khoản còn lại.', 'Việc xử lý dữ liệu cá nhân tuân thủ Quy định EU 2016/679 (GDPR), Luật số 110/2019 Sb. và § 316 BLLĐ.', 'Không bên nào chịu trách nhiệm về việc không thực hiện các nghĩa vụ phi tiền tệ do bất khả kháng (§ 2913(2) BLDS).'] });
  sections.push({ title: `${hasPremium ? 'XI' : 'IX'}. CHỮ KÝ`, body: [] });
  return sections;
}

function de(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const { effectiveTrial } = shared(d);
  const trialClause = effectiveTrial > 0 ? `Eine Probezeit von ${effectiveTrial} Monaten ab Beginn des Arbeitsverhältnisses wird vereinbart (§ 35 AGB in der Fassung des Gesetzes Nr. 120/2025 Slg.). Bei befristetem Arbeitsverhältnis darf die Probezeit nicht mehr als die Hälfte der vereinbarten Dauer betragen. Während der Probezeit kann jede Partei das Arbeitsverhältnis jederzeit beenden, mit oder ohne Angabe von Gründen.` : 'Eine Probezeit wird nicht vereinbart.';
  const duration = d.employmentType === 'fixed' ? `auf bestimmte Zeit bis ${fmtDate(d.endDate, 'de-DE') || 'nicht angegeben'} (§ 39 AGB)` : 'auf unbestimmte Zeit';
  const salary = d.salaryType === 'monthly' ? `Dem Arbeitnehmer steht ein monatliches Bruttogehalt in Höhe von ${fmtAmount(d.salary)} CZK zu. Das Gehalt ist am regulären Zahltag fällig, d. h. am ${pad(d.payDay) || '15'}. Tag des Kalendermonats, der auf den Monat folgt, für den das Gehalt gilt, durch Banküberweisung auf das Konto des Arbeitnehmers.` : `Dem Arbeitnehmer steht ein Brutto-Stundenlohn in Höhe von ${fmtAmount(d.hourlyRate)} CZK pro Stunde zu.`;
  const workTime = d.workHours ? `Vereinbarte wöchentliche Arbeitszeit: ${pad(d.workHours)} Stunden. Plan: ${pad(d.workSchedule) || 'Mo–Fr, 8:00–17:00'}.` : 'Die wöchentliche Arbeitszeit beträgt 40 Stunden (§ 79 AGB). Plan: Mo–Fr, 8:00–17:00.';
  const sections: ParaPair[] = [
    { title: 'PRÄAMBEL', body: ['Dieser Arbeitsvertrag (der „Vertrag") wird gemäß § 34 ff. des Gesetzes Nr. 262/2006 Slg., tschechisches Arbeitsgesetzbuch, in der geltenden Fassung („AGB"), geschlossen.', `Datum des Abschlusses: ${date(d.contractDate, 'de-DE')}`] },
    { title: 'I. VERTRAGSPARTEIEN', body: [`Arbeitgeber: ${pad(d.employerName)}, IČO: ${pad(d.employerIco) || '—'}, eingetragener Sitz: ${pad(d.employerAddress)}`, d.employerEmail ? `E-Mail des Arbeitgebers: ${pad(d.employerEmail)}` : '', `Arbeitnehmer: ${pad(d.employeeName)}, Geburtsdatum: ${pad(d.employeeBirth) || '—'}, Wohnsitz: ${pad(d.employeeAddress)}`, d.employeeEmail ? `E-Mail des Arbeitnehmers: ${pad(d.employeeEmail)}` : ''] },
    { title: 'II. ART UND ORT DER ARBEIT', body: [`Art der Arbeit (Berufsbezeichnung): ${pad(d.jobTitle) || 'nicht angegeben'}`, `Stellenbeschreibung: ${pad(d.jobDescription) || 'gemäß aktueller Stellenbeschreibung'}`, `Arbeitsort: ${pad(d.workPlace) || 'nicht angegeben'}`, d.remoteWork ? `Möglichkeit der Fernarbeit (Home Office): ${pad(d.remoteWork)}` : ''] },
    { title: 'III. BEGINN UND DAUER', body: [`Arbeitsantritt: ${fmtDate(d.startDate, 'de-DE') || 'nicht angegeben'}`, `Das Arbeitsverhältnis wird ${duration} vereinbart.`, trialClause] },
    { title: 'IV. ARBEITSZEIT', body: [workTime, `Ess- und Ruhepause: ${pad(d.breakMinutes) || '30'} Minuten gemäß § 88 AGB.`, `Urlaub: Der Arbeitnehmer hat Anspruch auf ${pad(d.vacationWeeks) || '4'} Wochen bezahlten Urlaub pro Kalenderjahr nach § 212 AGB.`] },
    { title: 'V. GEHALT UND VERGÜTUNG', body: [salary, d.bonusDesc ? `Dem Arbeitnehmer können variable Gehaltsbestandteile (Prämien/Boni) gewährt werden: ${pad(d.bonusDesc)}.` : '', 'Der Arbeitgeber hat dem Arbeitnehmer bei der Zahlung einen schriftlichen Beleg (Lohnabrechnung) mit Angaben zu den einzelnen Gehaltsbestandteilen und vorgenommenen Abzügen zu erteilen.'] },
    { title: 'VI. RECHTE UND PFLICHTEN DES ARBEITNEHMERS', body: ['Der Arbeitnehmer hat:', '(a) die Arbeit nach diesem Vertrag persönlich zu erbringen und die Arbeitszeit einzuhalten,', '(b) Arbeitsschutzvorschriften, die Arbeitsordnung des Arbeitgebers einzuhalten und gesetzlich vorgeschriebene Schulungen (§ 103 AGB) zu absolvieren,', '(c) Arbeitsverhinderungen (Krankheit, Pflege) unverzüglich anzuzeigen,', '(d) Stillschweigen über als vertraulich gekennzeichnete Informationen zu wahren,', '(e) das Eigentum des Arbeitgebers zu schützen und am Arbeitsplatz keinen Alkohol oder andere suchterzeugende Stoffe zu konsumieren.'] },
    { title: 'VII. BEENDIGUNG DES ARBEITSVERHÄLTNISSES', body: ['Das Arbeitsverhältnis kann beendet werden: durch Vereinbarung, Kündigung, fristlose Aufhebung oder Ablauf der vereinbarten Zeit (§ 48 AGB).', `Kündigungsfrist nach § 51 AGB: ${pad(d.noticePeriod) || '2'} Monate. Die Kündigungsfrist beginnt mit dem ersten Tag des Kalendermonats, der auf die Zustellung der Kündigung folgt.`, 'Eine Kündigung durch den Arbeitgeber muss begründet sein (§ 52 AGB). Der Arbeitnehmer kann mit oder ohne Angabe von Gründen kündigen.'] },
  ];
  if (hasPremium) {
    if (d.nonCompete) {
      sections.push({ title: 'VIII. WETTBEWERBSVERBOT', body: [`Für die Dauer von ${pad(d.nonCompetePeriod) || '12'} Monaten ab Ende des Arbeitsverhältnisses darf der Arbeitnehmer keine entgeltliche Tätigkeit ausüben, die mit dem Geschäftsgegenstand des Arbeitgebers identisch ist oder dem Arbeitgeber gegenüber Wettbewerbscharakter hat (§ 310 AGB).`, 'Für die Einhaltung steht dem Arbeitnehmer eine Karenzentschädigung in Höhe von mindestens der Hälfte des durchschnittlichen Monatsverdienstes für jeden Monat der Einhaltung zu. Die Entschädigung ist monatlich nachträglich zahlbar, jeweils bis zum 15. des Folgemonats.', 'Das Wettbewerbsverbot ist sachlich, zeitlich und örtlich unter Berücksichtigung der dem Arbeitnehmer zugänglichen Informationen festgelegt. Der Arbeitgeber kann während des Arbeitsverhältnisses vom Wettbewerbsverbot zurücktreten (§ 310(4) AGB).', 'Bei Verstoß hat der Arbeitnehmer die für die Verstoßmonate erhaltene Entschädigung zurückzuzahlen; das Recht des Arbeitgebers auf nachweisbaren Schadensersatz bleibt unberührt.'] });
    }
    sections.push({ title: 'IX. VERTRAULICHKEIT UND SCHUTZ DES GESCHÄFTSGEHEIMNISSES', body: ['Der Arbeitnehmer hat Stillschweigen über alle Tatsachen zu bewahren, die er im Zusammenhang mit seiner Beschäftigung erfahren hat und die als vertraulich gekennzeichnet sind oder deren Natur eine solche Vertraulichkeit offenkundig begründet.', 'Die Verschwiegenheitspflicht besteht während der Beschäftigung und 3 Jahre nach deren Ende.', 'Die Haftung für Schäden aus der Verletzung der Verschwiegenheitspflicht richtet sich nach § 257 AGB. Bei vorsätzlicher Schadensverursachung oder Schäden unter Einfluss von Alkohol oder anderen suchterzeugenden Stoffen haftet der Arbeitnehmer voll (§ 257(3) AGB). Hinweis: Vertragsstrafen zulasten des Arbeitnehmers dürfen im Arbeitsverhältnis nicht vereinbart werden (§ 346d AGB).'] });
  }
  sections.push({ title: `${hasPremium ? 'X' : 'VIII'}. SCHLUSSBESTIMMUNGEN`, body: ['Der Arbeitsvertrag unterliegt dem Gesetz Nr. 262/2006 Slg., dem AGB, in der geltenden Fassung, und subsidiär dem Gesetz Nr. 89/2012 Slg., BGB.', 'Der Arbeitgeber hat den Arbeitsvertrag vor Arbeitsantritt des Arbeitnehmers zu schließen (§ 34(3) AGB). Der Arbeitnehmer darf die Arbeit erst nach Unterzeichnung des Vertrags aufnehmen.', 'Arbeitsstreitigkeiten werden vom zuständigen Gericht nach § 9(1) ZPO entschieden.', 'Der Vertrag wird in zwei Ausfertigungen erstellt; jede Partei erhält eine (§ 37 AGB).', 'Änderungen sind nur in Form schriftlicher, nummerierter und unterzeichneter Nachträge wirksam (§ 564 BGB).', 'Die Unwirksamkeit einer einzelnen Bestimmung berührt die Wirksamkeit der übrigen Bestimmungen nicht.', 'Die Verarbeitung personenbezogener Daten erfolgt gemäß EU-Verordnung 2016/679 (DSGVO), Gesetz Nr. 110/2019 Slg. und § 316 AGB.', 'Keine Vertragspartei haftet für die Nichterfüllung nichtmonetärer Verpflichtungen aufgrund höherer Gewalt (§ 2913(2) BGB).'] });
  sections.push({ title: `${hasPremium ? 'XI' : 'IX'}. UNTERSCHRIFTEN`, body: [] });
  return sections;
}

export function buildEmploymentTranslationsBySection(d: StoredContractData, hasPremium: boolean): Array<NonNullable<ContractSection['translations']>> {
  return buildBilingualTranslations({
    en: () => en(d, hasPremium),
    uk: () => uk(d, hasPremium),
    ru: () => ru(d, hasPremium),
    vn: () => vn(d, hasPremium),
    de: () => de(d, hasPremium),
  });
}
