/**
 * Employment contract (pracovní smlouva) — translations EN/UK/RU/VN/DE.
 */
import type { ContractSection, StoredContractData } from '../contracts';
import { buildBilingualTranslations, fmtAmount, fmtDate, pad, type ParaPair } from './helpers';

const date = (v: unknown, l: string) => v ? fmtDate(v, l) : new Date().toLocaleDateString(l);

function shared(d: StoredContractData) {
  const leadershipRole = /vedouc|ředitel|manager|director|leader/i.test(String(d.jobTitle ?? '')) || Boolean(d.isManager || d.isExecutive || d.isLeader);
  const requestedTrialMonths = Number(d.trialPeriodMonths || 0);
  const maxTrialMonths = leadershipRole ? 8 : 4;
  const effectiveTrial = Number.isFinite(requestedTrialMonths) && requestedTrialMonths > 0 ? Math.min(requestedTrialMonths, maxTrialMonths) : 0;
  return { effectiveTrial };
}

function en(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const { effectiveTrial } = shared(d);
  const trialClause = effectiveTrial > 0 ? `A probationary period of ${effectiveTrial} month${effectiveTrial === 1 ? '' : 's'} from the start of employment is agreed (§ 35 Labour Code, as amended by Act No. 120/2025 Coll.). For a fixed-term employment, the probationary period may not exceed half of the agreed duration. During the probationary period either party may terminate employment at any time, with or without giving reasons.` : 'No probationary period is agreed.';
  const duration = d.employmentType === 'fixed' ? `for a fixed term until ${fmtDate(d.endDate) || 'unspecified'} (§ 39 Labour Code)` : 'for an indefinite term';
  const salary = d.salaryType === 'monthly' ? `The employee is entitled to a monthly gross salary of CZK ${fmtAmount(d.salary)}. Salary is due on the regular payday, i.e. the ${pad(d.payDay) || '15'}th day of the calendar month following the month for which it is paid, by bank transfer to the employee's account.` : `The employee is entitled to an hourly gross wage of CZK ${fmtAmount(d.hourlyRate)} per hour.`;
  const workTime = d.workHours ? `Agreed weekly working time: ${pad(d.workHours)} hours. Schedule: ${pad(d.workSchedule) || 'Mon–Fri, 8:00–17:00'}.` : 'Weekly working time is set at 40 hours (§ 79 Labour Code). Schedule: Mon–Fri, 8:00–17:00.';
  const sections: ParaPair[] = [
    { title: 'PREAMBLE', body: ['This employment contract (the "Contract") is concluded under § 34 et seq. of Act No. 262/2006 Coll., the Czech Labour Code, as amended (the "Labour Code").', `Date of conclusion: ${date(d.contractDate, 'en-GB')}`] },
    { title: 'I. PARTIES', body: [`Employer: ${pad(d.employerName)}, Company ID: ${pad(d.employerIco) || '—'}, registered office: ${pad(d.employerAddress)}`, d.employerEmail ? `Employer e-mail: ${pad(d.employerEmail)}` : '', `Employee: ${pad(d.employeeName)}, date of birth: ${pad(d.employeeBirth) || '—'}, residence: ${pad(d.employeeAddress)}`, d.employeeEmail ? `Employee e-mail: ${pad(d.employeeEmail)}` : ''] },
    { title: 'II. TYPE AND PLACE OF WORK', body: [`Type of work (job title): ${pad(d.jobTitle) || 'unspecified'}`, `Job description: ${pad(d.jobDescription) || 'according to the current job description'}`, `Place of work: ${pad(d.workPlace) || 'unspecified'}`, d.remoteWork ? `Remote work option (home office): ${pad(d.remoteWork)}` : ''] },
    { title: 'III. COMMENCEMENT AND DURATION', body: [`Start date: ${fmtDate(d.startDate) || 'unspecified'}`, `The employment is agreed ${duration}.`, trialClause] },
    { title: 'IV. WORKING TIME', body: [workTime, `Meal and rest break: ${pad(d.breakMinutes) || '30'} minutes under § 88 Labour Code.`, `Vacation: ${pad(d.vacationWeeks) || '4'} weeks of paid leave per calendar year under § 212 Labour Code.`] },
    { title: 'V. SALARY AND REMUNERATION', body: [salary, d.bonusDesc ? `Variable components of pay (bonuses) may be granted: ${pad(d.bonusDesc)}.` : '', 'The employer shall provide the employee, on payment, with a written pay slip showing the components of pay and deductions made.'] },
    { title: 'VI. RIGHTS AND DUTIES OF THE EMPLOYEE', body: ['The employee shall:', '(a) personally perform the work under this Contract and observe working time,', "(b) comply with occupational safety regulations and the employer's rules and complete legally required OSH training (§ 103 Labour Code),", '(c) notify the employer of work obstacles (illness, care duties) without undue delay,', '(d) maintain confidentiality regarding information marked as confidential,', "(e) protect the employer's property and not consume alcohol or other addictive substances at the workplace."] },
    { title: 'VII. TERMINATION OF EMPLOYMENT', body: ['Employment may be terminated by agreement, notice, immediate termination, or expiry of an agreed term (§ 48 Labour Code).', `Notice period under § 51 Labour Code: ${pad(d.noticePeriod) || '2'} months. The notice period starts on the first day of the calendar month following delivery of the notice.`, 'Notice from the employer must be justified (§ 52 Labour Code). The employee may give notice with or without giving reasons.'] },
  ];
  if (hasPremium) {
    if (d.nonCompete) {
      sections.push({ title: 'VIII. NON-COMPETE CLAUSE', body: [`For a period of ${pad(d.nonCompetePeriod) || '12'} months after termination of employment, the employee shall not engage in any gainful activity identical with or competing against the employer's business (§ 310 Labour Code).`, 'For compliance, the employee receives monetary compensation of at least half of the average monthly earnings for each month of compliance. The compensation is payable monthly in arrears, by the 15th day of the following month.', 'The non-compete is appropriate in subject matter, time and territory in light of the information accessible to the employee. The employer may withdraw from the non-compete during employment (§ 310(4) Labour Code).', "If the employee breaches the non-compete, the employee shall return compensation received for the months breached; this is without prejudice to the employer's right to demonstrable damages."] });
    }
    sections.push({ title: 'IX. CONFIDENTIALITY AND PROTECTION OF TRADE SECRETS', body: ['The employee shall maintain confidentiality of all facts learnt in connection with employment that are marked as confidential or whose nature plainly implies confidentiality.', 'This duty applies throughout employment and for 3 years after its end.', 'Liability is governed by § 257 Labour Code; intentional damage or damage caused under the influence of alcohol or other substances entails full liability (§ 257(3) Labour Code). Note: contractual penalties against the employee may not be agreed in an employment relationship (§ 346d Labour Code).'] });
  }
  sections.push({ title: `${hasPremium ? 'X' : 'VIII'}. FINAL PROVISIONS`, body: ['This Contract is governed by the Labour Code, as amended, and subsidiarily by Act No. 89/2012 Coll., the Civil Code.', 'The employer must conclude the employment contract before the employee starts work (§ 34(3) Labour Code). The employee may not start work until the Contract is signed.', 'Labour disputes shall be heard by the competent court under § 9(1) CCP.', 'The Contract is executed in two counterparts; each party receives one (§ 37 Labour Code).', 'Amendments are valid only as written, numbered and signed addenda (§ 564 Civil Code).', 'The invalidity of any individual provision does not affect the validity of the remaining provisions.', 'Personal data are processed under EU Regulation 2016/679 (GDPR), Act No. 110/2019 Coll. and § 316 of the Labour Code.', 'Neither party is liable for non-performance of non-monetary obligations caused by force majeure (§ 2913(2) Civil Code).'] });
  sections.push({ title: `${hasPremium ? 'XI' : 'IX'}. SIGNATURES`, body: [] });
  return sections;
}

function uk(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const { effectiveTrial } = shared(d);
  const trialClause = effectiveTrial > 0 ? `Випробувальний строк погоджується на ${effectiveTrial} місяців з дати виникнення трудових відносин (§ 35 ТК у редакції Закону № 120/2025 Sb.). У трудових відносинах на визначений строк випробувальний строк не може перевищити половини погодженої тривалості. Протягом випробувального строку будь-яка сторона може припинити трудові відносини у будь-який час, з будь-яких або без зазначення причини.` : 'Випробувальний строк не сторонується.';
  const duration = d.employmentType === 'fixed' ? `на визначений строк до ${fmtDate(d.endDate, 'uk-UA') || 'не вказано'} (§ 39 ТК)` : 'на невизначений строк';
  const salary = d.salaryType === 'monthly' ? `Працівнику належить щомісячна заробітна плата у розмірі ${fmtAmount(d.salary)} крон брутто. Заробітна плата сплачується у регулярний день виплати, тобто ${pad(d.payDay) || '15'}. дня календарного місяця, що настає за місяцем, за який належить заробітна плата, безготівковим переказом на банківський рахунок працівника.` : `Працівнику належить погодинна заробітна плата у розмірі ${fmtAmount(d.hourlyRate)} крон/год брутто.`;
  const workTime = d.workHours ? `Погоджений тижневий робочий час: ${pad(d.workHours)} годин. Графік: ${pad(d.workSchedule) || 'понеділок–п\'ятниця, 8:00–17:00'}.` : 'Тижневий робочий час встановлюється у обсязі 40 годин (§ 79 ТК). Графік: понеділок–п\'ятниця, 8:00–17:00.';
  const sections: ParaPair[] = [
    { title: 'ПРЕАМБУЛА', body: ['Ця трудова угода («Угода») укладається відповідно до § 34 та наступних Закону № 262/2006 Sb., Трудовий кодекс Чехії, з наступними змінами («ТК»).', `Дата укладення: ${date(d.contractDate, 'uk-UA')}`] },
    { title: 'I. СТОРОНИ', body: [`Роботодавець: ${pad(d.employerName)}, IČO: ${pad(d.employerIco) || '—'}, місцезнаходження: ${pad(d.employerAddress)}`, d.employerEmail ? `E-mail роботодавця: ${pad(d.employerEmail)}` : '', `Працівник: ${pad(d.employeeName)}, дата народження: ${pad(d.employeeBirth) || '—'}, місце проживання: ${pad(d.employeeAddress)}`, d.employeeEmail ? `E-mail працівника: ${pad(d.employeeEmail)}` : ''] },
    { title: 'II. ВИД ТА МІСЦЕ ВИКОНАННЯ РОБОТИ', body: [`Вид роботи (посада): ${pad(d.jobTitle) || 'не вказано'}`, `Опис посадових обов\'язків: ${pad(d.jobDescription) || 'згідно з актуальним описом робочого місця'}`, `Місце виконання роботи: ${pad(d.workPlace) || 'не вказано'}`, d.remoteWork ? `Можливість віддаленої роботи (home office): ${pad(d.remoteWork)}` : ''] },
    { title: 'III. ВИНИКНЕННЯ ТРУДОВИХ ВІДНОСИН І СТРОК', body: [`Трудові відносини виникають у день виходу на роботу: ${fmtDate(d.startDate, 'uk-UA') || 'не вказано'}`, `Трудові відносини сторонуються ${duration}.`, trialClause] },
    { title: 'IV. РОБОЧИЙ ЧАС', body: [workTime, `Перерва на обід та відпочинок: ${pad(d.breakMinutes) || '30'} хвилин за § 88 ТК.`, `Відпустка: Працівнику належить відпустка у тривалості ${pad(d.vacationWeeks) || '4'} тижнів за календарний рік за § 212 ТК.`] },
    { title: 'V. ЗАРОБІТНА ПЛАТА ТА ВИНАГОРОДА', body: [salary, d.bonusDesc ? `Працівнику можуть бути нараховані рухомі складові зарплати (премії/бонуси): ${pad(d.bonusDesc)}.` : '', 'Роботодавець зобов\'язаний при виплаті надати працівнику письмовий документ (платіжну стрічку) з даними про окремі складові зарплати та проведені утримання.'] },
    { title: 'VI. ПРАВА ТА ОБОВ\'ЯЗКИ ПРАЦІВНИКА', body: ['Працівник зобов\'язаний:', '(a) особисто виконувати роботу за трудовою угодою та дотримуватися робочого часу,', '(b) дотримуватися приписів безпеки праці, трудового розпорядку роботодавця та проходити законом вимагане навчання БНП (§ 103 ТК),', '(c) повідомляти роботодавця про перешкоди в роботі (хвороба, догляд) без зайвої затримки,', '(d) зберігати конфіденційність про інформацію, позначену як конфіденційну,', '(e) захищати майно роботодавця та не вживати алкоголь та інші засоби на робочому місці.'] },
    { title: 'VII. ПРИПИНЕННЯ ТРУДОВИХ ВІДНОСИН', body: ['Трудові відносини можуть бути припинені: угодою, попередженням, негайним розірванням або спливом погодженого строку (§ 48 ТК).', `Строк попередження відповідно до § 51 ТК становить ${pad(d.noticePeriod) || '2'} місяці. Строк попередження починається з першого дня календарного місяця, що настає за врученням попередження.`, 'Попередження від роботодавця має бути обґрунтоване (§ 52 ТК). Попередження від працівника може бути надано з будь-якої або без зазначення причини.'] },
  ];
  if (hasPremium) {
    if (d.nonCompete) {
      sections.push({ title: 'VIII. КОНКУРЕНТНА ОБМОВКА', body: [`Працівник зобов\'язується, що протягом ${pad(d.nonCompetePeriod) || '12'} місяців з припинення трудових відносин не виконуватиме платну діяльність, яка б була тотожна предмету бізнесу роботодавця або мала б щодо роботодавця конкурентний характер (§ 310 ТК).`, 'За дотримання цього зобов\'язання працівнику належить грошове компенсаційне забезпечення у розмірі принаймні половини середнього щомісячного заробітку за кожен місяць виконання зобов\'язання. Компенсація сплачується щомісяця заднім числом, завжди до 15. дня календарного місяця, що настає за місяцем, за який належить.', 'Конкурентна обмовка предметно, тимчасово і територіально визначена з урахуванням характеру інформації, до якої працівник мав доступ. Роботодавець має право відмовитись від конкурентної обмовки протягом тривалості трудових відносин працівника (§ 310(4) ТК).', 'При порушенні конкурентної обмовки працівник зобов\'язаний повернути отримане компенсаційне забезпечення, що припадає на місяці, у які зобов\'язання не дотримав; тим не порушується право роботодавця на відшкодування доведеної шкоди.'] });
    }
    sections.push({ title: 'IX. КОНФІДЕНЦІЙНІСТЬ ТА ЗАХИСТ КОМЕРЦІЙНОЇ ТАЄМНИЦІ', body: ['Працівник зобов\'язаний зберігати конфіденційність про всі факти, з якими ознайомився у зв\'язку з виконанням свого трудового відношення та які позначені як конфіденційні або характер яких явно вимагає такої конфіденційності.', 'Обов\'язок конфіденційності діє протягом тривалості трудових відносин та далі протягом 3 років з їхнього припинення.', 'За шкоду, заподіяну порушенням обов\'язку конфіденційності, працівник відповідає у обсязі § 257 ТК. У випадку умисного заподіяння шкоди або шкоди, заподіяної під впливом алкоголю чи інших звикальних речовин, працівник відповідає за шкоду в повному обсязі (§ 257(3) ТК). Зауваження: договірний штраф за рахунок працівника у трудово-правовому відношенні не сторонується (§ 346d ТК).'] });
  }
  sections.push({ title: `${hasPremium ? 'X' : 'VIII'}. ЗАКЛЮЧНІ ПОЛОЖЕННЯ`, body: ['Трудова угода регулюється Законом № 262/2006 Sb., Трудовим кодексом, з наступними змінами, та субсидіарно Законом № 89/2012 Sb., Цивільним кодексом.', 'Роботодавець зобов\'язаний укласти трудову угоду перед виходом працівника на роботу (§ 34(3) ТК). Працівник не може вийти на роботу, доки трудова угода не була підписана.', 'Трудові спори вирішує компетентний суд за § 9(1) ЦПК.', 'Угода складена у двох примірниках; кожна сторона отримує по одному (§ 37 ТК).', 'Зміни трудової угоди дійсні лише у формі писемних, нумерованих і підписаних доповнень (§ 564 ЦК).', 'Недійсність окремого положення не впливає на дійсність решти положень.', 'Обробка персональних даних здійснюється відповідно до Регламенту ЄС 2016/679 (GDPR), Закону № 110/2019 Sb. та § 316 ТК.', 'Жодна сторона не відповідає за невиконання немайнових зобов\'язань, спричинене форс-мажором (§ 2913(2) ЦК).'] });
  sections.push({ title: `${hasPremium ? 'XI' : 'IX'}. ПІДПИСИ`, body: [] });
  return sections;
}

export function buildEmploymentTranslationsBySection(d: StoredContractData, hasPremium: boolean): Array<NonNullable<ContractSection['translations']>> {
  return buildBilingualTranslations({
    en: () => en(d, hasPremium),
    ua: () => uk(d, hasPremium),
  });
}
