/**
 * Lease (nájemní smlouva) — paired Czech translations for EN and UA PDFs.
 * Mirrors buildLeaseContractSections paragraph-by-paragraph.
 *
 * NOTE: These translations require a Czech-law-aware native legal translator
 * review before going live. The Czech wording remains the prevailing version.
 */
import type { ContractSection, StoredContractData } from '../contracts';
import { buildBilingualTranslations, fmtAmount, fmtDate, pad, type ParaPair } from './helpers';

const date = (v: unknown, l: string) => v ? fmtDate(v, l) : new Date().toLocaleDateString(l);

function shared(d: StoredContractData) {
  const propertyAddress = pad(d.propertyAddress || d.flatAddress);
  const propertyLayout = pad(d.propertyLayout || d.flatLayout);
  const utilitiesAmount = d.utilitiesAmount ?? d.utilityAmount ?? '';
  const paymentDay = d.paymentDay ? String(d.paymentDay).replace(/\D/g, '') : '5';
  const isFixedTerm = d.duration === 'fixed' && Boolean(d.endDate);
  const hasDeposit = Number(d.depositAmount || 0) > 0;
  const hasUtilities = Number(utilitiesAmount || 0) > 0;
  const monthlyTotal = (Number(d.rentAmount || 0) + Number(utilitiesAmount || 0)).toString();
  const useIndex = (d.includeInflationIndexation === true || d.rentIndexationMode === 'cpi' || d.rentIndexationMode === 'inflation');
  return { propertyAddress, propertyLayout, utilitiesAmount, paymentDay, isFixedTerm, hasDeposit, hasUtilities, monthlyTotal, useIndex };
}

// ── EN ─────────────────────────────────────────────────────────────────────
function en(d: StoredContractData, hasPremium: boolean, includeLeaseHandoverProtocol: boolean): ParaPair[] {
  const s = shared(d);
  const useIndex = hasPremium && s.useIndex;
  const leaseDuration = d.leaseDuration ? pad(d.leaseDuration) : s.isFixedTerm ? `fixed, until ${fmtDate(d.endDate, 'en-GB')}` : 'indefinite';

  const sections: ParaPair[] = [
    { title: 'PREAMBLE', body: ['This lease agreement (the "Agreement") is concluded under § 2201 et seq. of Act No. 89/2012 Coll., the Czech Civil Code, as amended ("Civil Code"), and in particular § 2235 et seq. of the Civil Code (residential lease).', `Date of conclusion: ${date(d.contractDate, 'en-GB')}`] },
    { title: 'I. PARTIES', body: [`Landlord: ${pad(d.landlordName)}, date of birth / Company ID: ${pad(d.landlordId) || '—'}, residence / registered office: ${pad(d.landlordAddress)}`, d.landlordOP ? `Landlord ID card no.: ${pad(d.landlordOP)}` : '', d.landlordEmail ? `Landlord e-mail: ${pad(d.landlordEmail)}` : '', d.landlordPhone ? `Landlord phone: ${pad(d.landlordPhone)}` : '', `Tenant: ${pad(d.tenantName)}, date of birth / Company ID: ${pad(d.tenantId) || '—'}, residence / registered office: ${pad(d.tenantAddress)}`, d.tenantOP ? `Tenant ID card no.: ${pad(d.tenantOP)}` : '', d.tenantEmail ? `Tenant e-mail: ${pad(d.tenantEmail)}` : '', d.tenantPhone ? `Tenant phone: ${pad(d.tenantPhone)}` : ''] },
    { title: 'II. SUBJECT OF THE LEASE', body: [`The Landlord lets to the Tenant for consideration, for temporary use, the flat located at: ${s.propertyAddress}.`, `Layout: ${s.propertyLayout || 'not specified'}.`, d.flatUnitNumber ? `Flat unit number: ${pad(d.flatUnitNumber)}.` : '', d.cadastralArea ? `Cadastral area: ${pad(d.cadastralArea)}, parcel number: ${pad(d.parcelNumber) || 'not specified'}.` : '', d.ownershipSheet ? `Title deed no.: ${pad(d.ownershipSheet)}.` : '', d.floor ? `Floor: ${pad(d.floor)}.` : '', (d.flatArea || d.approxArea) ? `Floor area of the flat: ${pad(d.flatArea || d.approxArea)} m².` : '', 'The Landlord declares that it is entitled to let the flat to the Tenant and that no legal or factual obstacles are known.', 'The Tenant confirms having inspected the condition of the leased property prior to signing and accepts it as described in the handover protocol.'] },
    { title: 'III. LEASE TERM', body: [`The lease is concluded for a ${leaseDuration} term.`, d.startDate ? `Lease commencement: ${fmtDate(d.startDate)}.` : '', d.handoverDate ? `Physical handover date: ${fmtDate(d.handoverDate)}.` : '', s.isFixedTerm ? "The lease ends upon the expiry of the agreed term. Early termination only on statutory grounds or grounds set out herein. If the Tenant continues to use the flat for more than three months after the end without the Landlord's objection, the lease is deemed renewed for the same period (max. 2 years, § 2230 Civil Code)." : "The Tenant may terminate with 3 months' notice without reasons. The Landlord may terminate with 3 months' notice only on statutory grounds (§ 2288 Civil Code)."] },
    { title: 'IV. RENT AND PAYMENTS FOR SERVICES', body: [`Monthly rent: CZK ${fmtAmount(d.rentAmount)}.`, s.hasUtilities ? `Monthly advance payments for services: CZK ${fmtAmount(s.utilitiesAmount)}.` : "No separate monthly advances for services have been agreed; the Tenant pays for services directly to the providers or based on the Landlord's settlement.", s.hasUtilities ? `Total monthly payment (rent + advances): CZK ${fmtAmount(s.monthlyTotal)}.` : '', `Rent${s.hasUtilities ? ' and service advances are payable' : ' is payable'} by the ${s.paymentDay}${s.paymentDay === '1' ? 'st' : s.paymentDay === '2' ? 'nd' : s.paymentDay === '3' ? 'rd' : 'th'} day of the relevant month in advance.`, d.bankAccount ? `Landlord bank account: ${pad(d.bankAccount)}.` : '', d.variableSymbol ? `Variable symbol: ${pad(d.variableSymbol)}.` : '', d.utilitiesIncludedText ? `Services and advances covered: ${pad(d.utilitiesIncludedText)}.` : s.hasUtilities ? 'Service advances typically include: water/sewerage, heating/hot water, common areas, waste — based on actual costs.' : '', s.hasUtilities ? "The Landlord shall settle actual service costs once a year and deliver the settlement within 4 months of the end of the billing period (§ 7 Act No. 67/2013 Coll.)." : '', useIndex ? "The Landlord may, effective 1 April each year, unilaterally increase the rent by inflation (annual CPI change) published by the Czech Statistical Office. Written notice at least 30 days before the first due date of the increased rent." : "The Landlord may propose a rent increase in writing in line with the law, in particular customary local rent and limits under § 2249 Civil Code.", 'Electricity and gas drawn directly by the Tenant are not part of advances and are paid separately.', "In case of delay, the Landlord may claim statutory default interest (Government Decree No. 351/2013 Coll.)."] },
    { title: 'V. DEPOSIT', body: s.hasDeposit ? [`The Tenant shall pay a deposit of CZK ${fmtAmount(d.depositAmount)}${d.rentAmount && Number(d.rentAmount) > 0 ? ` (≈ ${Math.round(Number(d.depositAmount) / Number(d.rentAmount))}× the monthly rent)` : ''} before taking over the flat.`, "The deposit secures the Landlord's claims (unpaid rent, advances, damages beyond ordinary wear).", "At the end of the lease, the Landlord shall return the unused deposit with statutory interest (§ 2254(2) Civil Code), less proven and itemised claims. The parties should set out the timing and settlement procedure in the contract.", "The Landlord may set off duly specified, due claims; the Tenant must be notified in writing with an itemised statement.", "The deposit and any agreed contractual penalty claim may not exceed three times the monthly rent in aggregate (§ 2254 Civil Code)."] : ['No cash deposit has been agreed between the parties.'] },
    { title: 'VI. RULES OF USE', body: [d.maxOccupants ? `Maximum number of persons permanently occupying the flat: ${pad(d.maxOccupants)} (including the Tenant).` : '', `Pets: ${d.allowPets ? 'acknowledged; the Tenant is liable for damage and additional costs' : "the Tenant may keep an animal where it does not cause unreasonable disturbance; the Landlord must be informed in advance"}.`, `Smoking: ${d.allowSmoking ? 'permitted' : 'prohibited'}.`, `Short-term paid accommodation via Airbnb/Booking is sublease and is ${d.allowAirbnb ? 'permitted; the Tenant is liable for all damages and statutory accommodation-provider obligations' : "prohibited without the Landlord's prior written consent"}.`, `Business activity in the flat: ${d.businessUseAllowed ? 'permitted provided it does not increase wear beyond customary use' : "permitted only if it does not increase wear or disturb others; otherwise requires the Landlord's prior written consent (§ 2255 Civil Code)"}.`, d.inspectionAllowed ? "The Landlord may, after written (e-mail) notice with at least 24 hours' advance, inspect the flat (§ 2219 Civil Code)." : "The Landlord's right of entry is governed by statute (§ 2219 Civil Code).", d.strictPenalties ? 'For serious or repeated breach the Landlord may, after written notice, terminate on grounds of gross breach (§ 2288(1)(a)) or — for particularly serious breach harming the Landlord/occupants — without notice period (§ 2291).' : '', 'The Tenant shall maintain the flat in working order; report defects without delay; allow necessary repairs; pay minor repair costs (§ 2257); not carry out structural alterations without consent.', "The Tenant may sublet part of the flat where the Tenant resides in it; the Landlord must be informed without delay. Subletting the whole flat (or when the Tenant does not reside) requires prior written consent.", "Upon written request the Tenant shall, within 7 days, provide proof of valid household insurance covering liability (recommended min. CZK 500,000)."] },
    { title: 'VII. HANDOVER OF THE FLAT', body: [d.keysCount ? `The Landlord hands over ${pad(d.keysCount)} key(s).` : '', 'The Tenant may not make key copies without consent. Loss must be reported in writing; the Tenant bears lock/cylinder replacement cost.', d.electricityMeter ? `Electricity meter reading at handover: ${pad(d.electricityMeter)} kWh${d.electricityMeterSerial ? `, serial no. ${pad(d.electricityMeterSerial)}` : ''}.` : '', d.gasMeter ? `Gas meter reading at handover: ${pad(d.gasMeter)} m³${d.gasMeterSerial ? `, serial no. ${pad(d.gasMeterSerial)}` : ''}.` : '', d.waterMeter ? `Cold water meter reading at handover: ${pad(d.waterMeter)} m³${d.waterMeterSerial ? `, serial no. ${pad(d.waterMeterSerial)}` : ''}.` : '', d.hotWaterMeter ? `Hot water meter reading at handover: ${pad(d.hotWaterMeter)} m³${d.hotWaterMeterSerial ? `, serial no. ${pad(d.hotWaterMeterSerial)}` : ''}.` : '', d.equipmentList ? `Inventory of equipment: ${pad(d.equipmentList)}.` : '', d.knownDefects ? `Defects disclosed by the Landlord: ${pad(d.knownDefects)}.` : 'The flat is handed over without expressly disclosed defects beyond ordinary wear and tear.', includeLeaseHandoverProtocol ? 'The detailed handover protocol forms Annex 1.' : ''] },
    { title: 'VIII. TERMINATION OF THE LEASE', body: [d.duration === 'indefinite' ? 'An indefinite-term lease may be terminated by notice (§ 2231, § 2286 et seq.), by agreement, or otherwise as provided by law.' : 'A fixed-term lease ends upon the expiry of the agreed term. Either party may terminate on grounds set by law.', 'On termination the Tenant shall (a) vacate the flat and remove belongings, (b) restore the flat to its initial condition (ordinary wear excepted), (c) return all keys, (d) allow protocol-based handover.', `Failure to deliver up the flat properly and in time: the Tenant shall pay ${pad(d.lateVacatePenalty) || "one day's rent"} per day of delay.`] },
    { title: 'IX. EMERGENCIES AND REPAIRS', body: ['The Tenant shall report any emergency or damage-causing defect within 24 hours.', 'Necessary protective measures may be taken without prior consent; the Landlord shall be informed immediately.', 'The Tenant pays for ordinary maintenance and minor repairs (§ 2257 Civil Code) within Government Decree No. 308/2015 Coll.', 'Larger repairs are borne by the Landlord, unless caused by the Tenant or persons to whom the Tenant granted access.'] },
    { title: 'X. SERVICE OF NOTICES', body: [`Notices to the Landlord: ${pad(d.landlordAddress)}${d.landlordEmail ? `, or e-mail: ${pad(d.landlordEmail)}` : ''}.`, `Notices to the Tenant: ${s.propertyAddress}${d.tenantEmail ? `, or e-mail: ${pad(d.tenantEmail)}` : ''}.`, 'Notices affecting the lease relationship are delivered in person, by registered mail, via data box, or by other demonstrable means. E-mail is acceptable for routine communication.', 'Refusal of delivery is deemed delivered on the day of refusal; uncollected items are deemed delivered on the last day of the storage period where permitted by law.'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'XI. OPERATIONAL AND DOCUMENTATION TERMS', body: ['Material facts (defects, key handovers, household changes, repair records) shall be confirmed demonstrably — preferably by e-mail or registered post.', 'Upon termination a handover protocol (Annex 1) shall be drawn up, including meter readings, key list, equipment inventory and room-by-room assessment. Photographs may be attached.', 'For disputes about damage scope, the parties shall first seek amicable determination; failing agreement, an expert may be called in — cost borne by the party whose claim proves unfounded.', 'The Tenant is liable for damage caused by persons granted access.'] });
    sections.push({ title: 'XII. SPECIAL PROVISIONS ON TERMINATION', body: ['No later than 5 working days before the planned end, the parties shall confirm in writing the exact handover date and time. Failing agreement, the Landlord may unilaterally set the date with at least 3 working days\' notice.', 'The Landlord shall return the deposit per Art. V(3), with a written settlement of asserted claims (grounds, scope, amount). Without such settlement no part of the deposit may be unilaterally retained beyond the statutory framework.', 'For required repairs or professional cleaning at the Tenant\'s cost, the Landlord shall notify the Tenant in writing before commencing work and provide a reasonable period (at least 5 working days) for comments.'] });
  }
  sections.push({ title: `${hasPremium ? 'XIII' : 'XI'}. FINAL PROVISIONS`, body: ['Governed by Czech law, in particular Act No. 89/2012 Coll., the Civil Code, and Act No. 67/2013 Coll. (settlement of services).', 'Disputes shall be resolved primarily amicably; failing agreement, by the competent court of the Czech Republic.', 'Executed in two counterparts; each party receives one.', 'Amendments only as written, numbered and signed addenda.', 'Severability clause: invalidity of any individual provision does not affect the rest.', includeLeaseHandoverProtocol ? 'Annex 1 (handover protocol) forms an integral part of this Agreement.' : '', 'Change of ownership of the leased property does not in itself terminate the lease (§ 2221 Civil Code).', 'Personal data are processed under EU Regulation 2016/679 (GDPR) and Act No. 110/2019 Coll.', 'Force majeure exception (§ 2913(2) Civil Code).'] });
  sections.push({ title: `${hasPremium ? 'XIV' : 'XII'}. SIGNATURES`, body: [] });
  if (includeLeaseHandoverProtocol) {
    sections.push({ title: 'ANNEX 1 – HANDOVER PROTOCOL', body: [] });
  }
  return sections;
}

// ── UK ─────────────────────────────────────────────────────────────────────
function uk(d: StoredContractData, hasPremium: boolean, includeLeaseHandoverProtocol: boolean): ParaPair[] {
  const s = shared(d);
  const useIndex = hasPremium && s.useIndex;
  const leaseDuration = d.leaseDuration ? pad(d.leaseDuration) : s.isFixedTerm ? `визначений, до ${fmtDate(d.endDate, 'uk-UA')}` : 'невизначений';
  const sections: ParaPair[] = [
    { title: 'ПРЕАМБУЛА', body: ['Цей договір оренди («Договір») укладається відповідно до § 2201 та наступних Закону № 89/2012 Sb., Цивільний кодекс Чехії, з наступними змінами («ЦК»), та зокрема § 2235 та наступних ЦК (оренда житла).', `Дата укладення: ${date(d.contractDate, 'uk-UA')}`] },
    { title: 'I. СТОРОНИ', body: [`Орендодавець: ${pad(d.landlordName)}, дата народження / IČO: ${pad(d.landlordId) || '—'}, місце проживання / місцезнаходження: ${pad(d.landlordAddress)}`, d.landlordOP ? `Номер посвідчення орендодавця: ${pad(d.landlordOP)}` : '', d.landlordEmail ? `E-mail орендодавця: ${pad(d.landlordEmail)}` : '', d.landlordPhone ? `Телефон орендодавця: ${pad(d.landlordPhone)}` : '', `Орендар: ${pad(d.tenantName)}, дата народження / IČO: ${pad(d.tenantId) || '—'}, місце проживання / місцезнаходження: ${pad(d.tenantAddress)}`, d.tenantOP ? `Номер посвідчення орендаря: ${pad(d.tenantOP)}` : '', d.tenantEmail ? `E-mail орендаря: ${pad(d.tenantEmail)}` : '', d.tenantPhone ? `Телефон орендаря: ${pad(d.tenantPhone)}` : ''] },
    { title: 'II. ПРЕДМЕТ ОРЕНДИ', body: [`Орендодавець передає орендарю за плату у тимчасове користування квартиру за адресою: ${s.propertyAddress}.`, `Планування: ${s.propertyLayout || 'не вказано'}.`, d.flatUnitNumber ? `Номер квартири: ${pad(d.flatUnitNumber)}.` : '', d.cadastralArea ? `Кадастровий округ: ${pad(d.cadastralArea)}, номер ділянки: ${pad(d.parcelNumber) || 'не вказано'}.` : '', d.ownershipSheet ? `Аркуш власності: ${pad(d.ownershipSheet)}.` : '', d.floor ? `Поверх: ${pad(d.floor)}.` : '', (d.flatArea || d.approxArea) ? `Площа квартири: ${pad(d.flatArea || d.approxArea)} м².` : '', 'Орендодавець заявляє, що має право передати квартиру в оренду та йому не відомі правові чи фактичні перешкоди.', 'Орендар підтверджує, що перед підписом ознайомився зі станом предмета оренди та приймає його у стані, описаному в акті прийому-передачі.'] },
    { title: 'III. СТРОК ОРЕНДИ', body: [`Оренда укладається на ${leaseDuration} строк.`, d.startDate ? `Початок оренди: ${fmtDate(d.startDate, 'uk-UA')}.` : '', d.handoverDate ? `Дата фізичної передачі: ${fmtDate(d.handoverDate, 'uk-UA')}.` : '', s.isFixedTerm ? 'Оренда припиняється спливом погодженого строку. Дострокове припинення лише на законних підставах або підставах цього Договору. Якщо орендар продовжує користуватися квартирою більше 3 місяців після припинення без заперечень орендодавця, оренда вважається поновленою (макс. 2 роки, § 2230 ЦК).' : 'Орендар може припинити з 3-місячним строком попередження без зазначення причин. Орендодавець може припинити з 3-місячним строком попередження лише на законних підставах (§ 2288 ЦК).'] },
    { title: 'IV. ОРЕНДНА ПЛАТА ТА ПЛАТЕЖІ ЗА ПОСЛУГИ', body: [`Щомісячна орендна плата: ${fmtAmount(d.rentAmount)} крон.`, s.hasUtilities ? `Щомісячний авансовий платіж за послуги: ${fmtAmount(s.utilitiesAmount)} крон.` : 'Окремі щомісячні аванси за послуги не погоджено; орендар сплачує постачальникам безпосередньо або за розрахунком орендодавця.', s.hasUtilities ? `Загальний щомісячний платіж: ${fmtAmount(s.monthlyTotal)} крон.` : '', `Орендна плата${s.hasUtilities ? ' та аванси за послуги сплачуються' : ' сплачується'} до ${s.paymentDay} дня відповідного місяця авансом.`, d.bankAccount ? `Банківський рахунок орендодавця: ${pad(d.bankAccount)}.` : '', d.variableSymbol ? `Variable symbol: ${pad(d.variableSymbol)}.` : '', d.utilitiesIncludedText ? `Послуги, які покриваються: ${pad(d.utilitiesIncludedText)}.` : s.hasUtilities ? 'Аванси за послуги зазвичай включають: вода/каналізація, опалення/гаряча вода, спільні приміщення, відходи — за фактичними витратами.' : '', s.hasUtilities ? 'Орендодавець розраховує фактичні витрати на послуги один раз на рік і доставляє розрахунок протягом 4 місяців з закінчення розрахункового періоду (§ 7 Закону № 67/2013 Sb.).' : '', useIndex ? 'Орендодавець має право з 1 квітня кожного року в односторонньому порядку підвищити орендну плату на рівень інфляції (ICП) опубліковану ЧСУ. Письмове повідомлення не пізніше 30 днів до першої сплати збільшеної плати.' : 'Орендодавець може запропонувати збільшення орендної плати письмово відповідно до закону, зокрема з урахуванням звичайної місцевої орендної плати та обмежень за § 2249 ЦК.', 'Електроенергія та газ, що споживаються безпосередньо орендарем, не входять до авансів і сплачуються окремо.', 'У разі прострочення сплати орендодавець може вимагати законні відсотки за прострочення (Постанова уряду № 351/2013 Sb.).'] },
    { title: 'V. ГРОШОВА ЗАСТАВА (КАУЦІЯ)', body: s.hasDeposit ? [`Орендар сплачує грошову заставу (кауцію) у розмірі ${fmtAmount(d.depositAmount)} крон${d.rentAmount && Number(d.rentAmount) > 0 ? ` (≈ ${Math.round(Number(d.depositAmount) / Number(d.rentAmount))}× щомісячна орендна плата)` : ''} перед прийняттям квартири.`, 'Грошова застава забезпечує вимоги орендодавця (несплачена орендна плата, аванси, шкода понад звичайне зношування).', 'Після припинення оренди орендодавець повертає невикористану частину грошової застави із законними відсотками (§ 2254(2) ЦК), за вирахуванням доведених і конкретизованих вимог. Строк і порядок розрахунку бажано прямо визначити в договорі.', 'Орендодавець може зарахувати належно специфіковані вимоги; орендаря необхідно письмово повідомити з переліком.', 'Грошова застава і будь-яке погоджене право на договірний штраф разом не можуть перевищувати трикратний розмір місячної орендної плати (§ 2254 ЦК).'] : ['Грошова застава (кауція) між сторонами не погоджена.'] },
    { title: 'VI. ПРАВИЛА КОРИСТУВАННЯ', body: [d.maxOccupants ? `Максимальна кількість осіб, що постійно проживають у квартирі: ${pad(d.maxOccupants)} (включно з орендарем).` : '', `Домашні тварини: ${d.allowPets ? 'визнано; орендар відповідає за шкоду та підвищені витрати' : 'орендар може тримати тварину, якщо це не спричиняє непропорційних незручностей; орендодавець має бути попередньо проінформований'}.`, `Куріння: ${d.allowSmoking ? 'дозволено' : 'заборонено'}.`, `Короткостроковий платний прийом гостей через Airbnb/Booking — це піднайм і ${d.allowAirbnb ? 'дозволено; орендар відповідає за всю шкоду і виконує законні обов\'язки провайдера' : 'заборонено без попередньої письмової згоди орендодавця'}.`, `Підприємницька діяльність у квартирі: ${d.businessUseAllowed ? 'дозволена за умови, що не збільшує зношування понад звичайне' : 'дозволена лише якщо не збільшує зношування або не турбує інших; інакше потребує попередньої письмової згоди орендодавця (§ 2255 ЦК)'}.`, d.inspectionAllowed ? 'Орендодавець може після письмового (e-mail) повідомлення не менше ніж за 24 години перевірити квартиру (§ 2219 ЦК).' : 'Право входу орендодавця регулюється законом (§ 2219 ЦК).', d.strictPenalties ? 'За серйозне або повторне порушення орендодавець може після письмового нагадування припинити на підставі грубого порушення (§ 2288(1)(а)) або — при особливо серйозному порушенні, що шкодить орендодавцю/мешканцям — без строку попередження (§ 2291).' : '', 'Орендар зобов\'язаний підтримувати квартиру в робочому стані; повідомляти про дефекти без зволікання; допускати необхідні ремонти; сплачувати дрібні ремонти (§ 2257); не здійснювати будівельні зміни без згоди.', 'Орендар може передати частину квартири в піднайм, якщо там проживає; орендодавець має бути проінформований без зволікання. Піднайм цілої квартири (або коли орендар не проживає) потребує попередньої письмової згоди.', 'На письмовий запит орендар протягом 7 днів надає підтвердження дійсного страхування побутового майна з покриттям відповідальності (рекомендований мін. 500 000 крон).'] },
    { title: 'VII. ПЕРЕДАЧА КВАРТИРИ', body: [d.keysCount ? `Орендодавець передає ${pad(d.keysCount)} ключа(ів).` : '', 'Орендар не може робити копії ключів без згоди. Про втрату необхідно повідомити письмово; орендар несе вартість заміни замка.', d.electricityMeter ? `Показання електролічильника при передачі: ${pad(d.electricityMeter)} кВт·год${d.electricityMeterSerial ? `, серійний № ${pad(d.electricityMeterSerial)}` : ''}.` : '', d.gasMeter ? `Показання газового лічильника при передачі: ${pad(d.gasMeter)} м³${d.gasMeterSerial ? `, серійний № ${pad(d.gasMeterSerial)}` : ''}.` : '', d.waterMeter ? `Показання лічильника холодної води при передачі: ${pad(d.waterMeter)} м³${d.waterMeterSerial ? `, серійний № ${pad(d.waterMeterSerial)}` : ''}.` : '', d.hotWaterMeter ? `Показання лічильника гарячої води при передачі: ${pad(d.hotWaterMeter)} м³${d.hotWaterMeterSerial ? `, серійний № ${pad(d.hotWaterMeterSerial)}` : ''}.` : '', d.equipmentList ? `Інвентар обладнання: ${pad(d.equipmentList)}.` : '', d.knownDefects ? `Заявлені орендодавцем дефекти: ${pad(d.knownDefects)}.` : 'Квартира передається без явно заявлених дефектів понад звичайне зношування.', includeLeaseHandoverProtocol ? 'Детальний акт прийому-передачі є Додатком 1.' : ''] },
    { title: 'VIII. ПРИПИНЕННЯ ОРЕНДИ', body: [d.duration === 'indefinite' ? 'Оренду на невизначений строк можна припинити попередженням (§ 2231, § 2286 та наступні), угодою або іншим способом, передбаченим законом.' : 'Оренда на визначений строк припиняється спливом погодженого строку. Будь-яка зі сторін може припинити з підстав, встановлених законом.', 'При припиненні орендар зобов\'язаний (а) звільнити квартиру, (б) привести квартиру до первісного стану (з урахуванням звичайного зношування), (в) повернути всі ключі, (г) допустити протокольну передачу.', `Якщо орендар не передасть квартиру належно і вчасно: сплачує ${pad(d.lateVacatePenalty) || 'денну орендну плату'} за кожен день прострочення.`] },
    { title: 'IX. АВАРІЇ ТА РЕМОНТИ', body: ['Орендар зобов\'язаний повідомити про будь-яку аварію або дефект, що може спричинити шкоду, протягом 24 годин.', 'Необхідні захисні заходи можна вжити без попередньої згоди; орендодавець інформується негайно.', 'Орендар сплачує звичайне обслуговування та дрібні ремонти (§ 2257 ЦК) в обсязі Постанови уряду № 308/2015 Sb.', 'Більший ремонт несе орендодавець, якщо тільки шкоду не заподіяв орендар або особи, яким орендар надав доступ.'] },
    { title: 'X. ВРУЧЕННЯ ПИСЕМ', body: [`Письма орендодавцю: ${pad(d.landlordAddress)}${d.landlordEmail ? `, або e-mail: ${pad(d.landlordEmail)}` : ''}.`, `Письма орендарю: ${s.propertyAddress}${d.tenantEmail ? `, або e-mail: ${pad(d.tenantEmail)}` : ''}.`, 'Письма, що стосуються орендних відносин, доставляються особисто, рекомендованим листом, через датовану скриньку або іншим доказовим способом. E-mail прийнятний для звичайної комунікації.', 'Відмова від прийняття вважається врученням у день відмови; невирученими вважаються врученими в останній день строку зберігання, якщо це дозволено законом.'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'XI. ОПЕРАЦІЙНІ ТА ДОКУМЕНТАЦІЙНІ УМОВИ', body: ['Суттєві факти (дефекти, передача ключів, зміни у домогосподарстві, записи про ремонти) підтверджуються доказовим способом — переважно e-mail або рекомендованим листом.', 'При припиненні складається акт прийому-передачі (Додаток 1), що містить показання лічильників, перелік ключів, інвентар обладнання та оцінку кожної кімнати. Фотодокументація може бути додана.', 'При спорах про обсяг шкоди сторони спочатку шукають мирне визначення; за відсутності згоди можна залучити експерта — витрати несе сторона, чия вимога виявиться необґрунтованою.', 'Орендар відповідає за шкоду, заподіяну особами, яким він надав доступ.'] });
    sections.push({ title: 'XII. ОСОБЛИВІ УМОВИ ПРИ ПРИПИНЕННІ', body: ['Не пізніше 5 робочих днів до запланованого припинення сторони письмово підтверджують точну дату і час передачі. За відсутності згоди орендодавець може односторонньо визначити дату з мін. 3 робочими днями попередження.', 'Орендодавець повертає грошову заставу за ст. V(3), з письмовим розрахунком заявлених вимог (підстава, обсяг, сума). Без такого розрахунку не можна односторонньо утримати жодну частину грошової застави понад законні рамки.', 'Для необхідних ремонтів чи професійного прибирання за рахунок орендаря орендодавець письмово повідомляє орендаря перед початком робіт та надає розумний строк (мін. 5 робочих днів) для коментарів.'] });
  }
  sections.push({ title: `${hasPremium ? 'XIII' : 'XI'}. ЗАКЛЮЧНІ ПОЛОЖЕННЯ`, body: ['Регулюється чеським правом, зокрема Законом № 89/2012 Sb., Цивільним кодексом, та Законом № 67/2013 Sb. (розрахунок послуг).', 'Спори вирішуються насамперед мирним шляхом; за відсутності згоди — компетентним судом Чеської Республіки.', 'Складено у двох примірниках; кожна сторона отримує по одному.', 'Зміни лише у формі писемних, нумерованих і підписаних доповнень.', 'Недійсність окремого положення не впливає на інші.', includeLeaseHandoverProtocol ? 'Додаток 1 (акт прийому-передачі) є невід\'ємною частиною Договору.' : '', 'Зміна власника не припиняє оренду (§ 2221 ЦК).', 'Обробка персональних даних за GDPR і Законом № 110/2019 Sb.', 'Виняток для форс-мажору (§ 2913(2) ЦК).'] });
  sections.push({ title: `${hasPremium ? 'XIV' : 'XII'}. ПІДПИСИ`, body: [] });
  if (includeLeaseHandoverProtocol) {
    sections.push({ title: 'ДОДАТОК 1 – АКТ ПРИЙОМУ-ПЕРЕДАЧІ', body: [] });
  }
  return sections;
}

export function buildLeaseTranslationsBySection(d: StoredContractData, hasPremium: boolean, includeLeaseHandoverProtocol = false): Array<NonNullable<ContractSection['translations']>> {
  const translations = buildBilingualTranslations({
    en: () => en(d, hasPremium, includeLeaseHandoverProtocol),
    ua: () => uk(d, hasPremium, includeLeaseHandoverProtocol),
  });

  // In Ukrainian tenancy terminology, "завдаток" is an earnest-money deposit
  // and can imply a different legal function. A Czech lease security deposit
  // is therefore described as "грошова застава (кауція)" throughout.
  const terminology: Array<[string, string]> = [
    ['V. ЗАВДАТОК', 'V. ГРОШОВА ЗАСТАВА (КАУЦІЯ)'],
    ['Орендар сплачує завдаток', 'Орендар сплачує грошову заставу (кауцію)'],
    ['Завдаток забезпечує', 'Грошова застава забезпечує'],
    ['частину завдатку', 'частину грошової застави'],
    ['Завдаток і', 'Грошова застава і'],
    ['Грошовий завдаток (кауція)', 'Грошова застава (кауція)'],
    ['повертає завдаток', 'повертає грошову заставу'],
    ['Variable symbol', 'Варіабельний символ'],
    ['(ICП)', '(ІСЦ)'],
  ];

  for (const section of translations) {
    const ua = section.ua;
    if (!ua) continue;
    if (ua.title) {
      for (const [from, to] of terminology) ua.title = ua.title.replaceAll(from, to);
    }
    if (ua.body) {
      ua.body = ua.body.map((paragraph) => {
        let next = paragraph;
        for (const [from, to] of terminology) next = next.replaceAll(from, to);
        return next;
      });
    }
  }

  return translations;
}
