/**
 * Lease (nájemní smlouva) — translations EN/UK/RU/VN/DE.
 * Mirrors buildLeaseContractSections paragraph-by-paragraph.
 *
 * NOTE: These translations are first-pass and should be reviewed by a
 * Czech-law-aware native speaker before going live. Czech remains the
 * legally binding version.
 */
import type { ContractSection, StoredContractData } from '../contracts';
import { buildBilingualTranslations, fmtAmount, fmtDate, pad, type ParaPair } from './helpers';

const date = (v: unknown, l: string) => v ? fmtDate(v, l) : new Date().toLocaleDateString(l);

function shared(d: StoredContractData) {
  const propertyAddress = pad(d.propertyAddress || d.flatAddress);
  const propertyLayout = pad(d.propertyLayout || d.flatLayout);
  const utilitiesAmount = d.utilitiesAmount ?? d.utilityAmount ?? '';
  const paymentDay = d.paymentDay ? String(d.paymentDay).replace(/\D/g, '') : '5';
  const isFixedTerm = d.duration === 'fixed' && Boolean(d.endDate);
  const hasDeposit = Number(d.depositAmount || 0) > 0;
  const hasUtilities = Number(utilitiesAmount || 0) > 0;
  const monthlyTotal = (Number(d.rentAmount || 0) + Number(utilitiesAmount || 0)).toString();
  const useIndex = (d.includeInflationIndexation === true || d.rentIndexationMode === 'cpi' || d.rentIndexationMode === 'inflation');
  return { propertyAddress, propertyLayout, utilitiesAmount, paymentDay, isFixedTerm, hasDeposit, hasUtilities, monthlyTotal, useIndex };
}

// ── EN ─────────────────────────────────────────────────────────────────────
function en(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const s = shared(d);
  const useIndex = hasPremium && s.useIndex;
  const leaseDuration = d.leaseDuration ? pad(d.leaseDuration) : s.isFixedTerm ? `fixed, until ${fmtDate(d.endDate, 'en-GB')}` : 'indefinite';

  const sections: ParaPair[] = [
    { title: 'PREAMBLE', body: ['This lease agreement (the "Agreement") is concluded under § 2201 et seq. of Act No. 89/2012 Coll., the Czech Civil Code, as amended ("Civil Code"), and in particular § 2235 et seq. of the Civil Code (residential lease).', `Date of conclusion: ${date(d.contractDate, 'en-GB')}`] },
    { title: 'I. PARTIES', body: [`Landlord: ${pad(d.landlordName)}, date of birth / Company ID: ${pad(d.landlordId) || '—'}, residence / registered office: ${pad(d.landlordAddress)}`, d.landlordOP ? `Landlord ID card no.: ${pad(d.landlordOP)}` : '', d.landlordEmail ? `Landlord e-mail: ${pad(d.landlordEmail)}` : '', d.landlordPhone ? `Landlord phone: ${pad(d.landlordPhone)}` : '', `Tenant: ${pad(d.tenantName)}, date of birth / Company ID: ${pad(d.tenantId) || '—'}, residence / registered office: ${pad(d.tenantAddress)}`, d.tenantOP ? `Tenant ID card no.: ${pad(d.tenantOP)}` : '', d.tenantEmail ? `Tenant e-mail: ${pad(d.tenantEmail)}` : '', d.tenantPhone ? `Tenant phone: ${pad(d.tenantPhone)}` : ''] },
    { title: 'II. SUBJECT OF THE LEASE', body: [`The Landlord lets to the Tenant for consideration, for temporary use, the flat located at: ${s.propertyAddress}.`, `Layout: ${s.propertyLayout || 'not specified'}.`, d.flatUnitNumber ? `Flat unit number: ${pad(d.flatUnitNumber)}.` : '', d.cadastralArea ? `Cadastral area: ${pad(d.cadastralArea)}, parcel number: ${pad(d.parcelNumber) || 'not specified'}.` : '', d.ownershipSheet ? `Title deed no.: ${pad(d.ownershipSheet)}.` : '', d.floor ? `Floor: ${pad(d.floor)}.` : '', (d.flatArea || d.approxArea) ? `Floor area of the flat: ${pad(d.flatArea || d.approxArea)} m².` : '', 'The Landlord declares that it is entitled to let the flat to the Tenant and that no legal or factual obstacles are known.', 'The Tenant confirms having inspected the condition of the leased property prior to signing and accepts it as described in the handover protocol.'] },
    { title: 'III. LEASE TERM', body: [`The lease is concluded for a ${leaseDuration} term.`, d.startDate ? `Lease commencement: ${fmtDate(d.startDate)}.` : '', d.handoverDate ? `Physical handover date: ${fmtDate(d.handoverDate)}.` : '', s.isFixedTerm ? "The lease ends upon the expiry of the agreed term. Early termination only on statutory grounds or grounds set out herein. If the Tenant continues to use the flat for more than three months after the end without the Landlord's objection, the lease is deemed renewed for the same period (max. 2 years, § 2230 Civil Code)." : "The Tenant may terminate with 3 months' notice without reasons. The Landlord may terminate with 3 months' notice only on statutory grounds (§ 2288 Civil Code)."] },
    { title: 'IV. RENT AND PAYMENTS FOR SERVICES', body: [`Monthly rent: CZK ${fmtAmount(d.rentAmount)}.`, s.hasUtilities ? `Monthly advance payments for services: CZK ${fmtAmount(s.utilitiesAmount)}.` : "No separate monthly advances for services have been agreed; the Tenant pays for services directly to the providers or based on the Landlord's settlement.", s.hasUtilities ? `Total monthly payment (rent + advances): CZK ${fmtAmount(s.monthlyTotal)}.` : '', `Rent${s.hasUtilities ? ' and service advances are payable' : ' is payable'} by the ${s.paymentDay}${s.paymentDay === '1' ? 'st' : s.paymentDay === '2' ? 'nd' : s.paymentDay === '3' ? 'rd' : 'th'} day of the relevant month in advance.`, d.bankAccount ? `Landlord bank account: ${pad(d.bankAccount)}.` : '', d.variableSymbol ? `Variable symbol: ${pad(d.variableSymbol)}.` : '', d.utilitiesIncludedText ? `Services and advances covered: ${pad(d.utilitiesIncludedText)}.` : s.hasUtilities ? 'Service advances typically include: water/sewerage, heating/hot water, common areas, waste — based on actual costs.' : '', s.hasUtilities ? "The Landlord shall settle actual service costs once a year and deliver the settlement within 4 months of the end of the billing period (§ 7 Act No. 67/2013 Coll.)." : '', useIndex ? "The Landlord may, effective 1 April each year, unilaterally increase the rent by inflation (annual CPI change) published by the Czech Statistical Office. Written notice at least 30 days before the first due date of the increased rent." : "The Landlord may propose a rent increase in writing in line with the law, in particular customary local rent and limits under § 2249 Civil Code.", 'Electricity and gas drawn directly by the Tenant are not part of advances and are paid separately.', "In case of delay, the Landlord may claim statutory default interest (Government Decree No. 351/2013 Coll.)."] },
    { title: 'V. DEPOSIT', body: s.hasDeposit ? [`The Tenant shall pay a deposit of CZK ${fmtAmount(d.depositAmount)}${d.rentAmount && Number(d.rentAmount) > 0 ? ` (≈ ${Math.round(Number(d.depositAmount) / Number(d.rentAmount))}× the monthly rent)` : ''} before taking over the flat.`, "The deposit secures the Landlord's claims (unpaid rent, advances, damages beyond ordinary wear).", "The Landlord shall return the deposit within 1 month of the end of the lease and vacation, with statutory interest (§ 2254(2) Civil Code), less proven claims.", "The Landlord may set off duly specified, due claims; the Tenant must be notified in writing with an itemised statement."] : ['No cash deposit has been agreed between the parties.'] },
    { title: 'VI. RULES OF USE', body: [d.maxOccupants ? `Maximum number of persons permanently occupying the flat: ${pad(d.maxOccupants)} (including the Tenant).` : '', `Pets: ${d.allowPets ? 'acknowledged; the Tenant is liable for damage and additional costs' : "the Tenant may keep an animal where it does not cause unreasonable disturbance; the Landlord must be informed in advance"}.`, `Smoking: ${d.allowSmoking ? 'permitted' : 'prohibited'}.`, `Short-term paid accommodation via Airbnb/Booking is sublease and is ${d.allowAirbnb ? 'permitted; the Tenant is liable for all damages and statutory accommodation-provider obligations' : "prohibited without the Landlord's prior written consent"}.`, `Business activity in the flat: ${d.businessUseAllowed ? 'permitted provided it does not increase wear beyond customary use' : "permitted only if it does not increase wear or disturb others; otherwise requires the Landlord's prior written consent (§ 2255 Civil Code)"}.`, d.inspectionAllowed ? "The Landlord may, after written (e-mail) notice with at least 24 hours' advance, inspect the flat (§ 2219 Civil Code)." : "The Landlord's right of entry is governed by statute (§ 2219 Civil Code).", d.strictPenalties ? 'For serious or repeated breach the Landlord may, after written notice, terminate on grounds of gross breach (§ 2288(1)(a)) or — for particularly serious breach harming the Landlord/occupants — without notice period (§ 2291).' : '', 'The Tenant shall maintain the flat in working order; report defects without delay; allow necessary repairs; pay minor repair costs (§ 2257); not carry out structural alterations without consent.', "The Tenant may sublet part of the flat where the Tenant resides in it; the Landlord must be informed without delay. Subletting the whole flat (or when the Tenant does not reside) requires prior written consent.", "Upon written request the Tenant shall, within 7 days, provide proof of valid household insurance covering liability (recommended min. CZK 500,000)."] },
    { title: 'VII. HANDOVER OF THE FLAT', body: [d.keysCount ? `The Landlord hands over ${pad(d.keysCount)} key(s).` : '', 'The Tenant may not make key copies without consent. Loss must be reported in writing; the Tenant bears lock/cylinder replacement cost.', d.electricityMeter ? `Electricity meter reading at handover: ${pad(d.electricityMeter)} kWh.` : '', d.gasMeter ? `Gas meter reading at handover: ${pad(d.gasMeter)} m³.` : '', d.waterMeter ? `Water meter reading at handover: ${pad(d.waterMeter)} m³.` : '', d.equipmentList ? `Inventory of equipment: ${pad(d.equipmentList)}.` : '', d.knownDefects ? `Defects disclosed by the Landlord: ${pad(d.knownDefects)}.` : 'The flat is handed over without expressly disclosed defects beyond ordinary wear and tear.', 'The detailed handover protocol forms Annex 1.'] },
    { title: 'VIII. TERMINATION OF THE LEASE', body: [d.duration === 'indefinite' ? 'An indefinite-term lease may be terminated by notice (§ 2231, § 2286 et seq.), by agreement, or otherwise as provided by law.' : 'A fixed-term lease ends upon the expiry of the agreed term. Either party may terminate on grounds set by law.', 'On termination the Tenant shall (a) vacate the flat and remove belongings, (b) restore the flat to its initial condition (ordinary wear excepted), (c) return all keys, (d) allow protocol-based handover.', `Failure to deliver up the flat properly and in time: the Tenant shall pay ${pad(d.lateVacatePenalty) || "one day's rent"} per day of delay.`] },
    { title: 'IX. EMERGENCIES AND REPAIRS', body: ['The Tenant shall report any emergency or damage-causing defect within 24 hours.', 'Necessary protective measures may be taken without prior consent; the Landlord shall be informed immediately.', 'The Tenant pays for ordinary maintenance and minor repairs (§ 2257 Civil Code) within Government Decree No. 308/2015 Coll.', 'Larger repairs are borne by the Landlord, unless caused by the Tenant or persons to whom the Tenant granted access.'] },
    { title: 'X. SERVICE OF NOTICES', body: [`Notices to the Landlord: ${pad(d.landlordAddress)}${d.landlordEmail ? `, or e-mail: ${pad(d.landlordEmail)}` : ''}.`, `Notices to the Tenant: ${s.propertyAddress}${d.tenantEmail ? `, or e-mail: ${pad(d.tenantEmail)}` : ''}.`, 'Notices affecting the lease relationship are delivered in person, by registered mail, via data box, or by other demonstrable means. E-mail is acceptable for routine communication.', 'Refusal of delivery is deemed delivered on the day of refusal; uncollected items are deemed delivered on the last day of the storage period where permitted by law.'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'XI. OPERATIONAL AND DOCUMENTATION TERMS', body: ['Material facts (defects, key handovers, household changes, repair records) shall be confirmed demonstrably — preferably by e-mail or registered post.', 'Upon termination a handover protocol (Annex 1) shall be drawn up, including meter readings, key list, equipment inventory and room-by-room assessment. Photographs may be attached.', 'For disputes about damage scope, the parties shall first seek amicable determination; failing agreement, an expert may be called in — cost borne by the party whose claim proves unfounded.', 'The Tenant is liable for damage caused by persons granted access.'] });
    sections.push({ title: 'XII. SPECIAL PROVISIONS ON TERMINATION', body: ['No later than 5 working days before the planned end, the parties shall confirm in writing the exact handover date and time. Failing agreement, the Landlord may unilaterally set the date with at least 3 working days\' notice.', 'The Landlord shall return the deposit per Art. V(3), with a written settlement of asserted claims (grounds, scope, amount). Without such settlement no part of the deposit may be unilaterally retained beyond the statutory framework.', 'For required repairs or professional cleaning at the Tenant\'s cost, the Landlord shall notify the Tenant in writing before commencing work and provide a reasonable period (at least 5 working days) for comments.'] });
  }
  sections.push({ title: `${hasPremium ? 'XIII' : 'XI'}. FINAL PROVISIONS`, body: ['Governed by Czech law, in particular Act No. 89/2012 Coll., the Civil Code, and Act No. 67/2013 Coll. (settlement of services).', 'Disputes shall be resolved primarily amicably; failing agreement, by the competent court of the Czech Republic.', 'Executed in two counterparts; each party receives one.', 'Amendments only as written, numbered and signed addenda.', 'Severability clause: invalidity of any individual provision does not affect the rest.', 'Annex 1 (handover protocol) forms an integral part of this Agreement.', 'Change of ownership of the leased property does not in itself terminate the lease (§ 2221 Civil Code).', 'Personal data are processed under EU Regulation 2016/679 (GDPR) and Act No. 110/2019 Coll.', 'Force majeure exception (§ 2913(2) Civil Code).'] });
  sections.push({ title: `${hasPremium ? 'XIV' : 'XII'}. SIGNATURES`, body: [] });
  sections.push({ title: 'ANNEX 1 – HANDOVER PROTOCOL', body: [] });
  return sections;
}

// ── UK ─────────────────────────────────────────────────────────────────────
function uk(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const s = shared(d);
  const useIndex = hasPremium && s.useIndex;
  const leaseDuration = d.leaseDuration ? pad(d.leaseDuration) : s.isFixedTerm ? `визначений, до ${fmtDate(d.endDate, 'uk-UA')}` : 'невизначений';
  const sections: ParaPair[] = [
    { title: 'ПРЕАМБУЛА', body: ['Цей договір оренди («Договір») укладається відповідно до § 2201 та наступних Закону № 89/2012 Sb., Цивільний кодекс Чехії, з наступними змінами («ЦК»), та зокрема § 2235 та наступних ЦК (оренда житла).', `Дата укладення: ${date(d.contractDate, 'uk-UA')}`] },
    { title: 'I. СТОРОНИ', body: [`Орендодавець: ${pad(d.landlordName)}, дата народження / IČO: ${pad(d.landlordId) || '—'}, місце проживання / місцезнаходження: ${pad(d.landlordAddress)}`, d.landlordOP ? `Номер посвідчення орендодавця: ${pad(d.landlordOP)}` : '', d.landlordEmail ? `E-mail орендодавця: ${pad(d.landlordEmail)}` : '', d.landlordPhone ? `Телефон орендодавця: ${pad(d.landlordPhone)}` : '', `Орендар: ${pad(d.tenantName)}, дата народження / IČO: ${pad(d.tenantId) || '—'}, місце проживання / місцезнаходження: ${pad(d.tenantAddress)}`, d.tenantOP ? `Номер посвідчення орендаря: ${pad(d.tenantOP)}` : '', d.tenantEmail ? `E-mail орендаря: ${pad(d.tenantEmail)}` : '', d.tenantPhone ? `Телефон орендаря: ${pad(d.tenantPhone)}` : ''] },
    { title: 'II. ПРЕДМЕТ ОРЕНДИ', body: [`Орендодавець передає орендарю за плату у тимчасове користування квартиру за адресою: ${s.propertyAddress}.`, `Планування: ${s.propertyLayout || 'не вказано'}.`, d.flatUnitNumber ? `Номер квартири: ${pad(d.flatUnitNumber)}.` : '', d.cadastralArea ? `Кадастровий округ: ${pad(d.cadastralArea)}, номер ділянки: ${pad(d.parcelNumber) || 'не вказано'}.` : '', d.ownershipSheet ? `Аркуш власності: ${pad(d.ownershipSheet)}.` : '', d.floor ? `Поверх: ${pad(d.floor)}.` : '', (d.flatArea || d.approxArea) ? `Площа квартири: ${pad(d.flatArea || d.approxArea)} м².` : '', 'Орендодавець заявляє, що має право передати квартиру в оренду та йому не відомі правові чи фактичні перешкоди.', 'Орендар підтверджує, що перед підписом ознайомився зі станом предмета оренди та приймає його у стані, описаному в акті прийому-передачі.'] },
    { title: 'III. СТРОК ОРЕНДИ', body: [`Оренда укладається на ${leaseDuration} строк.`, d.startDate ? `Початок оренди: ${fmtDate(d.startDate, 'uk-UA')}.` : '', d.handoverDate ? `Дата фізичної передачі: ${fmtDate(d.handoverDate, 'uk-UA')}.` : '', s.isFixedTerm ? 'Оренда припиняється спливом погодженого строку. Дострокове припинення лише на законних підставах або підставах цього Договору. Якщо орендар продовжує користуватися квартирою більше 3 місяців після припинення без заперечень орендодавця, оренда вважається поновленою (макс. 2 роки, § 2230 ЦК).' : 'Орендар може припинити з 3-місячним строком попередження без зазначення причин. Орендодавець може припинити з 3-місячним строком попередження лише на законних підставах (§ 2288 ЦК).'] },
    { title: 'IV. ОРЕНДНА ПЛАТА ТА ПЛАТЕЖІ ЗА ПОСЛУГИ', body: [`Щомісячна орендна плата: ${fmtAmount(d.rentAmount)} крон.`, s.hasUtilities ? `Щомісячний авансовий платіж за послуги: ${fmtAmount(s.utilitiesAmount)} крон.` : 'Окремі щомісячні аванси за послуги не погоджено; орендар сплачує постачальникам безпосередньо або за розрахунком орендодавця.', s.hasUtilities ? `Загальний щомісячний платіж: ${fmtAmount(s.monthlyTotal)} крон.` : '', `Орендна плата${s.hasUtilities ? ' та аванси за послуги сплачуються' : ' сплачується'} до ${s.paymentDay} дня відповідного місяця авансом.`, d.bankAccount ? `Банківський рахунок орендодавця: ${pad(d.bankAccount)}.` : '', d.variableSymbol ? `Variable symbol: ${pad(d.variableSymbol)}.` : '', d.utilitiesIncludedText ? `Послуги, які покриваються: ${pad(d.utilitiesIncludedText)}.` : s.hasUtilities ? 'Аванси за послуги зазвичай включають: вода/каналізація, опалення/гаряча вода, спільні приміщення, відходи — за фактичними витратами.' : '', s.hasUtilities ? 'Орендодавець розраховує фактичні витрати на послуги один раз на рік і доставляє розрахунок протягом 4 місяців з закінчення розрахункового періоду (§ 7 Закону № 67/2013 Sb.).' : '', useIndex ? 'Орендодавець має право з 1 квітня кожного року в односторонньому порядку підвищити орендну плату на рівень інфляції (ICП) опубліковану ЧСУ. Письмове повідомлення не пізніше 30 днів до першої сплати збільшеної плати.' : 'Орендодавець може запропонувати збільшення орендної плати письмово відповідно до закону, зокрема з урахуванням звичайної місцевої орендної плати та обмежень за § 2249 ЦК.', 'Електроенергія та газ, що споживаються безпосередньо орендарем, не входять до авансів і сплачуються окремо.', 'У разі прострочення сплати орендодавець може вимагати законні відсотки за прострочення (Постанова уряду № 351/2013 Sb.).'] },
    { title: 'V. ЗАВДАТОК', body: s.hasDeposit ? [`Орендар сплачує завдаток у розмірі ${fmtAmount(d.depositAmount)} крон${d.rentAmount && Number(d.rentAmount) > 0 ? ` (≈ ${Math.round(Number(d.depositAmount) / Number(d.rentAmount))}× щомісячна орендна плата)` : ''} перед прийняттям квартири.`, 'Завдаток забезпечує вимоги орендодавця (несплачена орендна плата, аванси, шкода понад звичайне зношування).', 'Орендодавець повертає завдаток протягом 1 місяця з припинення оренди та звільнення з законними відсотками (§ 2254(2) ЦК), за вирахуванням доведених вимог.', 'Орендодавець може зарахувати належно специфіковані вимоги; орендаря необхідно письмово повідомити з переліком.'] : ['Грошовий завдаток (кауція) між сторонами не погоджено.'] },
    { title: 'VI. ПРАВИЛА КОРИСТУВАННЯ', body: [d.maxOccupants ? `Максимальна кількість осіб, що постійно проживають у квартирі: ${pad(d.maxOccupants)} (включно з орендарем).` : '', `Домашні тварини: ${d.allowPets ? 'визнано; орендар відповідає за шкоду та підвищені витрати' : 'орендар може тримати тварину, якщо це не спричиняє непропорційних незручностей; орендодавець має бути попередньо проінформований'}.`, `Куріння: ${d.allowSmoking ? 'дозволено' : 'заборонено'}.`, `Короткостроковий платний прийом гостей через Airbnb/Booking — це піднайм і ${d.allowAirbnb ? 'дозволено; орендар відповідає за всю шкоду і виконує законні обов\'язки провайдера' : 'заборонено без попередньої письмової згоди орендодавця'}.`, `Підприємницька діяльність у квартирі: ${d.businessUseAllowed ? 'дозволена за умови, що не збільшує зношування понад звичайне' : 'дозволена лише якщо не збільшує зношування або не турбує інших; інакше потребує попередньої письмової згоди орендодавця (§ 2255 ЦК)'}.`, d.inspectionAllowed ? 'Орендодавець може після письмового (e-mail) повідомлення не менше ніж за 24 години перевірити квартиру (§ 2219 ЦК).' : 'Право входу орендодавця регулюється законом (§ 2219 ЦК).', d.strictPenalties ? 'За серйозне або повторне порушення орендодавець може після письмового нагадування припинити на підставі грубого порушення (§ 2288(1)(а)) або — при особливо серйозному порушенні, що шкодить орендодавцю/мешканцям — без строку попередження (§ 2291).' : '', 'Орендар зобов\'язаний підтримувати квартиру в робочому стані; повідомляти про дефекти без зволікання; допускати необхідні ремонти; сплачувати дрібні ремонти (§ 2257); не здійснювати будівельні зміни без згоди.', 'Орендар може передати частину квартири в піднайм, якщо там проживає; орендодавець має бути проінформований без зволікання. Піднайм цілої квартири (або коли орендар не проживає) потребує попередньої письмової згоди.', 'На письмовий запит орендар протягом 7 днів надає підтвердження дійсного страхування побутового майна з покриттям відповідальності (рекомендований мін. 500 000 крон).'] },
    { title: 'VII. ПЕРЕДАЧА КВАРТИРИ', body: [d.keysCount ? `Орендодавець передає ${pad(d.keysCount)} ключа(ів).` : '', 'Орендар не може робити копії ключів без згоди. Про втрату необхідно повідомити письмово; орендар несе вартість заміни замка.', d.electricityMeter ? `Показання електролічильника при передачі: ${pad(d.electricityMeter)} кВт·год.` : '', d.gasMeter ? `Показання газового лічильника при передачі: ${pad(d.gasMeter)} м³.` : '', d.waterMeter ? `Показання водолічильника при передачі: ${pad(d.waterMeter)} м³.` : '', d.equipmentList ? `Інвентар обладнання: ${pad(d.equipmentList)}.` : '', d.knownDefects ? `Заявлені орендодавцем дефекти: ${pad(d.knownDefects)}.` : 'Квартира передається без явно заявлених дефектів понад звичайне зношування.', 'Детальний акт прийому-передачі є Додатком 1.'] },
    { title: 'VIII. ПРИПИНЕННЯ ОРЕНДИ', body: [d.duration === 'indefinite' ? 'Оренду на невизначений строк можна припинити попередженням (§ 2231, § 2286 та наступні), угодою або іншим способом, передбаченим законом.' : 'Оренда на визначений строк припиняється спливом погодженого строку. Будь-яка зі сторін може припинити з підстав, встановлених законом.', 'При припиненні орендар зобов\'язаний (а) звільнити квартиру, (б) привести квартиру до первісного стану (з урахуванням звичайного зношування), (в) повернути всі ключі, (г) допустити протокольну передачу.', `Якщо орендар не передасть квартиру належно і вчасно: сплачує ${pad(d.lateVacatePenalty) || 'денну орендну плату'} за кожен день прострочення.`] },
    { title: 'IX. АВАРІЇ ТА РЕМОНТИ', body: ['Орендар зобов\'язаний повідомити про будь-яку аварію або дефект, що може спричинити шкоду, протягом 24 годин.', 'Необхідні захисні заходи можна вжити без попередньої згоди; орендодавець інформується негайно.', 'Орендар сплачує звичайне обслуговування та дрібні ремонти (§ 2257 ЦК) в обсязі Постанови уряду № 308/2015 Sb.', 'Більший ремонт несе орендодавець, якщо тільки шкоду не заподіяв орендар або особи, яким орендар надав доступ.'] },
    { title: 'X. ВРУЧЕННЯ ПИСЕМ', body: [`Письма орендодавцю: ${pad(d.landlordAddress)}${d.landlordEmail ? `, або e-mail: ${pad(d.landlordEmail)}` : ''}.`, `Письма орендарю: ${s.propertyAddress}${d.tenantEmail ? `, або e-mail: ${pad(d.tenantEmail)}` : ''}.`, 'Письма, що стосуються орендних відносин, доставляються особисто, рекомендованим листом, через датовану скриньку або іншим доказовим способом. E-mail прийнятний для звичайної комунікації.', 'Відмова від прийняття вважається врученням у день відмови; невирученими вважаються врученими в останній день строку зберігання, якщо це дозволено законом.'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'XI. ОПЕРАЦІЙНІ ТА ДОКУМЕНТАЦІЙНІ УМОВИ', body: ['Суттєві факти (дефекти, передача ключів, зміни у домогосподарстві, записи про ремонти) підтверджуються доказовим способом — переважно e-mail або рекомендованим листом.', 'При припиненні складається акт прийому-передачі (Додаток 1), що містить показання лічильників, перелік ключів, інвентар обладнання та оцінку кожної кімнати. Фотодокументація може бути додана.', 'При спорах про обсяг шкоди сторони спочатку шукають мирне визначення; за відсутності згоди можна залучити експерта — витрати несе сторона, чия вимога виявиться необґрунтованою.', 'Орендар відповідає за шкоду, заподіяну особами, яким він надав доступ.'] });
    sections.push({ title: 'XII. ОСОБЛИВІ УМОВИ ПРИ ПРИПИНЕННІ', body: ['Не пізніше 5 робочих днів до запланованого припинення сторони письмово підтверджують точну дату і час передачі. За відсутності згоди орендодавець може односторонньо визначити дату з мін. 3 робочими днями попередження.', 'Орендодавець повертає завдаток за ст. V(3), з письмовим розрахунком заявлених вимог (підстава, обсяг, сума). Без такого розрахунку не можна односторонньо утримати жодну частину завдатку понад законні рамки.', 'Для необхідних ремонтів чи професійного прибирання за рахунок орендаря орендодавець письмово повідомляє орендаря перед початком робіт та надає розумний строк (мін. 5 робочих днів) для коментарів.'] });
  }
  sections.push({ title: `${hasPremium ? 'XIII' : 'XI'}. ЗАКЛЮЧНІ ПОЛОЖЕННЯ`, body: ['Регулюється чеським правом, зокрема Законом № 89/2012 Sb., Цивільним кодексом, та Законом № 67/2013 Sb. (розрахунок послуг).', 'Спори вирішуються насамперед мирним шляхом; за відсутності згоди — компетентним судом Чеської Республіки.', 'Складено у двох примірниках; кожна сторона отримує по одному.', 'Зміни лише у формі писемних, нумерованих і підписаних доповнень.', 'Недійсність окремого положення не впливає на інші.', 'Додаток 1 (акт прийому-передачі) є невід\'ємною частиною Договору.', 'Зміна власника не припиняє оренду (§ 2221 ЦК).', 'Обробка персональних даних за GDPR і Законом № 110/2019 Sb.', 'Виняток для форс-мажору (§ 2913(2) ЦК).'] });
  sections.push({ title: `${hasPremium ? 'XIV' : 'XII'}. ПІДПИСИ`, body: [] });
  sections.push({ title: 'ДОДАТОК 1 – АКТ ПРИЙОМУ-ПЕРЕДАЧІ', body: [] });
  return sections;
}

// ── RU ─────────────────────────────────────────────────────────────────────
function ru(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const s = shared(d);
  const useIndex = hasPremium && s.useIndex;
  const leaseDuration = d.leaseDuration ? pad(d.leaseDuration) : s.isFixedTerm ? `определённый, до ${fmtDate(d.endDate, 'ru-RU')}` : 'неопределённый';
  const sections: ParaPair[] = [
    { title: 'ПРЕАМБУЛА', body: ['Настоящий договор найма («Договор») заключается согласно § 2201 и далее Закона № 89/2012 Sb., Гражданский кодекс Чехии, с последующими изменениями («ГК»), и в частности § 2235 и далее ГК (наём жилья).', `Дата заключения: ${date(d.contractDate, 'ru-RU')}`] },
    { title: 'I. СТОРОНЫ', body: [`Наймодатель: ${pad(d.landlordName)}, дата рождения / IČO: ${pad(d.landlordId) || '—'}, место жительства / юридический адрес: ${pad(d.landlordAddress)}`, d.landlordOP ? `Номер удостоверения наймодателя: ${pad(d.landlordOP)}` : '', d.landlordEmail ? `E-mail наймодателя: ${pad(d.landlordEmail)}` : '', d.landlordPhone ? `Телефон наймодателя: ${pad(d.landlordPhone)}` : '', `Наниматель: ${pad(d.tenantName)}, дата рождения / IČO: ${pad(d.tenantId) || '—'}, место жительства / юридический адрес: ${pad(d.tenantAddress)}`, d.tenantOP ? `Номер удостоверения нанимателя: ${pad(d.tenantOP)}` : '', d.tenantEmail ? `E-mail нанимателя: ${pad(d.tenantEmail)}` : '', d.tenantPhone ? `Телефон нанимателя: ${pad(d.tenantPhone)}` : ''] },
    { title: 'II. ПРЕДМЕТ НАЙМА', body: [`Наймодатель передаёт нанимателю за плату во временное пользование квартиру по адресу: ${s.propertyAddress}.`, `Планировка: ${s.propertyLayout || 'не указано'}.`, d.flatUnitNumber ? `Номер квартиры: ${pad(d.flatUnitNumber)}.` : '', d.cadastralArea ? `Кадастровый округ: ${pad(d.cadastralArea)}, номер участка: ${pad(d.parcelNumber) || 'не указано'}.` : '', d.ownershipSheet ? `Лист собственности: ${pad(d.ownershipSheet)}.` : '', d.floor ? `Этаж: ${pad(d.floor)}.` : '', (d.flatArea || d.approxArea) ? `Площадь квартиры: ${pad(d.flatArea || d.approxArea)} м².` : '', 'Наймодатель заявляет, что вправе передать квартиру в наём и ему не известны правовые или фактические препятствия.', 'Наниматель подтверждает, что перед подписанием ознакомился с состоянием предмета найма и принимает его в состоянии, описанном в акте приёма-передачи.'] },
    { title: 'III. СРОК НАЙМА', body: [`Наём заключается на ${leaseDuration} срок.`, d.startDate ? `Начало найма: ${fmtDate(d.startDate, 'ru-RU')}.` : '', d.handoverDate ? `Дата физической передачи: ${fmtDate(d.handoverDate, 'ru-RU')}.` : '', s.isFixedTerm ? 'Наём прекращается истечением согласованного срока. Досрочное прекращение только по законным основаниям или основаниям настоящего Договора. Если наниматель продолжает пользоваться квартирой более 3 месяцев после прекращения без возражений наймодателя, наём считается возобновлённым (макс. 2 года, § 2230 ГК).' : 'Наниматель может прекратить с 3-месячным сроком уведомления без указания причин. Наймодатель может прекратить с 3-месячным сроком уведомления только по законным основаниям (§ 2288 ГК).'] },
    { title: 'IV. ПЛАТА ЗА НАЁМ И ПЛАТЕЖИ ЗА УСЛУГИ', body: [`Ежемесячная плата за наём: ${fmtAmount(d.rentAmount)} крон.`, s.hasUtilities ? `Ежемесячный авансовый платёж за услуги: ${fmtAmount(s.utilitiesAmount)} крон.` : 'Отдельные ежемесячные авансы за услуги не согласованы; наниматель оплачивает поставщикам напрямую или по расчёту наймодателя.', s.hasUtilities ? `Общий ежемесячный платёж: ${fmtAmount(s.monthlyTotal)} крон.` : '', `Плата за наём${s.hasUtilities ? ' и авансы за услуги уплачиваются' : ' уплачивается'} до ${s.paymentDay}-го дня соответствующего месяца авансом.`, d.bankAccount ? `Банковский счёт наймодателя: ${pad(d.bankAccount)}.` : '', d.variableSymbol ? `Variable symbol: ${pad(d.variableSymbol)}.` : '', d.utilitiesIncludedText ? `Услуги, которые покрываются: ${pad(d.utilitiesIncludedText)}.` : s.hasUtilities ? 'Авансы за услуги обычно включают: вода/канализация, отопление/горячая вода, общие помещения, отходы — по фактическим расходам.' : '', s.hasUtilities ? 'Наймодатель рассчитывает фактические расходы на услуги один раз в год и доставляет расчёт в течение 4 месяцев с окончания расчётного периода (§ 7 Закона № 67/2013 Sb.).' : '', useIndex ? 'Наймодатель имеет право с 1 апреля каждого года в одностороннем порядке повысить плату за наём на уровень инфляции (ИПЦ) опубликованной ЧСУ. Письменное уведомление не позднее 30 дней до первой уплаты увеличенной платы.' : 'Наймодатель может предложить увеличение платы за наём письменно в соответствии с законом, в частности с учётом обычной местной платы и ограничений по § 2249 ГК.', 'Электроэнергия и газ, потребляемые непосредственно нанимателем, не входят в авансы и уплачиваются отдельно.', 'В случае просрочки уплаты наймодатель может требовать законные проценты за просрочку (Постановление правительства № 351/2013 Sb.).'] },
    { title: 'V. ЗАЛОГ', body: s.hasDeposit ? [`Наниматель уплачивает залог в размере ${fmtAmount(d.depositAmount)} крон${d.rentAmount && Number(d.rentAmount) > 0 ? ` (≈ ${Math.round(Number(d.depositAmount) / Number(d.rentAmount))}× ежемесячная плата за наём)` : ''} до принятия квартиры.`, 'Залог обеспечивает требования наймодателя (неуплаченная плата за наём, авансы, ущерб сверх обычного износа).', 'Наймодатель возвращает залог в течение 1 месяца с прекращения найма и освобождения с законными процентами (§ 2254(2) ГК), за вычетом доказанных требований.', 'Наймодатель может зачесть должным образом конкретизированные требования; нанимателя необходимо письменно уведомить с перечнем.'] : ['Денежный залог (кауция) между сторонами не согласован.'] },
    { title: 'VI. ПРАВИЛА ПОЛЬЗОВАНИЯ', body: [d.maxOccupants ? `Максимальное количество лиц, постоянно проживающих в квартире: ${pad(d.maxOccupants)} (включая нанимателя).` : '', `Домашние животные: ${d.allowPets ? 'признано; наниматель отвечает за ущерб и повышенные расходы' : 'наниматель может держать животное, если это не причиняет непропорциональных неудобств; наймодатель должен быть предварительно проинформирован'}.`, `Курение: ${d.allowSmoking ? 'разрешено' : 'запрещено'}.`, `Краткосрочный платный приём гостей через Airbnb/Booking — это поднайм и ${d.allowAirbnb ? 'разрешено; наниматель отвечает за весь ущерб и выполняет законные обязанности провайдера' : 'запрещено без предварительного письменного согласия наймодателя'}.`, `Предпринимательская деятельность в квартире: ${d.businessUseAllowed ? 'разрешена при условии, что не увеличивает износ сверх обычного' : 'разрешена только если не увеличивает износ или не беспокоит других; иначе требует предварительного письменного согласия наймодателя (§ 2255 ГК)'}.`, d.inspectionAllowed ? 'Наймодатель может после письменного (e-mail) уведомления не менее чем за 24 часа проверить квартиру (§ 2219 ГК).' : 'Право входа наймодателя регулируется законом (§ 2219 ГК).', d.strictPenalties ? 'За серьёзное или повторное нарушение наймодатель может после письменного предупреждения прекратить на основании грубого нарушения (§ 2288(1)(а)) или — при особо серьёзном нарушении, причиняющем вред наймодателю/жильцам — без срока уведомления (§ 2291).' : '', 'Наниматель обязан поддерживать квартиру в рабочем состоянии; сообщать о дефектах без задержки; допускать необходимые ремонты; уплачивать мелкие ремонты (§ 2257); не осуществлять строительные изменения без согласия.', 'Наниматель может передать часть квартиры в поднайм, если там проживает; наймодатель должен быть проинформирован без задержки. Поднайм всей квартиры (или когда наниматель не проживает) требует предварительного письменного согласия.', 'По письменному запросу наниматель в течение 7 дней предоставляет подтверждение действительного страхования бытового имущества с покрытием ответственности (рекомендуемый мин. 500 000 крон).'] },
    { title: 'VII. ПЕРЕДАЧА КВАРТИРЫ', body: [d.keysCount ? `Наймодатель передаёт ${pad(d.keysCount)} ключа(ей).` : '', 'Наниматель не может делать копии ключей без согласия. О потере необходимо сообщить письменно; наниматель несёт стоимость замены замка.', d.electricityMeter ? `Показания электросчётчика при передаче: ${pad(d.electricityMeter)} кВт·ч.` : '', d.gasMeter ? `Показания газового счётчика при передаче: ${pad(d.gasMeter)} м³.` : '', d.waterMeter ? `Показания водосчётчика при передаче: ${pad(d.waterMeter)} м³.` : '', d.equipmentList ? `Инвентарь оборудования: ${pad(d.equipmentList)}.` : '', d.knownDefects ? `Заявленные наймодателем дефекты: ${pad(d.knownDefects)}.` : 'Квартира передаётся без явно заявленных дефектов сверх обычного износа.', 'Детальный акт приёма-передачи является Приложением 1.'] },
    { title: 'VIII. ПРЕКРАЩЕНИЕ НАЙМА', body: [d.duration === 'indefinite' ? 'Наём на неопределённый срок можно прекратить уведомлением (§ 2231, § 2286 и далее), соглашением или иным способом, предусмотренным законом.' : 'Наём на определённый срок прекращается истечением согласованного срока. Любая из сторон может прекратить по основаниям, установленным законом.', 'При прекращении наниматель обязан (а) освободить квартиру, (б) привести квартиру в первоначальное состояние (с учётом обычного износа), (в) вернуть все ключи, (г) допустить протокольную передачу.', `Если наниматель не передаст квартиру надлежащим образом и вовремя: уплачивает ${pad(d.lateVacatePenalty) || 'дневную плату за наём'} за каждый день просрочки.`] },
    { title: 'IX. АВАРИИ И РЕМОНТЫ', body: ['Наниматель обязан сообщить о любой аварии или дефекте, которые могут причинить ущерб, в течение 24 часов.', 'Необходимые защитные меры можно принять без предварительного согласия; наймодатель информируется незамедлительно.', 'Наниматель оплачивает обычное обслуживание и мелкие ремонты (§ 2257 ГК) в объёме Постановления правительства № 308/2015 Sb.', 'Более крупный ремонт несёт наймодатель, если только ущерб не причинил наниматель или лица, которым наниматель предоставил доступ.'] },
    { title: 'X. ВРУЧЕНИЕ ПИСЕМ', body: [`Письма наймодателю: ${pad(d.landlordAddress)}${d.landlordEmail ? `, или e-mail: ${pad(d.landlordEmail)}` : ''}.`, `Письма нанимателю: ${s.propertyAddress}${d.tenantEmail ? `, или e-mail: ${pad(d.tenantEmail)}` : ''}.`, 'Письма, касающиеся отношений найма, доставляются лично, заказным письмом, через электронный ящик или иным доказуемым способом. E-mail приемлем для обычной коммуникации.', 'Отказ от принятия считается вручением в день отказа; невостребованные считаются вручёнными в последний день срока хранения, если это разрешено законом.'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'XI. ОПЕРАЦИОННЫЕ И ДОКУМЕНТАЦИОННЫЕ УСЛОВИЯ', body: ['Существенные факты (дефекты, передача ключей, изменения в домохозяйстве, записи о ремонтах) подтверждаются доказуемым способом — преимущественно e-mail или заказным письмом.', 'При прекращении составляется акт приёма-передачи (Приложение 1), содержащий показания счётчиков, перечень ключей, инвентарь оборудования и оценку каждой комнаты. Фотодокументация может быть приложена.', 'При спорах об объёме ущерба стороны сначала ищут мирное определение; при отсутствии согласия можно привлечь эксперта — расходы несёт сторона, чьё требование окажется необоснованным.', 'Наниматель отвечает за ущерб, причинённый лицами, которым он предоставил доступ.'] });
    sections.push({ title: 'XII. ОСОБЫЕ УСЛОВИЯ ПРИ ПРЕКРАЩЕНИИ', body: ['Не позднее 5 рабочих дней до запланированного прекращения стороны письменно подтверждают точную дату и время передачи. При отсутствии согласия наймодатель может в одностороннем порядке определить дату с мин. 3 рабочими днями уведомления.', 'Наймодатель возвращает залог по ст. V(3), с письменным расчётом заявленных требований (основание, объём, сумма). Без такого расчёта нельзя в одностороннем порядке удержать какую-либо часть залога сверх законных рамок.', 'Для необходимых ремонтов или профессиональной уборки за счёт нанимателя наймодатель письменно уведомляет нанимателя до начала работ и предоставляет разумный срок (мин. 5 рабочих дней) для комментариев.'] });
  }
  sections.push({ title: `${hasPremium ? 'XIII' : 'XI'}. ЗАКЛЮЧИТЕЛЬНЫЕ ПОЛОЖЕНИЯ`, body: ['Регулируется чешским правом, в частности Законом № 89/2012 Sb., Гражданским кодексом, и Законом № 67/2013 Sb. (расчёт услуг).', 'Споры разрешаются прежде всего мирным путём; при отсутствии соглашения — компетентным судом Чешской Республики.', 'Составлен в двух экземплярах; каждая сторона получает по одному.', 'Изменения только в форме письменных, пронумерованных и подписанных дополнений.', 'Недействительность отдельного положения не влияет на другие.', 'Приложение 1 (акт приёма-передачи) является неотъемлемой частью Договора.', 'Изменение собственника не прекращает наём (§ 2221 ГК).', 'Обработка персональных данных по GDPR и Закону № 110/2019 Sb.', 'Исключение для форс-мажора (§ 2913(2) ГК).'] });
  sections.push({ title: `${hasPremium ? 'XIV' : 'XII'}. ПОДПИСИ`, body: [] });
  sections.push({ title: 'ПРИЛОЖЕНИЕ 1 – АКТ ПРИЁМА-ПЕРЕДАЧИ', body: [] });
  return sections;
}

// ── VN ─────────────────────────────────────────────────────────────────────
function vn(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const s = shared(d);
  const useIndex = hasPremium && s.useIndex;
  const leaseDuration = d.leaseDuration ? pad(d.leaseDuration) : s.isFixedTerm ? `xác định, đến ${fmtDate(d.endDate, 'vi-VN')}` : 'không xác định';
  const sections: ParaPair[] = [
    { title: 'LỜI MỞ ĐẦU', body: ['Hợp đồng thuê nhà này ("Hợp đồng") được ký kết theo § 2201 trở đi của Luật số 89/2012 Sb., Bộ luật Dân sự Séc, có sửa đổi ("BLDS"), và đặc biệt là § 2235 trở đi BLDS (thuê nhà ở).', `Ngày ký kết: ${date(d.contractDate, 'vi-VN')}`] },
    { title: 'I. CÁC BÊN', body: [`Bên cho thuê: ${pad(d.landlordName)}, ngày sinh / IČO: ${pad(d.landlordId) || '—'}, nơi cư trú / trụ sở: ${pad(d.landlordAddress)}`, d.landlordOP ? `Số CMND bên cho thuê: ${pad(d.landlordOP)}` : '', d.landlordEmail ? `E-mail bên cho thuê: ${pad(d.landlordEmail)}` : '', d.landlordPhone ? `Điện thoại bên cho thuê: ${pad(d.landlordPhone)}` : '', `Bên thuê: ${pad(d.tenantName)}, ngày sinh / IČO: ${pad(d.tenantId) || '—'}, nơi cư trú / trụ sở: ${pad(d.tenantAddress)}`, d.tenantOP ? `Số CMND bên thuê: ${pad(d.tenantOP)}` : '', d.tenantEmail ? `E-mail bên thuê: ${pad(d.tenantEmail)}` : '', d.tenantPhone ? `Điện thoại bên thuê: ${pad(d.tenantPhone)}` : ''] },
    { title: 'II. ĐỐI TƯỢNG THUÊ', body: [`Bên cho thuê cho bên thuê thuê có thu phí, sử dụng tạm thời căn hộ tại địa chỉ: ${s.propertyAddress}.`, `Bố trí: ${s.propertyLayout || 'chưa nêu rõ'}.`, d.flatUnitNumber ? `Số căn hộ: ${pad(d.flatUnitNumber)}.` : '', d.cadastralArea ? `Khu vực địa chính: ${pad(d.cadastralArea)}, số thửa đất: ${pad(d.parcelNumber) || 'chưa nêu rõ'}.` : '', d.ownershipSheet ? `Tờ sở hữu: ${pad(d.ownershipSheet)}.` : '', d.floor ? `Tầng: ${pad(d.floor)}.` : '', (d.flatArea || d.approxArea) ? `Diện tích căn hộ: ${pad(d.flatArea || d.approxArea)} m².` : '', 'Bên cho thuê tuyên bố có quyền cho thuê căn hộ và không biết về trở ngại pháp lý hoặc thực tế nào.', 'Bên thuê xác nhận đã kiểm tra tình trạng đối tượng thuê trước khi ký và chấp nhận trong tình trạng được mô tả trong biên bản bàn giao.'] },
    { title: 'III. THỜI HẠN THUÊ', body: [`Hợp đồng thuê được ký kết với thời hạn ${leaseDuration}.`, d.startDate ? `Bắt đầu thuê: ${fmtDate(d.startDate, 'vi-VN')}.` : '', d.handoverDate ? `Ngày bàn giao vật lý: ${fmtDate(d.handoverDate, 'vi-VN')}.` : '', s.isFixedTerm ? 'Hợp đồng thuê chấm dứt khi hết thời hạn đã thỏa thuận. Chấm dứt sớm chỉ trên căn cứ luật định hoặc căn cứ trong Hợp đồng này. Nếu bên thuê tiếp tục sử dụng căn hộ hơn 3 tháng sau khi chấm dứt mà không có ý kiến phản đối của bên cho thuê, hợp đồng thuê được coi là gia hạn (tối đa 2 năm, § 2230 BLDS).' : 'Bên thuê có thể chấm dứt với thời hạn báo trước 3 tháng không cần lý do. Bên cho thuê có thể chấm dứt với thời hạn báo trước 3 tháng chỉ trên căn cứ luật định (§ 2288 BLDS).'] },
    { title: 'IV. TIỀN THUÊ VÀ THANH TOÁN DỊCH VỤ', body: [`Tiền thuê hàng tháng: ${fmtAmount(d.rentAmount)} crown Séc.`, s.hasUtilities ? `Phí dịch vụ hàng tháng ứng trước: ${fmtAmount(s.utilitiesAmount)} crown Séc.` : 'Phí dịch vụ ứng trước hàng tháng riêng không được thỏa thuận; bên thuê thanh toán trực tiếp cho nhà cung cấp hoặc theo quyết toán của bên cho thuê.', s.hasUtilities ? `Tổng số thanh toán hàng tháng: ${fmtAmount(s.monthlyTotal)} crown Séc.` : '', `Tiền thuê${s.hasUtilities ? ' và phí dịch vụ ứng trước được thanh toán' : ' được thanh toán'} đến ngày ${s.paymentDay} của tháng tương ứng trước.`, d.bankAccount ? `Tài khoản ngân hàng của bên cho thuê: ${pad(d.bankAccount)}.` : '', d.variableSymbol ? `Variable symbol: ${pad(d.variableSymbol)}.` : '', d.utilitiesIncludedText ? `Dịch vụ được bao gồm: ${pad(d.utilitiesIncludedText)}.` : s.hasUtilities ? 'Phí dịch vụ ứng trước thường bao gồm: nước/nước thải, sưởi/nước nóng, khu vực chung, rác — theo chi phí thực tế.' : '', s.hasUtilities ? 'Bên cho thuê quyết toán chi phí dịch vụ thực tế một lần mỗi năm và gửi quyết toán trong vòng 4 tháng kể từ khi kết thúc kỳ tính phí (§ 7 Luật số 67/2013 Sb.).' : '', useIndex ? 'Bên cho thuê có quyền vào ngày 1 tháng 4 hàng năm đơn phương tăng tiền thuê theo lạm phát (CPI) do Cơ quan Thống kê Séc công bố. Thông báo bằng văn bản chậm nhất 30 ngày trước ngày đáo hạn đầu tiên của tiền thuê tăng.' : 'Bên cho thuê có thể đề xuất tăng tiền thuê bằng văn bản phù hợp với pháp luật, đặc biệt là tiền thuê địa phương thông thường và các giới hạn theo § 2249 BLDS.', 'Điện và khí đốt do bên thuê tiêu thụ trực tiếp không nằm trong khoản ứng trước và được thanh toán riêng.', 'Trong trường hợp chậm thanh toán, bên cho thuê có thể yêu cầu lãi chậm trả theo luật (Nghị định Chính phủ số 351/2013 Sb.).'] },
    { title: 'V. TIỀN ĐẶT CỌC', body: s.hasDeposit ? [`Bên thuê phải đặt cọc ${fmtAmount(d.depositAmount)} crown Séc${d.rentAmount && Number(d.rentAmount) > 0 ? ` (≈ ${Math.round(Number(d.depositAmount) / Number(d.rentAmount))}× tiền thuê hàng tháng)` : ''} trước khi nhận căn hộ.`, 'Tiền đặt cọc đảm bảo các yêu cầu của bên cho thuê (tiền thuê chưa trả, phí dịch vụ ứng trước, thiệt hại vượt quá hao mòn thông thường).', 'Bên cho thuê hoàn trả tiền đặt cọc trong vòng 1 tháng kể từ ngày chấm dứt hợp đồng thuê và giải phóng với lãi suất theo luật (§ 2254(2) BLDS), trừ các yêu cầu được chứng minh.', 'Bên cho thuê có thể bù trừ các yêu cầu đã được xác định hợp lệ; phải thông báo bằng văn bản cho bên thuê kèm danh sách chi tiết.'] : ['Tiền đặt cọc bằng tiền mặt không được các bên thỏa thuận.'] },
    { title: 'VI. QUY TẮC SỬ DỤNG', body: [d.maxOccupants ? `Số người tối đa thường trú trong căn hộ: ${pad(d.maxOccupants)} (bao gồm bên thuê).` : '', `Vật nuôi: ${d.allowPets ? 'được ghi nhận; bên thuê chịu trách nhiệm về thiệt hại và chi phí tăng thêm' : 'bên thuê có thể nuôi vật nuôi nếu việc đó không gây phiền hà không tương xứng; bên cho thuê phải được thông báo trước'}.`, `Hút thuốc: ${d.allowSmoking ? 'cho phép' : 'cấm'}.`, `Cho thuê ngắn hạn có thu phí qua Airbnb/Booking là cho thuê lại và ${d.allowAirbnb ? 'được phép; bên thuê chịu trách nhiệm về mọi thiệt hại và nghĩa vụ pháp lý của nhà cung cấp dịch vụ' : 'cấm nếu không có sự đồng ý trước bằng văn bản của bên cho thuê'}.`, `Hoạt động kinh doanh trong căn hộ: ${d.businessUseAllowed ? 'được phép với điều kiện không làm tăng hao mòn vượt quá mức thông thường' : 'chỉ được phép nếu không làm tăng hao mòn hoặc gây phiền cho người khác; nếu không, cần sự đồng ý trước bằng văn bản của bên cho thuê (§ 2255 BLDS)'}.`, d.inspectionAllowed ? 'Bên cho thuê có thể, sau khi thông báo bằng văn bản (e-mail) trước ít nhất 24 giờ, kiểm tra căn hộ (§ 2219 BLDS).' : 'Quyền vào của bên cho thuê được điều chỉnh bởi luật (§ 2219 BLDS).', d.strictPenalties ? 'Đối với vi phạm nghiêm trọng hoặc lặp lại, bên cho thuê có thể, sau khi nhắc nhở bằng văn bản, chấm dứt trên căn cứ vi phạm nghiêm trọng (§ 2288(1)(a)) hoặc — đối với vi phạm đặc biệt nghiêm trọng gây hại cho bên cho thuê/cư dân — chấm dứt không có thời hạn báo trước (§ 2291).' : '', 'Bên thuê có nghĩa vụ duy trì căn hộ ở tình trạng hoạt động; báo cáo lỗi không chậm trễ; cho phép sửa chữa cần thiết; thanh toán sửa chữa nhỏ (§ 2257); không thực hiện các thay đổi xây dựng mà không có sự đồng ý.', 'Bên thuê có thể cho thuê lại một phần căn hộ nếu vẫn cư trú tại đó; bên cho thuê phải được thông báo không chậm trễ. Cho thuê lại toàn bộ căn hộ (hoặc khi bên thuê không cư trú) cần sự đồng ý trước bằng văn bản.', 'Theo yêu cầu bằng văn bản, bên thuê trong vòng 7 ngày cung cấp bằng chứng bảo hiểm hộ gia đình hợp lệ với phạm vi trách nhiệm (tối thiểu khuyến nghị 500.000 crown Séc).'] },
    { title: 'VII. BÀN GIAO CĂN HỘ', body: [d.keysCount ? `Bên cho thuê bàn giao ${pad(d.keysCount)} chìa khóa.` : '', 'Bên thuê không được sao chép chìa khóa mà không có sự đồng ý. Mất phải được báo cáo bằng văn bản; bên thuê chịu chi phí thay khóa.', d.electricityMeter ? `Chỉ số điện kế tại lúc bàn giao: ${pad(d.electricityMeter)} kWh.` : '', d.gasMeter ? `Chỉ số đồng hồ gas tại lúc bàn giao: ${pad(d.gasMeter)} m³.` : '', d.waterMeter ? `Chỉ số đồng hồ nước tại lúc bàn giao: ${pad(d.waterMeter)} m³.` : '', d.equipmentList ? `Danh mục thiết bị: ${pad(d.equipmentList)}.` : '', d.knownDefects ? `Lỗi do bên cho thuê công bố: ${pad(d.knownDefects)}.` : 'Căn hộ được bàn giao mà không có lỗi rõ ràng vượt quá hao mòn thông thường.', 'Biên bản bàn giao chi tiết là Phụ lục 1.'] },
    { title: 'VIII. CHẤM DỨT HỢP ĐỒNG THUÊ', body: [d.duration === 'indefinite' ? 'Hợp đồng thuê không xác định thời hạn có thể chấm dứt bằng thông báo (§ 2231, § 2286 trở đi), bằng thỏa thuận hoặc theo cách khác do luật quy định.' : 'Hợp đồng thuê có thời hạn xác định chấm dứt khi hết thời hạn đã thỏa thuận. Bất kỳ bên nào có thể chấm dứt trên các căn cứ do luật quy định.', 'Khi chấm dứt, bên thuê có nghĩa vụ (a) giải phóng căn hộ, (b) đưa căn hộ về tình trạng ban đầu (có tính đến hao mòn thông thường), (c) trả lại tất cả chìa khóa, (d) cho phép bàn giao theo biên bản.', `Nếu bên thuê không bàn giao căn hộ đúng cách và đúng thời hạn: phải trả ${pad(d.lateVacatePenalty) || 'tiền thuê một ngày'} cho mỗi ngày chậm.`] },
    { title: 'IX. SỰ CỐ VÀ SỬA CHỮA', body: ['Bên thuê có nghĩa vụ báo cáo bất kỳ sự cố hoặc lỗi có thể gây thiệt hại trong vòng 24 giờ.', 'Các biện pháp bảo vệ cần thiết có thể được thực hiện mà không cần sự đồng ý trước; bên cho thuê được thông báo ngay lập tức.', 'Bên thuê thanh toán việc bảo dưỡng thông thường và sửa chữa nhỏ (§ 2257 BLDS) trong phạm vi Nghị định Chính phủ số 308/2015 Sb.', 'Sửa chữa lớn hơn do bên cho thuê chịu, trừ khi thiệt hại do bên thuê hoặc người được bên thuê cho phép vào gây ra.'] },
    { title: 'X. GIAO CÁC VĂN BẢN', body: [`Văn bản gửi cho bên cho thuê: ${pad(d.landlordAddress)}${d.landlordEmail ? `, hoặc e-mail: ${pad(d.landlordEmail)}` : ''}.`, `Văn bản gửi cho bên thuê: ${s.propertyAddress}${d.tenantEmail ? `, hoặc e-mail: ${pad(d.tenantEmail)}` : ''}.`, 'Các văn bản liên quan đến quan hệ thuê được giao trực tiếp, bằng thư đăng ký, qua hộp dữ liệu hoặc theo cách có thể chứng minh khác. E-mail chấp nhận được cho giao tiếp thường xuyên.', 'Từ chối nhận được coi là đã giao vào ngày từ chối; các vật không nhận được coi là đã giao vào ngày cuối cùng của thời gian lưu trữ nếu luật cho phép.'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'XI. ĐIỀU KIỆN HOẠT ĐỘNG VÀ TÀI LIỆU', body: ['Các sự kiện quan trọng (lỗi, bàn giao chìa khóa, thay đổi hộ gia đình, hồ sơ sửa chữa) được xác nhận theo cách có thể chứng minh — chủ yếu bằng e-mail hoặc thư đăng ký.', 'Khi chấm dứt, lập biên bản bàn giao (Phụ lục 1), bao gồm chỉ số đồng hồ, danh sách chìa khóa, danh mục thiết bị và đánh giá từng phòng. Có thể đính kèm tài liệu ảnh.', 'Đối với tranh chấp về phạm vi thiệt hại, các bên trước tiên tìm cách xác định thân thiện; khi không thỏa thuận được, có thể mời chuyên gia — chi phí do bên có yêu cầu chứng minh không có căn cứ chịu.', 'Bên thuê chịu trách nhiệm về thiệt hại do người được bên thuê cho phép vào gây ra.'] });
    sections.push({ title: 'XII. ĐIỀU KHOẢN ĐẶC BIỆT KHI CHẤM DỨT', body: ['Không muộn hơn 5 ngày làm việc trước khi chấm dứt theo kế hoạch, các bên xác nhận bằng văn bản ngày và giờ bàn giao chính xác. Khi không thỏa thuận được, bên cho thuê có thể đơn phương ấn định ngày với thời hạn báo trước tối thiểu 3 ngày làm việc.', 'Bên cho thuê hoàn trả tiền đặt cọc theo điều V(3), với quyết toán bằng văn bản các yêu cầu đã đưa ra (căn cứ, phạm vi, số tiền). Không có quyết toán này, không thể đơn phương giữ lại bất kỳ phần nào của tiền đặt cọc vượt quá khuôn khổ luật định.', 'Đối với các sửa chữa cần thiết hoặc dọn dẹp chuyên nghiệp bằng chi phí của bên thuê, bên cho thuê thông báo bằng văn bản cho bên thuê trước khi bắt đầu công việc và cung cấp thời gian hợp lý (tối thiểu 5 ngày làm việc) để bình luận.'] });
  }
  sections.push({ title: `${hasPremium ? 'XIII' : 'XI'}. ĐIỀU KHOẢN CUỐI CÙNG`, body: ['Được điều chỉnh bởi pháp luật Séc, đặc biệt là Luật số 89/2012 Sb., Bộ luật Dân sự, và Luật số 67/2013 Sb. (quyết toán dịch vụ).', 'Tranh chấp được giải quyết trước hết bằng cách thân thiện; khi không thỏa thuận được, do tòa án có thẩm quyền của Cộng hòa Séc giải quyết.', 'Được lập thành hai bản; mỗi bên nhận một bản.', 'Các sửa đổi chỉ có hiệu lực dưới dạng phụ lục bằng văn bản, được đánh số và ký.', 'Sự vô hiệu của một điều khoản riêng lẻ không ảnh hưởng đến các điều khoản khác.', 'Phụ lục 1 (biên bản bàn giao) là một phần không thể tách rời của Hợp đồng.', 'Thay đổi chủ sở hữu không tự chấm dứt hợp đồng thuê (§ 2221 BLDS).', 'Xử lý dữ liệu cá nhân theo GDPR và Luật số 110/2019 Sb.', 'Ngoại lệ bất khả kháng (§ 2913(2) BLDS).'] });
  sections.push({ title: `${hasPremium ? 'XIV' : 'XII'}. CHỮ KÝ`, body: [] });
  sections.push({ title: 'PHỤ LỤC 1 – BIÊN BẢN BÀN GIAO', body: [] });
  return sections;
}

// ── DE ─────────────────────────────────────────────────────────────────────
function de(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const s = shared(d);
  const useIndex = hasPremium && s.useIndex;
  const leaseDuration = d.leaseDuration ? pad(d.leaseDuration) : s.isFixedTerm ? `bestimmt, bis ${fmtDate(d.endDate, 'de-DE')}` : 'unbestimmt';
  const sections: ParaPair[] = [
    { title: 'PRÄAMBEL', body: ['Dieser Mietvertrag (der „Vertrag") wird gemäß § 2201 ff. des Gesetzes Nr. 89/2012 Slg., tschechisches BGB, in der geltenden Fassung („BGB"), und insbesondere § 2235 ff. BGB (Wohnungsmiete) geschlossen.', `Datum des Abschlusses: ${date(d.contractDate, 'de-DE')}`] },
    { title: 'I. VERTRAGSPARTEIEN', body: [`Vermieter: ${pad(d.landlordName)}, Geburtsdatum / IČO: ${pad(d.landlordId) || '—'}, Wohnsitz / Sitz: ${pad(d.landlordAddress)}`, d.landlordOP ? `Ausweisnummer des Vermieters: ${pad(d.landlordOP)}` : '', d.landlordEmail ? `E-Mail des Vermieters: ${pad(d.landlordEmail)}` : '', d.landlordPhone ? `Telefon des Vermieters: ${pad(d.landlordPhone)}` : '', `Mieter: ${pad(d.tenantName)}, Geburtsdatum / IČO: ${pad(d.tenantId) || '—'}, Wohnsitz / Sitz: ${pad(d.tenantAddress)}`, d.tenantOP ? `Ausweisnummer des Mieters: ${pad(d.tenantOP)}` : '', d.tenantEmail ? `E-Mail des Mieters: ${pad(d.tenantEmail)}` : '', d.tenantPhone ? `Telefon des Mieters: ${pad(d.tenantPhone)}` : ''] },
    { title: 'II. MIETGEGENSTAND', body: [`Der Vermieter überlässt dem Mieter gegen Entgelt zur vorübergehenden Nutzung die Wohnung an der Adresse: ${s.propertyAddress}.`, `Aufteilung: ${s.propertyLayout || 'nicht angegeben'}.`, d.flatUnitNumber ? `Wohnungsnummer: ${pad(d.flatUnitNumber)}.` : '', d.cadastralArea ? `Katastergebiet: ${pad(d.cadastralArea)}, Parzellennummer: ${pad(d.parcelNumber) || 'nicht angegeben'}.` : '', d.ownershipSheet ? `Eigentumsblatt: ${pad(d.ownershipSheet)}.` : '', d.floor ? `Geschoss: ${pad(d.floor)}.` : '', (d.flatArea || d.approxArea) ? `Wohnfläche: ${pad(d.flatArea || d.approxArea)} m².` : '', 'Der Vermieter erklärt, zur Überlassung der Wohnung berechtigt zu sein, und es sind ihm keine rechtlichen oder tatsächlichen Hindernisse bekannt.', 'Der Mieter bestätigt, den Zustand des Mietgegenstands vor Unterzeichnung geprüft zu haben, und nimmt ihn in dem im Übergabeprotokoll beschriebenen Zustand an.'] },
    { title: 'III. MIETZEIT', body: [`Die Miete wird auf ${leaseDuration}e Zeit geschlossen.`, d.startDate ? `Beginn der Miete: ${fmtDate(d.startDate, 'de-DE')}.` : '', d.handoverDate ? `Datum der physischen Übergabe: ${fmtDate(d.handoverDate, 'de-DE')}.` : '', s.isFixedTerm ? 'Die Miete endet mit Ablauf der vereinbarten Zeit. Vorzeitige Beendigung nur aus gesetzlichen Gründen oder Gründen dieses Vertrags. Setzt der Mieter die Nutzung der Wohnung mehr als 3 Monate nach dem Ende ohne Widerspruch des Vermieters fort, gilt die Miete als erneuert (max. 2 Jahre, § 2230 BGB).' : 'Der Mieter kann mit einer Kündigungsfrist von 3 Monaten ohne Angabe von Gründen kündigen. Der Vermieter kann mit einer Kündigungsfrist von 3 Monaten nur aus gesetzlichen Gründen kündigen (§ 2288 BGB).'] },
    { title: 'IV. MIETE UND NEBENKOSTENZAHLUNGEN', body: [`Monatliche Miete: ${fmtAmount(d.rentAmount)} CZK.`, s.hasUtilities ? `Monatliche Nebenkostenvorauszahlung: ${fmtAmount(s.utilitiesAmount)} CZK.` : 'Gesonderte monatliche Nebenkostenvorauszahlungen wurden nicht vereinbart; der Mieter zahlt direkt an die Anbieter oder nach Abrechnung des Vermieters.', s.hasUtilities ? `Gesamte monatliche Zahlung: ${fmtAmount(s.monthlyTotal)} CZK.` : '', `Die Miete${s.hasUtilities ? ' und die Nebenkostenvorauszahlungen sind' : ' ist'} bis zum ${s.paymentDay}. Tag des betreffenden Monats im Voraus zu zahlen.`, d.bankAccount ? `Bankkonto des Vermieters: ${pad(d.bankAccount)}.` : '', d.variableSymbol ? `Variable symbol: ${pad(d.variableSymbol)}.` : '', d.utilitiesIncludedText ? `Erfasste Dienstleistungen: ${pad(d.utilitiesIncludedText)}.` : s.hasUtilities ? 'Nebenkostenvorauszahlungen umfassen üblicherweise: Wasser/Abwasser, Heizung/Warmwasser, Gemeinschaftsbereiche, Abfall — nach tatsächlichen Kosten.' : '', s.hasUtilities ? 'Der Vermieter rechnet die tatsächlichen Nebenkosten einmal jährlich ab und liefert die Abrechnung innerhalb von 4 Monaten nach Ende der Abrechnungsperiode (§ 7 Gesetz Nr. 67/2013 Slg.).' : '', useIndex ? 'Der Vermieter kann jeweils zum 1. April eines Jahres die Miete einseitig um die Inflation (jährliche Veränderung des VPI) erhöhen, wie vom Tschechischen Statistischen Amt veröffentlicht. Schriftliche Mitteilung mindestens 30 Tage vor der ersten Fälligkeit der erhöhten Miete.' : 'Der Vermieter kann eine Mieterhöhung schriftlich gemäß Gesetz vorschlagen, insbesondere unter Berücksichtigung der ortsüblichen Miete und der Grenzen nach § 2249 BGB.', 'Strom und Gas, die vom Mieter direkt bezogen werden, sind nicht Teil der Vorauszahlungen und werden separat gezahlt.', 'Bei Zahlungsverzug kann der Vermieter gesetzliche Verzugszinsen verlangen (Regierungsverordnung Nr. 351/2013 Slg.).'] },
    { title: 'V. KAUTION', body: s.hasDeposit ? [`Der Mieter zahlt eine Kaution in Höhe von ${fmtAmount(d.depositAmount)} CZK${d.rentAmount && Number(d.rentAmount) > 0 ? ` (≈ ${Math.round(Number(d.depositAmount) / Number(d.rentAmount))}× monatliche Miete)` : ''} vor Übernahme der Wohnung.`, 'Die Kaution sichert Forderungen des Vermieters (unbezahlte Miete, Vorauszahlungen, Schäden über gewöhnliche Abnutzung hinaus).', 'Der Vermieter erstattet die Kaution innerhalb von 1 Monat nach Beendigung der Miete und Räumung mit gesetzlichen Zinsen (§ 2254(2) BGB), abzüglich nachgewiesener Forderungen.', 'Der Vermieter kann ordnungsgemäß spezifizierte Forderungen aufrechnen; der Mieter ist schriftlich mit Aufstellung zu benachrichtigen.'] : ['Eine Barkaution wurde zwischen den Parteien nicht vereinbart.'] },
    { title: 'VI. NUTZUNGSREGELN', body: [d.maxOccupants ? `Höchstzahl der dauerhaft in der Wohnung lebenden Personen: ${pad(d.maxOccupants)} (einschließlich des Mieters).` : '', `Haustiere: ${d.allowPets ? 'anerkannt; der Mieter haftet für Schäden und erhöhte Kosten' : 'der Mieter kann ein Tier halten, wenn dies keine unangemessenen Belästigungen verursacht; der Vermieter ist vorab zu informieren'}.`, `Rauchen: ${d.allowSmoking ? 'gestattet' : 'verboten'}.`, `Kurzfristige entgeltliche Unterbringung über Airbnb/Booking ist Untervermietung und ist ${d.allowAirbnb ? 'gestattet; der Mieter haftet für alle Schäden und gesetzliche Pflichten als Beherbergungsanbieter' : 'ohne vorherige schriftliche Zustimmung des Vermieters verboten'}.`, `Gewerbliche Tätigkeit in der Wohnung: ${d.businessUseAllowed ? 'gestattet, sofern die Abnutzung nicht über das übliche Maß hinausgeht' : 'nur gestattet, wenn keine Mehrabnutzung oder Störung anderer erfolgt; andernfalls vorherige schriftliche Zustimmung des Vermieters erforderlich (§ 2255 BGB)'}.`, d.inspectionAllowed ? 'Der Vermieter kann nach schriftlicher (E-Mail) Mitteilung mit mindestens 24 Stunden Vorlauf die Wohnung besichtigen (§ 2219 BGB).' : 'Das Zutrittsrecht des Vermieters richtet sich nach dem Gesetz (§ 2219 BGB).', d.strictPenalties ? 'Bei schwerwiegendem oder wiederholtem Verstoß kann der Vermieter nach schriftlicher Mahnung wegen grober Pflichtverletzung kündigen (§ 2288(1)(a)) oder — bei besonders schweren Verstößen zum Schaden des Vermieters/anderer Bewohner — fristlos (§ 2291).' : '', 'Der Mieter hat die Wohnung in betriebsfähigem Zustand zu halten; Mängel unverzüglich zu melden; notwendige Reparaturen zu dulden; Kleinreparaturen zu zahlen (§ 2257); keine baulichen Veränderungen ohne Zustimmung vorzunehmen.', 'Der Mieter kann einen Teil der Wohnung untervermieten, wenn er in ihr wohnt; der Vermieter ist unverzüglich zu informieren. Die Untervermietung der gesamten Wohnung (oder wenn der Mieter dort nicht wohnt) bedarf der vorherigen schriftlichen Zustimmung.', 'Auf schriftliche Aufforderung legt der Mieter innerhalb von 7 Tagen einen Nachweis über eine gültige Hausratversicherung mit Haftpflichtdeckung vor (empfohlen mind. 500.000 CZK).'] },
    { title: 'VII. ÜBERGABE DER WOHNUNG', body: [d.keysCount ? `Der Vermieter übergibt ${pad(d.keysCount)} Schlüssel.` : '', 'Der Mieter darf ohne Zustimmung keine Schlüsselkopien anfertigen. Verlust ist schriftlich zu melden; der Mieter trägt die Kosten für Schloss-/Zylinderwechsel.', d.electricityMeter ? `Stromzählerstand bei Übergabe: ${pad(d.electricityMeter)} kWh.` : '', d.gasMeter ? `Gaszählerstand bei Übergabe: ${pad(d.gasMeter)} m³.` : '', d.waterMeter ? `Wasserzählerstand bei Übergabe: ${pad(d.waterMeter)} m³.` : '', d.equipmentList ? `Bestandsverzeichnis der Ausstattung: ${pad(d.equipmentList)}.` : '', d.knownDefects ? `Vom Vermieter erklärte Mängel: ${pad(d.knownDefects)}.` : 'Die Wohnung wird ohne ausdrücklich erklärte Mängel über die gewöhnliche Abnutzung hinaus übergeben.', 'Das detaillierte Übergabeprotokoll ist Anlage 1.'] },
    { title: 'VIII. BEENDIGUNG DER MIETE', body: [d.duration === 'indefinite' ? 'Eine Miete auf unbestimmte Zeit kann durch Kündigung (§ 2231, § 2286 ff.), durch Vereinbarung oder auf andere gesetzlich vorgesehene Weise beendet werden.' : 'Eine befristete Miete endet mit Ablauf der vereinbarten Zeit. Beide Parteien können aus gesetzlichen Gründen kündigen.', 'Bei Beendigung hat der Mieter (a) die Wohnung zu räumen, (b) die Wohnung in den ursprünglichen Zustand zu versetzen (unter Berücksichtigung gewöhnlicher Abnutzung), (c) alle Schlüssel zurückzugeben, (d) protokollarische Übergabe zu ermöglichen.', `Versäumt der Mieter eine ordnungsgemäße und rechtzeitige Übergabe der Wohnung: zahlt ${pad(d.lateVacatePenalty) || 'eine Tagesmiete'} pro Tag des Verzugs.`] },
    { title: 'IX. NOTFÄLLE UND REPARATUREN', body: ['Der Mieter hat jeden Notfall oder schadensverursachenden Mangel innerhalb von 24 Stunden zu melden.', 'Notwendige Schutzmaßnahmen können ohne vorherige Zustimmung getroffen werden; der Vermieter ist sofort zu informieren.', 'Der Mieter zahlt gewöhnliche Instandhaltung und Kleinreparaturen (§ 2257 BGB) im Rahmen der Regierungsverordnung Nr. 308/2015 Slg.', 'Größere Reparaturen trägt der Vermieter, sofern der Schaden nicht vom Mieter oder von ihm zugelassenen Personen verursacht wurde.'] },
    { title: 'X. ZUSTELLUNG VON SCHRIFTSTÜCKEN', body: [`Mitteilungen an den Vermieter: ${pad(d.landlordAddress)}${d.landlordEmail ? `, oder E-Mail: ${pad(d.landlordEmail)}` : ''}.`, `Mitteilungen an den Mieter: ${s.propertyAddress}${d.tenantEmail ? `, oder E-Mail: ${pad(d.tenantEmail)}` : ''}.`, 'Mitteilungen, die das Mietverhältnis betreffen, werden persönlich, per Einschreiben, über das Datenpostfach oder auf andere nachweisbare Weise zugestellt. E-Mail ist für die laufende Kommunikation akzeptabel.', 'Eine Verweigerung der Annahme gilt als am Tag der Verweigerung zugestellt; nicht abgeholte Sendungen gelten als am letzten Tag der Aufbewahrungsfrist zugestellt, soweit das Gesetz dies zulässt.'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'XI. OPERATIVE UND DOKUMENTATIONSBESTIMMUNGEN', body: ['Wesentliche Tatsachen (Mängel, Schlüsselübergaben, Haushaltsänderungen, Reparaturaufzeichnungen) sind nachweisbar zu bestätigen — vorzugsweise per E-Mail oder Einschreiben.', 'Bei Beendigung wird ein Übergabeprotokoll (Anlage 1) erstellt, das Zählerstände, Schlüsselverzeichnis, Bestandsverzeichnis und Raum-für-Raum-Bewertung umfasst. Fotodokumentation kann beigefügt werden.', 'Bei Streitigkeiten über den Schadensumfang versuchen die Parteien zunächst eine einvernehmliche Feststellung; bei Nichteinigung kann ein Sachverständiger hinzugezogen werden — Kosten trägt die Partei, deren Anspruch sich als unbegründet erweist.', 'Der Mieter haftet für Schäden, die von ihm zugelassenen Personen verursacht werden.'] });
    sections.push({ title: 'XII. BESONDERE BESTIMMUNGEN BEI BEENDIGUNG', body: ['Spätestens 5 Werktage vor der geplanten Beendigung bestätigen die Parteien schriftlich Datum und Uhrzeit der Übergabe. Bei Nichteinigung kann der Vermieter den Termin einseitig mit einer Vorlauffrist von mindestens 3 Werktagen festlegen.', 'Der Vermieter erstattet die Kaution gemäß Art. V(3), mit schriftlicher Abrechnung der geltend gemachten Forderungen (Grund, Umfang, Höhe). Ohne diese Abrechnung darf kein Teil der Kaution einseitig über den gesetzlichen Rahmen hinaus einbehalten werden.', 'Für erforderliche Reparaturen oder professionelle Reinigung auf Kosten des Mieters benachrichtigt der Vermieter den Mieter schriftlich vor Beginn der Arbeiten und gewährt eine angemessene Frist (mind. 5 Werktage) zur Stellungnahme.'] });
  }
  sections.push({ title: `${hasPremium ? 'XIII' : 'XI'}. SCHLUSSBESTIMMUNGEN`, body: ['Unterliegt tschechischem Recht, insbesondere Gesetz Nr. 89/2012 Slg., BGB, und Gesetz Nr. 67/2013 Slg. (Dienstleistungsabrechnung).', 'Streitigkeiten werden vorrangig einvernehmlich beigelegt; bei Nichteinigung durch das zuständige Gericht der Tschechischen Republik.', 'In zwei Ausfertigungen erstellt; jede Partei erhält eine.', 'Änderungen nur als schriftliche, nummerierte und unterzeichnete Nachträge.', 'Die Unwirksamkeit einer einzelnen Bestimmung berührt die übrigen nicht.', 'Anlage 1 (Übergabeprotokoll) ist integraler Bestandteil des Vertrags.', 'Eigentümerwechsel beendet die Miete nicht (§ 2221 BGB).', 'Verarbeitung personenbezogener Daten nach DSGVO und Gesetz Nr. 110/2019 Slg.', 'Force-majeure-Ausnahme (§ 2913(2) BGB).'] });
  sections.push({ title: `${hasPremium ? 'XIV' : 'XII'}. UNTERSCHRIFTEN`, body: [] });
  sections.push({ title: 'ANLAGE 1 – ÜBERGABEPROTOKOLL', body: [] });
  return sections;
}

export function buildLeaseTranslationsBySection(d: StoredContractData, hasPremium: boolean): Array<NonNullable<ContractSection['translations']>> {
  return buildBilingualTranslations({
    en: () => en(d, hasPremium),
    ua: () => uk(d, hasPremium),
  });
}
