/**
 * Power of attorney (plná moc) — translations for EN/UK/RU/VN/DE.
 * Mirrors buildPowerOfAttorneyContractSections paragraph-by-paragraph.
 */
import type { ContractSection, StoredContractData } from '../contracts';
import { buildBilingualTranslations, fmtAmount, fmtDate, pad, type ParaPair } from './helpers';

// ── EN ─────────────────────────────────────────────────────────────────────
function en(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const scopeDesc = (() => {
    switch (d.poaType) {
      case 'property':
        return `any legal act relating to the transfer, purchase, sale, lease or other disposal of the real property at / in the cadastral area: ${pad(d.propertyAddress) || 'unspecified'}, in particular: signing the purchase agreement, future-purchase agreement, lease, and gift; representation before the Land Registry, financial institutions and public authorities. WARNING: This power of attorney requires officially certified signature of the principal (notary or Czech POINT). Without certification it will not be accepted by the Land Registry or financial institutions.`;
      case 'court':
        return `representation of the principal in proceedings at ${pad(d.courtName) || 'unspecified'}, file no. ${pad(d.caseNumber) || 'unspecified'}, including receipt of mail, lodging of appeals and conclusion of settlements. WARNING: A court power of attorney should bear an officially certified signature. In proceedings where representation by counsel is mandatory (§ 27 CCP), the agent must be an attorney.`;
      case 'company':
        return `representation of the principal as partner / director / shareholder of ${pad(d.companyName) || 'unspecified'}, Company ID ${pad(d.companyIco) || 'unspecified'}, for the following acts: ${pad(d.companyScope) || 'general meeting, dealings with public authorities, business negotiations'}`;
      case 'bank':
        return `representation at banks and financial institutions, in particular handling account no. ${pad(d.bankAccount) || 'unspecified'} held at ${pad(d.bankName) || 'unspecified'}, including withdrawals, deposits and administration. WARNING: Banks usually require their own power-of-attorney form or an officially certified signature. Verify with your bank that this document is accepted.`;
      default:
        return `${pad(d.customScope) || 'unspecified'}`;
    }
  })();
  const validity = d.validUntil
    ? `This power of attorney is valid until ${pad(d.validUntil)}.`
    : d.singleUse
    ? 'This power of attorney is one-off and expires upon completion of the act for which it was granted.'
    : 'This power of attorney is valid until expressly revoked by the principal.';
  const substitution = d.allowSubstitution
    ? 'The agent is entitled to grant a sub-power of attorney to a third party (substitution).'
    : 'The agent is not entitled to grant a power of attorney in his / her place to a third party (substitution prohibited).';

  const sections: ParaPair[] = [
    { title: 'POWER OF ATTORNEY', body: ['This power of attorney is granted under § 441 et seq. of Act No. 89/2012 Coll., the Czech Civil Code, as amended.', `Date granted: ${d.contractDate ? fmtDate(d.contractDate) : new Date().toLocaleDateString('en-GB')}`] },
    { title: 'I. PRINCIPAL', body: [`Name / company name: ${pad(d.principalName)}`, `Date of birth / Company ID: ${pad(d.principalId) || '—'}`, `Permanent residence / registered office: ${pad(d.principalAddress)}`, d.principalEmail ? `E-mail: ${pad(d.principalEmail)}` : ''] },
    { title: 'II. AGENT', body: [`Name / company name: ${pad(d.agentName)}`, `Date of birth / Company ID: ${pad(d.agentId) || '—'}`, `Permanent residence / registered office: ${pad(d.agentAddress)}`, d.agentEmail ? `E-mail: ${pad(d.agentEmail)}` : ''] },
    { title: 'III. SCOPE AND SUBJECT OF AUTHORISATION', body: ["The principal hereby authorises the agent to represent the principal and act in the principal's name and on the principal's account in the matter of:", scopeDesc, substitution] },
    { title: 'IV. VALIDITY', body: [validity, 'The power of attorney also expires upon the death of the principal or the agent, unless the nature of the matter implies otherwise.', 'The principal may revoke the power of attorney at any time; revocation takes effect upon delivery to the agent.'] },
    { title: "V. PRINCIPAL'S DECLARATIONS", body: ['The principal declares that:', '(a) this power of attorney is granted freely, seriously and without coercion,', '(b) the principal has full legal capacity,', '(c) the principal is aware of the scope of authority granted and its legal consequences.', hasPremium ? "The authenticity of the principal's signature is verified by a notary or at a Czech POINT. Official certification significantly increases the usability of the power of attorney towards third parties; some institutions may still require their own form or additional conditions under special rules or internal policies." : '', "(d) the agent shall act with due care and in the principal's best interest; the agent shall inform the principal of any legal act taken under this authorisation without undue delay.", '(e) the principal may revoke this power of attorney at any time in writing; revocation takes effect at the moment the agent learns of it (§ 448(1) Civil Code). The agent shall promptly return the original of the power of attorney to the principal upon revocation.'] },
  ];

  if (hasPremium) {
    sections.push({ title: 'VI. OFFICIAL SIGNATURE CERTIFICATION AND LEGAL EFFECTS TOWARDS THIRD PARTIES', body: ["Official certification of the principal's signature is performed by a notary, a Czech POINT, or the registry office of the municipal authority authorised to keep the registry. Certification is required in particular for legal acts concerning real estate to be recorded in the Land Registry (§ 6 Act No. 256/2013 Coll.), representation in proceedings before courts and public authorities, and handling bank accounts and funds.", "The original of the power of attorney is kept by the principal. The agent may present the original or an officially certified copy to third parties; upon termination of the authorisation or at the principal's request, the agent shall return the original without undue delay and destroy any copies.", 'The principal may revoke the power of attorney at any time; revocation takes effect against the agent upon delivery and against third parties at the moment they learn of it. For the avoidance of doubt, we recommend notifying third parties of the revocation in writing where the power was previously used.', 'This power of attorney is executed in two counterparts; one is kept by the principal, the other received by the agent as evidence. The principal may obtain further officially certified counterparts as needed.'] });
    sections.push({ title: 'VII. SANCTIONS FOR EXCEEDING AUTHORITY AND CONFLICT-OF-INTEREST PROHIBITION', body: ['The agent must not act in a matter in which the agent is a party or has a direct or indirect interest in the outcome (self-dealing prohibition). This restriction does not apply where the principal has granted prior express written consent, fully informed.', "The agent must not grant a sub-power of attorney without the principal's prior written consent. If a substitution is granted in breach, the agent is liable for the substitute's acts as for the agent's own.", d.agentPenalty && Number(d.agentPenalty) > 0 ? `Liability for damage caused by exceeding the scope of authority or negligent exercise of the power of attorney is governed by § 2913 Civil Code. For deliberate excess, the agent shall pay the principal a contractual penalty of CZK ${fmtAmount(d.agentPenalty)}; payment of the penalty is without prejudice to claims for damages.` : 'Liability for damage caused by exceeding the scope of authority or negligent exercise of the power of attorney is governed by § 2913 Civil Code. For deliberate excess the agent shall return any benefits received and compensate the principal for damage incurred, including reasonable costs of enforcing rights.', "If the agent exceeds the scope of authority, the excess does not bind the principal unless subsequently approved (§ 440 Civil Code). A third party acting in good faith may claim demonstrable damages against the agent."] });
  }

  sections.push({ title: `${hasPremium ? 'VIII' : 'VI'}. FINAL PROVISIONS`, body: ['This instrument is governed by the laws of the Czech Republic, in particular Act No. 89/2012 Coll., the Civil Code, as amended.', "The power of attorney takes effect upon signature of the principal and expires upon completion of the authorised act, expiry of the term, revocation by the principal, or death of a party (§ 448 Civil Code).", 'The principal may revoke this power of attorney in writing at any time, by delivering the revocation to the agent. Revocation takes effect at the moment the agent learns of it.', 'Limitation or extension of the scope of authority is valid only in writing.', 'The invalidity of any individual provision does not affect the validity of the remaining provisions.', 'Personal data are processed under EU Regulation 2016/679 (GDPR) and Act No. 110/2019 Coll., exclusively for the purpose of granting and performing this authorisation.'] });
  sections.push({ title: `${hasPremium ? 'IX' : 'VII'}. SIGNATURES`, body: [] });
  return sections;
}

// ── UK (Українська) ────────────────────────────────────────────────────────
function uk(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const scopeDesc = (() => {
    switch (d.poaType) {
      case 'property': return `будь-які правочини щодо передачі, купівлі, продажу, оренди або іншого розпорядження нерухомістю за адресою / у кадастровому окрузі: ${pad(d.propertyAddress) || 'не вказано'}, зокрема: підписання договору купівлі-продажу, договору про намір, договору оренди та дарування; представництво перед Кадастром нерухомості, фінансовими установами та органами державної влади. УВАГА: ця довіреність потребує офіційно засвідченого підпису довірителя (нотаріус або Czech POINT). Без засвідчення її не прийме Кадастр нерухомості та фінансові установи.`;
      case 'court': return `представництво довірителя у провадженні в ${pad(d.courtName) || 'не вказано'}, справа № ${pad(d.caseNumber) || 'не вказано'}, у тому числі отримання кореспонденції, подання скарг та укладення мирових угод. УВАГА: судова довіреність повинна мати офіційно засвідчений підпис. У провадженнях з обов'язковим адвокатським представництвом (§ 27 ЦПК) представником має бути адвокат.`;
      case 'company': return `представництво довірителя як учасника / директора / акціонера ${pad(d.companyName) || 'не вказано'}, IČO ${pad(d.companyIco) || 'не вказано'}, для таких дій: ${pad(d.companyScope) || 'загальні збори, спілкування з органами державної влади, ділові переговори'}`;
      case 'bank': return `представництво в банках і фінансових установах, зокрема розпорядження рахунком № ${pad(d.bankAccount) || 'не вказано'} у ${pad(d.bankName) || 'не вказано'}, включно зі зняттями, внесками та адмініструванням. УВАГА: банки зазвичай вимагають власну форму довіреності або офіційно засвідчений підпис. Перевірте у вашому банку, чи приймається цей документ.`;
      default: return `${pad(d.customScope) || 'не вказано'}`;
    }
  })();
  const validity = d.validUntil ? `Ця довіреність діє до ${pad(d.validUntil)}.` : d.singleUse ? 'Ця довіреність є одноразовою і припиняється виконанням дії, для якої вона була надана.' : 'Ця довіреність діє до її прямого скасування довірителем.';
  const substitution = d.allowSubstitution ? 'Повірений має право видати субдовіреність третій особі (передоручення).' : 'Повірений не має права передоручити повноваження третій особі (передоручення заборонено).';

  const sections: ParaPair[] = [
    { title: 'ДОВІРЕНІСТЬ', body: ['Ця довіреність надається відповідно до § 441 та наступних Закону № 89/2012 Sb., Цивільний кодекс Чехії, з наступними змінами.', `Дата надання: ${d.contractDate ? fmtDate(d.contractDate, 'uk-UA') : new Date().toLocaleDateString('uk-UA')}`] },
    { title: 'I. ДОВІРИТЕЛЬ', body: [`Ім'я / назва: ${pad(d.principalName)}`, `Дата народження / IČO: ${pad(d.principalId) || '—'}`, `Місце постійного проживання / місцезнаходження: ${pad(d.principalAddress)}`, d.principalEmail ? `E-mail: ${pad(d.principalEmail)}` : ''] },
    { title: 'II. ПОВІРЕНИЙ', body: [`Ім'я / назва: ${pad(d.agentName)}`, `Дата народження / IČO: ${pad(d.agentId) || '—'}`, `Місце постійного проживання / місцезнаходження: ${pad(d.agentAddress)}`, d.agentEmail ? `E-mail: ${pad(d.agentEmail)}` : ''] },
    { title: 'III. ОБСЯГ І ПРЕДМЕТ ПОВНОВАЖЕНЬ', body: ['Довіритель цим уповноважує повіреного представляти довірителя та діяти від його імені та на його рахунок у справі:', scopeDesc, substitution] },
    { title: 'IV. СТРОК ДІЇ', body: [validity, 'Довіреність також припиняється смертю довірителя або повіреного, якщо інше не випливає з характеру справи.', 'Довіритель може будь-коли скасувати довіреність; скасування набуває чинності з моменту вручення повіреному.'] },
    { title: 'V. ЗАЯВИ ДОВІРИТЕЛЯ', body: ['Довіритель заявляє, що:', '(a) ця довіреність надана вільно, серйозно та без примусу,', '(b) має повну дієздатність,', '(c) усвідомлює обсяг наданих повноважень та їхні правові наслідки.', hasPremium ? 'Справжність підпису довірителя засвідчується нотаріусом або в системі Czech POINT. Офіційне засвідчення значно підвищує застосовність довіреності щодо третіх осіб; деякі установи, однак, можуть і надалі вимагати власну форму або додаткові умови.' : '', "(d) повірений зобов'язаний діяти добросовісно та в найкращих інтересах довірителя; про кожен правочин повірений негайно інформує довірителя.", '(e) довіритель може у будь-який момент письмово скасувати цю довіреність; скасування набуває чинності в момент, коли про нього дізнається повірений (§ 448(1) ЦК). Повірений після скасування зобов\'язаний негайно повернути оригінал довіреності довірителю.'] },
  ];

  if (hasPremium) {
    sections.push({ title: 'VI. ОФІЦІЙНЕ ЗАСВІДЧЕННЯ ПІДПИСУ ТА ПРАВОВІ НАСЛІДКИ ЩОДО ТРЕТІХ ОСІБ', body: ['Офіційне засвідчення підпису довірителя здійснює нотаріус, контактна точка Czech POINT або реєстраційний відділ муніципального органу, уповноваженого вести реєстри. Засвідчення є обов\'язковим зокрема для: правочинів щодо нерухомості, що підлягає внесенню до Кадастру нерухомості (§ 6 Закону № 256/2013 Sb.), представництва у провадженнях перед судами та органами державної влади, розпорядження банківськими рахунками та коштами.', 'Оригінал довіреності зберігає довіритель. Повірений має право подавати третім особам оригінал або офіційно засвідчену копію; після припинення повноважень або на вимогу довірителя зобов\'язаний негайно повернути оригінал і знищити всі свої копії.', 'Довіритель має право у будь-який час скасувати довіреність; скасування набуває чинності щодо повіреного з моменту вручення та щодо третіх осіб з моменту, коли вони про нього дізналися. Для уникнення сумнівів рекомендуємо письмово повідомити про скасування третім особам, перед якими довіреність раніше застосовувалась.', 'Ця довіреність складена у двох примірниках; один залишається у довірителя, другий отримує повірений як підтверджуючий документ. Довіритель має право виготовити подальші офіційно засвідчені примірники за потребою.'] });
    sections.push({ title: 'VII. САНКЦІЇ ЗА ПЕРЕВИЩЕННЯ ПОВНОВАЖЕНЬ ТА ЗАБОРОНА КОНФЛІКТУ ІНТЕРЕСІВ', body: ['Повірений не може діяти у справі, в якій сам є стороною або має прямий чи непрямий інтерес у результаті (заборона "self-dealing"). Це обмеження не застосовується, якщо довіритель надав попередню виразну письмову згоду з повним обізнанням про всі обставини.', "Повірений не може видати субдовіреність без попередньої письмової згоди довірителя. Якщо передоручення здійснено всупереч цьому, повірений відповідає за дії субпредставника як за свої власні.", d.agentPenalty && Number(d.agentPenalty) > 0 ? `За шкоду, заподіяну перевищенням обсягу повноважень або недбалим виконанням довіреності, повірений відповідає за § 2913 ЦК. У разі свідомого перевищення повноважень повірений зобов'язаний сплатити довірителю штраф у розмірі ${fmtAmount(d.agentPenalty)} крон; сплата штрафу не виключає права на відшкодування шкоди.` : "За шкоду, заподіяну перевищенням обсягу повноважень або недбалим виконанням довіреності, повірений відповідає за § 2913 ЦК. У разі свідомого перевищення повноважень повірений зобов'язаний повернути отримане та відшкодувати довірителю заподіяну шкоду, включно з доцільно понесеними витратами на захист прав.", 'Якщо повірений перевищив обсяг повноважень, перевищення не є обов\'язковим для довірителя, якщо тільки довіритель додатково не схвалить (§ 440 ЦК). Третя особа, яка діяла з повіреним добросовісно, має право на відшкодування доведеної шкоди від повіреного.'] });
  }

  sections.push({ title: `${hasPremium ? 'VIII' : 'VI'}. ЗАКЛЮЧНІ ПОЛОЖЕННЯ`, body: ['Цей акт регулюється правом Чеської Республіки, зокрема Законом № 89/2012 Sb., Цивільним кодексом, з наступними змінами.', 'Довіреність набуває чинності з моменту підпису довірителя і припиняється виконанням повноважень, спливом строку, скасуванням довірителем або смертю однієї зі сторін (§ 448 ЦК).', 'Довіритель може у будь-який час письмово скасувати цю довіреність шляхом вручення скасування повіреному. Скасування набуває чинності в момент, коли про нього дізнається повірений.', 'Обмеження або розширення обсягу повноважень дійсне лише у письмовій формі.', 'Недійсність окремого положення не впливає на дійсність інших положень.', 'Обробка персональних даних здійснюється відповідно до Регламенту ЄС 2016/679 (GDPR) та Закону № 110/2019 Sb., виключно з метою надання та виконання повноважень.'] });
  sections.push({ title: `${hasPremium ? 'IX' : 'VII'}. ПІДПИСИ`, body: [] });
  return sections;
}

// ── RU (Русский) ───────────────────────────────────────────────────────────
function ru(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const scopeDesc = (() => {
    switch (d.poaType) {
      case 'property': return `любые юридические действия, касающиеся передачи, покупки, продажи, аренды или иного распоряжения недвижимостью по адресу / в кадастровом округе: ${pad(d.propertyAddress) || 'не указано'}, в частности: подписание договора купли-продажи, предварительного договора, договора аренды и дарения; представительство перед Кадастром недвижимости, финансовыми учреждениями и органами государственной власти. ВНИМАНИЕ: данная доверенность требует официально заверенной подписи доверителя (нотариус или Czech POINT). Без заверения её не примут Кадастр недвижимости и финансовые учреждения.`;
      case 'court': return `представительство доверителя в производстве в ${pad(d.courtName) || 'не указано'}, дело № ${pad(d.caseNumber) || 'не указано'}, включая получение почты, подачу обжалований и заключение мировых соглашений. ВНИМАНИЕ: судебная доверенность должна иметь официально заверенную подпись. В производствах с обязательным адвокатским представительством (§ 27 ГПК) представителем должен быть адвокат.`;
      case 'company': return `представительство доверителя как участника / директора / акционера ${pad(d.companyName) || 'не указано'}, IČO ${pad(d.companyIco) || 'не указано'}, для следующих действий: ${pad(d.companyScope) || 'общее собрание, общение с органами государственной власти, деловые переговоры'}`;
      case 'bank': return `представительство в банках и финансовых учреждениях, в частности распоряжение счётом № ${pad(d.bankAccount) || 'не указано'} в ${pad(d.bankName) || 'не указано'}, включая снятие, внесение и администрирование. ВНИМАНИЕ: банки обычно требуют собственную форму доверенности или официально заверенную подпись. Проверьте у своего банка, принимается ли данный документ.`;
      default: return `${pad(d.customScope) || 'не указано'}`;
    }
  })();
  const validity = d.validUntil ? `Настоящая доверенность действует до ${pad(d.validUntil)}.` : d.singleUse ? 'Настоящая доверенность является разовой и прекращается выполнением действия, для которого она была выдана.' : 'Настоящая доверенность действует до её прямой отмены доверителем.';
  const substitution = d.allowSubstitution ? 'Поверенный вправе выдать передоверие третьему лицу.' : 'Поверенный не вправе передоверять полномочия третьему лицу (передоверие запрещено).';

  const sections: ParaPair[] = [
    { title: 'ДОВЕРЕННОСТЬ', body: ['Настоящая доверенность выдаётся согласно § 441 и далее Закона № 89/2012 Sb., Гражданский кодекс Чехии, с последующими изменениями.', `Дата выдачи: ${d.contractDate ? fmtDate(d.contractDate, 'ru-RU') : new Date().toLocaleDateString('ru-RU')}`] },
    { title: 'I. ДОВЕРИТЕЛЬ', body: [`Имя / наименование: ${pad(d.principalName)}`, `Дата рождения / IČO: ${pad(d.principalId) || '—'}`, `Постоянное место жительства / юридический адрес: ${pad(d.principalAddress)}`, d.principalEmail ? `E-mail: ${pad(d.principalEmail)}` : ''] },
    { title: 'II. ПОВЕРЕННЫЙ', body: [`Имя / наименование: ${pad(d.agentName)}`, `Дата рождения / IČO: ${pad(d.agentId) || '—'}`, `Постоянное место жительства / юридический адрес: ${pad(d.agentAddress)}`, d.agentEmail ? `E-mail: ${pad(d.agentEmail)}` : ''] },
    { title: 'III. ОБЪЁМ И ПРЕДМЕТ ПОЛНОМОЧИЙ', body: ['Доверитель настоящим уполномочивает поверенного представлять доверителя и действовать от его имени и за его счёт в деле:', scopeDesc, substitution] },
    { title: 'IV. СРОК ДЕЙСТВИЯ', body: [validity, 'Доверенность также прекращается смертью доверителя или поверенного, если иное не вытекает из существа дела.', 'Доверитель может в любое время отменить доверенность; отмена вступает в силу с момента вручения поверенному.'] },
    { title: 'V. ЗАЯВЛЕНИЯ ДОВЕРИТЕЛЯ', body: ['Доверитель заявляет, что:', '(a) данная доверенность выдана свободно, серьёзно и без принуждения,', '(b) обладает полной дееспособностью,', '(c) осознаёт объём предоставленных полномочий и их правовые последствия.', hasPremium ? 'Подлинность подписи доверителя удостоверена нотариусом или в системе Czech POINT. Официальное удостоверение значительно повышает применимость доверенности в отношении третьих лиц; некоторые учреждения, однако, могут по-прежнему требовать собственную форму или дополнительные условия.' : '', '(d) поверенный обязан действовать с должной заботливостью и в наилучших интересах доверителя; о каждом юридическом действии поверенный безотлагательно информирует доверителя.', '(e) доверитель может в любое время отменить настоящую доверенность письменно; отмена вступает в силу в момент, когда о ней узнает поверенный (§ 448(1) ГК). После отмены поверенный обязан безотлагательно вернуть оригинал доверенности доверителю.'] },
  ];

  if (hasPremium) {
    sections.push({ title: 'VI. ОФИЦИАЛЬНОЕ ЗАВЕРЕНИЕ ПОДПИСИ И ПРАВОВЫЕ ПОСЛЕДСТВИЯ В ОТНОШЕНИИ ТРЕТЬИХ ЛИЦ', body: ['Официальное заверение подписи доверителя осуществляется нотариусом, контактным пунктом Czech POINT или регистрационным отделом муниципального органа, уполномоченного вести регистры. Заверение обязательно, в частности, для: юридических действий с недвижимостью, подлежащей внесению в Кадастр недвижимости (§ 6 Закона № 256/2013 Sb.), представительства в производствах перед судами и органами государственной власти, распоряжения банковскими счетами и средствами.', 'Оригинал доверенности хранится у доверителя. Поверенный вправе предъявлять третьим лицам оригинал или официально заверенную копию; после прекращения полномочий или по требованию доверителя обязан безотлагательно вернуть оригинал и уничтожить все свои копии.', 'Доверитель вправе в любое время отменить доверенность; отмена вступает в силу в отношении поверенного с момента вручения и в отношении третьих лиц с момента, когда они о ней узнали. Во избежание сомнений рекомендуем письменно уведомить об отмене третьих лиц, перед которыми доверенность ранее применялась.', 'Настоящая доверенность составлена в двух экземплярах; один остаётся у доверителя, другой получает поверенный как подтверждающий документ. Доверитель вправе изготовить дополнительные официально заверенные экземпляры по необходимости.'] });
    sections.push({ title: 'VII. САНКЦИИ ЗА ПРЕВЫШЕНИЕ ПОЛНОМОЧИЙ И ЗАПРЕТ КОНФЛИКТА ИНТЕРЕСОВ', body: ['Поверенный не вправе действовать в деле, в котором сам является стороной или имеет прямой или косвенный интерес в результате (запрет "self-dealing"). Это ограничение не применяется, если доверитель предоставил предварительное явное письменное согласие, будучи полностью осведомлённым обо всех обстоятельствах.', 'Поверенный не вправе выдавать передоверие без предварительного письменного согласия доверителя. Если передоверие предоставлено в нарушение, поверенный отвечает за действия передоверенного как за свои собственные.', d.agentPenalty && Number(d.agentPenalty) > 0 ? `За ущерб, причинённый превышением объёма полномочий или небрежным осуществлением доверенности, поверенный отвечает по § 2913 ГК. В случае сознательного превышения поверенный обязан уплатить доверителю штраф в размере ${fmtAmount(d.agentPenalty)} крон; уплата штрафа не исключает права на возмещение убытков.` : 'За ущерб, причинённый превышением объёма полномочий или небрежным осуществлением доверенности, поверенный отвечает по § 2913 ГК. В случае сознательного превышения поверенный обязан вернуть полученное и возместить доверителю причинённый ущерб, включая разумные расходы на защиту прав.', 'Если поверенный превысил объём полномочий, превышение не является обязательным для доверителя, если только доверитель не одобрит его впоследствии (§ 440 ГК). Третье лицо, действовавшее с поверенным добросовестно, вправе требовать возмещения доказанного ущерба от поверенного.'] });
  }

  sections.push({ title: `${hasPremium ? 'VIII' : 'VI'}. ЗАКЛЮЧИТЕЛЬНЫЕ ПОЛОЖЕНИЯ`, body: ['Настоящий акт регулируется правом Чешской Республики, в частности Законом № 89/2012 Sb., Гражданским кодексом, с последующими изменениями.', 'Доверенность вступает в силу с момента подписи доверителя и прекращается выполнением полномочий, истечением срока, отменой доверителем или смертью одной из сторон (§ 448 ГК).', 'Доверитель может в любое время отменить настоящую доверенность письменно путём вручения отмены поверенному. Отмена вступает в силу в момент, когда о ней узнает поверенный.', 'Ограничение или расширение объёма полномочий действительно только в письменной форме.', 'Недействительность отдельного положения не влияет на действительность остальных положений.', 'Обработка персональных данных осуществляется в соответствии с Регламентом ЕС 2016/679 (GDPR) и Законом № 110/2019 Sb., исключительно с целью предоставления и осуществления полномочий.'] });
  sections.push({ title: `${hasPremium ? 'IX' : 'VII'}. ПОДПИСИ`, body: [] });
  return sections;
}

// ── VN (Tiếng Việt) ────────────────────────────────────────────────────────
function vn(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const scopeDesc = (() => {
    switch (d.poaType) {
      case 'property': return `mọi hành vi pháp lý liên quan đến chuyển nhượng, mua, bán, cho thuê hoặc xử lý khác đối với bất động sản tại địa chỉ / trong khu vực địa chính: ${pad(d.propertyAddress) || 'chưa nêu rõ'}, đặc biệt: ký hợp đồng mua bán, hợp đồng hứa mua bán, hợp đồng thuê và hợp đồng tặng cho; đại diện trước Cơ quan Đăng ký Bất động sản, các tổ chức tài chính và cơ quan nhà nước. LƯU Ý: giấy ủy quyền này yêu cầu chữ ký được xác thực chính thức của bên ủy quyền (công chứng viên hoặc Czech POINT). Không có xác thực, văn bản sẽ không được Cơ quan Đăng ký Bất động sản và các tổ chức tài chính chấp nhận.`;
      case 'court': return `đại diện cho bên ủy quyền trong vụ việc tại ${pad(d.courtName) || 'chưa nêu rõ'}, số hồ sơ ${pad(d.caseNumber) || 'chưa nêu rõ'}, bao gồm nhận thư tín, nộp kháng cáo và ký kết thỏa thuận hòa giải. LƯU Ý: giấy ủy quyền tư pháp nên có chữ ký được xác thực chính thức. Trong các vụ việc bắt buộc phải có đại diện là luật sư (§ 27 BLTTDS), người được ủy quyền phải là luật sư.`;
      case 'company': return `đại diện cho bên ủy quyền với tư cách thành viên / giám đốc / cổ đông của ${pad(d.companyName) || 'chưa nêu rõ'}, IČO ${pad(d.companyIco) || 'chưa nêu rõ'}, cho các hành vi sau: ${pad(d.companyScope) || 'đại hội đồng, làm việc với cơ quan nhà nước, đàm phán kinh doanh'}`;
      case 'bank': return `đại diện tại các ngân hàng và tổ chức tài chính, đặc biệt là xử lý tài khoản số ${pad(d.bankAccount) || 'chưa nêu rõ'} mở tại ${pad(d.bankName) || 'chưa nêu rõ'}, bao gồm rút tiền, gửi tiền và quản lý. LƯU Ý: ngân hàng thường yêu cầu mẫu giấy ủy quyền riêng hoặc chữ ký được xác thực chính thức. Vui lòng kiểm tra với ngân hàng của bạn rằng văn bản này được chấp nhận.`;
      default: return `${pad(d.customScope) || 'chưa nêu rõ'}`;
    }
  })();
  const validity = d.validUntil ? `Giấy ủy quyền này có hiệu lực đến ${pad(d.validUntil)}.` : d.singleUse ? 'Giấy ủy quyền này là một lần và hết hiệu lực khi hoàn thành hành vi đã được ủy quyền.' : 'Giấy ủy quyền này có hiệu lực cho đến khi bên ủy quyền hủy bỏ một cách rõ ràng.';
  const substitution = d.allowSubstitution ? 'Người được ủy quyền có quyền ủy quyền lại cho bên thứ ba.' : 'Người được ủy quyền không có quyền ủy quyền lại cho bên thứ ba (cấm ủy quyền lại).';

  const sections: ParaPair[] = [
    { title: 'GIẤY ỦY QUYỀN', body: ['Giấy ủy quyền này được cấp theo § 441 trở đi của Luật số 89/2012 Sb., Bộ luật Dân sự Séc, có sửa đổi.', `Ngày cấp: ${d.contractDate ? fmtDate(d.contractDate, 'vi-VN') : new Date().toLocaleDateString('vi-VN')}`] },
    { title: 'I. BÊN ỦY QUYỀN', body: [`Họ tên / tên đầy đủ: ${pad(d.principalName)}`, `Ngày sinh / IČO: ${pad(d.principalId) || '—'}`, `Nơi cư trú thường xuyên / trụ sở: ${pad(d.principalAddress)}`, d.principalEmail ? `E-mail: ${pad(d.principalEmail)}` : ''] },
    { title: 'II. NGƯỜI ĐƯỢC ỦY QUYỀN', body: [`Họ tên / tên đầy đủ: ${pad(d.agentName)}`, `Ngày sinh / IČO: ${pad(d.agentId) || '—'}`, `Nơi cư trú thường xuyên / trụ sở: ${pad(d.agentAddress)}`, d.agentEmail ? `E-mail: ${pad(d.agentEmail)}` : ''] },
    { title: 'III. PHẠM VI VÀ ĐỐI TƯỢNG ỦY QUYỀN', body: ['Bên ủy quyền theo đây ủy quyền cho người được ủy quyền đại diện bên ủy quyền và hành động nhân danh và vì lợi ích của bên ủy quyền trong vụ việc:', scopeDesc, substitution] },
    { title: 'IV. THỜI HẠN HIỆU LỰC', body: [validity, 'Giấy ủy quyền cũng chấm dứt khi bên ủy quyền hoặc người được ủy quyền qua đời, trừ khi bản chất sự việc quy định khác.', 'Bên ủy quyền có thể hủy bỏ giấy ủy quyền bất kỳ lúc nào; việc hủy bỏ có hiệu lực kể từ thời điểm giao cho người được ủy quyền.'] },
    { title: 'V. TUYÊN BỐ CỦA BÊN ỦY QUYỀN', body: ['Bên ủy quyền tuyên bố rằng:', '(a) giấy ủy quyền này được cấp một cách tự nguyện, nghiêm túc và không bị cưỡng ép,', '(b) có đầy đủ năng lực hành vi pháp lý,', '(c) nhận thức được phạm vi quyền hạn được cấp và hậu quả pháp lý của chúng.', hasPremium ? 'Tính xác thực của chữ ký bên ủy quyền được công chứng viên hoặc Czech POINT xác thực. Việc xác thực chính thức làm tăng đáng kể khả năng sử dụng giấy ủy quyền đối với bên thứ ba; tuy nhiên, một số tổ chức có thể vẫn yêu cầu mẫu riêng hoặc các điều kiện bổ sung.' : '', '(d) người được ủy quyền có nghĩa vụ hành động cẩn trọng và vì lợi ích tốt nhất của bên ủy quyền; phải thông báo cho bên ủy quyền không chậm trễ về mọi hành vi pháp lý đã thực hiện trong khuôn khổ ủy quyền.', '(e) bên ủy quyền có thể hủy bỏ giấy ủy quyền này bất kỳ lúc nào bằng văn bản; việc hủy bỏ có hiệu lực vào thời điểm người được ủy quyền biết về nó (§ 448(1) BLDS). Sau khi hủy bỏ, người được ủy quyền phải lập tức trả lại bản gốc giấy ủy quyền cho bên ủy quyền.'] },
  ];

  if (hasPremium) {
    sections.push({ title: 'VI. XÁC THỰC CHỮ KÝ CHÍNH THỨC VÀ HIỆU LỰC PHÁP LÝ ĐỐI VỚI BÊN THỨ BA', body: ['Việc xác thực chính thức chữ ký của bên ủy quyền được thực hiện bởi công chứng viên, điểm Czech POINT hoặc văn phòng đăng ký của cơ quan thành phố được ủy quyền. Việc xác thực bắt buộc đặc biệt đối với: các hành vi pháp lý liên quan đến bất động sản được ghi vào Sổ đăng ký bất động sản (§ 6 Luật số 256/2013 Sb.), đại diện trong vụ việc trước tòa án và cơ quan nhà nước, và xử lý tài khoản ngân hàng và tiền.', 'Bản gốc giấy ủy quyền được bên ủy quyền giữ. Người được ủy quyền có quyền xuất trình cho bên thứ ba bản gốc hoặc bản sao có xác thực chính thức; sau khi chấm dứt ủy quyền hoặc theo yêu cầu của bên ủy quyền, phải lập tức trả lại bản gốc và tiêu hủy mọi bản sao.', 'Bên ủy quyền có quyền hủy bỏ giấy ủy quyền bất kỳ lúc nào; việc hủy bỏ có hiệu lực đối với người được ủy quyền vào thời điểm giao và đối với bên thứ ba vào thời điểm họ biết về nó. Để tránh nghi ngờ, chúng tôi khuyến nghị thông báo bằng văn bản cho bên thứ ba mà giấy ủy quyền đã được áp dụng trước đó.', 'Giấy ủy quyền này được lập thành hai bản; một bản do bên ủy quyền giữ, một bản do người được ủy quyền nhận làm bằng chứng. Bên ủy quyền có quyền lập thêm các bản có xác thực chính thức khi cần.'] });
    sections.push({ title: 'VII. CHẾ TÀI KHI VƯỢT QUÁ PHẠM VI ỦY QUYỀN VÀ CẤM XUNG ĐỘT LỢI ÍCH', body: ['Người được ủy quyền không được hành động trong vụ việc mà chính họ là một bên hoặc có lợi ích trực tiếp hoặc gián tiếp trong kết quả (cấm "self-dealing"). Hạn chế này không áp dụng nếu bên ủy quyền đã cấp trước sự đồng ý bằng văn bản rõ ràng với đầy đủ nhận thức về các tình huống liên quan.', 'Người được ủy quyền không được cấp ủy quyền lại nếu không có sự đồng ý bằng văn bản trước của bên ủy quyền. Nếu ủy quyền lại được cấp vi phạm điều này, người được ủy quyền chịu trách nhiệm về hành vi của người được ủy quyền lại như hành vi của chính mình.', d.agentPenalty && Number(d.agentPenalty) > 0 ? `Trách nhiệm về thiệt hại do vượt quá phạm vi ủy quyền hoặc thực hiện ủy quyền cẩu thả được điều chỉnh theo § 2913 BLDS. Đối với việc vượt quá có chủ ý, người được ủy quyền phải trả cho bên ủy quyền một khoản tiền phạt hợp đồng ${fmtAmount(d.agentPenalty)} crown Séc; việc trả phạt không ảnh hưởng đến yêu cầu bồi thường thiệt hại.` : 'Trách nhiệm về thiệt hại do vượt quá phạm vi ủy quyền hoặc thực hiện ủy quyền cẩu thả được điều chỉnh theo § 2913 BLDS. Đối với việc vượt quá có chủ ý, người được ủy quyền phải trả lại các lợi ích đã nhận và bồi thường cho bên ủy quyền thiệt hại đã phát sinh, bao gồm chi phí hợp lý để thực thi quyền.', 'Nếu người được ủy quyền vượt quá phạm vi ủy quyền, phần vượt quá không ràng buộc bên ủy quyền trừ khi bên ủy quyền sau đó chấp thuận (§ 440 BLDS). Bên thứ ba hành động ngay tình với người được ủy quyền có thể yêu cầu bồi thường thiệt hại được chứng minh từ người được ủy quyền.'] });
  }

  sections.push({ title: `${hasPremium ? 'VIII' : 'VI'}. ĐIỀU KHOẢN CUỐI CÙNG`, body: ['Văn bản này được điều chỉnh bởi pháp luật Cộng hòa Séc, đặc biệt là Luật số 89/2012 Sb., Bộ luật Dân sự, có sửa đổi.', 'Giấy ủy quyền có hiệu lực khi bên ủy quyền ký và chấm dứt khi hoàn thành ủy quyền, hết thời hạn, bị bên ủy quyền hủy bỏ hoặc một trong các bên qua đời (§ 448 BLDS).', 'Bên ủy quyền có thể hủy bỏ giấy ủy quyền này bằng văn bản bất kỳ lúc nào bằng cách giao việc hủy bỏ cho người được ủy quyền. Việc hủy bỏ có hiệu lực vào thời điểm người được ủy quyền biết về nó.', 'Việc hạn chế hoặc mở rộng phạm vi ủy quyền chỉ có hiệu lực bằng văn bản.', 'Sự vô hiệu của một điều khoản riêng lẻ không ảnh hưởng đến hiệu lực của các điều khoản còn lại.', 'Việc xử lý dữ liệu cá nhân tuân thủ Quy định EU 2016/679 (GDPR) và Luật số 110/2019 Sb., chỉ nhằm mục đích cấp và thực hiện ủy quyền này.'] });
  sections.push({ title: `${hasPremium ? 'IX' : 'VII'}. CHỮ KÝ`, body: [] });
  return sections;
}

// ── DE (Deutsch) ───────────────────────────────────────────────────────────
function de(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const scopeDesc = (() => {
    switch (d.poaType) {
      case 'property': return `jede Rechtshandlung betreffend Übertragung, Kauf, Verkauf, Vermietung oder sonstige Verfügung über die Immobilie an der Adresse / im Katastergebiet: ${pad(d.propertyAddress) || 'nicht angegeben'}, insbesondere: Unterzeichnung des Kaufvertrags, Vorvertrags, Mietvertrags und Schenkungsvertrags; Vertretung gegenüber dem Liegenschaftskataster, Finanzinstituten und Behörden. WARNUNG: Diese Vollmacht erfordert eine amtlich beglaubigte Unterschrift des Vollmachtgebers (Notar oder Czech POINT). Ohne Beglaubigung wird sie vom Liegenschaftskataster und Finanzinstituten nicht akzeptiert.`;
      case 'court': return `Vertretung des Vollmachtgebers im Verfahren bei ${pad(d.courtName) || 'nicht angegeben'}, Aktenzeichen ${pad(d.caseNumber) || 'nicht angegeben'}, einschließlich Empfangs von Sendungen, Einlegens von Rechtsmitteln und Abschluss von Vergleichen. WARNUNG: Eine gerichtliche Vollmacht sollte eine amtlich beglaubigte Unterschrift tragen. In Verfahren mit Anwaltszwang (§ 27 ZPO) muss der Vertreter ein Rechtsanwalt sein.`;
      case 'company': return `Vertretung des Vollmachtgebers als Gesellschafter / Geschäftsführer / Aktionär der ${pad(d.companyName) || 'nicht angegeben'}, IČO ${pad(d.companyIco) || 'nicht angegeben'}, für folgende Handlungen: ${pad(d.companyScope) || 'Hauptversammlung, Verhandlungen mit Behörden, Geschäftsverhandlungen'}`;
      case 'bank': return `Vertretung bei Banken und Finanzinstituten, insbesondere Verfügung über das Konto Nr. ${pad(d.bankAccount) || 'nicht angegeben'} bei ${pad(d.bankName) || 'nicht angegeben'}, einschließlich Abhebungen, Einzahlungen und Kontoverwaltung. WARNUNG: Banken verlangen üblicherweise ein eigenes Vollmachtsformular oder eine amtlich beglaubigte Unterschrift. Überprüfen Sie bei Ihrer Bank, ob dieses Dokument akzeptiert wird.`;
      default: return `${pad(d.customScope) || 'nicht angegeben'}`;
    }
  })();
  const validity = d.validUntil ? `Diese Vollmacht ist gültig bis ${pad(d.validUntil)}.` : d.singleUse ? 'Diese Vollmacht ist einmalig und erlischt mit der Erfüllung der Handlung, für die sie erteilt wurde.' : 'Diese Vollmacht gilt bis zum ausdrücklichen Widerruf durch den Vollmachtgeber.';
  const substitution = d.allowSubstitution ? 'Der Bevollmächtigte ist berechtigt, eine Untervollmacht an einen Dritten zu erteilen.' : 'Der Bevollmächtigte ist nicht berechtigt, an seiner Stelle einen Dritten zu bevollmächtigen (Substitution unzulässig).';

  const sections: ParaPair[] = [
    { title: 'VOLLMACHT', body: ['Diese Vollmacht wird gemäß § 441 ff. des Gesetzes Nr. 89/2012 Slg., tschechisches BGB, in der geltenden Fassung, erteilt.', `Datum der Erteilung: ${d.contractDate ? fmtDate(d.contractDate, 'de-DE') : new Date().toLocaleDateString('de-DE')}`] },
    { title: 'I. VOLLMACHTGEBER', body: [`Name / Firmenname: ${pad(d.principalName)}`, `Geburtsdatum / IČO: ${pad(d.principalId) || '—'}`, `Hauptwohnsitz / eingetragener Sitz: ${pad(d.principalAddress)}`, d.principalEmail ? `E-Mail: ${pad(d.principalEmail)}` : ''] },
    { title: 'II. BEVOLLMÄCHTIGTER', body: [`Name / Firmenname: ${pad(d.agentName)}`, `Geburtsdatum / IČO: ${pad(d.agentId) || '—'}`, `Hauptwohnsitz / eingetragener Sitz: ${pad(d.agentAddress)}`, d.agentEmail ? `E-Mail: ${pad(d.agentEmail)}` : ''] },
    { title: 'III. UMFANG UND GEGENSTAND DER BEVOLLMÄCHTIGUNG', body: ['Der Vollmachtgeber bevollmächtigt hiermit den Bevollmächtigten, den Vollmachtgeber zu vertreten und in dessen Namen und auf dessen Rechnung in der Angelegenheit:', scopeDesc, substitution] },
    { title: 'IV. GÜLTIGKEIT', body: [validity, 'Die Vollmacht erlischt auch mit dem Tod des Vollmachtgebers oder des Bevollmächtigten, soweit sich aus der Natur der Sache nichts anderes ergibt.', 'Der Vollmachtgeber kann die Vollmacht jederzeit widerrufen; der Widerruf wird mit Zugang beim Bevollmächtigten wirksam.'] },
    { title: 'V. ERKLÄRUNGEN DES VOLLMACHTGEBERS', body: ['Der Vollmachtgeber erklärt, dass:', '(a) diese Vollmacht frei, ernsthaft und ohne Zwang erteilt wird,', '(b) er voll geschäftsfähig ist,', '(c) er den Umfang der erteilten Befugnisse und deren Rechtsfolgen kennt.', hasPremium ? 'Die Echtheit der Unterschrift des Vollmachtgebers ist durch einen Notar oder Czech POINT beglaubigt. Die amtliche Beglaubigung erhöht die Verwendbarkeit der Vollmacht gegenüber Dritten erheblich; einige Stellen können dennoch ein eigenes Formular oder weitere Voraussetzungen verlangen.' : '', '(d) der Bevollmächtigte hat mit der Sorgfalt eines ordentlichen Geschäftsmanns und im besten Interesse des Vollmachtgebers zu handeln; über jede im Rahmen der Bevollmächtigung vorgenommene Rechtshandlung hat der Bevollmächtigte den Vollmachtgeber unverzüglich zu informieren.', '(e) der Vollmachtgeber kann diese Vollmacht jederzeit schriftlich widerrufen; der Widerruf wird wirksam, sobald der Bevollmächtigte davon Kenntnis erlangt (§ 448(1) BGB). Nach Widerruf hat der Bevollmächtigte das Original der Vollmacht unverzüglich an den Vollmachtgeber zurückzugeben.'] },
  ];

  if (hasPremium) {
    sections.push({ title: 'VI. AMTLICHE UNTERSCHRIFTSBEGLAUBIGUNG UND RECHTSWIRKUNG GEGENÜBER DRITTEN', body: ['Die amtliche Beglaubigung der Unterschrift des Vollmachtgebers erfolgt durch einen Notar, eine Czech-POINT-Stelle oder das Standesamt der mit Registerführung beauftragten Gemeindebehörde. Eine Beglaubigung ist insbesondere erforderlich für: Rechtshandlungen betreffend Immobilien, die ins Liegenschaftskataster einzutragen sind (§ 6 Gesetz Nr. 256/2013 Slg.), Vertretung in Verfahren vor Gerichten und Behörden sowie Verfügung über Bankkonten und Geldmittel.', 'Das Original der Vollmacht verwahrt der Vollmachtgeber. Der Bevollmächtigte ist berechtigt, Dritten das Original oder eine amtlich beglaubigte Kopie vorzulegen; nach Beendigung der Bevollmächtigung oder auf Aufforderung des Vollmachtgebers hat er das Original unverzüglich zurückzugeben und alle Kopien zu vernichten.', 'Der Vollmachtgeber ist berechtigt, die Vollmacht jederzeit zu widerrufen; der Widerruf wird gegenüber dem Bevollmächtigten mit Zugang und gegenüber Dritten mit deren Kenntnis wirksam. Zur Vermeidung von Zweifeln empfehlen wir, den Widerruf schriftlich auch Dritten mitzuteilen, gegenüber denen die Vollmacht zuvor verwendet wurde.', 'Diese Vollmacht wird in zwei Ausfertigungen erstellt; eine verbleibt beim Vollmachtgeber, die andere erhält der Bevollmächtigte als Nachweis. Der Vollmachtgeber kann weitere amtlich beglaubigte Ausfertigungen nach Bedarf erstellen lassen.'] });
    sections.push({ title: 'VII. SANKTIONEN BEI ÜBERSCHREITEN DER VOLLMACHT UND INTERESSENKONFLIKTVERBOT', body: ['Der Bevollmächtigte darf nicht in einer Angelegenheit handeln, in der er selbst Partei ist oder am Ergebnis ein unmittelbares oder mittelbares Interesse hat (Verbot des Selbstkontrahierens). Diese Beschränkung gilt nicht, wenn der Vollmachtgeber dafür im Voraus ausdrücklich schriftlich, in Kenntnis aller maßgeblichen Umstände, zugestimmt hat.', 'Der Bevollmächtigte darf ohne vorherige schriftliche Zustimmung des Vollmachtgebers keine Untervollmacht erteilen. Wird eine Untervollmacht entgegen dieser Bestimmung erteilt, haftet der Bevollmächtigte für die Handlungen des Untervertreters wie für eigene.', d.agentPenalty && Number(d.agentPenalty) > 0 ? `Für Schäden durch Überschreiten der Vollmacht oder durch fahrlässige Ausübung haftet der Bevollmächtigte gemäß § 2913 BGB. Bei vorsätzlicher Überschreitung hat der Bevollmächtigte dem Vollmachtgeber eine Vertragsstrafe von CZK ${fmtAmount(d.agentPenalty)} zu zahlen; die Zahlung der Vertragsstrafe lässt Schadensersatzansprüche unberührt.` : 'Für Schäden durch Überschreiten der Vollmacht oder durch fahrlässige Ausübung haftet der Bevollmächtigte gemäß § 2913 BGB. Bei vorsätzlicher Überschreitung hat der Bevollmächtigte erlangte Vorteile zurückzugewähren und dem Vollmachtgeber den entstandenen Schaden, einschließlich angemessener Rechtsverfolgungskosten, zu ersetzen.', 'Überschreitet der Bevollmächtigte den Umfang der Vollmacht, bindet die Überschreitung den Vollmachtgeber nicht, es sei denn, er genehmigt sie nachträglich (§ 440 BGB). Ein gutgläubiger Dritter kann gegen den Bevollmächtigten Schadensersatz für nachweisbare Schäden geltend machen.'] });
  }

  sections.push({ title: `${hasPremium ? 'VIII' : 'VI'}. SCHLUSSBESTIMMUNGEN`, body: ['Diese Urkunde unterliegt dem Recht der Tschechischen Republik, insbesondere dem Gesetz Nr. 89/2012 Slg., BGB, in der geltenden Fassung.', 'Die Vollmacht wird mit der Unterzeichnung durch den Vollmachtgeber wirksam und erlischt mit Erfüllung der bevollmächtigten Handlung, Zeitablauf, Widerruf durch den Vollmachtgeber oder Tod einer Partei (§ 448 BGB).', 'Der Vollmachtgeber kann diese Vollmacht jederzeit schriftlich widerrufen, indem er dem Bevollmächtigten den Widerruf zustellt. Der Widerruf wird wirksam, sobald der Bevollmächtigte davon Kenntnis erlangt.', 'Eine Einschränkung oder Erweiterung des Umfangs der Vollmacht ist nur in Schriftform wirksam.', 'Die Unwirksamkeit einer einzelnen Bestimmung berührt die Wirksamkeit der übrigen Bestimmungen nicht.', 'Die Verarbeitung personenbezogener Daten erfolgt gemäß EU-Verordnung 2016/679 (DSGVO) und Gesetz Nr. 110/2019 Slg., ausschließlich zum Zweck der Erteilung und Ausführung dieser Bevollmächtigung.'] });
  sections.push({ title: `${hasPremium ? 'IX' : 'VII'}. UNTERSCHRIFTEN`, body: [] });
  return sections;
}

export function buildPowerOfAttorneyTranslationsBySection(d: StoredContractData, hasPremium: boolean): Array<NonNullable<ContractSection['translations']>> {
  return buildBilingualTranslations({
    en: () => en(d, hasPremium),
    ua: () => uk(d, hasPremium),
  });
}
