/**
 * Sublease (podnájemní smlouva) — translations EN/UK/RU/VN/DE.
 * Mirrors buildSubleaseContractSections paragraph-by-paragraph.
 */
import type { ContractSection, StoredContractData } from '../contracts';
import { buildBilingualTranslations, fmtAmount, fmtDate, pad, type ParaPair } from './helpers';

// ── EN ─────────────────────────────────────────────────────────────────────
function en(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const consentNote = d.landlordConsent === 'yes'
    ? `The landlord's written consent to subletting was granted on ${fmtDate(d.consentDate) || 'unspecified'}.`
    : "Notice: Where the situation requires the landlord's consent to a sublease, the tenant must obtain it before signing. Subletting part of a flat is governed in particular by § 2274 and § 2275 Civil Code.";

  const sections: ParaPair[] = [
    { title: 'PREAMBLE', body: ['This sublease agreement (the "Agreement") is concluded under § 2274 et seq. of Act No. 89/2012 Coll., the Czech Civil Code, as amended (the "Civil Code").', consentNote, `Date of conclusion: ${d.contractDate ? fmtDate(d.contractDate) : new Date().toLocaleDateString('en-GB')}`] },
    { title: 'I. PARTIES', body: [`Tenant (sub-lessor): ${pad(d.landlordName)}, date of birth / Company ID: ${pad(d.landlordId) || '—'}, residence / registered office: ${pad(d.landlordAddress)}`, d.landlordEmail ? `Sub-lessor e-mail: ${pad(d.landlordEmail)}` : '', `Sub-tenant: ${pad(d.tenantName)}, date of birth / Company ID: ${pad(d.tenantId) || '—'}, residence / registered office: ${pad(d.tenantAddress)}`, d.tenantEmail ? `Sub-tenant e-mail: ${pad(d.tenantEmail)}` : ''] },
    { title: 'II. SUBJECT OF THE SUBLEASE', body: [`The sub-lessor lets to the sub-tenant: the flat / premises at ${pad(d.flatAddress) || 'unspecified'}, ${pad(d.flatLayout)}, ${d.flatUnitNumber ? `unit no. ${pad(d.flatUnitNumber)}, ` : ''}${d.floor ? `floor ${pad(d.floor)}, ` : ''}cadastral area ${pad(d.cadastralArea) || 'unspecified'}.`, d.subleaseArea ? `Floor area of sub-let space: ${pad(d.subleaseArea)} m²` : ''] },
    { title: 'III. SUBLEASE TERM', body: [d.duration === 'fixed' ? `The sublease is concluded for a fixed term from ${fmtDate(d.startDate) || 'unspecified'} to ${fmtDate(d.endDate) || 'unspecified'}.` : `The sublease is concluded for an indefinite term starting on ${fmtDate(d.startDate) || 'unspecified'}.`, d.duration === 'indefinite' ? `Notice period: ${pad(d.noticePeriod) || '3'} months; the notice period starts on the first day of the month following delivery of the notice.` : '', 'The sublease shall in any case end no later than the end of the head lease.'] },
    { title: 'IV. SUBLEASE RENT AND PAYMENTS', body: [`Monthly sublease rent: CZK ${fmtAmount(d.rentAmount)}.`, d.utilityAmount ? `Service / utility advance: CZK ${fmtAmount(d.utilityAmount)} per month.` : '', `Total monthly payment: CZK ${fmtAmount((Number(d.rentAmount) || 0) + (Number(d.utilityAmount) || 0))}.`, d.depositAmount ? `Deposit: CZK ${fmtAmount(d.depositAmount)}. The sub-lessor shall return the deposit within 30 days of the end of the sublease and the handover of the premises, after deducting duly specified and proven claims.` : '', `The sublease rent is payable by the ${pad(d.paymentDay) || '15'}th day of the relevant month ${d.bankAccount ? `to the sub-lessor's bank account no. ${pad(d.bankAccount)}` : 'in cash or by bank transfer'}.`, "In case of delay in payment, the sub-lessor is entitled to statutory default interest from the due date."] },
    { title: 'V. RULES OF THE SUBLEASE', body: ['The sub-tenant shall: use the premises only for the agreed purpose, keep order, make no alterations without the sub-lessor\'s consent, not damage the property, and comply with the house rules.', `Maximum number of occupants: ${pad(d.maxOccupants) || '2'}`, `Pets: ${d.allowPets ? 'expressly acknowledged between the parties; the sub-tenant is liable for any damage and additional costs they cause' : 'the sub-tenant may keep an animal only where this does not cause disturbance beyond what is reasonable in the building'}`, `Smoking: ${d.allowSmoking ? 'permitted' : 'prohibited'}`, `Airbnb / short-term sub-letting: ${d.allowAirbnb ? 'permitted' : 'prohibited'}`, 'The sub-tenant acknowledges the terms of the head lease and undertakes to comply with them.'] },
    { title: 'VI. HANDOVER OF THE PREMISES', body: [`Handover date: ${fmtDate(d.handoverDate) || 'unspecified'}.`, `Number of keys handed over: ${pad(d.keysCount) || '1'}`, d.equipmentList ? `Equipment handed over: ${pad(d.equipmentList)}` : '', d.knownDefects ? `Known defects: ${pad(d.knownDefects)}` : 'The premises are handed over without apparent defects.', 'A handover protocol signed by both parties shall be drawn up.'] },
    { title: 'VII. TERMINATION OF THE SUBLEASE', body: ['Upon termination of the sublease the sub-tenant shall vacate the premises, restore them to their initial condition (ordinary wear and tear excepted) and return the keys.', !isNaN(Number(d.rentAmount)) && Number(d.rentAmount) > 0 ? `For each day of delay in vacating, the sub-tenant shall pay compensation of CZK ${Math.round(Number(d.rentAmount) / 30)} per day (i.e. 1/30 of the agreed monthly sublease rent).` : 'For each day of delay in vacating, the sub-tenant shall pay compensation equal to 1/30 of the agreed monthly sublease rent.', 'The deposit shall be returned within 30 days of handover, after deduction of any claims of the sub-lessor.'] },
    { title: 'VIII. REPAIRS, EMERGENCIES AND MAINTENANCE', body: ['Minor repairs and ordinary maintenance costs of the sub-let premises are borne by the sub-tenant (to an extent proportionate to the nature of the sublease).', 'Minor repairs are borne by the sub-tenant within the scope of Government Decree No. 308/2015 Coll., as amended. Larger repairs are borne by the sub-lessor, unless caused by the sub-tenant.', 'The sub-tenant shall report to the sub-lessor, without undue delay and within 24 hours at the latest, any emergency, fault or damage. In case of immediate danger, the sub-tenant may take necessary protective measures without prior consent.', "The sub-tenant must not carry out any structural alterations without the sub-lessor's and (where required) the landlord's prior written consent. Unauthorised alterations must be restored at the sub-tenant's own cost."] },
  ];
  if (hasPremium) {
    sections.push({ title: 'IX. SPECIAL TERMS AND RELATIONSHIP TO THE HEAD LEASE', body: [`The sub-tenant acknowledges that the sub-lessor is bound to the property owner by a head lease dated ${fmtDate(d.mainLeaseDate) || 'unspecified'}. Termination of the head lease also terminates the sublease (§ 2277 Civil Code).`, 'The sub-tenant undertakes not to breach the terms of the head lease.', 'The sub-lessor shall promptly inform the sub-tenant of any change to the head lease that could affect the sub-tenant\'s rights and obligations.', "The sub-tenant may not further sublet the premises to a third party without prior written consent of both the sub-lessor and the landlord.", d.breachPenalty && Number(d.breachPenalty) > 0 ? `Contractual penalty for unauthorised further subletting or other breach of the head lease: CZK ${fmtAmount(d.breachPenalty)}.` : 'In case of unauthorised further subletting or other breach of the head lease, the sub-tenant shall compensate the sub-lessor for all demonstrable damage.'] });
    sections.push({ title: 'X. CONTRACTUAL PENALTIES AND SANCTIONS', body: [`Delay in payment of sublease rent: contractual penalty of 0.1% of the amount due per day of delay${d.minLatePenalty && Number(d.minLatePenalty) > 0 ? ` (min. CZK ${fmtAmount(d.minLatePenalty)}/day)` : ''}.`, (Number(d.rentAmount) || 0) > 0 ? `Delay in vacating: contractual penalty equal to 1/15 of the monthly sublease rent (i.e. CZK ${fmtAmount(Math.round(Number(d.rentAmount) * 2 / 30))}) per day of delay.` : 'Delay in vacating: contractual penalty equal to 1/15 of the monthly sublease rent per day of delay.', d.damagePenalty && Number(d.damagePenalty) > 0 ? `Unauthorised alteration or damage: contractual penalty of CZK ${fmtAmount(d.damagePenalty)} plus compensation for actual damage.` : 'Unauthorised alteration or damage: the sub-tenant is fully liable and shall restore the premises at their own cost.', 'Payment of a contractual penalty is without prejudice to the right to compensation for damage in full.', 'The sub-lessor may declare a contractual penalty immediately payable and rescind the Agreement if the sub-tenant is more than 30 days in arrears or seriously breaches the terms of the head lease.'] });
    sections.push({ title: 'XI. SERVICE OF NOTICES', body: ['All written communications shall be delivered to the addresses of the parties set out herein, or to the e-mail addresses where provided.', 'A document sent by registered post is deemed delivered on the third working day after dispatch, even if the addressee did not collect it.', 'Each party shall notify the other of any change of address in writing without undue delay; until such notice is delivered, the previous address remains effective.'] });
  }
  sections.push({ title: `${hasPremium ? 'XII' : 'IX'}. FINAL PROVISIONS`, body: ['This Agreement is governed by the laws of the Czech Republic, in particular Act No. 89/2012 Coll., the Civil Code, as amended.', 'Any disputes shall be resolved primarily amicably; failing agreement, by the competent court of the Czech Republic.', 'This Agreement is executed in two counterparts; each party receives one.', 'Amendments are valid only as written, numbered and signed addenda.', 'The invalidity of any individual provision does not affect the validity of the remaining provisions.', 'Personal data are processed in accordance with EU Regulation 2016/679 (GDPR) and Act No. 110/2019 Coll.', 'Neither party is liable for non-performance of non-monetary obligations caused by force majeure (§ 2913(2) Civil Code).'] });
  sections.push({ title: `${hasPremium ? 'XIII' : 'X'}. SIGNATURES`, body: [] });
  return sections;
}

// ── UK ─────────────────────────────────────────────────────────────────────
function uk(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const consentNote = d.landlordConsent === 'yes' ? `Письмова згода орендодавця на суборенду надана ${fmtDate(d.consentDate, 'uk-UA') || 'не вказано'}.` : 'Увага: якщо ситуація потребує згоди орендодавця на суборенду, орендар повинен її отримати перед підписанням. Суборенда частини квартири регулюється зокрема § 2274 та § 2275 ЦК.';
  const sections: ParaPair[] = [
    { title: 'ПРЕАМБУЛА', body: ['Цей договір суборенди («Договір») укладається відповідно до § 2274 та наступних Закону № 89/2012 Sb., Цивільний кодекс Чехії, з наступними змінами («ЦК»).', consentNote, `Дата укладення: ${d.contractDate ? fmtDate(d.contractDate, 'uk-UA') : new Date().toLocaleDateString('uk-UA')}`] },
    { title: 'I. СТОРОНИ', body: [`Орендар (субдавець): ${pad(d.landlordName)}, дата народження / IČO: ${pad(d.landlordId) || '—'}, місце проживання / місцезнаходження: ${pad(d.landlordAddress)}`, d.landlordEmail ? `E-mail субдавця: ${pad(d.landlordEmail)}` : '', `Суборендар: ${pad(d.tenantName)}, дата народження / IČO: ${pad(d.tenantId) || '—'}, місце проживання / місцезнаходження: ${pad(d.tenantAddress)}`, d.tenantEmail ? `E-mail суборендаря: ${pad(d.tenantEmail)}` : ''] },
    { title: 'II. ПРЕДМЕТ СУБОРЕНДИ', body: [`Субдавець передає суборендарю в суборенду: квартиру / приміщення за адресою ${pad(d.flatAddress) || 'не вказано'}, ${pad(d.flatLayout)}, ${d.flatUnitNumber ? `номер квартири ${pad(d.flatUnitNumber)}, ` : ''}${d.floor ? `поверх ${pad(d.floor)}, ` : ''}кадастровий округ ${pad(d.cadastralArea) || 'не вказано'}.`, d.subleaseArea ? `Площа суборендованого приміщення: ${pad(d.subleaseArea)} м²` : ''] },
    { title: 'III. СТРОК СУБОРЕНДИ', body: [d.duration === 'fixed' ? `Суборенда укладається на визначений строк з ${fmtDate(d.startDate, 'uk-UA') || 'не вказано'} до ${fmtDate(d.endDate, 'uk-UA') || 'не вказано'}.` : `Суборенда укладається на невизначений строк з ${fmtDate(d.startDate, 'uk-UA') || 'не вказано'}.`, d.duration === 'indefinite' ? `Строк попередження: ${pad(d.noticePeriod) || '3'} місяці; строк попередження починається з першого дня місяця, наступного після вручення повідомлення.` : '', 'Суборенда у будь-якому випадку припиняється не пізніше припинення основної оренди.'] },
    { title: 'IV. ПЛАТА ЗА СУБОРЕНДУ ТА ПЛАТЕЖІ', body: [`Щомісячна плата за суборенду: ${fmtAmount(d.rentAmount)} крон.`, d.utilityAmount ? `Авансовий платіж за послуги: ${fmtAmount(d.utilityAmount)} крон/місяць.` : '', `Загальний щомісячний платіж: ${fmtAmount((Number(d.rentAmount) || 0) + (Number(d.utilityAmount) || 0))} крон.`, d.depositAmount ? `Завдаток: ${fmtAmount(d.depositAmount)} крон. Субдавець повертає завдаток протягом 30 днів від припинення суборенди та передачі приміщення, після вирахування належно специфікованих та доведених вимог.` : '', `Плата за суборенду сплачується до ${pad(d.paymentDay) || '15'}. дня відповідного місяця ${d.bankAccount ? `на банківський рахунок субдавця № ${pad(d.bankAccount)}` : 'готівкою або банківським переказом'}.`, 'У разі прострочення сплати субдавець має право вимагати законні відсотки за прострочення з дня сплати.'] },
    { title: 'V. ПРАВИЛА СУБОРЕНДИ', body: ['Суборендар зобов\'язаний: використовувати приміщення лише за погодженою метою, дотримуватися порядку, не вносити змін без згоди субдавця, не пошкоджувати майно та дотримуватися правил будинку.', `Максимальна кількість осіб у квартирі: ${pad(d.maxOccupants) || '2'}`, `Домашні тварини: ${d.allowPets ? 'утримання прийнято до відома сторонами; суборендар відповідає за шкоду та підвищені витрати, спричинені ними' : 'суборендар має право тримати тварину лише якщо це не спричиняє непропорційних незручностей'}`, `Куріння: ${d.allowSmoking ? 'дозволено' : 'заборонено'}`, `Airbnb / короткострокова суборенда: ${d.allowAirbnb ? 'дозволено' : 'заборонено'}`, 'Суборендар бере до уваги умови основної оренди та зобов\'язується їх дотримуватися.'] },
    { title: 'VI. ПЕРЕДАЧА ПРИМІЩЕННЯ', body: [`Дата передачі: ${fmtDate(d.handoverDate, 'uk-UA') || 'не вказано'}.`, `Кількість переданих ключів: ${pad(d.keysCount) || '1'}`, d.equipmentList ? `Передане устаткування: ${pad(d.equipmentList)}` : '', d.knownDefects ? `Відомі дефекти: ${pad(d.knownDefects)}` : 'Приміщення передається без явних дефектів.', 'Буде складено акт прийому-передачі, підписаний обома сторонами.'] },
    { title: 'VII. ПРИПИНЕННЯ СУБОРЕНДИ', body: ['При припиненні суборенди суборендар зобов\'язаний звільнити приміщення, привести його у первісний стан (з урахуванням звичайного зношування) та повернути ключі.', !isNaN(Number(d.rentAmount)) && Number(d.rentAmount) > 0 ? `За кожен день прострочення зі звільненням суборендар зобов\'язаний сплачувати компенсацію ${Math.round(Number(d.rentAmount) / 30)} крон/день (тобто 1/30 погодженої щомісячної плати).` : 'За кожен день прострочення зі звільненням суборендар зобов\'язаний сплачувати компенсацію 1/30 погодженої щомісячної плати.', 'Завдаток повертається протягом 30 днів від передачі приміщення, після вирахування можливих вимог субдавця.'] },
    { title: 'VIII. РЕМОНТ, АВАРІЇ ТА ОБСЛУГОВУВАННЯ', body: ['Дрібний ремонт і витрати на звичайне обслуговування суборендованого приміщення несе суборендар (в межах, пропорційних характеру суборенди).', 'Дрібний ремонт несе суборендар у межах, встановлених Постановою уряду № 308/2015 Sb., зі змінами. Більший ремонт несе субдавець, якщо тільки шкода не була заподіяна суборендарем.', 'Суборендар зобов\'язаний негайно — не пізніше 24 годин — повідомити субдавцю про будь-яку аварію, поломку або пошкодження. У разі безпосередньої загрози має право вжити необхідних захисних заходів і без попередньої згоди.', 'Суборендар не може здійснювати будь-яких будівельних змін без попередньої письмової згоди субдавця та (за необхідності) орендодавця. Неавторизовані зміни суборендар зобов\'язаний за власні кошти повернути до первісного стану.'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'IX. ОСОБЛИВІ УМОВИ ТА ВІДНОШЕННЯ ДО ОСНОВНОЇ ОРЕНДИ', body: [`Суборендар бере до уваги, що субдавець перед власником нерухомості зв\'язаний договором оренди від ${fmtDate(d.mainLeaseDate, 'uk-UA') || 'не вказано'}. Припинення основної оренди припиняє і суборенду (§ 2277 ЦК).`, 'Суборендар зобов\'язується не порушувати умови основної оренди.', 'Субдавець зобов\'язаний негайно інформувати суборендаря про будь-яку зміну основної оренди, яка може вплинути на права та обов\'язки суборендаря.', 'Суборендар не має права передавати суборендоване приміщення в подальшу суборенду третій особі без попередньої письмової згоди субдавця та орендодавця.', d.breachPenalty && Number(d.breachPenalty) > 0 ? `Штраф за неавторизовану подальшу суборенду або інше порушення основної оренди: ${fmtAmount(d.breachPenalty)} крон.` : 'При неавторизованій подальшій суборенді або іншому порушенні основної оренди суборендар зобов\'язаний відшкодувати субдавцю всю доведену шкоду.'] });
    sections.push({ title: 'X. ШТРАФИ І САНКЦІЇ', body: [`Прострочення сплати плати за суборенду: штраф у розмірі 0,1% від заборгованості за кожен день прострочення${d.minLatePenalty && Number(d.minLatePenalty) > 0 ? ` (мін. ${fmtAmount(d.minLatePenalty)} крон/день)` : ''}.`, (Number(d.rentAmount) || 0) > 0 ? `Прострочення зі звільненням: штраф у розмірі 1/15 щомісячної плати за суборенду (тобто ${fmtAmount(Math.round(Number(d.rentAmount) * 2 / 30))} крон) за кожен день прострочення.` : 'Прострочення зі звільненням: штраф у розмірі 1/15 щомісячної плати за суборенду за кожен день прострочення.', d.damagePenalty && Number(d.damagePenalty) > 0 ? `Неавторизована зміна або пошкодження: штраф ${fmtAmount(d.damagePenalty)} крон і відшкодування фактичної шкоди.` : 'Неавторизована зміна або пошкодження: суборендар несе повну відповідальність і зобов\'язаний за власні кошти повернути приміщення до первісного стану.', 'Сплата штрафу не позбавляє права на повне відшкодування шкоди.', 'Субдавець має право оголосити штраф негайно сплатним і відразу відмовитися від договору, якщо суборендар прострочує сплату більше 30 днів або серйозно порушує умови основної оренди.'] });
    sections.push({ title: 'XI. ВРУЧЕННЯ ПИСЕМ', body: ['Усі писемні документи доставляються на адреси сторін, зазначені у цьому Договорі, або на електронні адреси, якщо сторона їх повідомила.', 'Письмо, надіслане рекомендованим листом, вважається врученим на третій робочий день після відправлення, навіть якщо адресат його не отримав.', 'Зміну адреси сторона зобов\'язана негайно письмово повідомити іншій стороні; до моменту вручення повідомлення діє первісна адреса.'] });
  }
  sections.push({ title: `${hasPremium ? 'XII' : 'IX'}. ЗАКЛЮЧНІ ПОЛОЖЕННЯ`, body: ['Договір регулюється правом Чеської Республіки, зокрема Законом № 89/2012 Sb., Цивільним кодексом, з наступними змінами.', 'Будь-які спори вирішуються насамперед мирним шляхом; за відсутності згоди — компетентним судом Чеської Республіки.', 'Договір укладений у двох примірниках; кожна сторона отримує по одному.', 'Зміни дійсні лише у формі писемних, нумерованих і підписаних доповнень.', 'Недійсність окремого положення не впливає на дійсність решти положень.', 'Обробка персональних даних здійснюється відповідно до Регламенту ЄС 2016/679 (GDPR) та Закону № 110/2019 Sb.', 'Жодна сторона не відповідає за невиконання немайнових зобов\'язань, спричинене форс-мажором (§ 2913(2) ЦК).'] });
  sections.push({ title: `${hasPremium ? 'XIII' : 'X'}. ПІДПИСИ`, body: [] });
  return sections;
}

// ── RU ─────────────────────────────────────────────────────────────────────
function ru(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const consentNote = d.landlordConsent === 'yes' ? `Письменное согласие наймодателя на поднайм предоставлено ${fmtDate(d.consentDate, 'ru-RU') || 'не указано'}.` : 'Внимание: если ситуация требует согласия наймодателя на поднайм, наниматель обязан получить его до подписания. Поднайм части квартиры регулируется в особенности § 2274 и § 2275 ГК.';
  const sections: ParaPair[] = [
    { title: 'ПРЕАМБУЛА', body: ['Настоящий договор поднайма («Договор») заключается согласно § 2274 и далее Закона № 89/2012 Sb., Гражданский кодекс Чехии, с последующими изменениями («ГК»).', consentNote, `Дата заключения: ${d.contractDate ? fmtDate(d.contractDate, 'ru-RU') : new Date().toLocaleDateString('ru-RU')}`] },
    { title: 'I. СТОРОНЫ', body: [`Наниматель (поднаймодатель): ${pad(d.landlordName)}, дата рождения / IČO: ${pad(d.landlordId) || '—'}, место жительства / юридический адрес: ${pad(d.landlordAddress)}`, d.landlordEmail ? `E-mail поднаймодателя: ${pad(d.landlordEmail)}` : '', `Поднаниматель: ${pad(d.tenantName)}, дата рождения / IČO: ${pad(d.tenantId) || '—'}, место жительства / юридический адрес: ${pad(d.tenantAddress)}`, d.tenantEmail ? `E-mail поднанимателя: ${pad(d.tenantEmail)}` : ''] },
    { title: 'II. ПРЕДМЕТ ПОДНАЙМА', body: [`Поднаймодатель передаёт поднанимателю в поднайм: квартиру / помещение по адресу ${pad(d.flatAddress) || 'не указано'}, ${pad(d.flatLayout)}, ${d.flatUnitNumber ? `номер квартиры ${pad(d.flatUnitNumber)}, ` : ''}${d.floor ? `этаж ${pad(d.floor)}, ` : ''}кадастровый округ ${pad(d.cadastralArea) || 'не указано'}.`, d.subleaseArea ? `Площадь поднимаемого помещения: ${pad(d.subleaseArea)} м²` : ''] },
    { title: 'III. СРОК ПОДНАЙМА', body: [d.duration === 'fixed' ? `Поднайм заключается на определённый срок с ${fmtDate(d.startDate, 'ru-RU') || 'не указано'} по ${fmtDate(d.endDate, 'ru-RU') || 'не указано'}.` : `Поднайм заключается на неопределённый срок с ${fmtDate(d.startDate, 'ru-RU') || 'не указано'}.`, d.duration === 'indefinite' ? `Срок уведомления: ${pad(d.noticePeriod) || '3'} месяца; срок уведомления начинается с первого дня месяца, следующего за вручением уведомления.` : '', 'Поднайм в любом случае прекращается не позднее окончания основного найма.'] },
    { title: 'IV. ПЛАТА ЗА ПОДНАЙМ И ПЛАТЕЖИ', body: [`Ежемесячная плата за поднайм: ${fmtAmount(d.rentAmount)} крон.`, d.utilityAmount ? `Авансовый платёж за услуги: ${fmtAmount(d.utilityAmount)} крон/месяц.` : '', `Общий ежемесячный платёж: ${fmtAmount((Number(d.rentAmount) || 0) + (Number(d.utilityAmount) || 0))} крон.`, d.depositAmount ? `Залог: ${fmtAmount(d.depositAmount)} крон. Поднаймодатель возвращает залог в течение 30 дней с прекращения поднайма и передачи помещения, после вычета должным образом конкретизированных и доказанных требований.` : '', `Плата за поднайм уплачивается до ${pad(d.paymentDay) || '15'}-го дня соответствующего месяца ${d.bankAccount ? `на банковский счёт поднаймодателя № ${pad(d.bankAccount)}` : 'наличными или банковским переводом'}.`, 'В случае просрочки уплаты поднаймодатель вправе требовать законные проценты за просрочку со дня уплаты.'] },
    { title: 'V. ПРАВИЛА ПОДНАЙМА', body: ['Поднаниматель обязан: использовать помещение только по согласованному назначению, поддерживать порядок, не делать изменений без согласия поднаймодателя, не повреждать имущество и соблюдать правила дома.', `Максимальное количество лиц в квартире: ${pad(d.maxOccupants) || '2'}`, `Домашние животные: ${d.allowPets ? 'их содержание принято к сведению сторонами; поднаниматель отвечает за ущерб и повышенные расходы, вызванные ими' : 'поднаниматель вправе содержать животное только если это не причиняет непропорциональных неудобств'}`, `Курение: ${d.allowSmoking ? 'разрешено' : 'запрещено'}`, `Airbnb / краткосрочный поднайм: ${d.allowAirbnb ? 'разрешено' : 'запрещено'}`, 'Поднаниматель принимает к сведению условия основного найма и обязуется их соблюдать.'] },
    { title: 'VI. ПЕРЕДАЧА ПОМЕЩЕНИЯ', body: [`Дата передачи: ${fmtDate(d.handoverDate, 'ru-RU') || 'не указано'}.`, `Количество переданных ключей: ${pad(d.keysCount) || '1'}`, d.equipmentList ? `Переданное оборудование: ${pad(d.equipmentList)}` : '', d.knownDefects ? `Известные дефекты: ${pad(d.knownDefects)}` : 'Помещение передаётся без явных дефектов.', 'Будет составлен акт приёма-передачи, подписанный обеими сторонами.'] },
    { title: 'VII. ПРЕКРАЩЕНИЕ ПОДНАЙМА', body: ['При прекращении поднайма поднаниматель обязан освободить помещение, привести его в первоначальное состояние (с учётом обычного износа) и вернуть ключи.', !isNaN(Number(d.rentAmount)) && Number(d.rentAmount) > 0 ? `За каждый день просрочки с освобождением поднаниматель обязан уплачивать компенсацию ${Math.round(Number(d.rentAmount) / 30)} крон/день (т.е. 1/30 согласованной ежемесячной платы).` : 'За каждый день просрочки с освобождением поднаниматель обязан уплачивать компенсацию 1/30 согласованной ежемесячной платы.', 'Залог возвращается в течение 30 дней с передачи помещения, после вычета возможных требований поднаймодателя.'] },
    { title: 'VIII. РЕМОНТ, АВАРИИ И ОБСЛУЖИВАНИЕ', body: ['Мелкий ремонт и расходы на обычное обслуживание поднанимаемого помещения несёт поднаниматель (в пределах, пропорциональных характеру поднайма).', 'Мелкий ремонт несёт поднаниматель в пределах, установленных Постановлением правительства № 308/2015 Sb., с изменениями. Более крупный ремонт несёт поднаймодатель, если только ущерб не был причинён поднанимателем.', 'Поднаниматель обязан незамедлительно — не позднее 24 часов — сообщить поднаймодателю о любой аварии, поломке или повреждении. В случае непосредственной опасности вправе принять необходимые защитные меры и без предварительного согласия.', 'Поднаниматель не может производить никаких строительных изменений без предварительного письменного согласия поднаймодателя и (при необходимости) наймодателя. Неавторизованные изменения поднаниматель обязан за свой счёт привести в первоначальное состояние.'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'IX. ОСОБЫЕ УСЛОВИЯ И ОТНОШЕНИЕ К ОСНОВНОМУ НАЙМУ', body: [`Поднаниматель принимает к сведению, что поднаймодатель перед собственником недвижимости связан договором найма от ${fmtDate(d.mainLeaseDate, 'ru-RU') || 'не указано'}. Прекращение основного найма прекращает и поднайм (§ 2277 ГК).`, 'Поднаниматель обязуется не нарушать условия основного найма.', 'Поднаймодатель обязан незамедлительно информировать поднанимателя о любом изменении основного найма, которое может повлиять на права и обязанности поднанимателя.', 'Поднаниматель не вправе передавать поднанимаемое помещение в дальнейший поднайм третьему лицу без предварительного письменного согласия поднаймодателя и наймодателя.', d.breachPenalty && Number(d.breachPenalty) > 0 ? `Штраф за неавторизованный дальнейший поднайм или иное нарушение основного найма: ${fmtAmount(d.breachPenalty)} крон.` : 'При неавторизованном дальнейшем поднайме или ином нарушении основного найма поднаниматель обязан возместить поднаймодателю весь доказанный ущерб.'] });
    sections.push({ title: 'X. ШТРАФЫ И САНКЦИИ', body: [`Просрочка уплаты платы за поднайм: штраф в размере 0,1% от задолженности за каждый день просрочки${d.minLatePenalty && Number(d.minLatePenalty) > 0 ? ` (мин. ${fmtAmount(d.minLatePenalty)} крон/день)` : ''}.`, (Number(d.rentAmount) || 0) > 0 ? `Просрочка с освобождением: штраф в размере 1/15 ежемесячной платы за поднайм (т.е. ${fmtAmount(Math.round(Number(d.rentAmount) * 2 / 30))} крон) за каждый день просрочки.` : 'Просрочка с освобождением: штраф в размере 1/15 ежемесячной платы за поднайм за каждый день просрочки.', d.damagePenalty && Number(d.damagePenalty) > 0 ? `Неавторизованное изменение или повреждение: штраф ${fmtAmount(d.damagePenalty)} крон и возмещение фактического ущерба.` : 'Неавторизованное изменение или повреждение: поднаниматель несёт полную ответственность и обязан за свой счёт восстановить помещение.', 'Уплата штрафа не лишает права на полное возмещение ущерба.', 'Поднаймодатель вправе объявить штраф немедленно подлежащим уплате и сразу отказаться от Договора, если поднаниматель просрочивает уплату более 30 дней или серьёзно нарушает условия основного найма.'] });
    sections.push({ title: 'XI. ВРУЧЕНИЕ ПИСЕМ', body: ['Все письменные документы доставляются по адресам сторон, указанным в настоящем Договоре, или по электронным адресам, если сторона их сообщила.', 'Письмо, отправленное заказным письмом, считается врученным на третий рабочий день после отправки, даже если адресат его не получил.', 'Изменение адреса сторона обязана незамедлительно письменно сообщить другой стороне; до момента вручения уведомления действует первоначальный адрес.'] });
  }
  sections.push({ title: `${hasPremium ? 'XII' : 'IX'}. ЗАКЛЮЧИТЕЛЬНЫЕ ПОЛОЖЕНИЯ`, body: ['Договор регулируется правом Чешской Республики, в частности Законом № 89/2012 Sb., Гражданским кодексом, с последующими изменениями.', 'Любые споры решаются прежде всего мирным путём; при отсутствии соглашения — компетентным судом Чешской Республики.', 'Договор составлен в двух экземплярах; каждая сторона получает по одному.', 'Изменения действительны только в форме письменных, пронумерованных и подписанных дополнений.', 'Недействительность отдельного положения не влияет на действительность остальных положений.', 'Обработка персональных данных осуществляется в соответствии с Регламентом ЕС 2016/679 (GDPR) и Законом № 110/2019 Sb.', 'Ни одна из сторон не отвечает за неисполнение неимущественных обязательств, вызванное форс-мажором (§ 2913(2) ГК).'] });
  sections.push({ title: `${hasPremium ? 'XIII' : 'X'}. ПОДПИСИ`, body: [] });
  return sections;
}

// ── VN ─────────────────────────────────────────────────────────────────────
function vn(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const consentNote = d.landlordConsent === 'yes' ? `Sự đồng ý bằng văn bản của chủ nhà đối với việc cho thuê lại đã được cấp ngày ${fmtDate(d.consentDate, 'vi-VN') || 'chưa nêu rõ'}.` : 'Lưu ý: Trong trường hợp cần có sự đồng ý của chủ nhà đối với việc cho thuê lại, bên thuê phải có được sự đồng ý đó trước khi ký. Việc cho thuê lại một phần căn hộ được điều chỉnh đặc biệt bởi § 2274 và § 2275 BLDS.';
  const sections: ParaPair[] = [
    { title: 'LỜI MỞ ĐẦU', body: ['Hợp đồng cho thuê lại này ("Hợp đồng") được ký kết theo § 2274 trở đi của Luật số 89/2012 Sb., Bộ luật Dân sự Séc, có sửa đổi ("BLDS").', consentNote, `Ngày ký kết: ${d.contractDate ? fmtDate(d.contractDate, 'vi-VN') : new Date().toLocaleDateString('vi-VN')}`] },
    { title: 'I. CÁC BÊN', body: [`Bên thuê (bên cho thuê lại): ${pad(d.landlordName)}, ngày sinh / IČO: ${pad(d.landlordId) || '—'}, nơi cư trú / trụ sở: ${pad(d.landlordAddress)}`, d.landlordEmail ? `E-mail bên cho thuê lại: ${pad(d.landlordEmail)}` : '', `Bên thuê lại: ${pad(d.tenantName)}, ngày sinh / IČO: ${pad(d.tenantId) || '—'}, nơi cư trú / trụ sở: ${pad(d.tenantAddress)}`, d.tenantEmail ? `E-mail bên thuê lại: ${pad(d.tenantEmail)}` : ''] },
    { title: 'II. ĐỐI TƯỢNG CHO THUÊ LẠI', body: [`Bên cho thuê lại cho bên thuê lại thuê: căn hộ / phòng tại ${pad(d.flatAddress) || 'chưa nêu rõ'}, ${pad(d.flatLayout)}, ${d.flatUnitNumber ? `số căn hộ ${pad(d.flatUnitNumber)}, ` : ''}${d.floor ? `tầng ${pad(d.floor)}, ` : ''}khu vực địa chính ${pad(d.cadastralArea) || 'chưa nêu rõ'}.`, d.subleaseArea ? `Diện tích không gian cho thuê lại: ${pad(d.subleaseArea)} m²` : ''] },
    { title: 'III. THỜI HẠN CHO THUÊ LẠI', body: [d.duration === 'fixed' ? `Việc cho thuê lại được ký kết với thời hạn xác định từ ${fmtDate(d.startDate, 'vi-VN') || 'chưa nêu rõ'} đến ${fmtDate(d.endDate, 'vi-VN') || 'chưa nêu rõ'}.` : `Việc cho thuê lại được ký kết với thời hạn không xác định từ ${fmtDate(d.startDate, 'vi-VN') || 'chưa nêu rõ'}.`, d.duration === 'indefinite' ? `Thời hạn thông báo: ${pad(d.noticePeriod) || '3'} tháng; thời hạn thông báo bắt đầu từ ngày đầu tiên của tháng sau khi giao thông báo.` : '', 'Việc cho thuê lại trong mọi trường hợp sẽ chấm dứt không muộn hơn ngày kết thúc hợp đồng thuê chính.'] },
    { title: 'IV. TIỀN THUÊ LẠI VÀ THANH TOÁN', body: [`Tiền thuê lại hàng tháng: ${fmtAmount(d.rentAmount)} crown Séc.`, d.utilityAmount ? `Phí dịch vụ ứng trước: ${fmtAmount(d.utilityAmount)} crown Séc/tháng.` : '', `Tổng số thanh toán hàng tháng: ${fmtAmount((Number(d.rentAmount) || 0) + (Number(d.utilityAmount) || 0))} crown Séc.`, d.depositAmount ? `Tiền đặt cọc: ${fmtAmount(d.depositAmount)} crown Séc. Bên cho thuê lại phải trả lại tiền đặt cọc trong vòng 30 ngày kể từ ngày chấm dứt việc cho thuê lại và bàn giao không gian, sau khi trừ các khoản yêu cầu được xác định và chứng minh hợp lệ.` : '', `Tiền thuê lại được thanh toán đến ngày ${pad(d.paymentDay) || '15'} của tháng tương ứng ${d.bankAccount ? `vào tài khoản ngân hàng số ${pad(d.bankAccount)} của bên cho thuê lại` : 'bằng tiền mặt hoặc chuyển khoản'}.`, 'Trong trường hợp chậm thanh toán, bên cho thuê lại có quyền yêu cầu lãi chậm trả theo luật từ ngày đến hạn.'] },
    { title: 'V. QUY TẮC CHO THUÊ LẠI', body: ['Bên thuê lại có nghĩa vụ: sử dụng không gian chỉ cho mục đích đã thỏa thuận, giữ trật tự, không thực hiện các thay đổi mà không có sự đồng ý của bên cho thuê lại, không làm hỏng tài sản và tuân thủ nội quy tòa nhà.', `Số người tối đa trong căn hộ: ${pad(d.maxOccupants) || '2'}`, `Vật nuôi: ${d.allowPets ? 'việc nuôi được các bên ghi nhận; bên thuê lại chịu trách nhiệm về thiệt hại và chi phí phát sinh do chúng' : 'bên thuê lại chỉ có quyền nuôi vật nuôi nếu việc đó không gây phiền hà không tương xứng'}`, `Hút thuốc: ${d.allowSmoking ? 'cho phép' : 'cấm'}`, `Airbnb / cho thuê lại ngắn hạn: ${d.allowAirbnb ? 'cho phép' : 'cấm'}`, 'Bên thuê lại ghi nhận các điều khoản của hợp đồng thuê chính và cam kết tuân thủ.'] },
    { title: 'VI. BÀN GIAO KHÔNG GIAN', body: [`Ngày bàn giao: ${fmtDate(d.handoverDate, 'vi-VN') || 'chưa nêu rõ'}.`, `Số chìa khóa đã giao: ${pad(d.keysCount) || '1'}`, d.equipmentList ? `Thiết bị bàn giao: ${pad(d.equipmentList)}` : '', d.knownDefects ? `Lỗi đã biết: ${pad(d.knownDefects)}` : 'Không gian được bàn giao mà không có lỗi rõ ràng.', 'Sẽ lập biên bản bàn giao được hai bên ký.'] },
    { title: 'VII. CHẤM DỨT CHO THUÊ LẠI', body: ['Khi chấm dứt việc cho thuê lại, bên thuê lại có nghĩa vụ giải phóng không gian, đưa nó về tình trạng ban đầu (có tính đến hao mòn thông thường) và trả lại chìa khóa.', !isNaN(Number(d.rentAmount)) && Number(d.rentAmount) > 0 ? `Đối với mỗi ngày chậm trả giải phóng, bên thuê lại có nghĩa vụ trả khoản bồi thường ${Math.round(Number(d.rentAmount) / 30)} crown Séc/ngày (tức 1/30 tiền thuê hàng tháng đã thỏa thuận).` : 'Đối với mỗi ngày chậm giải phóng, bên thuê lại có nghĩa vụ trả khoản bồi thường tương đương 1/30 tiền thuê hàng tháng đã thỏa thuận.', 'Tiền đặt cọc sẽ được trả lại trong vòng 30 ngày từ ngày bàn giao, sau khi trừ các khoản yêu cầu có thể có của bên cho thuê lại.'] },
    { title: 'VIII. SỬA CHỮA, SỰ CỐ VÀ BẢO TRÌ', body: ['Bên thuê lại chịu các chi phí sửa chữa nhỏ và bảo trì thông thường của không gian cho thuê lại (trong phạm vi tương xứng với tính chất của việc cho thuê lại).', 'Bên thuê lại chịu sửa chữa nhỏ trong phạm vi do Nghị định Chính phủ số 308/2015 Sb. quy định, có sửa đổi. Sửa chữa lớn do bên cho thuê lại chịu, trừ khi thiệt hại do bên thuê lại gây ra.', 'Bên thuê lại có nghĩa vụ báo cáo cho bên cho thuê lại không chậm trễ — chậm nhất trong vòng 24 giờ — về bất kỳ sự cố, hỏng hóc hoặc thiệt hại nào. Trong trường hợp nguy hiểm cấp bách, có thể thực hiện các biện pháp bảo vệ cần thiết mà không cần sự đồng ý trước.', 'Bên thuê lại không được thực hiện bất kỳ thay đổi xây dựng nào mà không có sự đồng ý trước bằng văn bản của bên cho thuê lại và (nếu cần) chủ nhà. Bên thuê lại phải tự chi trả phục hồi các thay đổi trái phép về tình trạng ban đầu.'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'IX. ĐIỀU KHOẢN ĐẶC BIỆT VÀ QUAN HỆ VỚI HỢP ĐỒNG THUÊ CHÍNH', body: [`Bên thuê lại ghi nhận rằng bên cho thuê lại bị ràng buộc với chủ sở hữu bất động sản bởi hợp đồng thuê chính ngày ${fmtDate(d.mainLeaseDate, 'vi-VN') || 'chưa nêu rõ'}. Việc chấm dứt hợp đồng thuê chính cũng chấm dứt việc cho thuê lại (§ 2277 BLDS).`, 'Bên thuê lại cam kết không vi phạm các điều khoản của hợp đồng thuê chính.', 'Bên cho thuê lại phải thông báo ngay cho bên thuê lại về bất kỳ thay đổi nào trong hợp đồng thuê chính có thể ảnh hưởng đến quyền và nghĩa vụ của bên thuê lại.', 'Bên thuê lại không có quyền cho thuê lại không gian cho bên thứ ba mà không có sự đồng ý trước bằng văn bản của cả bên cho thuê lại và chủ nhà.', d.breachPenalty && Number(d.breachPenalty) > 0 ? `Tiền phạt hợp đồng cho việc cho thuê lại trái phép hoặc vi phạm khác của hợp đồng thuê chính: ${fmtAmount(d.breachPenalty)} crown Séc.` : 'Trong trường hợp cho thuê lại trái phép hoặc vi phạm khác của hợp đồng thuê chính, bên thuê lại có nghĩa vụ bồi thường cho bên cho thuê lại tất cả thiệt hại đã chứng minh.'] });
    sections.push({ title: 'X. TIỀN PHẠT HỢP ĐỒNG VÀ CHẾ TÀI', body: [`Chậm thanh toán tiền thuê lại: tiền phạt hợp đồng 0,1% giá trị nợ cho mỗi ngày chậm${d.minLatePenalty && Number(d.minLatePenalty) > 0 ? ` (tối thiểu ${fmtAmount(d.minLatePenalty)} crown Séc/ngày)` : ''}.`, (Number(d.rentAmount) || 0) > 0 ? `Chậm giải phóng: tiền phạt hợp đồng tương đương 1/15 tiền thuê lại hàng tháng (tức ${fmtAmount(Math.round(Number(d.rentAmount) * 2 / 30))} crown Séc) cho mỗi ngày chậm.` : 'Chậm giải phóng: tiền phạt hợp đồng tương đương 1/15 tiền thuê lại hàng tháng cho mỗi ngày chậm.', d.damagePenalty && Number(d.damagePenalty) > 0 ? `Thay đổi hoặc hư hỏng trái phép: tiền phạt ${fmtAmount(d.damagePenalty)} crown Séc và bồi thường thiệt hại thực tế.` : 'Thay đổi hoặc hư hỏng trái phép: bên thuê lại chịu trách nhiệm hoàn toàn và phải tự chi trả phục hồi không gian.', 'Việc thanh toán tiền phạt hợp đồng không ảnh hưởng đến quyền được bồi thường thiệt hại đầy đủ.', 'Bên cho thuê lại có quyền tuyên bố tiền phạt phải thanh toán ngay và hủy bỏ Hợp đồng nếu bên thuê lại chậm thanh toán quá 30 ngày hoặc vi phạm nghiêm trọng các điều khoản của hợp đồng thuê chính.'] });
    sections.push({ title: 'XI. GIAO CÁC VĂN BẢN', body: ['Tất cả các thông tin liên lạc bằng văn bản sẽ được giao đến địa chỉ của các bên được nêu trong Hợp đồng này, hoặc đến địa chỉ email khi đã cung cấp.', 'Tài liệu gửi bằng thư đăng ký được coi là đã giao vào ngày làm việc thứ ba sau khi gửi, ngay cả khi người nhận không nhận.', 'Mỗi bên phải thông báo cho bên kia bất kỳ thay đổi địa chỉ nào bằng văn bản không chậm trễ; cho đến khi thông báo được giao, địa chỉ trước vẫn có hiệu lực.'] });
  }
  sections.push({ title: `${hasPremium ? 'XII' : 'IX'}. ĐIỀU KHOẢN CUỐI CÙNG`, body: ['Hợp đồng này được điều chỉnh bởi pháp luật Cộng hòa Séc, đặc biệt là Luật số 89/2012 Sb., Bộ luật Dân sự, có sửa đổi.', 'Mọi tranh chấp được giải quyết trước hết bằng cách thân thiện; khi không thỏa thuận được, do tòa án có thẩm quyền của Cộng hòa Séc.', 'Hợp đồng này được lập thành hai bản; mỗi bên nhận một bản.', 'Các sửa đổi chỉ có hiệu lực dưới dạng phụ lục bằng văn bản, được đánh số và ký.', 'Sự vô hiệu của một điều khoản riêng lẻ không ảnh hưởng đến hiệu lực của các điều khoản còn lại.', 'Việc xử lý dữ liệu cá nhân tuân thủ Quy định EU 2016/679 (GDPR) và Luật số 110/2019 Sb.', 'Không bên nào chịu trách nhiệm về việc không thực hiện các nghĩa vụ phi tiền tệ do bất khả kháng (§ 2913(2) BLDS).'] });
  sections.push({ title: `${hasPremium ? 'XIII' : 'X'}. CHỮ KÝ`, body: [] });
  return sections;
}

// ── DE ─────────────────────────────────────────────────────────────────────
function de(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const consentNote = d.landlordConsent === 'yes' ? `Die schriftliche Zustimmung des Vermieters zur Untervermietung wurde am ${fmtDate(d.consentDate, 'de-DE') || 'nicht angegeben'} erteilt.` : 'Hinweis: Sofern die konkrete Situation eine Zustimmung des Vermieters zur Untervermietung erfordert, hat der Mieter diese vor Unterzeichnung einzuholen. Die Untervermietung eines Teils der Wohnung wird insbesondere durch § 2274 und § 2275 BGB geregelt.';
  const sections: ParaPair[] = [
    { title: 'PRÄAMBEL', body: ['Dieser Untermietvertrag (der „Vertrag") wird gemäß § 2274 ff. des Gesetzes Nr. 89/2012 Slg., tschechisches BGB, in der geltenden Fassung („BGB"), geschlossen.', consentNote, `Datum des Abschlusses: ${d.contractDate ? fmtDate(d.contractDate, 'de-DE') : new Date().toLocaleDateString('de-DE')}`] },
    { title: 'I. VERTRAGSPARTEIEN', body: [`Mieter (Untervermieter): ${pad(d.landlordName)}, Geburtsdatum / IČO: ${pad(d.landlordId) || '—'}, Wohnsitz / Sitz: ${pad(d.landlordAddress)}`, d.landlordEmail ? `E-Mail des Untervermieters: ${pad(d.landlordEmail)}` : '', `Untermieter: ${pad(d.tenantName)}, Geburtsdatum / IČO: ${pad(d.tenantId) || '—'}, Wohnsitz / Sitz: ${pad(d.tenantAddress)}`, d.tenantEmail ? `E-Mail des Untermieters: ${pad(d.tenantEmail)}` : ''] },
    { title: 'II. GEGENSTAND DER UNTERVERMIETUNG', body: [`Der Untervermieter überlässt dem Untermieter zur Untervermietung: die Wohnung / die Räume an der Adresse ${pad(d.flatAddress) || 'nicht angegeben'}, ${pad(d.flatLayout)}, ${d.flatUnitNumber ? `Einheitsnummer ${pad(d.flatUnitNumber)}, ` : ''}${d.floor ? `Geschoss ${pad(d.floor)}, ` : ''}Katastergebiet ${pad(d.cadastralArea) || 'nicht angegeben'}.`, d.subleaseArea ? `Wohnfläche des untervermieteten Raums: ${pad(d.subleaseArea)} m²` : ''] },
    { title: 'III. UNTERMIETZEIT', body: [d.duration === 'fixed' ? `Die Untervermietung wird auf bestimmte Zeit vom ${fmtDate(d.startDate, 'de-DE') || 'nicht angegeben'} bis ${fmtDate(d.endDate, 'de-DE') || 'nicht angegeben'} abgeschlossen.` : `Die Untervermietung wird auf unbestimmte Zeit ab dem ${fmtDate(d.startDate, 'de-DE') || 'nicht angegeben'} abgeschlossen.`, d.duration === 'indefinite' ? `Kündigungsfrist: ${pad(d.noticePeriod) || '3'} Monate; die Kündigungsfrist beginnt mit dem ersten Tag des Monats, der auf die Zustellung der Kündigung folgt.` : '', 'Die Untervermietung endet in jedem Fall spätestens mit dem Ende des Hauptmietvertrags.'] },
    { title: 'IV. UNTERMIETZAHLUNGEN', body: [`Monatliche Untermietzahlung: ${fmtAmount(d.rentAmount)} CZK.`, d.utilityAmount ? `Nebenkostenvorauszahlung: ${fmtAmount(d.utilityAmount)} CZK/Monat.` : '', `Gesamte monatliche Zahlung: ${fmtAmount((Number(d.rentAmount) || 0) + (Number(d.utilityAmount) || 0))} CZK.`, d.depositAmount ? `Kaution: ${fmtAmount(d.depositAmount)} CZK. Der Untervermieter erstattet die Kaution innerhalb von 30 Tagen nach Beendigung der Untervermietung und Übergabe der Räume zurück, abzüglich ordnungsgemäß spezifizierter und nachgewiesener Forderungen.` : '', `Die Untermiete ist bis zum ${pad(d.paymentDay) || '15'}. Tag des betreffenden Monats ${d.bankAccount ? `auf das Bankkonto des Untervermieters Nr. ${pad(d.bankAccount)}` : 'in bar oder per Banküberweisung'} zu zahlen.`, 'Bei Zahlungsverzug ist der Untervermieter berechtigt, gesetzliche Verzugszinsen ab Fälligkeit zu verlangen.'] },
    { title: 'V. REGELN DER UNTERVERMIETUNG', body: ['Der Untermieter hat: die Räume nur zum vereinbarten Zweck zu nutzen, Ordnung zu halten, keine Veränderungen ohne Zustimmung des Untervermieters vorzunehmen, das Eigentum nicht zu beschädigen und die Hausordnung einzuhalten.', `Maximale Anzahl der Bewohner: ${pad(d.maxOccupants) || '2'}`, `Haustiere: ${d.allowPets ? 'die Haltung wird zwischen den Parteien zur Kenntnis genommen; der Untermieter haftet für Schäden und erhöhte Kosten' : 'der Untermieter darf ein Tier nur halten, wenn dies keine unangemessenen Belästigungen verursacht'}`, `Rauchen: ${d.allowSmoking ? 'gestattet' : 'verboten'}`, `Airbnb / kurzfristige Untervermietung: ${d.allowAirbnb ? 'gestattet' : 'verboten'}`, 'Der Untermieter nimmt die Bedingungen des Hauptmietvertrags zur Kenntnis und verpflichtet sich, diese einzuhalten.'] },
    { title: 'VI. ÜBERGABE DER RÄUME', body: [`Übergabedatum: ${fmtDate(d.handoverDate, 'de-DE') || 'nicht angegeben'}.`, `Anzahl der übergebenen Schlüssel: ${pad(d.keysCount) || '1'}`, d.equipmentList ? `Übergebene Ausstattung: ${pad(d.equipmentList)}` : '', d.knownDefects ? `Bekannte Mängel: ${pad(d.knownDefects)}` : 'Die Räume werden ohne offensichtliche Mängel übergeben.', 'Es wird ein von beiden Parteien unterzeichnetes Übergabeprotokoll erstellt.'] },
    { title: 'VII. BEENDIGUNG DER UNTERVERMIETUNG', body: ['Bei Beendigung der Untervermietung ist der Untermieter verpflichtet, die Räume zu räumen, sie in ihren ursprünglichen Zustand (unter Berücksichtigung der gewöhnlichen Abnutzung) zurückzuversetzen und die Schlüssel zurückzugeben.', !isNaN(Number(d.rentAmount)) && Number(d.rentAmount) > 0 ? `Für jeden Tag der Räumungsverzögerung hat der Untermieter eine Entschädigung von ${Math.round(Number(d.rentAmount) / 30)} CZK/Tag (d. h. 1/30 der vereinbarten monatlichen Untermiete) zu zahlen.` : 'Für jeden Tag der Räumungsverzögerung hat der Untermieter eine Entschädigung in Höhe von 1/30 der vereinbarten monatlichen Untermiete zu zahlen.', 'Die Kaution wird innerhalb von 30 Tagen nach der Übergabe zurückerstattet, nach Abzug etwaiger Forderungen des Untervermieters.'] },
    { title: 'VIII. REPARATUREN, NOTFÄLLE UND INSTANDHALTUNG', body: ['Kleinere Reparaturen und Kosten der gewöhnlichen Instandhaltung der untervermieteten Räume trägt der Untermieter (in einem dem Charakter der Untervermietung angemessenen Umfang).', 'Kleinere Reparaturen trägt der Untermieter im Umfang der Regierungsverordnung Nr. 308/2015 Slg., in der geltenden Fassung. Größere Reparaturen trägt der Untervermieter, sofern der Schaden nicht vom Untermieter verursacht wurde.', 'Der Untermieter hat unverzüglich — spätestens innerhalb von 24 Stunden — jeden Notfall, jede Störung oder Beschädigung dem Untervermieter zu melden. Bei unmittelbarer Gefahr darf der Untermieter notwendige Schutzmaßnahmen auch ohne vorherige Zustimmung treffen.', 'Der Untermieter darf keine baulichen Veränderungen ohne vorherige schriftliche Zustimmung des Untervermieters und (sofern erforderlich) des Vermieters vornehmen. Unautorisierte Veränderungen hat der Untermieter auf eigene Kosten in den ursprünglichen Zustand zurückzuversetzen.'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'IX. BESONDERE BEDINGUNGEN UND VERHÄLTNIS ZUM HAUPTMIETVERTRAG', body: [`Der Untermieter nimmt zur Kenntnis, dass der Untervermieter gegenüber dem Eigentümer der Immobilie durch den Hauptmietvertrag vom ${fmtDate(d.mainLeaseDate, 'de-DE') || 'nicht angegeben'} gebunden ist. Mit Beendigung des Hauptmietvertrags endet auch die Untervermietung (§ 2277 BGB).`, 'Der Untermieter verpflichtet sich, die Bedingungen des Hauptmietvertrags nicht zu verletzen.', 'Der Untervermieter hat den Untermieter unverzüglich über jede Änderung des Hauptmietvertrags zu informieren, die sich auf die Rechte und Pflichten des Untermieters auswirken könnte.', 'Der Untermieter darf die untervermieteten Räume ohne vorherige schriftliche Zustimmung sowohl des Untervermieters als auch des Vermieters nicht weiter untervermieten.', d.breachPenalty && Number(d.breachPenalty) > 0 ? `Vertragsstrafe bei unautorisierter Weiteruntervermietung oder anderem Verstoß gegen den Hauptmietvertrag: ${fmtAmount(d.breachPenalty)} CZK.` : 'Bei unautorisierter Weiteruntervermietung oder anderem Verstoß gegen den Hauptmietvertrag hat der Untermieter dem Untervermieter alle nachweisbaren Schäden zu ersetzen.'] });
    sections.push({ title: 'X. VERTRAGSSTRAFEN UND SANKTIONEN', body: [`Verzug bei Zahlung der Untermiete: Vertragsstrafe in Höhe von 0,1% der geschuldeten Summe pro Tag des Verzugs${d.minLatePenalty && Number(d.minLatePenalty) > 0 ? ` (min. ${fmtAmount(d.minLatePenalty)} CZK/Tag)` : ''}.`, (Number(d.rentAmount) || 0) > 0 ? `Verzug bei der Räumung: Vertragsstrafe in Höhe von 1/15 der monatlichen Untermiete (d. h. ${fmtAmount(Math.round(Number(d.rentAmount) * 2 / 30))} CZK) pro Tag des Verzugs.` : 'Verzug bei der Räumung: Vertragsstrafe in Höhe von 1/15 der monatlichen Untermiete pro Tag des Verzugs.', d.damagePenalty && Number(d.damagePenalty) > 0 ? `Unautorisierte Veränderung oder Beschädigung: Vertragsstrafe ${fmtAmount(d.damagePenalty)} CZK und Ersatz des tatsächlichen Schadens.` : 'Unautorisierte Veränderung oder Beschädigung: der Untermieter haftet voll und hat die Räume auf eigene Kosten wiederherzustellen.', 'Die Zahlung der Vertragsstrafe lässt das Recht auf vollen Schadensersatz unberührt.', 'Der Untervermieter ist berechtigt, die Vertragsstrafe für sofort fällig zu erklären und vom Vertrag zurückzutreten, wenn der Untermieter mehr als 30 Tage in Verzug ist oder den Hauptmietvertrag erheblich verletzt.'] });
    sections.push({ title: 'XI. ZUSTELLUNG VON SCHRIFTSTÜCKEN', body: ['Alle schriftlichen Mitteilungen werden an die in diesem Vertrag angegebenen Adressen der Parteien oder an die E-Mail-Adressen, sofern angegeben, zugestellt.', 'Eine per Einschreiben versandte Sendung gilt als am dritten Werktag nach der Versendung zugestellt, auch wenn der Adressat sie nicht in Empfang genommen hat.', 'Jede Partei hat der anderen Partei einen Adresswechsel unverzüglich schriftlich mitzuteilen; bis zur Zustellung der Mitteilung gilt die bisherige Adresse.'] });
  }
  sections.push({ title: `${hasPremium ? 'XII' : 'IX'}. SCHLUSSBESTIMMUNGEN`, body: ['Der Vertrag unterliegt dem Recht der Tschechischen Republik, insbesondere dem Gesetz Nr. 89/2012 Slg., BGB, in der geltenden Fassung.', 'Etwaige Streitigkeiten werden vorrangig einvernehmlich beigelegt; bei Nichteinigung durch das zuständige Gericht der Tschechischen Republik.', 'Der Vertrag wird in zwei Ausfertigungen erstellt; jede Partei erhält eine.', 'Änderungen sind nur in Form schriftlicher, nummerierter und unterzeichneter Nachträge wirksam.', 'Die Unwirksamkeit einer einzelnen Bestimmung berührt die Wirksamkeit der übrigen Bestimmungen nicht.', 'Die Verarbeitung personenbezogener Daten erfolgt gemäß EU-Verordnung 2016/679 (DSGVO) und Gesetz Nr. 110/2019 Slg.', 'Keine Vertragspartei haftet für die Nichterfüllung nichtmonetärer Verpflichtungen aufgrund höherer Gewalt (§ 2913(2) BGB).'] });
  sections.push({ title: `${hasPremium ? 'XIII' : 'X'}. UNTERSCHRIFTEN`, body: [] });
  return sections;
}

export function buildSubleaseTranslationsBySection(d: StoredContractData, hasPremium: boolean): Array<NonNullable<ContractSection['translations']>> {
  return buildBilingualTranslations({
    en: () => en(d, hasPremium),
    uk: () => uk(d, hasPremium),
    ru: () => ru(d, hasPremium),
    vn: () => vn(d, hasPremium),
    de: () => de(d, hasPremium),
  });
}
