/**
 * Sublease (podnájemní smlouva) — translations EN/UK/RU/VN/DE.
 * Mirrors buildSubleaseContractSections paragraph-by-paragraph.
 */
import type { ContractSection, StoredContractData } from '../contracts';
import { buildBilingualTranslations, fmtAmount, fmtDate, pad, type ParaPair } from './helpers';

// ── EN ─────────────────────────────────────────────────────────────────────
function en(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const consentNote = d.landlordConsent === 'yes'
    ? `The landlord's written consent to subletting was granted on ${fmtDate(d.consentDate) || 'unspecified'}.`
    : "Notice: Where the situation requires the landlord's consent to a sublease, the tenant must obtain it before signing. Subletting part of a flat is governed in particular by § 2274 and § 2275 Civil Code.";

  const sections: ParaPair[] = [
    { title: 'PREAMBLE', body: ['This sublease agreement (the "Agreement") is concluded under § 2274 et seq. of Act No. 89/2012 Coll., the Czech Civil Code, as amended (the "Civil Code").', consentNote, `Date of conclusion: ${d.contractDate ? fmtDate(d.contractDate) : new Date().toLocaleDateString('en-GB')}`] },
    { title: 'I. PARTIES', body: [`Tenant (sub-lessor): ${pad(d.landlordName)}, date of birth / Company ID: ${pad(d.landlordId) || '—'}, residence / registered office: ${pad(d.landlordAddress)}`, d.landlordEmail ? `Sub-lessor e-mail: ${pad(d.landlordEmail)}` : '', `Sub-tenant: ${pad(d.tenantName)}, date of birth / Company ID: ${pad(d.tenantId) || '—'}, residence / registered office: ${pad(d.tenantAddress)}`, d.tenantEmail ? `Sub-tenant e-mail: ${pad(d.tenantEmail)}` : ''] },
    { title: 'II. SUBJECT OF THE SUBLEASE', body: [`The sub-lessor lets to the sub-tenant: the flat / premises at ${pad(d.flatAddress) || 'unspecified'}, ${pad(d.flatLayout)}, ${d.flatUnitNumber ? `unit no. ${pad(d.flatUnitNumber)}, ` : ''}${d.floor ? `floor ${pad(d.floor)}, ` : ''}cadastral area ${pad(d.cadastralArea) || 'unspecified'}.`, d.subleaseArea ? `Floor area of sub-let space: ${pad(d.subleaseArea)} m²` : ''] },
    { title: 'III. SUBLEASE TERM', body: [d.duration === 'fixed' ? `The sublease is concluded for a fixed term from ${fmtDate(d.startDate) || 'unspecified'} to ${fmtDate(d.endDate) || 'unspecified'}.` : `The sublease is concluded for an indefinite term starting on ${fmtDate(d.startDate) || 'unspecified'}.`, d.duration === 'indefinite' ? `Notice period: ${pad(d.noticePeriod) || '3'} months; the notice period starts on the first day of the month following delivery of the notice.` : '', 'The sublease shall in any case end no later than the end of the head lease.'] },
    { title: 'IV. SUBLEASE RENT AND PAYMENTS', body: [`Monthly sublease rent: CZK ${fmtAmount(d.rentAmount)}.`, d.utilityAmount ? `Service / utility advance: CZK ${fmtAmount(d.utilityAmount)} per month.` : '', `Total monthly payment: CZK ${fmtAmount((Number(d.rentAmount) || 0) + (Number(d.utilityAmount) || 0))}.`, d.depositAmount ? `Deposit: CZK ${fmtAmount(d.depositAmount)}. The sub-lessor shall return the deposit within 30 days of the end of the sublease and the handover of the premises, after deducting duly specified and proven claims.` : '', `The sublease rent is payable by the ${pad(d.paymentDay) || '15'}th day of the relevant month ${d.bankAccount ? `to the sub-lessor's bank account no. ${pad(d.bankAccount)}` : 'in cash or by bank transfer'}.`, "In case of delay in payment, the sub-lessor is entitled to statutory default interest from the due date."] },
    { title: 'V. RULES OF THE SUBLEASE', body: ['The sub-tenant shall: use the premises only for the agreed purpose, keep order, make no alterations without the sub-lessor\'s consent, not damage the property, and comply with the house rules.', `Maximum number of occupants: ${pad(d.maxOccupants) || '2'}`, `Pets: ${d.allowPets ? 'expressly acknowledged between the parties; the sub-tenant is liable for any damage and additional costs they cause' : 'the sub-tenant may keep an animal only where this does not cause disturbance beyond what is reasonable in the building'}`, `Smoking: ${d.allowSmoking ? 'permitted' : 'prohibited'}`, `Airbnb / short-term sub-letting: ${d.allowAirbnb ? 'permitted' : 'prohibited'}`, 'The sub-tenant acknowledges the terms of the head lease and undertakes to comply with them.'] },
    { title: 'VI. HANDOVER OF THE PREMISES', body: [`Handover date: ${fmtDate(d.handoverDate) || 'unspecified'}.`, `Number of keys handed over: ${pad(d.keysCount) || '1'}`, d.equipmentList ? `Equipment handed over: ${pad(d.equipmentList)}` : '', d.knownDefects ? `Known defects: ${pad(d.knownDefects)}` : 'The premises are handed over without apparent defects.', 'A handover protocol signed by both parties shall be drawn up.'] },
    { title: 'VII. TERMINATION OF THE SUBLEASE', body: ['Upon termination of the sublease the sub-tenant shall vacate the premises, restore them to their initial condition (ordinary wear and tear excepted) and return the keys.', !isNaN(Number(d.rentAmount)) && Number(d.rentAmount) > 0 ? `For each day of delay in vacating, the sub-tenant shall pay compensation of CZK ${Math.round(Number(d.rentAmount) / 30)} per day (i.e. 1/30 of the agreed monthly sublease rent).` : 'For each day of delay in vacating, the sub-tenant shall pay compensation equal to 1/30 of the agreed monthly sublease rent.', 'The deposit shall be returned within 30 days of handover, after deduction of any claims of the sub-lessor.'] },
    { title: 'VIII. REPAIRS, EMERGENCIES AND MAINTENANCE', body: ['Minor repairs and ordinary maintenance costs of the sub-let premises are borne by the sub-tenant (to an extent proportionate to the nature of the sublease).', 'Minor repairs are borne by the sub-tenant within the scope of Government Decree No. 308/2015 Coll., as amended. Larger repairs are borne by the sub-lessor, unless caused by the sub-tenant.', 'The sub-tenant shall report to the sub-lessor, without undue delay and within 24 hours at the latest, any emergency, fault or damage. In case of immediate danger, the sub-tenant may take necessary protective measures without prior consent.', "The sub-tenant must not carry out any structural alterations without the sub-lessor's and (where required) the landlord's prior written consent. Unauthorised alterations must be restored at the sub-tenant's own cost."] },
  ];
  if (hasPremium) {
    sections.push({ title: 'IX. SPECIAL TERMS AND RELATIONSHIP TO THE HEAD LEASE', body: [`The sub-tenant acknowledges that the sub-lessor is bound to the property owner by a head lease dated ${fmtDate(d.mainLeaseDate) || 'unspecified'}. Termination of the head lease also terminates the sublease (§ 2277 Civil Code).`, 'The sub-tenant undertakes not to breach the terms of the head lease.', 'The sub-lessor shall promptly inform the sub-tenant of any change to the head lease that could affect the sub-tenant\'s rights and obligations.', "The sub-tenant may not further sublet the premises to a third party without prior written consent of both the sub-lessor and the landlord.", d.breachPenalty && Number(d.breachPenalty) > 0 ? `Contractual penalty for unauthorised further subletting or other breach of the head lease: CZK ${fmtAmount(d.breachPenalty)}.` : 'In case of unauthorised further subletting or other breach of the head lease, the sub-tenant shall compensate the sub-lessor for all demonstrable damage.'] });
    sections.push({ title: 'X. CONTRACTUAL PENALTIES AND SANCTIONS', body: [`Delay in payment of sublease rent: contractual penalty of 0.1% of the amount due per day of delay${d.minLatePenalty && Number(d.minLatePenalty) > 0 ? ` (min. CZK ${fmtAmount(d.minLatePenalty)}/day)` : ''}.`, (Number(d.rentAmount) || 0) > 0 ? `Delay in vacating: contractual penalty equal to 1/15 of the monthly sublease rent (i.e. CZK ${fmtAmount(Math.round(Number(d.rentAmount) * 2 / 30))}) per day of delay.` : 'Delay in vacating: contractual penalty equal to 1/15 of the monthly sublease rent per day of delay.', d.damagePenalty && Number(d.damagePenalty) > 0 ? `Unauthorised alteration or damage: contractual penalty of CZK ${fmtAmount(d.damagePenalty)} plus compensation for actual damage.` : 'Unauthorised alteration or damage: the sub-tenant is fully liable and shall restore the premises at their own cost.', 'Payment of a contractual penalty is without prejudice to the right to compensation for damage in full.', 'The sub-lessor may declare a contractual penalty immediately payable and rescind the Agreement if the sub-tenant is more than 30 days in arrears or seriously breaches the terms of the head lease.'] });
    sections.push({ title: 'XI. SERVICE OF NOTICES', body: ['All written communications shall be delivered to the addresses of the parties set out herein, or to the e-mail addresses where provided.', 'A document sent by registered post is deemed delivered on the third working day after dispatch, even if the addressee did not collect it.', 'Each party shall notify the other of any change of address in writing without undue delay; until such notice is delivered, the previous address remains effective.'] });
  }
  sections.push({ title: `${hasPremium ? 'XII' : 'IX'}. FINAL PROVISIONS`, body: ['This Agreement is governed by the laws of the Czech Republic, in particular Act No. 89/2012 Coll., the Civil Code, as amended.', 'Any disputes shall be resolved primarily amicably; failing agreement, by the competent court of the Czech Republic.', 'This Agreement is executed in two counterparts; each party receives one.', 'Amendments are valid only as written, numbered and signed addenda.', 'The invalidity of any individual provision does not affect the validity of the remaining provisions.', 'Personal data are processed in accordance with EU Regulation 2016/679 (GDPR) and Act No. 110/2019 Coll.', 'Neither party is liable for non-performance of non-monetary obligations caused by force majeure (§ 2913(2) Civil Code).'] });
  sections.push({ title: `${hasPremium ? 'XIII' : 'X'}. SIGNATURES`, body: [] });
  return sections;
}

// ── UK ─────────────────────────────────────────────────────────────────────
function uk(d: StoredContractData, hasPremium: boolean): ParaPair[] {
  const consentNote = d.landlordConsent === 'yes' ? `Письмова згода орендодавця на суборенду надана ${fmtDate(d.consentDate, 'uk-UA') || 'не вказано'}.` : 'Увага: якщо ситуація потребує згоди орендодавця на суборенду, орендар повинен її отримати перед підписанням. Суборенда частини квартири регулюється зокрема § 2274 та § 2275 ЦК.';
  const sections: ParaPair[] = [
    { title: 'ПРЕАМБУЛА', body: ['Цей договір суборенди («Договір») укладається відповідно до § 2274 та наступних Закону № 89/2012 Sb., Цивільний кодекс Чехії, з наступними змінами («ЦК»).', consentNote, `Дата укладення: ${d.contractDate ? fmtDate(d.contractDate, 'uk-UA') : new Date().toLocaleDateString('uk-UA')}`] },
    { title: 'I. СТОРОНИ', body: [`Орендар (субдавець): ${pad(d.landlordName)}, дата народження / IČO: ${pad(d.landlordId) || '—'}, місце проживання / місцезнаходження: ${pad(d.landlordAddress)}`, d.landlordEmail ? `E-mail субдавця: ${pad(d.landlordEmail)}` : '', `Суборендар: ${pad(d.tenantName)}, дата народження / IČO: ${pad(d.tenantId) || '—'}, місце проживання / місцезнаходження: ${pad(d.tenantAddress)}`, d.tenantEmail ? `E-mail суборендаря: ${pad(d.tenantEmail)}` : ''] },
    { title: 'II. ПРЕДМЕТ СУБОРЕНДИ', body: [`Субдавець передає суборендарю в суборенду: квартиру / приміщення за адресою ${pad(d.flatAddress) || 'не вказано'}, ${pad(d.flatLayout)}, ${d.flatUnitNumber ? `номер квартири ${pad(d.flatUnitNumber)}, ` : ''}${d.floor ? `поверх ${pad(d.floor)}, ` : ''}кадастровий округ ${pad(d.cadastralArea) || 'не вказано'}.`, d.subleaseArea ? `Площа суборендованого приміщення: ${pad(d.subleaseArea)} м²` : ''] },
    { title: 'III. СТРОК СУБОРЕНДИ', body: [d.duration === 'fixed' ? `Суборенда укладається на визначений строк з ${fmtDate(d.startDate, 'uk-UA') || 'не вказано'} до ${fmtDate(d.endDate, 'uk-UA') || 'не вказано'}.` : `Суборенда укладається на невизначений строк з ${fmtDate(d.startDate, 'uk-UA') || 'не вказано'}.`, d.duration === 'indefinite' ? `Строк попередження: ${pad(d.noticePeriod) || '3'} місяці; строк попередження починається з першого дня місяця, наступного після вручення повідомлення.` : '', 'Суборенда у будь-якому випадку припиняється не пізніше припинення основної оренди.'] },
    { title: 'IV. ПЛАТА ЗА СУБОРЕНДУ ТА ПЛАТЕЖІ', body: [`Щомісячна плата за суборенду: ${fmtAmount(d.rentAmount)} крон.`, d.utilityAmount ? `Авансовий платіж за послуги: ${fmtAmount(d.utilityAmount)} крон/місяць.` : '', `Загальний щомісячний платіж: ${fmtAmount((Number(d.rentAmount) || 0) + (Number(d.utilityAmount) || 0))} крон.`, d.depositAmount ? `Грошова застава (кауція): ${fmtAmount(d.depositAmount)} крон. Субдавець повертає грошову заставу протягом 30 днів від припинення суборенди та передачі приміщення, після вирахування належно специфікованих та доведених вимог.` : '', `Плата за суборенду сплачується до ${pad(d.paymentDay) || '15'}. дня відповідного місяця ${d.bankAccount ? `на банківський рахунок субдавця № ${pad(d.bankAccount)}` : 'готівкою або банківським переказом'}.`, 'У разі прострочення сплати субдавець має право вимагати законні відсотки за прострочення з дня сплати.'] },
    { title: 'V. ПРАВИЛА СУБОРЕНДИ', body: ['Суборендар зобов\'язаний: використовувати приміщення лише за погодженою метою, дотримуватися порядку, не вносити змін без згоди субдавця, не пошкоджувати майно та дотримуватися правил будинку.', `Максимальна кількість осіб у квартирі: ${pad(d.maxOccupants) || '2'}`, `Домашні тварини: ${d.allowPets ? 'утримання прийнято до відома сторонами; суборендар відповідає за шкоду та підвищені витрати, спричинені ними' : 'суборендар має право тримати тварину лише якщо це не спричиняє непропорційних незручностей'}`, `Куріння: ${d.allowSmoking ? 'дозволено' : 'заборонено'}`, `Airbnb / короткострокова суборенда: ${d.allowAirbnb ? 'дозволено' : 'заборонено'}`, 'Суборендар бере до уваги умови основної оренди та зобов\'язується їх дотримуватися.'] },
    { title: 'VI. ПЕРЕДАЧА ПРИМІЩЕННЯ', body: [`Дата передачі: ${fmtDate(d.handoverDate, 'uk-UA') || 'не вказано'}.`, `Кількість переданих ключів: ${pad(d.keysCount) || '1'}`, d.equipmentList ? `Передане устаткування: ${pad(d.equipmentList)}` : '', d.knownDefects ? `Відомі дефекти: ${pad(d.knownDefects)}` : 'Приміщення передається без явних дефектів.', 'Буде складено акт прийому-передачі, підписаний обома сторонами.'] },
    { title: 'VII. ПРИПИНЕННЯ СУБОРЕНДИ', body: ['При припиненні суборенди суборендар зобов\'язаний звільнити приміщення, привести його у первісний стан (з урахуванням звичайного зношування) та повернути ключі.', !isNaN(Number(d.rentAmount)) && Number(d.rentAmount) > 0 ? `За кожен день прострочення зі звільненням суборендар зобов\'язаний сплачувати компенсацію ${Math.round(Number(d.rentAmount) / 30)} крон/день (тобто 1/30 погодженої щомісячної плати).` : 'За кожен день прострочення зі звільненням суборендар зобов\'язаний сплачувати компенсацію 1/30 погодженої щомісячної плати.', 'Грошова застава повертається протягом 30 днів від передачі приміщення, після вирахування можливих вимог субдавця.'] },
    { title: 'VIII. РЕМОНТ, АВАРІЇ ТА ОБСЛУГОВУВАННЯ', body: ['Дрібний ремонт і витрати на звичайне обслуговування суборендованого приміщення несе суборендар (в межах, пропорційних характеру суборенди).', 'Дрібний ремонт несе суборендар у межах, встановлених Постановою уряду № 308/2015 Sb., зі змінами. Більший ремонт несе субдавець, якщо тільки шкода не була заподіяна суборендарем.', 'Суборендар зобов\'язаний негайно — не пізніше 24 годин — повідомити субдавцю про будь-яку аварію, поломку або пошкодження. У разі безпосередньої загрози має право вжити необхідних захисних заходів і без попередньої згоди.', 'Суборендар не може здійснювати будь-яких будівельних змін без попередньої письмової згоди субдавця та (за необхідності) орендодавця. Неавторизовані зміни суборендар зобов\'язаний за власні кошти повернути до первісного стану.'] },
  ];
  if (hasPremium) {
    sections.push({ title: 'IX. ОСОБЛИВІ УМОВИ ТА ВІДНОШЕННЯ ДО ОСНОВНОЇ ОРЕНДИ', body: [`Суборендар бере до уваги, що субдавець перед власником нерухомості зв\'язаний договором оренди від ${fmtDate(d.mainLeaseDate, 'uk-UA') || 'не вказано'}. Припинення основної оренди припиняє і суборенду (§ 2277 ЦК).`, 'Суборендар зобов\'язується не порушувати умови основної оренди.', 'Субдавець зобов\'язаний негайно інформувати суборендаря про будь-яку зміну основної оренди, яка може вплинути на права та обов\'язки суборендаря.', 'Суборендар не має права передавати суборендоване приміщення в подальшу суборенду третій особі без попередньої письмової згоди субдавця та орендодавця.', d.breachPenalty && Number(d.breachPenalty) > 0 ? `Штраф за неавторизовану подальшу суборенду або інше порушення основної оренди: ${fmtAmount(d.breachPenalty)} крон.` : 'При неавторизованій подальшій суборенді або іншому порушенні основної оренди суборендар зобов\'язаний відшкодувати субдавцю всю доведену шкоду.'] });
    sections.push({ title: 'X. ШТРАФИ І САНКЦІЇ', body: [`Прострочення сплати плати за суборенду: штраф у розмірі 0,1% від заборгованості за кожен день прострочення${d.minLatePenalty && Number(d.minLatePenalty) > 0 ? ` (мін. ${fmtAmount(d.minLatePenalty)} крон/день)` : ''}.`, (Number(d.rentAmount) || 0) > 0 ? `Прострочення зі звільненням: штраф у розмірі 1/15 щомісячної плати за суборенду (тобто ${fmtAmount(Math.round(Number(d.rentAmount) * 2 / 30))} крон) за кожен день прострочення.` : 'Прострочення зі звільненням: штраф у розмірі 1/15 щомісячної плати за суборенду за кожен день прострочення.', d.damagePenalty && Number(d.damagePenalty) > 0 ? `Неавторизована зміна або пошкодження: штраф ${fmtAmount(d.damagePenalty)} крон і відшкодування фактичної шкоди.` : 'Неавторизована зміна або пошкодження: суборендар несе повну відповідальність і зобов\'язаний за власні кошти повернути приміщення до первісного стану.', 'Сплата штрафу не позбавляє права на повне відшкодування шкоди.', 'Субдавець має право оголосити штраф негайно сплатним і відразу відмовитися від договору, якщо суборендар прострочує сплату більше 30 днів або серйозно порушує умови основної оренди.'] });
    sections.push({ title: 'XI. ВРУЧЕННЯ ПИСЕМ', body: ['Усі писемні документи доставляються на адреси сторін, зазначені у цьому Договорі, або на електронні адреси, якщо сторона їх повідомила.', 'Письмо, надіслане рекомендованим листом, вважається врученим на третій робочий день після відправлення, навіть якщо адресат його не отримав.', 'Зміну адреси сторона зобов\'язана негайно письмово повідомити іншій стороні; до моменту вручення повідомлення діє первісна адреса.'] });
  }
  sections.push({ title: `${hasPremium ? 'XII' : 'IX'}. ЗАКЛЮЧНІ ПОЛОЖЕННЯ`, body: ['Договір регулюється правом Чеської Республіки, зокрема Законом № 89/2012 Sb., Цивільним кодексом, з наступними змінами.', 'Будь-які спори вирішуються насамперед мирним шляхом; за відсутності згоди — компетентним судом Чеської Республіки.', 'Договір укладений у двох примірниках; кожна сторона отримує по одному.', 'Зміни дійсні лише у формі писемних, нумерованих і підписаних доповнень.', 'Недійсність окремого положення не впливає на дійсність решти положень.', 'Обробка персональних даних здійснюється відповідно до Регламенту ЄС 2016/679 (GDPR) та Закону № 110/2019 Sb.', 'Жодна сторона не відповідає за невиконання немайнових зобов\'язань, спричинене форс-мажором (§ 2913(2) ЦК).'] });
  sections.push({ title: `${hasPremium ? 'XIII' : 'X'}. ПІДПИСИ`, body: [] });
  return sections;
}

// ── RU ─────────────────────────────────────────────────────────────────────
export function buildSubleaseTranslationsBySection(d: StoredContractData, hasPremium: boolean): Array<NonNullable<ContractSection['translations']>> {
  return buildBilingualTranslations({
    en: () => en(d, hasPremium),
    ua: () => uk(d, hasPremium),
  });
}
