// Skript pro generování vzorových PDF smluv
// Spuštění: node --experimental-strip-types scripts/generate-samples.ts

import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { renderContractPdf } from '../lib/pdf';
import type { StoredContractData, Tier } from '../lib/contracts';

const projectDir = process.cwd();
const outputDir = path.join(projectDir, 'vzory-smluv');

// ── Vzorová data pro každý typ smlouvy ─────────────────────────────────────

const today = new Date().toISOString().split('T')[0];

const SAMPLES: Array<{ data: StoredContractData; tier: Tier; label: string }> = [
  // 1. NÁJEMNÍ SMLOUVA
  {
    tier: 'complete',
    label: '01_Najemni_smlouva',
    data: {
      contractType: 'lease',
      notaryUpsell: true,
      tier: 'complete',
      landlordName: 'Jan Novák',
      landlordId: '15. 3. 1975',
      landlordAddress: 'Dlouhá 12, Praha 1, 110 00',
      landlordEmail: 'jan.novak@email.cz',
      landlordPhone: '+420 777 123 456',
      tenantName: 'Marie Horáková',
      tenantId: '20. 7. 1990',
      tenantAddress: 'Krátká 5, Brno, 602 00',
      tenantEmail: 'marie.horakova@email.cz',
      tenantPhone: '+420 605 987 654',
      propertyAddress: 'Veselá 8, Praha 2, 120 00',
      propertyLayout: '2+1',
      flatUnitNumber: 'Byt č. 14, 3. patro',
      rentAmount: '18000',
      utilitiesAmount: '3000',
      depositAmount: '54000',
      paymentDay: '5',
      duration: 'fixed',
      endDate: '2026-12-31',
      petsAllowed: true,
      smokingAllowed: false,
      airbnbAllowed: false,
      leaseDuration: 'určitou, a to do 31. 12. 2026',
    },
  },
  // 2. KUPNÍ SMLOUVA NA VOZIDLO
  {
    tier: 'complete',
    label: '02_Kupni_smlouva_auto',
    data: {
      contractType: 'car_sale',
      notaryUpsell: true,
      tier: 'complete',
      sellerName: 'Petr Svoboda',
      sellerId: '10. 1. 1980',
      sellerAddress: 'Nová 3, Ostrava, 702 00',
      buyerName: 'Tomáš Dvořák',
      buyerId: '5. 9. 1985',
      buyerAddress: 'Stará 7, Plzeň, 301 00',
      carMake: 'Škoda',
      carModel: 'Octavia',
      carYear: '2018',
      carVIN: 'TMBEG7NE9J0123456',
      carPlate: '1P2 3456',
      carMileage: '87500',
      carColor: 'Stříbrná metalíza',
      carEngineCC: '1598',
      carSTK: '2025-11-30',
      carPrice: '285000',
      carPriceWords: 'dvěstě osmdesát pět tisíc',
      paymentMethod: 'transfer',
      knownDefects: 'Drobná koroze na prazích, jinak bez vad.',
    },
  },
  // 3. DAROVACÍ SMLOUVA
  {
    tier: 'complete',
    label: '03_Darovaci_smlouva',
    data: {
      contractType: 'gift',
      notaryUpsell: true,
      tier: 'complete',
      donorName: 'Alena Marková',
      donorId: '3. 6. 1955',
      donorAddress: 'Lipová 22, Olomouc, 772 00',
      donorEmail: 'alena.markova@email.cz',
      doneeName: 'Lukáš Marko',
      doneeId: '18. 4. 1985',
      doneeAddress: 'Polní 11, Hradec Králové, 500 02',
      doneeEmail: 'lukas.marko@email.cz',
      giftType: 'money',
      amount: '250000',
      amountWords: 'dvěstě padesát tisíc',
      currency: 'Kč',
      transferMethod: 'transfer',
      bankAccount: '1234567890/0800',
      giftDate: today,
      withReservation: false,
    },
  },
  // 4. SMLOUVA O DÍLO
  {
    tier: 'complete',
    label: '04_Smlouva_o_dilo',
    data: {
      contractType: 'work_contract',
      notaryUpsell: true,
      tier: 'complete',
      clientName: 'Stavby s.r.o.',
      clientId: '12345678',
      clientAddress: 'Průmyslová 4, Praha 9, 190 00',
      contractorName: 'Josef Tesař',
      contractorId: '87654321',
      contractorAddress: 'Řemeslná 6, Kladno, 272 01',
      workDescription: 'Rekonstrukce koupelny v bytě č. 5 na adrese Veselá 8, Praha 2 — bourací práce, obkládání, instalatérské práce, elektroinstalace, sádrokarton.',
      workPrice: '180000',
      workPriceWords: 'sto osmdesát tisíc',
      paymentTerms: 'payment_schedule',
      advancePercent: '30',
      deadlineDate: '2026-06-30',
      warrantyMonths: '60',
      delayPenaltyPerDay: '0,05',
      maxPenaltyPercent: '15',
      clientPenaltyPerDay: '0,05',
      defectPenaltyPercent: '10',
    },
  },
  // 5. SMLOUVA O ZÁPŮJČCE
  {
    tier: 'complete',
    label: '05_Smlouva_o_zapujcce',
    data: {
      contractType: 'loan',
      notaryUpsell: true,
      tier: 'complete',
      lenderName: 'Robert Fiala',
      lenderId: '22. 11. 1965',
      lenderAddress: 'Lipová 3, Liberec, 460 01',
      borrowerName: 'Simona Červenková',
      borrowerId: '30. 8. 1988',
      borrowerAddress: 'Luční 9, Pardubice, 530 02',
      loanAmount: '150000',
      loanAmountWords: 'sto padesát tisíc',
      interestRate: '5',
      repaymentType: 'installments',
      installmentAmount: '5000',
      installmentDay: '15',
      repaymentDate: '2028-12-31',
      hasSecurity: true,
      securityDescription: 'Zástavní právo k osobnímu automobilu Škoda Fabia, RZ: 1L2 3456, VIN: TMBEA6NE8G0000001',
      latePenaltyRate: '0,05',
      minLatePenalty: '100',
    },
  },
  // 6. NDA — SMLOUVA O MLČENLIVOSTI
  {
    tier: 'complete',
    label: '06_NDA_smlouva',
    data: {
      contractType: 'nda',
      notaryUpsell: true,
      tier: 'complete',
      disclosingPartyName: 'TechStart s.r.o.',
      disclosingPartyId: '09876543',
      disclosingPartyAddress: 'Technologická 1, Praha 6, 160 00',
      receivingPartyName: 'Martin Kubík',
      receivingPartyId: '12. 2. 1982',
      receivingPartyAddress: 'Sadová 14, Brno, 612 00',
      ndaType: 'unilateral',
      purpose: 'Posouzení možnosti obchodní spolupráce při vývoji mobilní aplikace pro správu nemovitostí.',
      confidentialInfo: 'Obchodní strategie, zdrojový kód, databáze klientů, finanční výkazy a veškeré technické dokumentace.',
      durationYears: '3',
      nonCompete: true,
      nonSolicitation: true,
      jurisdiction: 'Praha',
    },
  },
  // 7. KUPNÍ SMLOUVA (obecná)
  {
    tier: 'complete',
    label: '07_Kupni_smlouva_obecna',
    data: {
      contractType: 'general_sale',
      notaryUpsell: true,
      tier: 'complete',
      sellerName: 'Eva Procházková',
      sellerId: '7. 7. 1972',
      sellerAddress: 'Nádražní 18, České Budějovice, 370 01',
      buyerName: 'Karel Zeman',
      buyerId: '14. 3. 1990',
      buyerAddress: 'Polní 33, Jihlava, 586 01',
      itemDescription: 'Notebook Apple MacBook Pro 14" (2023), sériové číslo: C02XXXXXXX, v dobrém stavu.',
      price: '45000',
      priceWords: 'čtyřicet pět tisíc',
      currency: 'Kč',
      paymentMethod: 'cash',
      handoverDate: today,
      warrantyMonths: '12',
      knownDefects: 'Drobné škrábance na krytu, jinak plně funkční.',
    },
  },
  // 8. PRACOVNÍ SMLOUVA
  {
    tier: 'complete',
    label: '08_Pracovni_smlouva',
    data: {
      contractType: 'employment',
      notaryUpsell: true,
      tier: 'complete',
      employerName: 'Digitální Média s.r.o.',
      employerIco: '11223344',
      employerAddress: 'Václavské náměstí 1, Praha 1, 110 00',
      employeeName: 'Ondřej Blaha',
      employeeId: '4. 12. 1995',
      employeeAddress: 'Botanická 7, Praha 6, 160 00',
      jobTitle: 'Senior Software Developer',
      workLocation: 'Praha 1, Václavské náměstí 1 (možnost home office)',
      startDate: '2026-04-01',
      contractType2: 'indefinite',
      grossSalary: '85000',
      trialPeriodMonths: '3',
      weeklyHours: '40',
      vacationDays: '25',
      noticePeriodMonths: '2',
    },
  },
  // 9. DOHODA O PROVEDENÍ PRÁCE
  {
    tier: 'complete',
    label: '09_DPP',
    data: {
      contractType: 'dpp',
      notaryUpsell: true,
      tier: 'complete',
      employerName: 'Vydavatelství Knižní svět s.r.o.',
      employerIco: '55667788',
      employerAddress: 'Korunní 23, Praha 2, 120 00',
      employeeName: 'Petra Vlčková',
      employeeId: '25. 5. 1998',
      employeeAddress: 'Mánesova 5, Praha 2, 120 00',
      workDescription: 'Překlad odborného textu z angličtiny do češtiny, redakční korektura — rozsah cca 80 normostran.',
      hourlyRate: '350',
      estimatedHours: '120',
      totalReward: '42000',
      startDate: '2026-04-01',
      endDate: '2026-05-31',
      maxHoursPerYear: '300',
    },
  },
  // 10. SMLOUVA O POSKYTOVÁNÍ SLUŽEB
  {
    tier: 'complete',
    label: '10_Smlouva_o_sluzbach',
    data: {
      contractType: 'service',
      notaryUpsell: true,
      tier: 'complete',
      providerName: 'WebStudio Praha s.r.o.',
      providerId: '98765432',
      providerAddress: 'Korunní 15, Praha 2, 120 00',
      clientName: 'Restaurace U Karla',
      clientId: '11334455',
      clientAddress: 'Náměstí Míru 8, Praha 2, 120 00',
      serviceDescription: 'Správa a provoz webových stránek, SEO optimalizace, správa sociálních sítí (Facebook, Instagram) a pravidelný reporting.',
      monthlyFee: '12000',
      contractDurationMonths: '12',
      startDate: '2026-04-01',
      noticePeriodDays: '60',
      deliveryDeadlineDays: '14',
    },
  },
  // 11. PODNÁJEMNÍ SMLOUVA
  {
    tier: 'complete',
    label: '11_Podnajem_smlouva',
    data: {
      contractType: 'sublease',
      notaryUpsell: true,
      tier: 'complete',
      tenantName: 'Barbora Součková',
      tenantId: '19. 9. 1982',
      tenantAddress: 'Mánesova 5, Praha 2, 120 00',
      subtenantName: 'Radek Novotný',
      subtenantId: '28. 2. 1996',
      subtenantAddress: 'Holečkova 3, Praha 5, 150 00',
      propertyAddress: 'Mánesova 5, Praha 2, 120 00 — pokoj č. 2',
      roomDescription: 'Pokoj o výměře 18 m², sdílení kuchyně a koupelny.',
      monthlyRent: '9500',
      utilitiesIncluded: true,
      depositAmount: '19000',
      startDate: '2026-04-01',
      endDate: '2026-09-30',
      landlordConsent: true,
    },
  },
  // 12. PLNÁ MOC
  {
    tier: 'complete',
    label: '12_Plna_moc',
    data: {
      contractType: 'power_of_attorney',
      notaryUpsell: true,
      tier: 'complete',
      principalName: 'Věra Horáčková',
      principalId: '11. 11. 1960',
      principalAddress: 'Táborská 22, Praha 4, 140 00',
      agentName: 'JUDr. Michal Svoboda',
      agentId: '5. 3. 1975',
      agentAddress: 'Právnická 3, Praha 1, 110 00',
      poaType: 'property',
      propertyAddress: 'Táborská 22, Praha 4, LV č. 1234, k. ú. Nusle',
      singleUse: false,
      allowSubstitution: false,
    },
  },
  // 13. UZNÁNÍ DLUHU
  {
    tier: 'complete',
    label: '13_Uznani_dluhu',
    data: {
      contractType: 'debt_acknowledgment',
      notaryUpsell: true,
      tier: 'complete',
      creditorName: 'Ing. Filip Starý',
      creditorId: '22. 4. 1968',
      creditorAddress: 'Vinohradská 30, Praha 2, 120 00',
      debtorName: 'Jakub Šimánek',
      debtorId: '16. 6. 1990',
      debtorAddress: 'Korunní 7, Praha 2, 120 00',
      debtAmount: '85000',
      debtAmountWords: 'osmdesát pět tisíc',
      debtOrigin: 'Nezaplacená faktura č. 2025/0089 ze dne 15. 9. 2025 za provedené stavební práce.',
      repaymentDate: '2026-09-30',
      interestRate: '5',
      installmentPlan: true,
      installmentAmount: '10000',
      installmentDay: '28',
    },
  },
  // 14. SMLOUVA O SPOLUPRÁCI
  {
    tier: 'complete',
    label: '14_Smlouva_o_spolupraci',
    data: {
      contractType: 'cooperation',
      notaryUpsell: true,
      tier: 'complete',
      partyAName: 'CreativeLab s.r.o.',
      partyAId: '22334455',
      partyAAddress: 'Jugoslávská 14, Praha 2, 120 00',
      partyARepresentative: 'Jana Mrázková, jednatelka',
      partyBName: 'DataAnalytics s.r.o.',
      partyBId: '66778899',
      partyBAddress: 'Americká 5, Praha 2, 120 00',
      partyBRepresentative: 'Ing. Pavel Horník, jednatel',
      cooperationScope: 'Společný vývoj a prodej analytického softwaru pro e-commerce segment. Strana A zajistí design a frontend, strana B zajistí backend a datové modely.',
      profitSplitA: '50',
      profitSplitB: '50',
      durationMonths: '24',
      startDate: '2026-04-01',
      exclusivity: true,
      nonCompetePeriodMonths: '12',
    },
  },
];

async function main(): Promise<void> {
  await mkdir(outputDir, { recursive: true });
  for (const sample of SAMPLES) {
    const data: StoredContractData = { ...sample.data, tier: sample.tier };
    const pdf = await renderContractPdf(data);
    const outPath = path.join(outputDir, `${sample.label}.pdf`);
    await writeFile(outPath, pdf);
    console.log(`Wrote ${outPath}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
